Repository MinaProtocol/mina, pull requests merged in 2019-08, with the labels that each got.

#3066 Make contributors' PRs pass CI
  frontend/website/package.json
Labels: ready-to-merge

#3033 Update Ubuntu install process
  frontend/website/docs/getting-started.md
Labels: ready-to-merge

#3081 Try to connect to all given peers on Kademlia startup
  src/app/kademlia-haskell/app/Main.hs
Labels: ready-to-merge

#3067 Website: Simplify CI hacks
  frontend/website/package.json
Labels: ready-to-merge

#3064 Notify peers when they're banned
  src/lib/coda_intf/network_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/gossip_net/gossip_net.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/trust_system/peer_trust.ml
  src/lib/trust_system/peer_trust.mli
Labels: ready-to-merge

#3072 Less fatal find_ip
  frontend/website/docs/getting-started.md
  frontend/website/docs/troubleshooting.md
  src/app/cli/src/coda.ml
  src/app/cli/src/find_ip.ml
  src/app/cli/src/find_ip.mli
Labels: ready-to-merge

#3087 discard transitioned_staged_ledger by unregistering its mask
  src/config/test_postake_holy_grail.mlh
  src/lib/proposer/proposer.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#3073 address random issues on docs
  frontend/website/docs/architecture/consensus.md
  frontend/website/docs/faq.md
  frontend/website/docs/troubleshooting.md
Labels: documentation, ready-to-merge

#3095 Skip-if-only-frontend should base off of develop
  scripts/skip_if_only_frontend.sh
Labels: ready-to-merge

#3104 [Feature] new genesis time, increased supply in genesis ledger
  src/config/testnet_postake_medium_curves.mlh
  src/lib/genesis_ledger/testnet_postake_ledger.ml
Labels: ready-to-merge

#3090 Full stack product eng post
  frontend/website/jobs/fullstack-engineer.markdown
  frontend/website/jobs/marketing-and-communications-manager.markdown
  frontend/website/jobs/senior-designer.markdown
  frontend/website/src/Render.re
Labels: ready-to-merge

#3108 Website: Copy blog posts from Medium
  .circleci/config.yml
  .circleci/config.yml.jinja
  frontend/website/posts/testnet-beta.markdown
  frontend/website/posts/testnet-retro-1.markdown
Labels: ready-to-merge

#3117 Website: Fix site/static mkdir crash
  frontend/website/src/Render.re
Labels: ready-to-merge

#3118 Website: Add relocation benefit
  frontend/website/src/Careers.re
Labels: ready-to-merge

#3122 Website: detect dev server during deploy
  frontend/website/deploy-website.sh
Labels: ready-to-merge

#3068 If ledger transfer fails, delete DB and try again
  src/lib/coda_base/ledger_transfer.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
Labels: ready-to-merge

#3110 SIMPLE:move dune profile setting in macos build
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#3113 add pvkeyhash and cibuild to deb version
  scripts/rebuild-deb.sh
Labels: ready-to-merge

#3121 Boot wait log message
  src/app/cli/src/coda.ml
Labels: ready-to-merge

#3111 update docs for release
  frontend/website/docs/coda-testnet.md
  frontend/website/docs/getting-started.md
  frontend/website/docs/my-first-transaction.md
  frontend/website/docs/node-operator.md
  frontend/website/mkdocs.yml
Labels: documentation, ready-to-merge

#3126 docs one liner
  frontend/website/docs/coda-testnet.md
Labels: ready-to-merge

#3115 SIMPLE:expand with-balances to with-details
  src/app/cli/src/client.ml
  src/app/cli/src/coda_commands.ml
  src/app/cli/src/coda_run.ml
  src/lib/cli_lib/render.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
Labels: ready-to-merge

#3112 Created eager bootstrap
  CODEOWNERS
  src/app/cli/src/coda_worker_testnet.ml
  src/app/cli/src/dune
  src/app/cli/src/graphql.ml
  src/best_tip_prover.opam
  src/lib/best_tip_prover/best_tip_prover.ml
  src/lib/best_tip_prover/dune
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/dune
  src/lib/coda_intf/network_intf.ml
  src/lib/coda_intf/staged_ledger_intf.ml
  src/lib/coda_intf/transition_frontier_components_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/dune
  src/lib/coda_networking/coda_networking.ml
  src/lib/kademlia/membership.ml
  src/lib/root_prover/dune
  src/lib/root_prover/root_prover.ml
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/sync_handler/dune
  src/lib/sync_handler/sync_handler.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_frontier_controller_tests/dune
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
  src/lib/transition_frontier_controller_tests/test_root_prover.ml
  src/lib/transition_frontier_controller_tests/test_sync_handler.ml
  src/lib/transition_router/transition_router.ml
  src/lib/transition_router/transition_router.mli
Labels: ready-to-merge

#3125 coda crash report
  src/app/cli/src/coda_run.ml
Labels: ready-to-merge

#3127 Simpler upnpc command
  frontend/website/docs/troubleshooting.md
Labels: ready-to-merge

#3133 update docs copy / formatting
  frontend/website/docs/troubleshooting.md
Labels: ready-to-merge

#3123 bkase owns the Makefile and scripts too
  CODEOWNERS
Labels: ready-to-merge

#3135 update footer
  frontend/website/src/Page.re
Labels: ready-to-merge, website

#3148 update docs
  frontend/website/docs/getting-started.md
Labels: ready-to-merge

#3134 An unsafe account import
  src/app/cli/src/client.ml
  src/app/cli/src/coda.ml
  src/lib/cli_lib/default.ml
  src/lib/cli_lib/flag.ml
Labels: ready-to-merge

#3161 Lookup all peer addresses
  src/app/cli/src/coda.ml
Labels: ready-to-merge

#3069 log fatal exns to json
  src/app/cli/src/coda_run.ml
  src/lib/gossip_net/gossip_net.ml
  src/lib/kademlia/membership.ml
Labels: ready-to-merge

#3166 Update parameters for new staking testnet release
  src/config/testnet_postake_medium_curves.mlh
  src/lib/consensus/proof_of_stake.ml
Labels: ready-to-merge

#3158 Add graphql accounts list cli command
  .gitattributes
  graphql_schema.json
  src/app/cli/src/client.ml
  src/app/cli/src/coda.ml
  src/app/cli/src/dune
  src/app/cli/src/graphql_client.ml
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_frontend.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/fake_hash.mlh
  src/config/test_postake.mlh
  src/config/test_postake_bootstrap.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_delegation.mlh
  src/config/test_postake_delegation_medium_curves.mlh
  src/config/test_postake_five_even_snarkless.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_snarkless_medium_curves_unit_test.mlh
  src/config/test_postake_snarkless_unittest.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_split_snarkless.mlh
  src/config/test_postake_split_snarkless_medium_curves.mlh
  src/config/test_postake_txns.mlh
  src/config/test_postake_txns_medium_curves.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_proposers.mlh
  src/config/testnet_postake_many_proposers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/lib/cli_lib/background_daemon.ml
  src/lib/cli_lib/background_daemon.mli
  src/lib/cli_lib/flag.ml
  src/lib/cli_lib/port.ml
Labels: ready-to-merge

#3177 Frontend: Fix package.json licenses
  frontend/wallet/.gitignore
  frontend/wallet/package-lock.json
  frontend/wallet/package.json
  frontend/website/.gitignore
  frontend/website/package.json
Labels: ready-to-merge

#3023 Fix some output capitalization and formatting
  src/app/cli/src/coda_run.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
Labels: ready-to-merge

#3182 update url for testnet release
  frontend/website/docs/my-first-transaction.md
  frontend/website/docs/node-operator.md
Labels: ready-to-merge

#3071 restart kademlia subprocess on failure
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#3088 [Feature] added a build argument to daemon dockerfile
  dockerfiles/Dockerfile-coda-daemon
  dockerfiles/Dockerfile-codaslim
Labels: ready-to-merge

#2767 Changed Snark worker dynamically at runtime
  .circleci/config.yml
  scripts/test.py
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_change_snark_worker_test.ml
  src/app/cli/src/coda_process.ml
  src/app/cli/src/coda_processes.ml
  src/app/cli/src/coda_run.ml
  src/app/cli/src/coda_transitive_peers_test.ml
  src/app/cli/src/coda_worker.ml
  src/app/cli/src/coda_worker_testnet.ml
  src/app/cli/src/full_test.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/config.ml
  src/lib/kademlia/membership.ml
  src/lib/kademlia/node_addrs_and_ports.ml
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/snark_worker/rpcs.ml
Labels: ready-to-merge

#3170 CODEOWNERS simplification for faster review cycles
  CODEOWNERS
  src/app/cli/dune-project
  src/app/cli/src/cli.opam
  src/app/cli/src/coda.ml
  src/app/cli/src/dune
  src/app/cli/src/dune-project
  src/app/cli/src/init.opam
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/coda_tracing.ml
  src/app/cli/src/init/dune
  src/app/cli/src/init/find_ip.ml
  src/app/cli/src/init/find_ip.mli
  src/app/cli/src/init/graphql_client.ml
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/app/cli/src/init/visualization_message.ml
  src/app/cli/src/init/web_pipe.ml
  src/app/cli/src/tests.opam
  src/app/cli/src/tests/coda_archive_node_test.ml
  src/app/cli/src/tests/coda_batch_payment_test.ml
  src/app/cli/src/tests/coda_block_production_test.ml
  src/app/cli/src/tests/coda_bootstrap_test.ml
  src/app/cli/src/tests/coda_change_snark_worker_test.ml
  src/app/cli/src/tests/coda_delegation_test.ml
  src/app/cli/src/tests/coda_five_nodes_test.ml
  src/app/cli/src/tests/coda_long_fork.ml
  src/app/cli/src/tests/coda_peers_test.ml
  src/app/cli/src/tests/coda_process.ml
  src/app/cli/src/tests/coda_processes.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_restart_node_test.ml
  src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml
  src/app/cli/src/tests/coda_shared_prefix_multiproposer_test.ml
  src/app/cli/src/tests/coda_shared_prefix_test.ml
  src/app/cli/src/tests/coda_shared_state_test.ml
  src/app/cli/src/tests/coda_transitive_peers_test.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/app/cli/src/tests/dune
  src/app/cli/src/tests/full_test.ml
  src/app/cli/src/transition_frontier_persistence_rpc_worker.ml
  src/coda_commands.opam
  src/coda_graphql.opam
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_commands/dune
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_graphql/dune
  src/lib/test/dune
  src/lib/test/test.ml
Labels: ready-to-merge

#3191 Temporarily replace finger trees with lists
  src/lib/network_pool/f_sequence.ml
Labels: ready-to-merge

#3195 testnet no-snark-work fix
  src/lib/parallel_scan/parallel_scan.ml
Labels: ready-to-merge

#3096 Gate admission into the peer list on having the same "chain id"
  frontend/website/docs/troubleshooting.md
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/coda_networking.mli
  src/lib/gossip_net/dune
  src/lib/gossip_net/gossip_net.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
Labels: ready-to-merge

#3189 Allow versioning of GADT types
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/dune
  src/lib/ppx_coda/tests/versioned_bad_gadt.ml
  src/lib/ppx_coda/tests/versioned_bad_gadt_results.ml
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/versioned.ml
Labels: ready-to-merge

#3198 Website: Testnet leaderboard mvp
  frontend/website/src/Render.re
  frontend/website/src/Testnet.re
  frontend/website/static/js/leaderboard.js
Labels: ready-to-merge

#3211 Update docs glossary to reflect RFC
  frontend/website/docs/glossary.md
Labels: documentation, ready-to-merge

#3192 Created set_snark_work commands
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/dune
  src/app/cli/src/init/graphql_client.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
Labels: ready-to-merge

#3212 remove background in ci
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#3216 Same yojson encoding in stable and unstable Public_key.Compressed
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
Labels: ready-to-merge

#3175 Add bot service
  .circleci/config.yml
  .circleci/config.yml.jinja
  frontend/bot/.gitignore
  frontend/bot/bsconfig.json
  frontend/bot/package.json
  frontend/bot/src/App.re
  frontend/bot/src/Coda.re
  frontend/bot/src/Constants.re
  frontend/bot/src/Discord.re
  frontend/bot/src/Echo.re
  frontend/bot/src/Faucet.re
  frontend/bot/src/Graphql.re
  frontend/bot/src/Logger.re
  frontend/bot/src/Messages.re
  frontend/bot/src/SubscriptionsTransportWS.re
  frontend/bot/yarn.lock
Labels: ready-to-merge

#3208 Unit type for __versioned__
  src/lib/ppx_coda/versioned.ml
  src/lib/unsigned_extended/unsigned_extended.ml
Labels: ready-to-merge

#3238 Replace README codaprocotol.org with .com version
  README.md
Labels: ready-to-merge

#3239 Synchronously stop snark workers
  src/app/cli/src/tests/coda_process.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#3204 Wallet: Fix pagination and date parsing
  frontend/wallet/src/render/views/footer/Footer.re
  frontend/wallet/src/render/views/transactions/TransactionCell.re
  frontend/wallet/src/render/views/transactions/Transactions.re
  frontend/wallet/src/render/views/transactions/TransactionsList.re
Labels: ready-to-merge

#3243 Fix double-logging issue
  src/app/cli/src/coda.ml
Labels: ready-to-merge

#3245 Polish leaderboard & update docs
  frontend/website/.gitignore
  frontend/website/docs/coda-testnet.md
  frontend/website/docs/getting-started.md
  frontend/website/docs/node-operator.md
  frontend/website/src/Testnet.re
  frontend/website/static/js/leaderboard.js
Labels: ready-to-merge, website

#3199 Fix exception when splitting F_sequences.
  src/lib/network_pool/f_sequence.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ready-to-merge

#3249 update link to leaderboard
  frontend/website/docs/coda-testnet.md
Labels: ready-to-merge

#3218 better error message for empty epoch
  src/lib/consensus/proof_of_stake.ml
Labels: ready-to-merge

#3207 Created set-snark-work-fee for graphql and cli
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/daemon_rpcs/daemon_rpcs.ml
Labels: ready-to-merge

#3250 Code JSON directly
  src/lib/cli_lib/render.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
Labels: ready-to-merge

#3255 Add cryptography engineer jd
  frontend/website/jobs/cryptography-engineer.markdown
  frontend/website/src/Render.re
Labels: ready-to-merge, website

#3254 Check OCaml word size
  src/app/cli/src/coda.ml
  src/lib/ppx_coda/check_ocaml_word_size.ml
Labels: ready-to-merge

#3241 handle crash-report exns
  src/app/cli/src/init/coda_run.ml
Labels: ready-to-merge

#3145 Serialize non-zero curve points using the compressed representation
  src/lib/coda_base/user_command.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
Labels: ready-to-merge

#3086 Auditing {Hashtbl,Table}.add{,exn}
  src/lib/consensus/proof_of_stake.ml
  src/lib/kademlia/membership.ml
  src/lib/work_selector/inputs.ml
Labels: ready-to-merge

#3248 Fixing 2 potential racing conditions in bootstrap controller
  src/app/cli/src/tests/coda_long_fork.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#3258 Update website to jsx3
  frontend/website/bsconfig.json
  frontend/website/package.json
  frontend/website/src/A.re
  frontend/website/src/AnnouncementBar.re
  frontend/website/src/Blog.re
  frontend/website/src/BlogPost.re
  frontend/website/src/CareerPost.re
  frontend/website/src/Careers.re
  frontend/website/src/CryptoAppsSection.re
  frontend/website/src/Docs.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/Head.re
  frontend/website/src/HeroSection.re
  frontend/website/src/Home.re
  frontend/website/src/Image.re
  frontend/website/src/InclusiveSection.re
  frontend/website/src/InvestorsSection.re
  frontend/website/src/Links.re
  frontend/website/src/Markdown.re
  frontend/website/src/Nav.re
  frontend/website/src/NewsletterWidget.re
  frontend/website/src/Page.re
  frontend/website/src/RawHtml.re
  frontend/website/src/Render.re
  frontend/website/src/RunScript.re
  frontend/website/src/SideText.re
  frontend/website/src/SustainableSection.re
  frontend/website/src/Svg.re
  frontend/website/src/TeamSection.re
  frontend/website/src/Testnet.re
  frontend/website/src/Title.re
  frontend/website/src/Wrapped.re
  frontend/website/yarn.lock
Labels: ready-to-merge

#3247 Memory profiling support in daemon
  .circleci/config.yml
  .circleci/config.yml.jinja
  README-dev.md
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile-toolchain
  scripts/macos-setup.sh
  src/app/cli/src/coda.ml
  src/app/cli/src/memprof_helpers.ml
  src/lib/cli_lib/arg_type.ml
Labels: ready-to-merge

#3221 Use gzip to build crash report.
  src/app/cli/src/init/coda_run.ml
Labels: ready-to-merge

#3251 Eager bootstrap connects to multiple people
  src/app/cli/src/tests/coda_worker.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_intf/network_intf.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/gossip_net/gossip_net.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
  src/lib/transition_router/transition_router.ml
  src/lib/transition_router/transition_router.mli
Labels: ready-to-merge

#3237 Increase offline timeout. Closes #3186.
  src/lib/coda_networking/coda_networking.ml
  src/lib/consensus/constants.ml
  src/lib/consensus/intf.ml
Labels: ready-to-merge

#3252 cli to view snark pool
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/lib/coda_intf/core_intf.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/network_pool/intf.ml
  src/lib/network_pool/mocks.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_work/transaction_snark_work.ml
Labels: ready-to-merge

#3223 snark work logs
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/coda_metrics/coda_metrics.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/coda_networking.mli
  src/lib/gossip_net/gossip_net.ml
  src/lib/network_pool/intf.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/work_selector/work_lib.ml
Labels: ready-to-merge

#3253 snark jobs in graphql block
  graphql_schema.json
  src/lib/auxiliary_database/filtered_external_transition.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_intf/core_intf.ml
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark_work/transaction_snark_work.ml
  src/lib/transaction_snark_work/transaction_snark_work.mli
  src/lib/transition_frontier_controller_tests/stubs.ml
Labels: ready-to-merge

#3268 Don't fail when missing entry in peers_by_ip
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#3256 Ship logproc as coda-logproc in mac dist
  .circleci/config.yml
  .circleci/config.yml.jinja
  scripts/rebuild-deb.sh
Labels: ready-to-merge

#3259 Unblock OOO nathan+corey
  CODEOWNERS
Labels: ready-to-merge

#3270 Memory profile file in config dir
  src/app/cli/src/coda.ml
  src/app/cli/src/memprof_helpers.ml
Labels: ready-to-merge

#3274 Add basic bot dockerfile
  frontend/bot/Dockerfile
  frontend/bot/package.json
Labels: ready-to-merge

#3275 Dump OCaml memory stats
  src/app/cli/src/coda.ml
Labels: ready-to-merge

#3279 Fix wallet with faker
  frontend/wallet/.gitignore
  frontend/wallet/README.md
  frontend/wallet/generate-schema.js
  frontend/wallet/package.json
  frontend/wallet/src/main/DaemonProcess.re
Labels: ready-to-merge

#3271 fix the merkle_root mismatch
  src/lib/sync_handler/sync_handler.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#3283 [Bot] added README, minor edits
  frontend/bot/Dockerfile
  frontend/bot/README.md
  frontend/bot/src/Constants.re
  frontend/bot/src/Graphql.re
Labels: ready-to-merge

#3152 make proposer not crash if validation fails
  src/lib/proposer/proposer.ml
Labels: ready-to-merge

#3276 Remove memprof
  .circleci/config.yml
  .circleci/config.yml.jinja
  README-dev.md
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile-toolchain
  scripts/macos-setup.sh
  src/app/cli/src/coda.ml
  src/app/cli/src/memprof_helpers.ml
  src/lib/cli_lib/arg_type.ml
Labels: ready-to-merge

#3293 Fix calculation of memory bytes
  src/app/cli/src/coda.ml
Labels: ready-to-merge

#3281 Fix/holy grail not restart proposer
  src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml
  src/config/test_postake_holy_grail.mlh
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger/test_holy_grail.ml
Labels: ready-to-merge

#3286 Fix slot_diff
  src/lib/consensus/proof_of_stake.ml
Labels: ready-to-merge

#3287 swap two checks in frontier-dependencies-validation
  src/lib/coda_transition/external_transition.ml
Labels: ready-to-merge

#3298 TRIVIAL: enable time offsets on develop
  src/config/testnet_postake_medium_curves.mlh
Labels: ready-to-merge

#3297 TRIVIAL: store build config
  scripts/rebuild-deb.sh
Labels: ready-to-merge

#3295 Add testnet blogs
  frontend/website/posts/testnet-retro-2.markdown
  frontend/website/posts/testnet-retro-3.markdown
  frontend/website/posts/testnet-retro-4.markdown
Labels: ready-to-merge, website

#3303 Add more GC metrics to prometheus
  src/lib/coda_metrics/coda_metrics.ml
Labels: ready-to-merge

#3306 Fix links in node-operator docs page
  frontend/website/docs/node-operator.md
Labels: ready-to-merge

#3307 Update GraphQL docs for pooledUserCommands
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge

#3310 update leaderboard and docs for week 6
  frontend/website/docs/coda-testnet.md
  frontend/website/docs/getting-started.md
  frontend/website/docs/my-first-transaction.md
  frontend/website/docs/node-operator.md
  frontend/website/src/Testnet.re
Labels: ready-to-merge

#3076 [RFC] Glossary terms
  rfcs/0021-glossary-terms.md
Labels: RFC, ready-to-merge

#3220 Improve Logproc documentation
  src/app/logproc/logproc.ml
Labels: ready-to-merge

#3315 [Feature] automated release debs
  scripts/publish-deb.sh
  scripts/rebuild-deb.sh
Labels: ready-to-merge

#3299 snark-pool work using graphql
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/lib/cli_lib/graphql_types.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_intf/core_intf.ml
  src/lib/network_pool/intf.ml
  src/lib/network_pool/mocks.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark_work/transaction_snark_work.ml
Labels: ready-to-merge

#3318 libp2p deb build flow similar to kademlia
  Makefile
  dockerfiles/Dockerfile-toolchain-libp2p
  src/app/libp2p_helper/build/DEBIAN/control
Labels: ready-to-merge

#3291 Sorted external transitions after bootstrapping
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_transition/external_transition.ml
  src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
Labels: ready-to-merge

#3316 CLI command to cancel transactions
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/network_pool/indexed_pool.mli
Labels: ready-to-merge

#3296 Add grafana dashboard to leaderboard page
  frontend/website/src/Testnet.re
Labels: ready-to-merge, website

#3321 Convert cancel-txn to use rpc
  src/app/cli/src/init/client.ml
Labels: ready-to-merge

#3338 Remove product eng job post
  frontend/website/jobs/frontend-engineer.markdown
  frontend/website/jobs/fullstack-engineer.markdown
  frontend/website/src/Render.re
Labels: ready-to-merge
