Repository MinaProtocol/mina, pull requests merged in 2019-04, with the labels that each got.

#2051 worker: don't write to closed event pipes
  src/app/cli/src/coda_worker.ml
Labels: ready-to-merge

#2088 Generate val declarations for versioned types in module signatures
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/versioned.ml
Labels: ready-to-merge

#2089 Require versioning of types with parameters used by versioned types
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/dune
  src/lib/ppx_coda/tests/versioned_bad_type_parameters.ml
  src/lib/ppx_coda/tests/versioned_good_type_parameters.ml
  src/lib/ppx_coda/versioned.ml
Labels: ready-to-merge

#2084 Refactor pedersen code
  src/lib/coda_base/hash_prefix.ml
  src/lib/coda_base/ledger_hash.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/receipt.ml
  src/lib/crypto_params/gen/gen.ml
  src/lib/snark_params/pedersen.ml
  src/lib/snark_params/pedersen.mli
  src/lib/snark_params/pedersen_inputs_intf.ml
  src/lib/snark_params/snark_params.ml
Labels: ready-to-merge

#2087 Acceptable sustainable section
  frontend/website/src/SustainableSection.re
Labels: ready-to-merge

#2093 Rebuild code page, other fixes
  frontend/website/src/Code.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/RawHtml.re
  frontend/website/src/Render.re
  frontend/website/src/Style.re
Labels: ready-to-merge

#2094 Allow option and list type constructors in versioned types
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/dune
  src/lib/ppx_coda/tests/versioned_good_option.ml
  src/lib/ppx_coda/versioned.ml
Labels: ready-to-merge

#2090 ledger catchup should remove the failed transitions from the cache
  src/lib/ledger_catchup/ledger_catchup.ml
Labels: ready-to-merge

#2100 Deriving version for envelopes
  src/lib/envelope/dune
  src/lib/envelope/envelope.ml
  src/lib/envelope/envelope.mli
  src/lib/network_peer/peer.ml
Labels: category-versioning, ready-to-merge

#2092 disable the random restart in holy_grail test
  src/app/cli/src/coda_restarts_and_txns_holy_grail.ml
  src/config/test_postake_five_even_txns.mlh
Labels: ready-to-merge

#2102 Slightly push signup button
  frontend/website/src/Nav.re
Labels: ready-to-merge

#2105 Point to staging social image for now
  frontend/website/src/Head.re
Labels: ready-to-merge

#2106 Get those favicons in
  frontend/website/static/favicon-16x16.png
  frontend/website/static/favicon-32x32.png
Labels: ready-to-merge

#2111 Add ref to list of type constructors
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/dune
  src/lib/ppx_coda/tests/versioned_bad_option.ml
  src/lib/ppx_coda/tests/versioned_good_option.ml
  src/lib/ppx_coda/tests/versioned_good_type_constructors.ml
  src/lib/ppx_coda/versioned.ml
Labels: ready-to-merge

#2108 Where there's a form, there's a new tab
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/SideText.re
  frontend/website/src/Testnet.re
Labels: ready-to-merge

#2104 Don't ask why safari didn't like this
  frontend/website/src/InclusiveSection.re
Labels: ready-to-merge

#2101 More links and more correct links
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/Links.re
Labels: ready-to-merge

#2107 Sustainable always green
  frontend/website/src/SustainableSection.re
Labels: ready-to-merge

#2098 syncable ledger keeps auxiliary data
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/syncable_ledger/test.ml
  src/lib/transition_frontier_controller_tests/test_sync_handler.ml
Labels: ready-to-merge

#1763 Feature/bgverifier
  src/lib/snarky_verifier/bowe_gabizon.ml
Labels: ready-to-merge

#2113 Tooltip on sustainable
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/SustainableSection.re
  frontend/website/src/Svg.re
  frontend/website/static/img/chart-blockchain-energy.svg
Labels: ready-to-merge

#2120 Revamp blog index
  frontend/website/src/Blog.re
  frontend/website/src/BlogPost.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/Style.re
Labels: ready-to-merge

#2121 Allow sexp_opaque type constructor
  src/lib/ppx_coda/tests/versioned_good_type_constructors.ml
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2116 Links optionally CDN
  frontend/website/package-lock.json
  frontend/website/package.json
  frontend/website/src/Blog.re
  frontend/website/src/Careers.re
  frontend/website/src/Head.re
  frontend/website/src/Home.re
  frontend/website/src/Image.re
  frontend/website/src/InvestorsSection.re
  frontend/website/src/Links.re
  frontend/website/src/Markdown.re
  frontend/website/src/Render.re
  frontend/website/src/Svg.re
  frontend/website/src/TeamSection.re
  frontend/website/src/filter.js
Labels: ready-to-merge

#2122 Update tooltip copy to newest
  frontend/website/src/SustainableSection.re
  frontend/website/static/img/chart-blockchain-energy.svg
  frontend/website/static/img/chart-blockchain-size.svg
Labels: ready-to-merge

#2119 New copy everywhere
  frontend/website/src/CryptoAppsSection.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/HeroSection.re
  frontend/website/src/InclusiveSection.re
  frontend/website/src/SideText.re
  frontend/website/src/Style.re
  frontend/website/src/SustainableSection.re
Labels: ready-to-merge

#2082 Added the rest of the positions
  frontend/website/src/Render.re
Labels: ready-to-merge

#2125 Don't shift nav up until status-lift crosses
  frontend/website/src/Nav.re
  frontend/website/src/Page.re
  frontend/website/src/Style.re
Labels: ready-to-merge

#2127 Fix menu zindex
  frontend/website/src/Blog.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/Grid.re
  frontend/website/src/Markdown.re
  frontend/website/src/Nav.re
Labels: ready-to-merge

#2126 Fix regressions with the `p` reset
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/SideText.re
Labels: ready-to-merge

#2128 Cleanup the vertical whitespace everywhere
  frontend/website/src/Blog.re
  frontend/website/src/Careers.re
  frontend/website/src/Code.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/HeroSection.re
  frontend/website/src/Home.re
  frontend/website/src/Page.re
  frontend/website/src/Testnet.re
Labels: ready-to-merge

#2129 O(1) section redesign
  .circleci/config.yml
  .circleci/config.yml.jinja
  .gitattributes
  frontend/website/.gitignore
  frontend/website/package.json
  frontend/website/src/Home.re
  frontend/website/src/InvestorsSection.re
  frontend/website/src/Page.re
  frontend/website/src/Render.re
  frontend/website/src/Style.re
  frontend/website/src/TeamSection.re
  frontend/website/static/font/PragmataPro.zip
  frontend/website/static/img/investors/caffeinated.png
  frontend/website/static/img/investors/charlie.png
  frontend/website/static/img/investors/curious.jpg
  frontend/website/static/img/investors/dekrypt.png
  frontend/website/static/img/investors/elad.jpg
  frontend/website/static/img/investors/electric.png
  frontend/website/static/img/investors/fred.jpg
  frontend/website/static/img/investors/jack.jpg
  frontend/website/static/img/investors/kindred.png
  frontend/website/static/img/investors/linda.jpg
  frontend/website/static/img/investors/metastable.png
  frontend/website/static/img/investors/naval.png
  frontend/website/static/img/investors/nima.png
  frontend/website/static/img/investors/o.png
  frontend/website/static/img/investors/polychain.jpg
  frontend/website/static/img/investors/scifivc.png
  frontend/website/static/img/sahai.jpg
Labels: ready-to-merge

#2132 Add collapse to knowledgebase
  frontend/website/src/Blog.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/Nav.re
Labels: ready-to-merge

#2131 Pending coinbase aux to and from base64
  src/lib/coda_base/staged_ledger_hash.ml
Labels: ready-to-merge

#2117 Feature/punishments in syncable ledger
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_main.ml
  src/app/cli/src/coda_worker.ml
  src/app/cli/src/full_test.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_base/dune
  src/lib/coda_base/sync_ledger.ml
  src/lib/coda_base/trust_system.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/gossip_net/dune
  src/lib/gossip_net/gossip_net.ml
  src/lib/kademlia/dune
  src/lib/kademlia/membership.ml
  src/lib/kademlia/membership.mli
  src/lib/logger/logger.ml
  src/lib/merkle_address/merkle_address.ml
  src/lib/peer_trust/dune
  src/lib/sync_handler/sync_handler.ml
  src/lib/syncable_ledger/dune
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/syncable_ledger/test.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
  src/lib/transition_frontier_controller_tests/test_sync_handler.ml
  src/lib/transition_router/transition_router.ml
  src/lib/trust_system/banned_status.ml
  src/lib/trust_system/dune
  src/lib/trust_system/peer_status.ml
  src/lib/trust_system/peer_trust.ml
  src/lib/trust_system/peer_trust.mli
  src/lib/trust_system/record.ml
  src/lib/trust_system/record.mli
  src/lib/trust_system/trust_system.ml
  src/protocols/coda_transition_frontier.ml
  src/protocols/dune
  src/trust_system.opam
Labels: ready-to-merge

#2124 Attach verify_payment command to CLI
  src/app/cli/src/client.ml
Labels: ready-to-merge

#2136 Knockout the small things
  frontend/website/src/Careers.re
  frontend/website/src/InclusiveSection.re
  frontend/website/src/Page.re
  frontend/website/src/Testnet.re
  frontend/website/static/img/chart-blockchain-size.svg
Labels: ready-to-merge

#2137 Copy tweak from Evan
  frontend/website/src/HeroSection.re
Labels: ready-to-merge

#2133 Fixed a nasty bug in parallel scan
  src/lib/parallel_scan/parallel_scan.ml
Labels: ready-to-merge

#2097 complain about the pipe being closed
  src/app/cli/src/coda_worker.ml
Labels: ready-to-merge

#2139 Many copy changes
  frontend/website/src/CryptoAppsSection.re
  frontend/website/src/HeroSection.re
  frontend/website/src/InclusiveSection.re
  frontend/website/src/SustainableSection.re
Labels: ready-to-merge

#2118 Use version ppx for modules in Staged_ledger_hash
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/data_hash.mli
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/pending_coinbase_intf.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/staged_ledger_hash.ml
  src/lib/coda_base/staged_ledger_hash.mli
  src/lib/lite_lib/sparse_ledger.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/sparse_ledger_lib/sparse_ledger.mli
  src/lib/transaction_snark/dune
  src/lib/transaction_snark/transaction_snark.ml
  src/protocols/coda_pow.ml
Labels: category-versioning, ready-to-merge

#2067 Prevent multiple inbound connections from the same IP
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_block_production_test.ml
  src/app/cli/src/coda_bootstrap_test.ml
  src/app/cli/src/coda_five_nodes_test.ml
  src/app/cli/src/coda_peers_test.ml
  src/app/cli/src/coda_process.ml
  src/app/cli/src/coda_processes.ml
  src/app/cli/src/coda_receipt_chain_test.ml
  src/app/cli/src/coda_restart_node_test.ml
  src/app/cli/src/coda_restarts_and_txns_holy_grail.ml
  src/app/cli/src/coda_shared_prefix_multiproposer_test.ml
  src/app/cli/src/coda_shared_prefix_test.ml
  src/app/cli/src/coda_shared_state_test.ml
  src/app/cli/src/coda_transitive_peers_test.ml
  src/app/cli/src/coda_worker.ml
  src/app/cli/src/coda_worker_testnet.ml
  src/app/cli/src/full_test.ml
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#2114 trivial: support many_proposers
  .circleci/config.yml
  .mergify.yml
  Makefile
  scripts/test.py
Labels: ready-to-merge

#2140 Update address and harold
  frontend/website/html/Privacy.html
  frontend/website/html/TOS.html
  frontend/website/static/img/herbert.jpg
Labels: ready-to-merge

#2138 Add view-all buttons to team section
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/InvestorsSection.re
  frontend/website/src/Render.re
  frontend/website/src/Style.re
  frontend/website/src/TeamSection.re
Labels: ready-to-merge

#2142 Another pass of small things
  frontend/website/.gitignore
  frontend/website/src/Head.re
  frontend/website/src/Links.re
  frontend/website/src/Style.re
  frontend/website/static/font/PragmataPro.zip
  frontend/website/static/img/bonneau.jpg
  frontend/website/static/img/coda_facebook_OG.jpg
  frontend/website/static/img/mercer.jpg
Labels: ready-to-merge

#2143 trivial: proper syntax for or in makefile
  Makefile
Labels: ready-to-merge

#2145 The easy pass through the last todos
  .gitattributes
  frontend/website/src/Blog.re
  frontend/website/src/CryptoAppsSection.re
  frontend/website/src/HeroSection.re
  frontend/website/src/Page.re
  frontend/website/src/Testnet.re
  frontend/website/static/img/chart-blockchain-energy.svg
  frontend/website/static/img/chart-blockchain-size.svg
  frontend/website/static/presskit.zip
Labels: ready-to-merge

#2146 Many IE and Edge fixes
  frontend/website/.gitignore
  frontend/website/src/Blog.re
  frontend/website/src/Code.re
  frontend/website/src/InvestorsSection.re
  frontend/website/src/Style.re
  frontend/website/src/TeamSection.re
  frontend/website/static/font/PragmataPro.zip
Labels: ready-to-merge

#2109 Blake2 refactor
  src/blake2.opam
  src/lib/blake2/blake2.ml
  src/lib/blake2/dune
  src/lib/random_oracle/dune
  src/lib/random_oracle/random_oracle.ml
  src/lib/snarky_blake2/dune
  src/lib/snarky_blake2/snarky_blake2.ml
  src/lib/snarky_blake2/snarky_blake2.mli
Labels: ready-to-merge

#2152 only report duplicate transitions the second time we see it
  .circleci/config.yml
  .circleci/config.yml.jinja
  README-dev.md
  dockerfiles/Dockerfile
  src/lib/transition_handler/dune
  src/lib/transition_handler/validator.ml
  src/opam.export
Labels: ready-to-merge

#2144 Bootstrap should make a separate rpc call for scan_state
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/sync_handler/sync_handler.ml
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/syncable_ledger/test.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
  src/lib/transition_frontier_controller_tests/test_sync_handler.ml
  src/protocols/coda_transition_frontier.ml
Labels: ready-to-merge

#2153 Unnumbered option to deriving version to eliminate unused value warnings
  src/app/cli/src/coda_main.ml
  src/lib/blockchain_snark/blockchain.ml
  src/lib/blockchain_snark/dune
  src/lib/coda_base/account.ml
  src/lib/coda_base/ancestor.ml
  src/lib/coda_base/block_time.ml
  src/lib/coda_base/blockchain_state.ml
  src/lib/coda_base/external_transition.ml
  src/lib/coda_base/internal_transition.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/protocol_state.ml
  src/lib/coda_base/sok_message.ml
  src/lib/coda_base/staged_ledger_hash.ml
  src/lib/coda_base/sync_ledger.ml
  src/lib/coda_base/target.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/user_command.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_numbers/nat.ml
  src/lib/consensus/proof_of_signature.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/currency/currency.ml
  src/lib/currency/currency.mli
  src/lib/merkle_address/merkle_address.ml
  src/lib/module_version/dune
  src/lib/module_version/registration.ml
  src/lib/network_pool/dune
  src/lib/network_pool/network_pool.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/dune
  src/lib/ppx_coda/tests/versioned_bad_unnumbered.ml
  src/lib/ppx_coda/tests/versioned_good_unnumbered.ml
  src/lib/ppx_coda/versioned.ml
  src/lib/staged_ledger/dune
  src/lib/staged_ledger/staged_ledger_diff.ml
  src/lib/staged_ledger/transaction_snark_work.ml
  src/lib/transaction_pool/dune
  src/lib/transaction_pool/transaction_pool.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge

#2155 Allow recursion in versioned types
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/dune
  src/lib/ppx_coda/tests/unexpired.ml
  src/lib/ppx_coda/tests/unexpired_in_module.ml
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/tests/versioned_good_contained_types.ml
  src/lib/ppx_coda/tests/versioned_good_type_constructors.ml
  src/lib/ppx_coda/tests/versioned_good_type_parameters.ml
  src/lib/ppx_coda/tests/versioned_good_unnumbered.ml
  src/lib/ppx_coda/tests/versioned_good_wrapped.ml
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2156 Versioning for staged_ledger_diff
  src/lib/coda_base/external_transition.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/protocols/coda_pow.ml
Labels: category-versioning, ready-to-merge

#2159 trivial:let many=50
  src/lib/genesis_ledger/testnet_postake_ledger_many_proposers.ml
Labels: ready-to-merge

#2150 reorg snark params
  src/lib/snark_params/snark_params.ml
  src/lib/snarkette/fields.ml
Labels: ready-to-merge

#2162 Typo successfull -> successful
  scripts/test.py
Labels: ready-to-merge

#2149 Tweak reformat-diff: reformat staged and untracked files too
  Makefile
Labels: ready-to-merge

#2163 Final changes on website last minute (already deployed)
  frontend/website/deploy-cdn.sh
  frontend/website/deploy-website.sh
  frontend/website/firebase.json
  frontend/website/package.json
  frontend/website/src/A.re
  frontend/website/src/AnnouncementBar.re
  frontend/website/src/Blog.re
  frontend/website/src/BlogPost.re
  frontend/website/src/Careers.re
  frontend/website/src/Code.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/Head.re
  frontend/website/src/HeroSection.re
  frontend/website/src/InvestorsSection.re
  frontend/website/src/Links.re
  frontend/website/src/Markdown.re
  frontend/website/src/Nav.re
  frontend/website/src/Page.re
  frontend/website/src/Render.re
  frontend/website/src/SideText.re
  frontend/website/src/Testnet.re
  frontend/website/src/filter.js
  frontend/website/static/blog/coda2019/comparison.png
  frontend/website/static/css/blog.css
  frontend/website/static/img/chart-blockchain-energy.svg
  frontend/website/static/img/chart-blockchain-size.svg
  src/app/website/posts/coda2019.markdown
Labels: ready-to-merge

#2164 Allow option 'rpc' to version ppx
  src/lib/coda_networking/coda_networking.ml
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2165 Type name is msg, not message
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2166 Add version {rpc} where possible, or in comment
  src/lib/coda_base/external_transition.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/non_empty_list/dune
  src/lib/non_empty_list/non_empty_list.ml
  src/lib/non_empty_list/non_empty_list.mli
  src/lib/staged_ledger/staged_ledger.ml
  src/protocols/coda_pow.ml
Labels: category-versioning, ready-to-merge

#2167 strict_pipe: don't use option in exception data
  src/lib/pipe_lib/strict_pipe.ml
  src/lib/pipe_lib/strict_pipe.mli
Labels: ready-to-merge

#2169 Rpc-version get-ancestry query type
  src/lib/coda_base/protocol_state.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/consensus/dune
  src/lib/consensus/intf.ml
Labels: category-versioning, ready-to-merge

#2170 Rpc-version get ancestry response
  src/lib/coda_networking/coda_networking.ml
  src/lib/proof_carrying_data/dune
  src/lib/proof_carrying_data/proof_carrying_data.ml
Labels: category-versioning, ready-to-merge

#2171 Jane St versioned RPC for snark workers
  src/app/cli/src/coda_main.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/snark_worker_lib/dune
  src/lib/snark_worker_lib/intf.ml
  src/lib/snark_worker_lib/rpcs.ml
  src/lib/snark_worker_lib/worker.ml
Labels: category-versioning, ready-to-merge

#2172 Better margin on blog post mobile / desktop
  frontend/website/src/BlogPost.re
  frontend/website/src/CareerPost.re
Labels: ready-to-merge

#2178 Decrypt-ci shortcircuits if no creds
  frontend/website/package.json
Labels: ready-to-merge

#2181 "asserted" option to version ppx
  src/lib/blockchain_snark/blockchain.ml
  src/lib/coda_base/account.ml
  src/lib/coda_base/blockchain_state.ml
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/external_transition.ml
  src/lib/coda_base/internal_transition.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/proof.ml
  src/lib/coda_base/protocol_state.ml
  src/lib/coda_base/signature.ml
  src/lib/coda_base/sync_ledger.ml
  src/lib/coda_base/target.ml
  src/lib/coda_base/transaction_witness.ml
  src/lib/consensus/proof_of_signature.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/merkle_address/dune
  src/lib/merkle_address/merkle_address.ml
  src/lib/network_peer/dune
  src/lib/network_peer/peer.ml
  src/lib/network_pool/network_pool.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/parallel_scan/ring_buffer.ml
  src/lib/parallel_scan/state.ml
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/versioned.ml
  src/lib/snark_params/dune
  src/lib/snark_params/pedersen.ml
  src/lib/snark_params/pedersen.mli
  src/lib/snark_params/snark_params.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger_diff.ml
  src/lib/staged_ledger/transaction_snark_work.ml
  src/lib/transaction_pool/transaction_pool.ml
Labels: category-versioning, ready-to-merge

#2183 Version Job in parallel-scan-state
  src/lib/parallel_scan/parallel_scan.mli
  src/lib/parallel_scan/state.ml
Labels: category-versioning, ready-to-merge

#2187 Allow OCaml array constructor in version ppx
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2188 Use OCaml array constructor to avoid wrapping
  src/lib/parallel_scan/state.ml
Labels: category-versioning, ready-to-merge

#2189 Use int instead of Int.t to avoid wrapping
  src/lib/coda_base/pending_coinbase.ml
Labels: category-versioning, ready-to-merge

#2191 Remove asserted from deriving version in Blockchain
  src/lib/blockchain_snark/blockchain.ml
  src/lib/coda_base/protocol_state.ml
Labels: category-versioning, ready-to-merge

#2160 Versioned Sparse Ledger
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/sparse_ledger.mli
  src/lib/coda_base/stake_proof.ml
  src/lib/coda_base/transaction_witness.ml
  src/lib/lite_base/account.ml
  src/lib/lite_base/consensus_state.ml
  src/lib/lite_base/dune
  src/lib/lite_base/lite_chain.ml
  src/lib/lite_base/public_key.ml
  src/lib/lite_lib/dune
  src/lib/lite_lib/sparse_ledger.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/pedersen_lib/pedersen.ml
  src/lib/snark_worker_lib/intf.ml
  src/lib/snarkette/fields.ml
  src/lib/sparse_ledger_lib/dune
  src/lib/sparse_ledger_lib/inputs.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/sparse_ledger_lib/sparse_ledger.mli
  src/lib/staged_ledger/inputs.ml
  src/lib/transaction_snark_scan_state/inputs.ml
Labels: category-versioning, ready-to-merge

#2192 Remove asserted from deriving version in Account
  src/app/cli/src/coda_main.ml
  src/app/cli/src/full_test.ml
  src/lib/coda_base/account.ml
  src/lib/coda_base/ledger.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/genesis_ledger/functor.ml
  src/lib/merkle_ledger_tests/test_stubs.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
Labels: category-versioning, ready-to-merge

#2196 Use Poly.t not Poly.Stable.Latest.t
  src/app/cli/src/coda_main.ml
  src/lib/coda_base/payment_payload.ml
  src/lib/coda_base/payment_payload.mli
  src/lib/coda_base/staged_ledger_hash.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/transaction_union_payload.ml
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command_payload.ml
  src/lib/coda_base/user_command_payload.mli
  src/lib/currency/currency.ml
  src/lib/currency/currency.mli
  src/lib/lite_base/lite_chain.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/signature_lib/public_key.mli
  src/lib/snarky_blake2/snarky_blake2.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
Labels: ready-to-merge

#2195 Add graphql-faker to wallet
  .circleci/config.yml
  .circleci/config.yml.jinja
  frontend/wallet/.gitignore
  frontend/wallet/graphql_schema.json
  frontend/wallet/package-lock.json
  frontend/wallet/package.json
  frontend/wallet/schema.graphql
  frontend/wallet/src/Body.re
Labels: ready-to-merge

#2198 Remove asserted from deriving version in Blockchain_state
  src/lib/coda_base/block_time.mli
  src/lib/coda_base/blockchain_state.ml
  src/lib/coda_base/external_transition.ml
Labels: category-versioning, ready-to-merge

#2199 Remove asserted from External_transition deriving version
  src/lib/coda_base/external_transition.ml
Labels: category-versioning, ready-to-merge

#2203 Version Snark_transition
  src/app/cli/src/prover.ml
  src/lib/coda_base/internal_transition.ml
  src/lib/coda_base/snark_transition.ml
Labels: category-versioning, ready-to-merge

#2197 Created graphql for sync status
  src/app/cli/src/coda_main.ml
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#2205 Version Prover_state
  src/app/cli/src/prover.ml
  src/lib/coda_base/internal_transition.ml
  src/lib/coda_base/stake_proof.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_signature.ml
  src/lib/consensus/proof_of_stake.ml
  src/protocols/coda_pow.ml
Labels: category-versioning, ready-to-merge

#2201 Improve the parallel scan latency
  src/config/scan_state/small.mlh
  src/config/scan_state/standard.mlh
  src/config/scan_state/tiny.mlh
  src/lib/parallel_scan/parallel_scan.ml
  src/lib/parallel_scan/parallel_scan.mli
  src/lib/parallel_scan/state.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark_scan_state/constants.ml
  src/lib/transaction_snark_scan_state/constants.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/protocols/coda_pow.ml
Labels: ready-to-merge

#2173 fix gossip tcp error (fixes #2157)
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#2208 Add for_test option to version ppx
  src/lib/ppx_coda/versioned.ml
  src/lib/staged_ledger/staged_ledger.ml
Labels: category-versioning, ready-to-merge

#2209 Remove asserted from deriving version in Protocol_state
  src/lib/coda_base/protocol_state.ml
Labels: category-versioning, ready-to-merge

#2194 Versioning Snark Worker and Pending Coinbase
  src/app/cli/src/coda_main.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/pending_coinbase_intf.ml
  src/lib/coda_base/pending_coinbase_witness.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/transaction.ml
  src/lib/coda_base/user_command.mli
  src/lib/coda_networking/coda_networking.ml
  src/lib/snark_worker_lib/debug.ml
  src/lib/snark_worker_lib/intf.ml
  src/lib/snark_worker_lib/prod.ml
  src/lib/snark_worker_lib/rpcs.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/transition_frontier_persistence/diff_mutant.ml
  src/lib/transition_frontier_persistence/transition_database_schema.ml
  src/lib/transition_frontier_persistence/worker.ml
Labels: ready-to-merge

#2210 Versioned pending coinbase witness
  src/app/cli/src/prover.ml
  src/lib/coda_base/pending_coinbase_witness.ml
Labels: category-versioning, ready-to-merge

#2215 Add int32 and int64 types as OCaml builtins for version ppx
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2216 Remove version number, generated by ppx
  src/lib/coda_networking/coda_networking.ml
Labels: category-versioning, ready-to-merge

#2217 Removed version{asserted} in Transaction Pool
  src/lib/transaction_pool/transaction_pool.ml
Labels: category-versioning, ready-to-merge

#2214 Remove asserted from deriving version in Staged_ledger_diff
  src/app/cli/src/coda_main.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger_diff.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/protocols/coda_pow.ml
Labels: category-versioning, ready-to-merge

#2220 Update kad
  .circleci/config.yml
  .circleci/config.yml.jinja
  README-dev.md
  dockerfiles/Dockerfile
  src/app/kademlia-haskell/packages.nix
  src/app/kademlia-haskell/stack.yaml
Labels: ready-to-merge

#2219 Use OCaml array instead of Array.t to allow versioning
  src/lib/parallel_scan/ring_buffer.ml
Labels: category-versioning, ready-to-merge

#2206 Detect offline/online state of a node
  src/app/cli/src/coda_main.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/dune
  src/lib/consensus/constants.ml
  src/lib/consensus/constants.mli
Labels: ready-to-merge

#2218 Versioning/trivial
  src/lib/network_pool/network_pool.ml
  src/lib/staged_ledger/transaction_snark_work.ml
Labels: category-versioning, ready-to-merge

#2222 Add bytes type to version ppx
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2225 Remove asserted from deriving version for Snark_pool_diff
  src/app/cli/src/coda_main.ml
  src/lib/network_pool/network_pool.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/protocols/coda_pow.ml
Labels: category-versioning, ready-to-merge

#2223 Remove asserted from versioning in Stake_proof
  src/app/cli/src/coda_worker.ml
  src/lib/coda_base/account.ml
  src/lib/coda_base/stake_proof.ml
  src/lib/signature_lib/private_key.ml
Labels: category-versioning, ready-to-merge

#2226 Support for modals and deeplinking
  frontend/wallet/src/App.re
  frontend/wallet/src/AppWindow.re
  frontend/wallet/src/Delete.re
  frontend/wallet/src/MainCommunication.re
  frontend/wallet/src/Messages.re
  frontend/wallet/src/Modal.re
  frontend/wallet/src/Page.re
  frontend/wallet/src/RendererCommunication.re
  frontend/wallet/src/Route.re
  frontend/wallet/src/Router.re
  frontend/wallet/src/Send.re
  frontend/wallet/src/StyleGuide.re
Labels: ready-to-merge

#2231 Whitelist Jane St stable modules in version ppx
  src/lib/parallel_scan/state.ml
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2232 In Peer, remove asserted from deriving version
  src/lib/network_peer/peer.ml
  src/lib/network_pool/network_pool.ml
Labels: category-versioning, ready-to-merge

#2229 Switch off reduce_to_prover by default
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge

#2236 Remove asserted from Sync_ledger deriving version
  src/lib/coda_base/sync_ledger.ml
  src/lib/syncable_ledger/dune
  src/lib/syncable_ledger/syncable_ledger.ml
Labels: category-versioning, ready-to-merge

#2238 Use Longident flatten fun
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2228 Versioning Proof of Stake/ Proof Of Signature
  src/lib/coda_base/snark_transition.ml
  src/lib/consensus/dune
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_signature.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/transition_frontier_persistence/diff_mutant.ml
  src/lib/with_hash/dune
  src/lib/with_hash/with_hash.ml
  src/protocols/coda_pow.ml
Labels: category-versioning, ready-to-merge

#2239 Make sqrt_flagged more deterministic
  src/lib/snarky_group_map/checked_map.ml
Labels: ready-to-merge

#2241 Special-case Jane St library with unusual module path
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_coda/versioned.ml
Labels: category-versioning, ready-to-merge

#2213 Versioning Nat in Lite Chain and some dependencies
  src/lib/lite_base/account.ml
  src/lib/lite_base/block_time.ml
  src/lib/lite_base/blockchain_state.ml
  src/lib/lite_base/consensus_state.ml
  src/lib/lite_base/dune
  src/lib/lite_base/length.ml
  src/lib/lite_base/lite_chain.ml
  src/lib/lite_base/nat.ml
  src/lib/lite_base/protocol_state.ml
Labels: ready-to-merge

#2240 Versioning polymorphic types in snark worker
  src/lib/coda_networking/coda_networking.ml
  src/lib/snark_work_lib/dune
  src/lib/snark_work_lib/work.ml
  src/lib/snark_work_lib/work.mli
  src/lib/snark_worker_lib/debug.ml
  src/lib/snark_worker_lib/intf.ml
  src/lib/snark_worker_lib/prod.ml
  src/lib/snark_worker_lib/rpcs.ml
Labels: category-versioning, ready-to-merge

#2243 Introduce settings communication
  .circleci/config.yml
  .circleci/config.yml.jinja
  frontend/wallet/.gitignore
  frontend/wallet/__tests__/wallet_test.re
  frontend/wallet/bsconfig.json
  frontend/wallet/package-lock.json
  frontend/wallet/package.json
  frontend/wallet/src/App.re
  frontend/wallet/src/AppWindow.re
  frontend/wallet/src/Body.re
  frontend/wallet/src/CallTable.re
  frontend/wallet/src/CallTable.rei
  frontend/wallet/src/FlatFileDb.re
  frontend/wallet/src/MainCommunication.re
  frontend/wallet/src/Messages.re
  frontend/wallet/src/Modal.re
  frontend/wallet/src/Page.re
  frontend/wallet/src/PublicKey.re
  frontend/wallet/src/PublicKey.rei
  frontend/wallet/src/Route.re
  frontend/wallet/src/Router.re
  frontend/wallet/src/Settings.re
  frontend/wallet/src/SettingsMain.re
  frontend/wallet/src/SettingsMain.rei
  frontend/wallet/src/SettingsRenderer.re
  frontend/wallet/src/SettingsRenderer.rei
  frontend/wallet/src/Tc.re
Labels: ready-to-merge

#2246 Ppx for mirroring definitions locally
  src/lib/coda_base/account.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/proof.ml
  src/lib/coda_base/sok_message.ml
  src/lib/merkle_address/merkle_address.ml
  src/lib/network_peer/peer.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/ppx_coda/define_locally.ml
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/define_locally_good.ml
  src/lib/ppx_coda/tests/dune
  src/lib/snark_params/pedersen.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Labels: ready-to-merge

#2245 Correctly mutates shared state
  frontend/wallet/src/CallTable.re
Labels: ready-to-merge

#2247 Stick footer in place, no style
  frontend/wallet/src/Footer.re
  frontend/wallet/src/Page.re
  frontend/wallet/src/StyleGuide.re
  frontend/wallet/src/Tc.re
  frontend/wallet/src/bindings.re
Labels: ready-to-merge

#2252 Make snark worker spec non-opaque for sexp
  src/lib/snark_work_lib/work.ml
  src/lib/snark_worker_lib/prod.ml
Labels: ready-to-merge

#2261 Blockchain accumulator is dead code
  src/app/cli/src/blockchain_accumulator.ml
  src/app/cli/src/blockchain_accumulator.mli
Labels: ready-to-merge

#2244 Showed Offline status on command line
  src/app/cli/src/coda_main.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/daemon_rpcs/dune
  src/lib/sync_status/dune
  src/lib/sync_status/sync_status.ml
  src/sync_status.opam
Labels: ready-to-merge

#2264 removed community manager
  frontend/website/src/Render.re
  src/app/website/jobs/community-manager.markdown
Labels: ready-to-merge

#2267 Use define_locally in Coda_main
  src/app/cli/src/coda_main.ml
Labels: ready-to-merge

#2266 TRIVIAL: two simple cosmetic changes (snark worker and histograms)
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/snark_worker_lib/worker.ml
Labels: ready-to-merge

#2270 Settings reactively updates across processes
  frontend/wallet/__tests__/wallet_test.re
  frontend/wallet/src/AppWindow.re
  frontend/wallet/src/CallTable.re
  frontend/wallet/src/CallTable.rei
  frontend/wallet/src/MainCommunication.re
  frontend/wallet/src/MainCommunication.rei
  frontend/wallet/src/Messages.re
  frontend/wallet/src/Page.re
  frontend/wallet/src/SettingsRenderer.rei
Labels: ready-to-merge

#2260 Put logic in place for transactions view
  frontend/wallet/src/Body.re
  frontend/wallet/src/ConsensusState.re
  frontend/wallet/src/PublicKey.re
  frontend/wallet/src/PublicKey.rei
  frontend/wallet/src/StyleGuide.re
  frontend/wallet/src/TransactionCell.re
  frontend/wallet/src/TransactionsView.re
Labels: ready-to-merge

#2262 Add content to Send/Delete modals
  frontend/wallet/src/Delete.re
  frontend/wallet/src/ModalButtons.re
  frontend/wallet/src/Page.re
  frontend/wallet/src/Send.re
  frontend/wallet/src/StyleGuide.re
  frontend/wallet/src/Wallet.re
Labels: ready-to-merge

#2276 TRIVIAL: check for json params
  scripts/getkeys.sh
Labels: ready-to-merge

#2250 MacOS OpenMP Support
  README-dev.md
  scripts/macos-setup.sh
Labels: ready-to-merge

#2272 clean up catchup scheduler before start bootstrap
  src/app/cli/src/coda_restarts_and_txns_holy_grail.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_frontier_controller_tests/test_catchup_scheduler.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
  src/protocols/coda_transition_frontier.ml
Labels: ready-to-merge

#2278 pending coinbase stack mismatch fix
  src/lib/coda_base/pending_coinbase.ml
Labels: ready-to-merge

#2273 Settings pane uses real settings
  frontend/wallet/src/Body.re
  frontend/wallet/src/Page.re
  frontend/wallet/src/SettingsRenderer.re
  frontend/wallet/src/StyleGuide.re
  frontend/wallet/src/WalletItem.re
Labels: ready-to-merge

#2280 Replace faulty_peer by trust system record in Coda_networking
  src/lib/coda_networking/coda_networking.ml
Labels: ready-to-merge

#2282 Ledger catchup uses trust system
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml
  src/lib/transition_router/transition_router.ml
  src/protocols/coda_transition_frontier.ml
Labels: ready-to-merge

#2269 Placeholder for RPC deserialization tests
  src/lib/coda_networking/dune
  src/lib/coda_networking/rpc_tests.ml
Labels: ready-to-merge

#2283 Bootstrap controller, add trust system
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
Labels: ready-to-merge

#2248 Safer final exp
  src/lib/snarky_pairing/final_exponentiation.ml
Labels: ready-to-merge

#2277 Create subscription service for sync status
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  README-dev.md
  dockerfiles/Dockerfile
  src/app/cli/src/coda_main.ml
  src/app/cli/src/dune
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/dune
  src/opam.export
Labels: ready-to-merge

#2017 Epoch Ledger Synchronization
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_main.ml
  src/app/cli/src/coda_worker.ml
  src/app/cli/src/full_test.ml
  src/config/test_postake_txns.mlh
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/sparse_ledger.mli
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/consensus/dune
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_signature.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/external_transition_validation/external_transition_validation.ml
  src/lib/network_peer/dune
  src/lib/network_peer/network_peer.ml
  src/lib/pipe_lib/broadcast_pipe.ml
  src/lib/pipe_lib/broadcast_pipe.mli
  src/lib/proposer/proposer.ml
  src/lib/protocol_state_validator/protocol_state_validator.ml
  src/lib/root_prover/root_prover.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_handler/validator.ml
  src/protocols/coda_pow.ml
  src/protocols/coda_transition_frontier.ml
  src/protocols/dune
Labels: ready-to-merge

#2285 Move Run from coda_main to coda_run
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_block_production_test.ml
  src/app/cli/src/coda_bootstrap_test.ml
  src/app/cli/src/coda_five_nodes_test.ml
  src/app/cli/src/coda_inputs.ml
  src/app/cli/src/coda_intf.ml
  src/app/cli/src/coda_peers_test.ml
  src/app/cli/src/coda_process.ml
  src/app/cli/src/coda_processes.ml
  src/app/cli/src/coda_receipt_chain_test.ml
  src/app/cli/src/coda_restart_node_test.ml
  src/app/cli/src/coda_restarts_and_txns_holy_grail.ml
  src/app/cli/src/coda_run.ml
  src/app/cli/src/coda_shared_prefix_multiproposer_test.ml
  src/app/cli/src/coda_shared_prefix_test.ml
  src/app/cli/src/coda_shared_state_test.ml
  src/app/cli/src/coda_transitive_peers_test.ml
  src/app/cli/src/coda_worker.ml
  src/app/cli/src/coda_worker_testnet.ml
  src/app/cli/src/full_test.ml
Labels: ready-to-merge

#2287 Move graphql to different file
  .circleci/config.yml
  scripts/test.py
  src/app/cli/src/coda_run.ml
  src/app/cli/src/graphql.ml
Labels: ready-to-merge

#2281 Added more logging to tf persistence
  src/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml
  src/lib/transition_frontier_persistence/diff_mutant.ml
  src/lib/transition_frontier_persistence/transition_frontier_persistence.ml
  src/lib/transition_frontier_persistence/worker.ml
Labels: ready-to-merge

#2289 Removed functional programming requirement for Engineering Manager
  src/app/website/jobs/engineering-manager.markdown
Labels: ready-to-merge

#2293 Reward response in RPC calls
  src/lib/coda_networking/coda_networking.ml
Labels: area-networking, ready-to-merge

#2286 Gossip net, add trust system for RPC calls
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#2295 Remove unused version number in Ledger_proof
  src/app/cli/src/ledger_proof.ml
Labels: category-versioning, ready-to-merge

#2291 Remove developer advocate position
  frontend/website/src/Render.re
  src/app/website/jobs/developer-advocate.markdown
Labels: ready-to-merge

#2292 Made payment type in Graphql
  src/app/cli/src/graphql.ml
  src/lib/coda_base/user_command_memo.mli
  src/lib/random_oracle/random_oracle.ml
  src/lib/random_oracle/random_oracle.mli
Labels: ready-to-merge

#2301 Add version query to graphql api
  src/app/cli/src/coda_run.ml
  src/app/cli/src/graphql.ml
Labels: ready-to-merge

#2312 fix gossip_net failure
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#2314 Add currentSnarkWorker to graphql api
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_inputs.ml
  src/app/cli/src/coda_run.ml
  src/app/cli/src/coda_worker.ml
  src/app/cli/src/full_test.ml
  src/app/cli/src/graphql.ml
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge
