Repository MinaProtocol/mina, pull requests merged in 2019-07, with the labels that each got.

#2547 re-enable medium, use xlarge
  .circleci/config.yml
  .circleci/config.yml.jinja
  .mergify.yml
  scripts/test.py
Labels: ready-to-merge

#2750 Add logging flags to daemon cli
  src/app/cli/src/coda.ml
  src/lib/logger/dune
  src/lib/logger/logger.ml
  src/lib/logger/logger.mli
Labels: ready-to-merge

#2761 Remove remaining uses of base64
  src/app/cli/src/dune
  src/lib/base58_check/version_bytes.ml
  src/lib/coda_base/receipt.ml
  src/lib/coda_base/signature.ml
  src/lib/codable/codable.ml
  src/lib/codable/dune
  src/lib/lite_curve_choice/dune
  src/lib/lite_params/dune
  src/lib/lite_params/gen/dune
  src/lib/lite_params/gen/gen.ml
  src/lib/lite_precomputed_values/gen/gen.ml
  src/lib/non_zero_curve_point/dune
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/random_oracle/dune
  src/lib/secrets/secret_box.ml
  src/lib/signature_lib/dune
  src/lib/signature_lib/public_key.mli
  src/opam.export
Labels: ready-to-merge

#2640 snarky bowe gabizon hash
  src/lib/bowe_gabizon_hash/bowe_gabizon_hash.ml
  src/lib/bowe_gabizon_hash/inputs_intf.ml
  src/lib/snarky_bowe_gabizon_hash/dune
  src/lib/snarky_bowe_gabizon_hash/inputs_intf.ml
  src/lib/snarky_bowe_gabizon_hash/snarky_bowe_gabizon_hash.ml
  src/lib/snarky_bowe_gabizon_hash/snarky_bowe_gabizon_hash.mli
  src/snarky_bowe_gabizon_hash.opam
Labels: ready-to-merge

#2738 Eliminating the hard-coded timestamp
  src/app/cli/src/coda_processes.ml
  src/lib/coda_base/genesis_state_timestamp.ml
  src/lib/coda_state/blockchain_state.ml
Labels: ready-to-merge

#1467 Created test that validates whether a background coda is spun up
  src/command_line_tests.opam
  src/lib/command_line_tests/command_line_tests.ml
  src/lib/command_line_tests/dune
Labels: ready-to-merge

#2766 Benchmark executable and script
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  README-dev.md
  dockerfiles/Dockerfile
  scripts/benchmarks.sh
  src/app/benchmarks/benchmarks.opam
  src/app/benchmarks/dune
  src/app/benchmarks/dune-project
  src/app/benchmarks/main.ml
  src/lib/snark_params/dune
  src/lib/snark_params/snark_params.ml
  src/opam.export
Labels: ready-to-merge

#2769 Add 'advanced' subsection to coda cli
  src/app/cli/src/client.ml
  src/app/cli/src/coda.ml
Labels: ready-to-merge

#2754 Instantiate bowe-gabizon
  src/lib/bowe_gabizon_hash/bowe_gabizon_hash.ml
  src/lib/bowe_gabizon_hash/inputs_intf.ml
  src/lib/crypto_params/crypto_params.ml
  src/lib/crypto_params/dune
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/lite_base/crypto_params.ml
  src/lib/lite_base/dune
  src/lib/lite_base/pedersen.ml
  src/lib/lite_base/proof.ml
  src/lib/lite_base/proof.mli
  src/lib/lite_base/public_key.ml
  src/lib/lite_base/receipt.ml
  src/lib/snark_params/dune
  src/lib/snark_params/snark_params.ml
  src/lib/snarkette/bowe_gabizon.ml
  src/lib/snarkette/fields.ml
  src/lib/snarkette/mnt6753.ml
  src/lib/snarkette/mnt6_80.ml
  src/lib/snarky_bowe_gabizon_hash/snarky_bowe_gabizon_hash.ml
Labels: ready-to-merge

#2773 Add vrf eval benchmarks
  src/app/benchmarks/dune
  src/app/benchmarks/main.ml
  src/lib/vrf_lib/dune
  src/lib/vrf_lib/integrated_test.ml
  src/vrf_lib_tests.opam
Labels: ready-to-merge

#2774 Base58check rep of ledger hash, use it in client status
  src/app/cli/src/coda_commands.ml
  src/lib/base58_check/version_bytes.ml
  src/lib/coda_base/ledger_hash.ml
  src/lib/coda_base/ledger_hash_intf.ml
Labels: ready-to-merge

#2779 Don't encode/decode pedersen_params
  src/lib/lite_params/gen/gen.ml
Labels: ready-to-merge

#2780 Fix get-wallet-keys.sh - CLI parameters changed
  scripts/get-wallet-keys.sh
Labels: ready-to-merge

#2783 Be more tolerant of network failures and ungraceful shutdown in trust system
  src/lib/trust_system/trust_system.ml
Labels: ready-to-merge

#2755 Switch over to bowe-gabizon
  src/lib/blockchain_snark/blockchain_transition.ml
  src/lib/coda_base/transition_system.ml
  src/lib/crypto_params/crypto_params.ml
  src/lib/dummy_values/gen_values/gen_values.ml
  src/lib/lite_base/proof.ml
  src/lib/lite_base/proof.mli
  src/lib/lite_compat/lite_compat.ml
  src/lib/lite_precomputed_values/gen/gen.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/snark_params/snark_params.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge

#2791 Temporarily disable artifactory publish step
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#2795 Fix heartbeat timeout
  src/lib/parallel/parallel.ml
Labels: ready-to-merge

#2568 Hook up the caching in Keys
  src/lib/keys_lib/keys.ml
Labels: ready-to-merge

#2474 adding our modified BG snark construction paper
  frontend/website/src/Links.re
  src/app/website/static/modified-BG-snark-05-03-2019-0.pdf
Labels: ready-to-merge

#2802 Disable transition frontier persistence
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#2797 Implement dumb internal logrotate logic
  src/app/cli/src/coda.ml
  src/lib/logger/impl.ml
  src/lib/logger/impl.mli
  src/lib/logger/logger.ml
  src/lib/logger/logger.mli
  src/lib/logger/test.ml
Labels: ready-to-merge

#2807 Remove dead code in Transaction_snark
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge

#2798 Graphql: First pass on docs cleanup
  src/app/cli/src/coda.ml
  src/app/cli/src/graphql.ml
Labels: ready-to-merge

#2822 Website: Rework cdn behavior
  frontend/website/.gitignore
  frontend/website/deploy-cdn.sh
  frontend/website/deploy-website.sh
  frontend/website/firebase.json
  frontend/website/package.json
  frontend/website/posts/snark-challenge.markdown
  frontend/website/posts/snarky.markdown
  frontend/website/posts/zkp.markdown
  frontend/website/src/Links.re
  frontend/website/src/Markdown.re
  frontend/website/src/Render.re
  frontend/website/src/filter.js
  frontend/website/static/constraints.txt
  frontend/website/static/modified-BG-snark-05-03-2019-0.pdf
  frontend/website/yarn.lock
Labels: ready-to-merge

#2777 Created set staking cli command
  src/app/cli/src/client.ml
  src/app/cli/src/coda_commands.ml
  src/app/cli/src/coda_run.ml
  src/app/cli/src/graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/signature_lib/keypair.ml
  src/lib/signature_lib/keypair.mli
Labels: ready-to-merge

#2826 Website: Update product eng job description
  frontend/website/jobs/frontend-engineer.markdown
  frontend/website/jobs/senior-frontend-engineer.markdown
Labels: ready-to-merge

#2786 Add log when VRF-evaluation slot disagrees from slot at actual time of proposal.
  src/lib/consensus/epoch.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/consensus/slot.ml
  src/lib/consensus/stake_proof.ml
  src/lib/proposer/proposer.ml
Labels: ready-to-merge

#2775 Make Genesis_ledger.t lazy
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_state/blockchain_state.ml
  src/lib/coda_state/blockchain_state.mli
  src/lib/coda_state/genesis_protocol_state.ml
  src/lib/coda_state/genesis_protocol_state.mli
  src/lib/coda_state/protocol_state.ml
  src/lib/coda_state/protocol_state.mli
  src/lib/coda_state/snark_transition.ml
  src/lib/coda_state/snark_transition.mli
  src/lib/coda_transition/external_transition.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/genesis_ledger/functor.ml
  src/lib/genesis_ledger/intf.ml
  src/lib/lite_precomputed_values/gen/gen.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/staged_ledger_hash/staged_ledger_hash.ml
  src/lib/staged_ledger_hash/staged_ledger_hash.mli
  src/lib/transition_frontier_controller_tests/stubs.ml
Labels: ready-to-merge

#2730 pare down insecure
  src/lib/coda_base/insecure.ml
  src/lib/coda_base/schnorr.ml
  src/lib/coda_base/secure_random.ml
  src/lib/coda_base/secure_random.mli
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_state/blockchain_state.ml
Labels: ready-to-merge

#2830 [Website] update target for staging to different firebase environment
  frontend/website/README.md
  frontend/website/deploy-website.sh
Labels: ready-to-merge

#2844 GraphQL scalars for PublicKey and UInt64
  frontend/wallet/schema.graphql
  frontend/wallet/src/common/Wallet.re
  frontend/wallet/src/render/Apollo.re
  frontend/wallet/src/render/components/RequestCodaModal.re
  frontend/wallet/src/render/components/SideBar.re
  frontend/wallet/src/render/components/WalletDropdownItem.re
  frontend/wallet/src/render/views/footer/Footer.re
  frontend/wallet/src/render/views/footer/SendButton.re
  frontend/wallet/src/render/views/walletlist/WalletItem.re
  frontend/wallet/src/render/views/walletlist/WalletList.re
  src/app/cli/src/graphql.ml
Labels: ready-to-merge

#2821 Use version{rpc} in Rpc module in PoStake
  src/lib/consensus/proof_of_stake.ml
Labels: ready-to-merge

#2770 New threshold function
  src/app/proposer_simulation/sim.py
  src/lib/consensus/proof_of_stake.ml
  src/lib/currency/currency.ml
  src/lib/currency/currency.mli
Labels: ready-to-merge

#2857 Generate graphql SDL file from daemon
  frontend/wallet/__tests__/wallet_test.re
  frontend/wallet/generate-schema.js
  frontend/wallet/package.json
  frontend/wallet/schema.graphql
  frontend/wallet/src/common/Bindings.re
  frontend/wallet/src/main/DaemonProcess.re
  frontend/wallet/src/render/Apollo.re
  frontend/wallet/src/render/Preload.re
  frontend/wallet/src/render/views/footer/Footer.re
  frontend/wallet/src/render/views/settings/WalletSettings.re
  frontend/wallet/src/render/views/transactions/Transactions.re
  frontend/website/package.json
  frontend/website/yarn.lock
Labels: ready-to-merge

#2875 Some log message cleanup
  src/app/cli/src/coda_worker_testnet.ml
  src/lib/pipe_lib/strict_pipe.ml
  src/lib/transition_handler/processor.ml
Labels: ready-to-merge

#2829 Less noisy snark worker logs
  src/app/cli/src/coda_run.ml
Labels: ready-to-merge

#2839 Add Matt as a codeowner on crypto_params
  CODEOWNERS
Labels: ready-to-merge

#2877 Revert investigation logs
  src/lib/coda_base/transition_system.ml
  src/lib/verifier/prod.ml
Labels: ready-to-merge

#2746 Website: Add Newsletter Widget
  frontend/website/lambdas/sendgrid-subscription/.gitignore
  frontend/website/lambdas/sendgrid-subscription/handler.js
  frontend/website/lambdas/sendgrid-subscription/package.json
  frontend/website/lambdas/sendgrid-subscription/serverless.yml
  frontend/website/lambdas/sendgrid-subscription/yarn.lock
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/Head.re
  frontend/website/src/HeroSection.re
  frontend/website/src/Nav.re
  frontend/website/src/NewsletterWidget.re
  frontend/website/src/SideText.re
  frontend/website/src/Style.re
Labels: ready-to-merge

#2878 Some logger fixes
  src/app/cli/src/coda_run.ml
  src/lib/coda_base/account.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/pending_coinbase_intf.ml
  src/lib/coda_base/pending_coinbase_witness.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/sparse_ledger.mli
  src/lib/coda_base/stake_proof.ml
  src/lib/coda_intf/core_intf.ml
  src/lib/coda_intf/staged_ledger_intf.ml
  src/lib/coda_intf/tmp_test_stub_hack.ml
  src/lib/coda_lib/coda_subscriptions.ml
  src/lib/coda_state/snark_transition.ml
  src/lib/coda_state/snark_transition.mli
  src/lib/coda_transition/internal_transition.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/lite_base/account.ml
  src/lib/lite_base/dune
  src/lib/lite_base/nat.ml
  src/lib/lite_base/public_key.ml
  src/lib/lite_base/receipt.ml
  src/lib/lite_base/state_hash.mli
  src/lib/lite_lib/dune
  src/lib/lite_lib/sparse_ledger.ml
  src/lib/non_zero_curve_point/dune
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/proposer/proposer.ml
  src/lib/signature_lib/private_key.ml
  src/lib/snarkette/dune
  src/lib/snarkette/fields.ml
  src/lib/snarkette/nat.ml
  src/lib/snarkette/nat_intf.ml
  src/lib/snarky_field_extensions/field_extensions.ml
  src/lib/sparse_ledger_lib/dune
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger_diff/staged_ledger_diff.ml
  src/lib/staged_ledger_diff/staged_ledger_diff.mli
  src/lib/transaction_snark_work/transaction_snark_work.ml
  src/lib/transaction_snark_work/transaction_snark_work.mli
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#2880 Info logging auditted
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_commands.ml
  src/app/cli/src/coda_run.ml
  src/app/cli/src/coda_worker.ml
  src/lib/cached/cached.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/kademlia/membership.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/proposer/proposer.ml
  src/lib/root_prover/root_prover.ml
  src/lib/snark_worker/functor.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_handler/catchup_scheduler.ml
Labels: ready-to-merge

#2848 Feature/transaction status
  frontend/wallet/schema.graphql
  src/app/cli/src/graphql.ml
  src/lib/coda_intf/transition_frontier_intf.ml
  src/lib/coda_lib/dune
  src/lib/network_pool/intf.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_status/dune
  src/lib/transaction_status/transaction_status.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier_controller_tests/dune
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/transition_frontier_controller_tests/test_transaction_status.ml
  src/transaction_status.opam
Labels: ready-to-merge

#2892 Wait to run transition router until genesis
  src/lib/proposer/proposer.ml
  src/lib/transition_router/transition_router.ml
Labels: ready-to-merge

#2895 Clean up log when a block is received out of its window
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#2896 Default log level INFO+
  src/app/cli/src/coda.ml
Labels: ready-to-merge

#2881 Look for kademlia binary relative to coda binary
  src/lib/kademlia/caml_syslimits.c
  src/lib/kademlia/dune
  src/lib/kademlia/membership.ml
  src/lib/kademlia/syslimits.ml
Labels: ready-to-merge

#2894 Simplify pv key handling
  .circleci/config.yml
  .circleci/config.yml.jinja
  .mergify.yml
  Makefile
  scripts/artifacts.sh
  scripts/publish-deb.sh
  scripts/pvkeys-download.sh
  scripts/rebuild-deb.sh
  scripts/test.py
Labels: ready-to-merge

#2847 Snark work refactor
  .circleci/config.yml
  .circleci/config.yml.jinja
  src/config/dev.mlh
  src/config/ledger_depth/small.mlh
  src/config/test_postake_snarkless_unittest.mlh
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/ledger.mli
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command_intf.ml
  src/lib/coda_intf/staged_ledger_intf.ml
  src/lib/coda_intf/tmp_test_stub_hack.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/network_pool/dune
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/mocks.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/network_pool/test.ml
  src/lib/quickcheck_lib/dune
  src/lib/quickcheck_lib/quickcheck_lib.ml
  src/lib/quickcheck_lib/quickcheck_lib.mli
  src/lib/signature_lib/keypair.ml
  src/lib/signature_lib/keypair.mli
  src/lib/signature_lib/private_key.ml
  src/lib/snark_work_lib/dune
  src/lib/snark_work_lib/work.ml
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/snark_worker/prod.ml
  src/lib/snark_worker/rpcs.ml
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/work_selector/inputs.ml
  src/lib/work_selector/intf.ml
  src/lib/work_selector/random.ml
  src/lib/work_selector/test.ml
  src/lib/work_selector/work_lib.ml
  src/lib/work_selector/work_selector.ml
  src/lib/work_selector/work_selector.mli
Labels: ready-to-merge

#2905 testnet_postake_medium_curves future genesis 2019-07-18 1:30:00-07:00
  src/config/testnet_postake_medium_curves.mlh
Labels: ready-to-merge

#2897 Feature/transaction status cli
  src/app/cli/src/client.ml
  src/app/cli/src/graphql.ml
  src/lib/base58_check/version_bytes.ml
  src/lib/coda_base/dune
  src/lib/coda_base/signature.mli
  src/lib/coda_base/state_hash.mli
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command.mli
  src/lib/coda_base/user_command_intf.ml
  src/lib/codable/codable.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/daemon_rpcs/dune
  src/lib/transaction_status/dune
  src/lib/transaction_status/transaction_status.ml
Labels: ready-to-merge

#2910 Add bkase and mrmr1993 as codeowners on VRF lib
  CODEOWNERS
Labels: ready-to-merge

#2917 Quick Fix: add get txn status cli
  src/app/cli/src/client.ml
Labels: ready-to-merge

#2920 add homebrew install directory for proving key
  src/app/cli/src/web_pipe.ml
  src/lib/blockchain_snark/blockchain_transition.ml
  src/lib/cache_dir/cache_dir.ml
  src/lib/cache_dir/dune
  src/lib/cached/cached.ml
  src/lib/cached/cached.mli
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge

#2912 Audit some more logs
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_delegation_test.ml
  src/lib/coda_intf/tmp_test_stub_hack.ml
  src/lib/kademlia/membership.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transition_router/initial_validator.ml
Labels: ready-to-merge

#2918 future genesis 2019-07-19 10:30:00-07:00
  src/config/testnet_postake_medium_curves.mlh
Labels: ready-to-merge

#2928 Audit some more logger messages
  src/lib/cache_lib/cache_lib.ml
  src/lib/coda_base/transition_system.ml
  src/lib/secrets/wallets.ml
Labels: ready-to-merge

#2931 Change log locations
  src/lib/logger/impl.ml
  src/lib/logger/test.ml
Labels: ready-to-merge

#2938 Another batch log message audits
  src/app/cli/src/web_pipe.ml
  src/lib/transition_frontier_persistence/transition_frontier_persistence.ml
  src/lib/transition_handler/breadcrumb_builder.ml
Labels: ready-to-merge

#2929 Audit logs for postake code
  src/lib/consensus/proof_of_stake.ml
Labels: ready-to-merge

#2942 bind rest server to all addresses on a machine
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_run.ml
Labels: ready-to-merge

#2940 Find keys using brew prefix
  src/lib/cache_dir/cache_dir.ml
Labels: ready-to-merge

#2587 Fixed invalid user command error when producing fake breadcrumbs
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
Labels: ready-to-merge

#2944 Commit transactions to SNARKed ledger in a batch when moving root
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#2915 Created Archive Node
  .circleci/config.yml
  scripts/test.py
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_archive_node_test.ml
  src/app/cli/src/coda_process.ml
  src/app/cli/src/coda_processes.ml
  src/app/cli/src/coda_transitive_peers_test.ml
  src/app/cli/src/coda_worker.ml
  src/app/cli/src/coda_worker_testnet.ml
  src/lib/auxiliary_database/filtered_external_transition.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_subscriptions.ml
  src/lib/coda_lib/config.ml
Labels: ready-to-merge

#2955 Make pretty logging prettier
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_delegation_test.ml
  src/app/cli/src/full_test.ml
  src/lib/logger/impl.ml
Labels: ready-to-merge

#2952 [Logging] nits
  src/app/cli/src/client.ml
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_run.ml
  src/app/cli/src/web_pipe.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/participating_state/participating_state.ml
Labels: ready-to-merge

#2943 Properly unregister masks when moving tf root + better error messages
  src/lib/merkle_mask/maskable_merkle_tree.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#2953 Status shows the highest block length encountered
  src/app/cli/src/coda_commands.ml
  src/app/cli/src/graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/transition_router/transition_router.ml
  src/lib/transition_router/transition_router.mli
Labels: ready-to-merge

#2872 [Website] Add docs
  .circleci/config.yml
  .circleci/config.yml.jinja
  .github/ISSUE_TEMPLATES/help.md
  CODEOWNERS
  CODE_OF_CONDUCT.md
  DIRECTORY_STRUCTURE.md
  README.md
  docs/README.md
  docs/consensus.md
  docs/demo.md
  docs/directory-structure.md
  docs/lifecycle-payment.md
  docs/proof-of-stake.md
  docs/reporting-guidelines.md
  frontend/node_modules/.yarn-integrity
  frontend/wallet/README.md
  frontend/website/.gitignore
  frontend/website/README.md
  frontend/website/deploy-website.sh
  frontend/website/docs/README.md
  frontend/website/docs/architecture/consensus.md
  frontend/website/docs/architecture/index.md
  frontend/website/docs/architecture/lifecycle-payment.md
  frontend/website/docs/architecture/proof-of-stake.md
  frontend/website/docs/cli-reference.md
  frontend/website/docs/code-of-conduct.md
  frontend/website/docs/contributing.md
  frontend/website/docs/developers/code-reviews.md
  frontend/website/docs/developers/directory-structure.md
  frontend/website/docs/developers/graphql-api.md
  frontend/website/docs/developers/index.md
  frontend/website/docs/developers/style-guide.md
  frontend/website/docs/getting-started.md
  frontend/website/docs/glossary.md
  frontend/website/docs/index.md
  frontend/website/docs/my-first-transaction.md
  frontend/website/docs/node-operator.md
  frontend/website/docs/reporting-guidelines.md
  frontend/website/docs/troubleshooting.md
  frontend/website/mkdocs.yml
  frontend/website/package-lock.json
  frontend/website/package.json
  frontend/website/src/AnnouncementBar.re
  frontend/website/src/BlogPost.re
  frontend/website/src/Code.re
  frontend/website/src/Docs.re
  frontend/website/src/GetInvolvedSection.re
  frontend/website/src/HeroSection.re
  frontend/website/src/Nav.re
  frontend/website/src/Render.re
  frontend/website/src/Style.re
  frontend/website/src/Testnet.re
  frontend/website/static/img/chevron-down.svg
  frontend/website/static/img/copy.svg
  frontend/website/static/img/link.svg
  frontend/website/static/js/clipboard.js
  frontend/website/yarn.lock
Labels: not-ready-to-merge

#2982 Add website cdn prefix check
  frontend/website/src/Docs.re
  frontend/website/src/Links.re
  frontend/website/src/Markdown.re
  frontend/website/src/Render.re
Labels: ready-to-merge

#2922 Audit log msgs for SNARK workers
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/prod.ml
Labels: ready-to-merge

#2716 [RFC] Memos with arbitrary bytes
  rfcs/0023-memos-with-arbitrary-bytes
Labels: ready-to-merge

#2977 Fix overly-eager bootstrap log message
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#2837 Fix/clean up root history
  CODEOWNERS
  src/lib/coda_intf/transition_frontier_intf.ml
  src/lib/root_history/dune
  src/lib/root_history/root_history.ml
  src/lib/root_history/root_history.mli
  src/lib/transition_frontier/extensions.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/root_history.opam
Labels: ready-to-merge

#3007 remove redundant ledger transfer
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#2950 Make genesis timestamp in SNARK unchanging
  src/lib/coda_state/blockchain_state.ml
Labels: ready-to-merge

#3012 Don't leak masks from Staged_ledger.snarked_ledger
  src/lib/coda_intf/staged_ledger_intf.ml
  src/lib/staged_ledger/staged_ledger.ml
Labels: ready-to-merge

#3010 Improve formatting of coda client status
  src/lib/consensus/proof_of_stake.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
Labels: ready-to-merge

#3037 Website: Make pragpro font optional for dev build
  frontend/website/src/Config.re
  frontend/website/src/Links.re
  frontend/website/src/Render.re
  frontend/website/src/Style.re
Labels: ready-to-merge

#3005 Store disconnected peers to cope with net outages
  src/app/cli/src/coda_processes.ml
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#3009 Fix/unregistered mask testnet
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/ledger.mli
  src/lib/merkle_ledger_tests/test_mask.ml
  src/lib/merkle_mask/maskable_merkle_tree.ml
  src/lib/merkle_mask/maskable_merkle_tree_intf.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#3021 Added nonce option to send-payment
  frontend/wallet/schema.graphql
  frontend/wallet/src/render/components/Header.re
  src/app/cli/src/client.ml
  src/app/cli/src/coda_commands.ml
  src/app/cli/src/graphql.ml
  src/lib/coda_numbers/account_nonce.mli
  src/lib/coda_numbers/coda_numbers.ml
  src/lib/coda_numbers/intf.ml
  src/lib/coda_numbers/nat.ml
  src/lib/coda_numbers/nat.mli
  src/lib/unsigned_extended/intf.ml
  src/lib/unsigned_extended/unsigned_extended.ml
  src/lib/unsigned_extended/unsigned_extended.mli
Labels: ready-to-merge

#3043 Add -no-bans flag to daemon
  src/app/cli/src/coda.ml
  src/lib/trust_system/peer_trust.ml
  src/lib/trust_system/peer_trust.mli
  src/lib/trust_system/record.ml
  src/lib/trust_system/record.mli
Labels: ready-to-merge

#2997 client rpc handling: don't leak sockets
  src/app/cli/src/coda_run.ml
Labels: ready-to-merge

#2925 remove State_hash.to_bytes
  src/app/cli/src/coda_commands.ml
  src/app/cli/src/graphql.ml
  src/lib/coda_base/state_hash.ml
  src/lib/coda_base/state_hash.mli
  src/lib/transition_frontier/diff.ml
Labels: ready-to-merge

#2842 Feature/incremental ledger catchup
  CODEOWNERS
  src/app/cli/src/coda_commands.ml
  src/app/cli/src/graphql.ml
  src/config/test_postake_delegation.mlh
  src/config/test_postake_delegation_medium_curves.mlh
  src/config/test_postake_holy_grail.mlh
  src/lib/coda_intf/network_intf.ml
  src/lib/coda_intf/transition_frontier_components_intf.ml
  src/lib/coda_intf/transition_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_transition/external_transition.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/ledger_catchup/dune
  src/lib/ledger_catchup/inputs.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/merkle_list/dune
  src/lib/merkle_list/merkle_list.ml
  src/lib/non_empty_list/non_empty_list.ml
  src/lib/non_empty_list/non_empty_list.mli
  src/lib/root_prover/root_prover.ml
  src/lib/rose_tree/dune
  src/lib/rose_tree/rose_tree.ml
  src/lib/rose_tree/rose_tree.mli
  src/lib/sync_handler/sync_handler.ml
  src/lib/transition_chain_witness/dune
  src/lib/transition_chain_witness/transition_chain_witness.ml
  src/lib/transition_frontier_controller_tests/stubs.ml
  src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml
  src/lib/transition_handler/breadcrumb_builder.ml
  src/transition_chain_witness.opam
Labels: ready-to-merge

#3054 Log not-performed bans; don't ban on add_trust
  src/lib/trust_system/peer_trust.ml
  src/lib/trust_system/record.ml
  src/lib/trust_system/record.mli
Labels: ready-to-merge

#3034 Update docs
  CODE_OF_CONDUCT.md
  docs/consensus.md
  docs/directory-structure.md
  docs/lifecycle-payment.md
  docs/lifecycle_of_a_payment_technical.md
  docs/proof-of-stake.md
  docs/reporting-guidelines.md
  frontend/website/docs/architecture/consensus.md
  frontend/website/docs/architecture/lifecycle-payment-technical.md
  frontend/website/docs/architecture/lifecycle-payment.md
  frontend/website/docs/architecture/proof-of-stake.md
  frontend/website/docs/coda-testnet.md
  frontend/website/docs/contributing.md
  frontend/website/docs/developers/codebase-overview.md
  frontend/website/docs/developers/directory-structure.md
  frontend/website/docs/developers/style-guide.md
  frontend/website/docs/faq.md
  frontend/website/docs/getting-started.md
  frontend/website/docs/index.md
  frontend/website/docs/reporting-guidelines.md
  frontend/website/docs/troubleshooting.md
  frontend/website/mkdocs.yml
Labels: website

#2609 Parallel scan refactor (part 1 and part 2)
  src/app/cli/src/coda_worker_testnet.ml
  src/app/cli/src/full_test.ml
  src/config/dev.mlh
  src/config/fake_hash.mlh
  src/config/scan_state/medium.mlh
  src/config/scan_state/point1tps.mlh
  src/config/scan_state/small.mlh
  src/config/scan_state/standard.mlh
  src/config/scan_state/tiny.mlh
  src/config/test_postake_bootstrap.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_five_even_snarkless.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_txns.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/coda_intf/staged_ledger_intf.ml
  src/lib/coda_intf/tmp_test_stub_hack.ml
  src/lib/parallel_scan/dune
  src/lib/parallel_scan/parallel_scan.ml
  src/lib/parallel_scan/parallel_scan.mli
  src/lib/parallel_scan/ring_buffer.ml
  src/lib/parallel_scan/scan_state.md
  src/lib/parallel_scan/state.ml
  src/lib/snark_params/snark_params.ml
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/state_or_error/dune
  src/lib/state_or_error/state_or_error.ml
  src/lib/state_or_error/state_or_error_intf.ml
  src/lib/transaction_snark_scan_state/constants.ml
  src/lib/transaction_snark_scan_state/constants.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transition_frontier/extensions.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/state_or_error.opam
Labels: ready-to-merge

#3057 Announcment bar points to hello coda + typos
  frontend/website/docs/getting-started.md
  frontend/website/src/AnnouncementBar.re
Labels: ready-to-merge

#3056 Fix fd leak when connect() fails
  src/app/cli/src/coda_run.ml
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#3059 Add txn failure docs
  frontend/website/docs/architecture/lifecycle-payment.md
  frontend/website/docs/getting-started.md
Labels: documentation

#2364 Schnorr signatures spec and reference code
  docs/specs/signatures/crs.py
  docs/specs/signatures/description.md
  docs/specs/signatures/reference.py
Labels: ready-to-merge

#3061 add new challenges
  frontend/website/docs/coda-testnet.md
Labels: documentation

#3046 Wait time for snark work reassignment
  src/app/cli/src/client.ml
  src/app/cli/src/coda.ml
  src/app/cli/src/coda_worker.ml
  src/app/cli/src/full_test.ml
  src/config/curve/medium.mlh
  src/config/curve/small.mlh
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_frontend.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/fake_hash.mlh
  src/config/test_postake.mlh
  src/config/test_postake_bootstrap.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_delegation.mlh
  src/config/test_postake_delegation_medium_curves.mlh
  src/config/test_postake_five_even_snarkless.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_snarkless_medium_curves_unit_test.mlh
  src/config/test_postake_snarkless_unittest.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_split_snarkless.mlh
  src/config/test_postake_split_snarkless_medium_curves.mlh
  src/config/test_postake_txns.mlh
  src/config/test_postake_txns_medium_curves.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_proposers.mlh
  src/config/testnet_postake_many_proposers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/lib/cli_lib/default.ml
  src/lib/cli_lib/fee.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/config.ml
  src/lib/work_selector/dune
  src/lib/work_selector/intf.ml
  src/lib/work_selector/test.ml
  src/lib/work_selector/work_lib.ml
Labels: ready-to-merge

#3058 Parallel scan bin-io
  .circleci/config.yml
  .circleci/config.yml.jinja
  README-dev.md
  dockerfiles/Dockerfile
  src/lib/parallel_scan/dune
  src/lib/parallel_scan/parallel_scan.ml
  src/lib/parallel_scan/parallel_scan.mli
  src/opam.export
Labels: ready-to-merge

#3038 Staged ledger hash optional for dump-ledger; script to generate OCaml genesis
  .genesis-ledger.ml.jinja
  CODEOWNERS
  Makefile
  scripts/generate-genesis-ledger.py
  src/app/cli/src/client.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/daemon_rpcs/daemon_rpcs.ml
Labels: ready-to-merge

#3063 Website: add new bios
  frontend/website/src/Docs.re
  frontend/website/src/TeamSection.re
  frontend/website/static/img/janecka.jpg
  frontend/website/static/img/swann.jpg
  frontend/website/static/img/tekişalp.jpg
Labels: ready-to-merge

#2527 New schnorr
  src/lib/coda_base/schnorr.ml
  src/lib/coda_base/signature.ml
  src/lib/coda_base/signature.mli
  src/lib/coda_base/user_command.ml
  src/lib/coda_state/blockchain_state.ml
  src/lib/coda_state/blockchain_state.mli
  src/lib/signature_lib/checked.ml
  src/lib/signature_lib/dune
Labels: ready-to-merge
