Repository MinaProtocol/mina, pull requests merged in 2019-10, with the labels that each got.

#3531 Trivial: old privs, new pubs
  src/lib/genesis_ledger/testnet_postake_ledger.ml
Labels: ready-to-merge

#3538 Registration of async shutdown handlers
  src/app/cli/src/init/coda_run.ml
  src/lib/exit_handlers/dune
  src/lib/exit_handlers/exit_handlers.ml
Labels: ready-to-merge

#3541 Expose more information in Sparse_ledger error messages
  src/lib/sparse_ledger_lib/sparse_ledger.ml
Labels: ready-to-merge

#3544 Return status-code 200 on graphql server error
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/graphql_internal.ml
Labels: ready-to-merge

#3423 [Feature] added docker docs and a docker release script
  docs/docker.md
  frontend/bot/Dockerfile
  frontend/bot/wait-for-it.sh
  scripts/release-docker.sh
Labels: ready-to-merge

#3548 Cleaning up some broken links on the root README
  README.md
Labels: ready-to-merge

#3550 trivial: remove unused import
  src/app/libp2p_helper/src/codanet.go
Labels: ready-to-merge

#3532 Conditionally update pins in CI
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  README-dev.md
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile-toolchain
  scripts/pin-external-packages.sh
  scripts/pin-external-submodules.sh
  scripts/update-opam-in-docker.sh
Labels: ready-to-merge

#3516 Poseidon for blockchain snark vks
  src/lib/blockchain_snark/blockchain_transition.ml
  src/lib/coda_base/transition_system.ml
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/keys_lib/keys.ml
  src/lib/snarky_verifier/bowe_gabizon.ml
  src/lib/verifier/prod.ml
Labels: ready-to-merge

#3555 Bot: Update reason-urql version (improve error msgs)
  frontend/bot/package.json
  frontend/bot/src/Coda.re
  frontend/bot/src/Echo.re
  frontend/bot/src/Faucet.re
  frontend/bot/src/Graphql.re
  frontend/bot/src/Repeater.re
  frontend/bot/src/SubscriptionsTransportWS.re
  frontend/bot/yarn.lock
Labels: ready-to-merge

#3563 Use .dockerenv, not CODA_DOCKER
  dockerfiles/Dockerfile-toolchain
  scripts/update-opam-in-docker.sh
Labels: ready-to-merge

#3530 Fix fake hash builds by fixing coda_net2 dune file
  src/lib/coda_net2/dune
Labels: ready-to-merge

#3545 a hack to mitigate bootstrap_pipe overflow bug
  src/lib/transition_router/initial_validator.ml
  src/lib/transition_router/transition_router.ml
Labels: ready-to-merge

#3425 Wallet: Support Account Lock/Unlock
  frontend/wallet/src/common/Bindings.re
  frontend/wallet/src/common/Wallet.re
  frontend/wallet/src/render/Theme.re
  frontend/wallet/src/render/components/Button.re
  frontend/wallet/src/render/components/Icon.re
  frontend/wallet/src/render/components/Modal.re
  frontend/wallet/src/render/components/RequestCodaModal.re
  frontend/wallet/src/render/components/SideBar.re
  frontend/wallet/src/render/components/TextField.re
  frontend/wallet/src/render/components/WalletName.re
  frontend/wallet/src/render/views/footer/Footer.re
  frontend/wallet/src/render/views/footer/SendButton.re
  frontend/wallet/src/render/views/footer/SendModal.re
  frontend/wallet/src/render/views/sidebar/AddWalletModal.re
  frontend/wallet/src/render/views/sidebar/SideBar.re
  frontend/wallet/src/render/views/sidebar/UnlockModal.re
  frontend/wallet/src/render/views/sidebar/WalletItem.re
  frontend/wallet/src/render/views/sidebar/WalletList.re
  frontend/wallet/src/render/views/walletlist/AddWalletModal.re
  frontend/wallet/src/render/views/walletlist/WalletItem.re
Labels: ready-to-merge

#3572 Kinds for child processes
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/child_processes/dune
  src/lib/child_processes/termination.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/test.ml
  src/lib/prover/prover.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transition_frontier_controller_tests/test_bootstrap_controller.ml
  src/lib/transition_frontier_controller_tests/test_catchup_scheduler.ml
  src/lib/transition_frontier_controller_tests/test_ledger_catchup.ml
  src/lib/transition_frontier_controller_tests/test_sync_handler.ml
  src/lib/transition_frontier_controller_tests/test_transaction_status.ml
  src/lib/transition_frontier_controller_tests/test_transition_frontier.ml
  src/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml
  src/lib/verifier/prod.ml
Labels: ready-to-merge

#3571 Separate update-deps for Rust toolchain
  Makefile
  scripts/update-rust-toolchain-references.sh
  scripts/update-toolchain-references.sh
Labels: ready-to-merge

#3578 Wallet: Enable copy/paste
  frontend/wallet/package.json
  frontend/wallet/src/main/App.re
  frontend/wallet/yarn.lock
Labels: ready-to-merge

#3450 Create testnet-retro-8.markdown
  frontend/website/posts/testnet-retro-8.markdown
Labels: ready-to-merge

#3582 Add new blogposts
  frontend/website/posts/testnet-press-release.markdown
  frontend/website/posts/testnet-retro-phase-1.markdown
  frontend/website/static/blog/testnet-press-release/testnet-advisors.jpg
  frontend/website/static/blog/testnet-retro-phase-1/block-count.png
  frontend/website/static/blog/testnet-retro-phase-1/twitter-card.jpg
Labels: ready-to-merge

#3584 Wallet: Onboarding
  frontend/wallet/package.json
  frontend/wallet/public/images/hero-illustration.svg
  frontend/wallet/public/index.html
  frontend/wallet/public/map@2x.png
  frontend/wallet/src/common/Bindings.re
  frontend/wallet/src/main/App.re
  frontend/wallet/src/main/DaemonProcess.re
  frontend/wallet/src/render/Apollo.re
  frontend/wallet/src/render/Preload.re
  frontend/wallet/src/render/ReactApp.re
  frontend/wallet/src/render/Theme.re
  frontend/wallet/src/render/components/Link.re
  frontend/wallet/src/render/components/Loader.re
  frontend/wallet/src/render/components/RequestCodaModal.re
  frontend/wallet/src/render/components/Window.re
  frontend/wallet/src/render/contexts/OnboardingProvider.re
  frontend/wallet/src/render/views/onboarding/AccountCreationStep.re
  frontend/wallet/src/render/views/onboarding/CompletionStep.re
  frontend/wallet/src/render/views/onboarding/Onboarding.re
  frontend/wallet/src/render/views/onboarding/OnboardingHeader.re
  frontend/wallet/src/render/views/onboarding/SetupNodeStep.re
  frontend/wallet/src/render/views/onboarding/WelcomeStep.re
  frontend/wallet/src/render/views/settings/NetworkDropdown.re
Labels: ready-to-merge

#3596 Try-with for stop_snark_worker RPC in disconnect
  src/app/cli/src/tests/coda_archive_node_test.ml
  src/app/cli/src/tests/coda_batch_payment_test.ml
  src/app/cli/src/tests/coda_block_production_test.ml
  src/app/cli/src/tests/coda_bootstrap_test.ml
  src/app/cli/src/tests/coda_change_snark_worker_test.ml
  src/app/cli/src/tests/coda_delegation_test.ml
  src/app/cli/src/tests/coda_five_nodes_test.ml
  src/app/cli/src/tests/coda_long_fork.ml
  src/app/cli/src/tests/coda_peers_test.ml
  src/app/cli/src/tests/coda_process.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_restart_node_test.ml
  src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml
  src/app/cli/src/tests/coda_shared_prefix_multiproposer_test.ml
  src/app/cli/src/tests/coda_shared_prefix_test.ml
  src/app/cli/src/tests/coda_shared_state_test.ml
  src/app/cli/src/tests/coda_transitive_peers_test.ml
  src/app/cli/src/tests/coda_txns_and_restart_non_proposers.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
Labels: ready-to-merge

#3586 Typo in kademlia-haskell/build/DEBIAN/control
  src/app/kademlia-haskell/build/DEBIAN/control
Labels: ready-to-merge

#3602 libp2p: use external IP
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/lib/coda_net2/coda_net2.ml
  src/lib/coda_net2/coda_net2.mli
  src/lib/gossip_net/gossip_net.ml
Labels: ready-to-merge

#3490 CLI command for generating SNARK flame graphs
  src/app/cli/src/coda.ml
  src/app/cli/src/init/dune
  src/app/cli/src/init/snark_flame_graphs.ml
Labels: ready-to-merge

#3511 Use base58 representation in visualizations
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/sync_ledger.ml
  src/lib/coda_state/blockchain_state.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/merkle_ledger/intf.ml
  src/lib/merkle_ledger_tests/test_stubs.ml
  src/lib/merkle_mask/maskable_merkle_tree.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#3606 fix leaderboard stuff
  frontend/website/package.json
  frontend/website/src/Testnet.re
  frontend/website/static/js/leaderboard.js
  frontend/website/yarn.lock
Labels: ready-to-merge

#3589 Serialization tests for types with version asserted
  src/lib/coda_base/signature.ml
  src/lib/coda_base/target.ml
  src/lib/coda_base/target.mli
  src/lib/merkle_ledger_tests/test_stubs.ml
  src/lib/module_version/README-version-asserted.md
  src/lib/module_version/dune
  src/lib/module_version/serialization.ml
  src/lib/non_zero_curve_point/dune
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/signature_lib/dune
  src/lib/trust_system/banned_status.ml
  src/lib/trust_system/dune
Labels: ready-to-merge

#3611 Fix bug where epoch was used instead of slot
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge

#3619 Don't pin ppx_optcomp in scripts
  scripts/pin-external-packages.sh
  scripts/update-opam-in-docker.sh
Labels: ready-to-merge

#3591 Serialization test for Proof
  src/lib/coda_base/proof.ml
Labels: ready-to-merge

#3614 CLI: Graphql cleanup/fixes
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/app/cli/src/init/graphql_query.ml
  src/lib/graphql_client_lib/dune
  src/lib/graphql_client_lib/graphql_client_lib.ml
Labels: ready-to-merge

#3620 [WIP] Wallet: Rename Wallet to Account
  frontend/wallet/public/build/icon.png
  frontend/wallet/public/menubar-icon.png
  frontend/wallet/public/menubar-icon@2x.png
  frontend/wallet/public/menubar-icon@3x.png
  frontend/wallet/public/menubar-iconTemplate.png
  frontend/wallet/public/menubar-iconTemplate@2x.png
  frontend/wallet/public/menubar-iconTemplate@3x.png
  frontend/wallet/src/render/Router.re
  frontend/wallet/src/render/components/Well.re
  frontend/wallet/src/render/views/footer/SendModal.re
  frontend/wallet/src/render/views/settings/AccountSettings.re
  frontend/wallet/src/render/views/settings/ConsensusSettings.re
  frontend/wallet/src/render/views/settings/SettingsPage.re
  frontend/wallet/src/render/views/sidebar/NewAccountModal.re
  frontend/wallet/src/render/views/sidebar/SideBar.re
  frontend/wallet/src/render/views/transactions/Transactions.re
Labels: not-ready-to-merge

#3622 Extended pooled_user_command_query to query all user commands in pool
  scripts/introspection_query.py
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge

#3600 Attempt to uncomment unit tests for codanet2
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  README-dev.md
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile-toolchain
  dockerfiles/Dockerfile-toolchain-haskell
  scripts/rebuild-deb.sh
  src/app/cli/src/tests/coda_processes.ml
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/lib/coda_net2/coda_net2.ml
Labels: ready-to-merge

#3626 Allow generation of let version = for types with params
  src/lib/ppx_coda/versioned.ml
Labels: ready-to-merge

#3634 [HOTFIX] Divide frontier update and disable expensive metrics
  src/lib/kademlia/membership.ml
  src/lib/non_empty_list/dune
  src/lib/non_empty_list/non_empty_list.ml
  src/lib/non_empty_list/non_empty_list.mli
  src/lib/transition_frontier/transition_frontier.ml
Labels: not-ready-to-merge

#3608 remove unused modules in verifier
  src/lib/prover/prover.ml
  src/lib/verifier/prod.ml
Labels: ready-to-merge

#3635 Fix the possibility of introducing a null for sync status
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/sync_status/dune
  src/lib/sync_status/sync_status.ml
Labels: ready-to-merge

#3588 [Fix] replace wait-for-it script
  frontend/bot/Dockerfile
  frontend/bot/wait-for-it.sh
  scripts/release-docker.sh
Labels: ready-to-merge

#3217 add Ledger_hash.merge benchmark
  src/app/benchmarks/dune
  src/app/benchmarks/main.ml
  src/lib/coda_base/dune
  src/lib/coda_base/ledger_hash.ml
Labels: ready-to-merge

#3631 base proof and merge proof metrics
  src/lib/coda_metrics/coda_metrics.ml
  src/lib/snark_worker/functor.ml
Labels: ready-to-merge

#3645 Fix for #3599
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/participating_state/dune
  src/lib/participating_state/participating_state.ml
Labels: ready-to-merge

#3649 versioned ppx for Ancestor
  src/lib/coda_state/ancestor.ml
Labels: ready-to-merge

#3632 re-annotate with tracing metadata
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/web_pipe.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_subscriptions.ml
  src/lib/gossip_net/gossip_net.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/o1trace/o1trace.ml
  src/lib/o1trace/o1trace.mli
  src/lib/proposer/proposer.ml
  src/lib/random_oracle/dune
  src/lib/random_oracle/random_oracle.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/breadcrumb_builder.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_router/transition_router.ml
Labels: ready-to-merge

#3624 Add graphiql explorer and codegen
  src/app/cli/src/init/assets/index_extensions.html
  src/app/cli/src/init/dune
  src/app/cli/src/init/graphql_internal.ml
Labels: ready-to-merge

#3647 versioned ppx for Account
  src/app/cli/src/tests/coda_worker.ml
  src/lib/coda_base/account.ml
  src/lib/merkle_ledger_tests/test_stubs.ml
Labels: ready-to-merge

#3651 Guard against unused desereialize_binary_opt
  src/lib/ppx_coda/versioned_module.ml
Labels: ready-to-merge

#3636 moving average for tps with 10 min rolling interval
  src/lib/coda_metrics/coda_metrics.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#3642 histogram for long async cycles
  src/app/cli/src/coda.ml
  src/lib/coda_metrics/coda_metrics.ml
Labels: ready-to-merge

#3643 Wallet: adds active and focus button styles
  frontend/wallet/src/render/components/Button.re
  frontend/wallet/src/render/components/TextField.re
Labels: ready-to-merge

#3656 Fix race when killing kademlia helper
  src/lib/kademlia/membership.ml
Labels: ready-to-merge

#3648 metrics for snark fee
  src/lib/coda_metrics/coda_metrics.ml
  src/lib/network_pool/snark_pool.ml
Labels: ready-to-merge

#3633 Syntax linter
  src/app/cli/src/tests/dune
  src/lib/blake2/dune
  src/lib/chunked_pedersen_lib/dune
  src/lib/coda_base/dune
  src/lib/coda_networking/dune
  src/lib/coda_numbers/dune
  src/lib/coda_transition/dune
  src/lib/consensus/dune
  src/lib/currency/dune
  src/lib/lite_base/dune
  src/lib/lite_lib/dune
  src/lib/merkle_address/dune
  src/lib/module_version/dune
  src/lib/network_pool/dune
  src/lib/parallel_scan/dune
  src/lib/ppx_coda/lint_version_syntax.ml
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/bad_version_syntax_bin_io_in_functor.ml
  src/lib/ppx_coda/tests/bad_version_syntax_bin_io_in_nested_functor.ml
  src/lib/ppx_coda/tests/bad_version_syntax_extension.ml
  src/lib/ppx_coda/tests/bad_version_syntax_missing_version.ml
  src/lib/ppx_coda/tests/bad_version_syntax_multiple_errors.ml
  src/lib/ppx_coda/tests/bad_version_syntax_version_in_functor.ml
  src/lib/ppx_coda/tests/bad_version_syntax_versioned_in_functor.ml
  src/lib/ppx_coda/tests/dune
  src/lib/ppx_coda/tests/good_version_syntax.ml
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/signature_lib/dune
  src/lib/snark_worker/dune
  src/lib/sparse_ledger_lib/dune
  src/lib/transaction_snark/dune
  src/lib/transition_frontier/dune
  src/lib/trust_system/dune
  src/lib/work_selector/dune
Labels: ready-to-merge

#3615 Fix typo on GUI wallet page url
  frontend/website/docs/gui-wallet.md
Labels: ready-to-merge

#3627 Created pooledUserCommands cli command
  graphql_schema.json
  src/app/archive/lib/processor.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/graphql_client_lib/graphql_client_lib.ml
Labels: ready for review

#3657 Versioned ppx in Coda_state...
  src/lib/coda_state/blockchain_state.ml
  src/lib/coda_state/protocol_state.ml
  src/lib/coda_state/snark_transition.ml
  src/lib/non_empty_list/non_empty_list.ml
  src/lib/trust_system/peer_status.ml
Labels: ready-to-merge

#3662 Jemalloc for develop
  .circleci/config.yml
  .circleci/config.yml.jinja
  README-dev.md
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile-toolchain
  scripts/macos-setup-brew.sh
  scripts/rebuild-deb.sh
  src/app/cli/src/coda.ml
  src/app/cli/src/dune
  src/dune
  src/lib/coda_metrics/coda_metrics.ml
  src/lib/coda_metrics/dune
  src/opam.export
Labels: ready-to-merge

#3679 Version ppx in aux db
  src/lib/auxiliary_database/external_transition_database.ml
  src/lib/auxiliary_database/filtered_external_transition.ml
Labels: ready-to-merge

#3664 Fix another race with kademlia helper restarts
  src/lib/gossip_net/gossip_net.ml
  src/lib/kademlia/membership.ml
Labels: ready-to-merge

#3683 Versioned ppx in Priced_proof
  src/lib/network_pool/priced_proof.ml
Labels: ready-to-merge

#3686 whoops! needed to delete extra loading line
  frontend/wallet/src/render/views/sidebar/UnlockModal.re
Labels: ready-to-merge

#3682 Versioned ppx in Internal_transition
  src/lib/coda_transition/internal_transition.ml
Labels: ready-to-merge

#3689 Enable the wallet to build on linux
  frontend/wallet/package.json
  frontend/wallet/src/main/DaemonProcess.re
  frontend/wallet/src/render/Theme.re
Labels: ready-to-merge

#3694 Versioned ppx for Transaction_snark
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge

#3690 versioned ppx Keypair, Work
  src/lib/signature_lib/keypair.ml
  src/lib/snark_work_lib/work.ml
Labels: ready-to-merge

#3687 Refactored Wallet to Account
  frontend/wallet/README.md
  frontend/wallet/src/common/Account.re
  frontend/wallet/src/common/CodaCliSettings.re
  frontend/wallet/src/common/Settings.rei
  frontend/wallet/src/render/Hooks.re
  frontend/wallet/src/render/Router.re
  frontend/wallet/src/render/components/AccountDropdownItem.re
  frontend/wallet/src/render/components/AccountName.re
  frontend/wallet/src/render/components/AddressPill.re
  frontend/wallet/src/render/components/RequestCodaModal.re
  frontend/wallet/src/render/views/footer/Footer.re
  frontend/wallet/src/render/views/footer/SendButton.re
  frontend/wallet/src/render/views/footer/SendModal.re
  frontend/wallet/src/render/views/onboarding/AccountCreationStep.re
  frontend/wallet/src/render/views/settings/AccountSettings.re
  frontend/wallet/src/render/views/settings/SettingsPage.re
  frontend/wallet/src/render/views/sidebar/AccountItem.re
  frontend/wallet/src/render/views/sidebar/AccountList.re
  frontend/wallet/src/render/views/sidebar/NewAccountModal.re
  frontend/wallet/src/render/views/sidebar/SideBar.re
  frontend/wallet/src/render/views/sidebar/UnlockModal.re
  frontend/wallet/src/render/views/transactions/TransactionCell.re
  frontend/wallet/src/render/views/transactions/Transactions.re
Labels: ready-to-merge

#3696 Same pps in dune libraries for Vrf
  src/lib/vrf_lib/dune
Labels: ready-to-merge

#3698 Version ppx for Proof_carrying_data
  src/lib/proof_carrying_data/dune
  src/lib/proof_carrying_data/proof_carrying_data.ml
Labels: ready-to-merge

#3695 Version ppx With_hash
  src/lib/with_hash/with_hash.ml
Labels: ready-to-merge

#3697 Version ppx for Sync_status, Syncable_ledger
  src/lib/sync_status/sync_status.ml
  src/lib/syncable_ledger/syncable_ledger.ml
Labels: ready-to-merge

#3517 fixing cache leak in transition processor
  src/lib/transition_handler/processor.ml
Labels: ready-to-merge

#3709 Hotfix/delete binary data from log
  src/lib/consensus/proof_of_stake.ml
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/ledger_proof/ledger_proof_intf.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ready-to-merge

#3704 Website: Fix echo service link
  frontend/website/docs/my-first-transaction.md
Labels: ready-to-merge

#3655 Versioned ppx for Truth, External_transition
  src/lib/coda_transition/external_transition.ml
  src/lib/truth/dune
  src/lib/truth/truth.ml
  src/lib/truth/truth.mli
Labels: ready-to-merge

#3681 Versioned ppx in Blockchain
  src/lib/blockchain_snark/blockchain.ml
  src/lib/blockchain_snark/blockchain.mli
  src/lib/prover/prover.ml
  src/lib/verifier/prod.ml
Labels: ready-to-merge

#3663 Refactored receipt_chain_database
  CODEOWNERS
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/cli_lib/render.ml
  src/lib/coda_base/dune
  src/lib/coda_base/payment_proof.ml
  src/lib/coda_base/payment_proof.mli
  src/lib/coda_base/receipt.mli
  src/lib/coda_base/receipt_chain_database.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_lib/dune
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/receipt_chain_database/dune
  src/lib/receipt_chain_database/intf.ml
  src/lib/receipt_chain_database/receipt_chain_database.ml
  src/lib/receipt_chain_database/receipt_chain_database.mli
  src/lib/receipt_chain_database/tree_node.ml
  src/lib/receipt_chain_database_lib/database.ml
  src/lib/receipt_chain_database_lib/database.mli
  src/lib/receipt_chain_database_lib/intf.ml
  src/lib/receipt_chain_database_lib/payment_proof.ml
  src/lib/receipt_chain_database_lib/tree_node.ml
  src/lib/receipt_chain_database_lib/verifier.ml
  src/receipt_chain_database.opam
Labels: ready-to-merge

#3597 Feature/transition frontier diff
  .gitattributes
  CODEOWNERS
  scripts/archive/change_constraint.py
  scripts/archive/check_hasura_configurations.sh
  scripts/archive/docker-compose.override.yml
  scripts/archive/make_and_check_hasura_configurations.sh
  scripts/archive/make_hasura_configurations.sh
  scripts/archive/metadata.json
  src/app/archive/archive.opam
  src/app/archive/archive_graphql_schema.json
  src/app/archive/create_schema.sql
  src/app/archive/dune-project
  src/app/archive/lib/archive_lib.opam
  src/app/archive/lib/ast.ml
  src/app/archive/lib/dune
  src/app/archive/lib/dune-project
  src/app/archive/lib/graphql_query.ml
  src/app/archive/lib/graphql_query.opam
  src/app/archive/lib/graphql_query/base_types.ml
  src/app/archive/lib/graphql_query/blocks.ml
  src/app/archive/lib/graphql_query/clear_data.ml
  src/app/archive/lib/graphql_query/dune
  src/app/archive/lib/graphql_query/fee_transfers.ml
  src/app/archive/lib/graphql_query/graphql_query.ml
  src/app/archive/lib/graphql_query/public_keys.ml
  src/app/archive/lib/graphql_query/user_commands.ml
  src/app/archive/lib/processor.ml
  src/app/archive/lib/test.ml
  src/app/archive/lib/types.ml
  src/app/cli/src/init/client.ml
  src/lib/base58_check/version_bytes.ml
  src/lib/coda_base/block_time.ml
  src/lib/coda_base/block_time.mli
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/data_hash.mli
  src/lib/coda_base/fee_transfer.ml
  src/lib/coda_base/fee_transfer.mli
  src/lib/coda_base/transaction_hash.ml
  src/lib/coda_numbers/length.ml
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
Labels: ready-to-merge

#3723 Van helsing docs update
  frontend/website/docs/getting-started.md
  frontend/website/docs/my-first-transaction.md
  frontend/website/docs/node-operator.md
  frontend/website/docs/troubleshooting.md
Labels: ready-to-merge

#3265 Add serve config and update routes
  frontend/website/serve.json
  frontend/website/src/AnnouncementBar.re
  frontend/website/src/Nav.re
  frontend/website/src/Render.re
Labels: ready-to-merge, website

#3729 Require versioned types in constraints
  src/lib/ppx_coda/versioned.ml
Labels: ready-to-merge

#3732 Next proposal status supports time offsets
  src/lib/coda_base/block_time.ml
  src/lib/coda_base/block_time.mli
  src/lib/coda_commands/coda_commands.ml
Labels: ready-to-merge

#3745 Website: Fix testnet stats url
  frontend/website/src/Testnet.re
Labels: ready-to-merge

#3727 %%versioned many daemon RPC types
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/signature_lib/keypair.ml
  src/lib/signature_lib/keypair.mli
Labels: ready-to-merge

#3735 Build libp2p in CI
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#3748 Website: Rename to platform engineer
  frontend/website/jobs/platform-engineer.markdown
  frontend/website/jobs/senior-frontend-engineer.markdown
  frontend/website/src/Render.re
Labels: ready-to-merge

#3750 Require build-auxiliary job
  .mergify.yml
  scripts/test.py
Labels: ready-to-merge

#3741 Lift Merkel_address, Transaction_logic versioned types out of functors
  src/lib/coda_base/ledger.mli
  src/lib/coda_base/transaction_logic.ml
  src/lib/merkle_address/merkle_address.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Labels: ready-to-merge

#3684 Lint detects "include Stable.Latest"
  src/lib/blake2/blake2.ml
  src/lib/blake2/intf.ml
  src/lib/coda_base/block_time.ml
  src/lib/coda_base/signature.ml
  src/lib/coda_base/signature.mli
  src/lib/coda_base/user_command.ml
  src/lib/ppx_coda/lint_version_syntax.ml
Labels: ready-to-merge

#3724 Wallet: Update peers for latest Testnet
  frontend/wallet/src/render/CodaProcess.re
  frontend/wallet/src/render/views/onboarding/SetupNodeStep.re
Labels: ready-to-merge

#3765 Website: Change Read here to Join Now
  frontend/website/src/AnnouncementBar.re
Labels: ready-to-merge

#3769 fix ocaml format
  src/lib/coda_lib/coda_lib.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
Labels: ready-to-merge

#3777 Update Set up port forwarding and any firewalls
  frontend/website/docs/getting-started.md
Labels: ready-to-merge

#3778 Update Using UPnP
  frontend/website/docs/troubleshooting.md
Labels: ready-to-merge

#3770 Wallet: Add log link to tray
  frontend/wallet/src/main/App.re
  frontend/wallet/src/main/DaemonProcess.re
Labels: ready-to-merge

#3718 Functored over the monad for key_value_db
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/auxiliary_database/external_transition_database.ml
  src/lib/auxiliary_database/transaction_database.ml
  src/lib/best_tip_prover/best_tip_prover.ml
  src/lib/coda_base/ledger.ml
  src/lib/kademlia/membership.ml
  src/lib/key_value_database/key_value_database.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/intf.ml
  src/lib/merkle_ledger_tests/test_stubs.ml
  src/lib/merkle_list_prover/merkle_list_prover.ml
  src/lib/receipt_chain_database/intf.ml
  src/lib/receipt_chain_database/receipt_chain_database.ml
  src/lib/receipt_chain_database/receipt_chain_database.mli
  src/lib/rocksdb/database.ml
  src/lib/rocksdb/serializable.ml
  src/lib/test/dune
  src/lib/test/test.ml
  src/lib/transition_chain_prover/transition_chain_prover.ml
  src/lib/transition_frontier_persistence/transition_frontier_persistence.ml
  src/lib/transition_frontier_persistence/worker.ml
  src/lib/trust_system/peer_trust.ml
  src/lib/trust_system/peer_trust.mli
Labels: ready-to-merge

#3670 pending snark work (fixes #3504)
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/cli_lib/graphql_types.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/work_selector/intf.ml
  src/lib/work_selector/random.ml
  src/lib/work_selector/sequence.ml
  src/lib/work_selector/work_lib.ml
Labels: ready-to-merge

#3779 Fixes warning
  frontend/wallet/src/render/views/onboarding/AccountCreationStep.re
  frontend/wallet/src/render/views/onboarding/CompletionStep.re
  frontend/wallet/src/render/views/onboarding/SetupNodeStep.re
  frontend/wallet/src/render/views/onboarding/WelcomeStep.re
Labels: ready-to-merge

#3773 fix blog post bug
  frontend/website/posts/testnet-retro-8.markdown
  frontend/website/src/BlogPost.re
Labels: ready-to-merge

#3783 Fix units in jemalloc stats
  src/app/cli/src/coda.ml
  src/lib/coda_metrics/coda_metrics.ml
Labels: ready-to-merge

#3800 Remove cryptography engineer job posting
  frontend/website/jobs/cryptography-engineer.markdown
  frontend/website/src/Render.re
Labels: ready-to-merge

#3744 Refactor child process management into library
  src/app/cli/src/coda.ml
  src/lib/child_processes/caml_syslimits.c
  src/lib/child_processes/child_processes.ml
  src/lib/child_processes/child_processes.mli
  src/lib/child_processes/dune
  src/lib/child_processes/syslimits.ml
  src/lib/child_processes/tester.sh
  src/lib/coda_net2/coda_net2.ml
  src/lib/coda_net2/dune
  src/lib/file_system/file_system.ml
  src/lib/kademlia/dune
  src/lib/kademlia/membership.ml
  src/lib/logger/impl.ml
  src/lib/logger/impl.mli
Labels: ready-to-merge

#3797 Displayed field representation of state_hash
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/data_hash.mli
  src/lib/coda_base/data_hash_intf.ml
  src/lib/coda_base/state_hash.ml
  src/lib/coda_base/state_hash.mli
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge

#3782 delete snarked-ledger-verification
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
Labels: ready-to-merge

#3796 SNARK docs
  frontend/website/docs/snarks/constructions.md
  frontend/website/docs/snarks/index.md
  frontend/website/docs/snarks/snarky-universe.md
  frontend/website/docs/snarks/snarky.md
  frontend/website/docs/snarks/snarkyjs-crypto.md
  frontend/website/mkdocs.yml
  frontend/website/serve.json
Labels: ready-to-merge

#3802 Fix/snark niceness
  src/app/cli/src/coda.ml
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/blockchain_snark/blockchain_snark_state.mli
  src/lib/blockchain_snark/blockchain_transition.ml
  src/lib/coda_base/transition_system.ml
  src/lib/prover/prover.ml
  src/lib/prover/prover.mli
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge

#3812 Graphql: add experimental verification key
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_graphql/dune
Labels: ready-to-merge

#3795 Flesh out pinned package instructions
  README-dev.md
Labels: ready-to-merge

#3817 Disallow include Stable.Vn
  src/lib/ppx_coda/lint_version_syntax.ml
  src/lib/secrets/secret_box.ml
Labels: ready-to-merge

#3660 Versioned ppx in Coda_base
  src/lib/auxiliary_database/external_transition_database.ml
  src/lib/auxiliary_database/pagination.ml
  src/lib/coda_base/block_time.ml
  src/lib/coda_base/fee_transfer.ml
  src/lib/coda_base/payment_payload.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/pending_coinbase_witness.ml
  src/lib/coda_base/sok_message.ml
  src/lib/coda_base/stake_delegation.ml
  src/lib/coda_base/sync_ledger.ml
  src/lib/coda_base/transaction.ml
  src/lib/coda_base/transaction_witness.ml
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command_memo.ml
  src/lib/coda_base/user_command_payload.ml
Labels: ready-to-merge

#3661 Versioned ppx in Proof_of_stake
  src/lib/consensus/proof_of_stake.ml
  src/lib/ppx_coda/versioned_module.ml
Labels: ready-to-merge

#3809 Use %%versioned in Parallel_scan
  src/lib/parallel_scan/dune
  src/lib/parallel_scan/parallel_scan.ml
Labels: ready-to-merge

#3818 Added behaviors to new block subscription
  src/app/cli/src/tests/coda_worker.ml
  src/lib/auxiliary_database/filtered_external_transition.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/coda_subscriptions.ml
Labels: ready-to-merge

#3820 Lift Verification_key out of functor
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/lite_precomputed_values/dune
  src/lib/lite_precomputed_values/gen/dune
  src/lib/lite_precomputed_values/gen/gen.ml
  src/lib/snarkette/bowe_gabizon.ml
Labels: ready-to-merge
