Repository MinaProtocol/mina, pull requests merged in 2020-08, with the labels that each got.

#5491 Remove fake hash
  .circleci/config.yml
  .mergify.yml
  scripts/test.py
  src/app/cli/src/coda.ml
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_frontend.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/fake_hash.mlh
  src/config/fuzz_medium.mlh
  src/config/fuzz_small.mlh
  src/config/nonconsensus_medium_curves.mlh
  src/config/print_versioned_types.mlh
  src/config/test_archive_processor.mlh
  src/config/test_postake.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_full_epoch.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_producers.mlh
  src/config/testnet_postake_many_producers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/lib/coda_base/user_command.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5534 Derive [eq, bin_io, sexp, compare, yojson, hash] in zexe backends
  src/lib/zexe_backend/zexe_backend_common/curve.ml
  src/lib/zexe_backend/zexe_backend_common/field.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5548 Rosetta: Supports empty partial block id
  src/app/rosetta/lib/block.ml
  src/app/rosetta/test-curl/block-newest.sh
Labels: ci-build-me, ready-to-merge

#5538 [trivial] Moves operation expectation to file
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/operation_expectation.ml
Labels: ci-build-me, ready-to-merge

#5545 Validate block production rate
  src/app/validation/config/config.exs
  src/app/validation/lib/architecture/log_provider.ex
  src/app/validation/lib/architecture/statistic.ex
  src/app/validation/lib/architecture/validation.ex
  src/app/validation/lib/coda.ex
  src/app/validation/lib/coda/application.ex
  src/app/validation/lib/coda/providers/block_produced.ex
  src/app/validation/lib/coda/resource_classifier.ex
  src/app/validation/lib/coda/resources/block_producer.ex
  src/app/validation/lib/coda/statistics/block_production_rate.ex
  src/app/validation/lib/coda/validations/block_production_rate.ex
  src/app/validation/lib/coda/validations/configuration.ex
  src/app/validation/lib/util.ex
  src/app/validation/mix.exs
  src/app/validation/mix.lock
Labels: ci-build-me, ready-to-merge-into-develop

#5536 Separate Random_oracle.Input into its own library
  src/lib/coda_base/account_id.ml
  src/lib/coda_base/account_id.mli
  src/lib/coda_base/transaction_union_tag.ml
  src/lib/random_oracle/dune
  src/lib/random_oracle/intf.ml
  src/lib/random_oracle/random_oracle.ml
  src/lib/random_oracle/random_oracle.mli
  src/lib/random_oracle_input/dune
  src/lib/random_oracle_input/random_oracle_input.ml
  src/nonconsensus/random_oracle/dune
  src/nonconsensus/random_oracle/input.ml
  src/random_oracle_input.opam
Labels: ci-build-me, ready-to-merge-into-develop

#5560 Rosetta agent test assures block matches mempool
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/validation.ml
  src/app/rosetta/start.sh
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/operation_expectation.ml
  src/app/rosetta/test-agent/peek.ml
Labels: ci-build-me, ready-to-merge

#5568 [Trivial] Deduplicate ppx entries in dune files
  src/lib/base58_check/dune
  src/lib/consensus/dune
  src/lib/merkle_mask/dune
  src/lib/snark_worker/dune
  src/lib/trust_system/dune
  src/lib/vrf_lib/dune
Labels: ci-build-me, ready-to-merge-into-develop

#5577 Change block parsing in Leaderboard automation
  frontend/leaderboard/__tests__/blocks/block1.json
  frontend/leaderboard/__tests__/blocks/block10.json
  frontend/leaderboard/__tests__/blocks/block2.json
  frontend/leaderboard/__tests__/blocks/block3.json
  frontend/leaderboard/__tests__/blocks/block4.json
  frontend/leaderboard/__tests__/blocks/block5.json
  frontend/leaderboard/__tests__/blocks/block6.json
  frontend/leaderboard/__tests__/blocks/block7.json
  frontend/leaderboard/__tests__/blocks/block8.json
  frontend/leaderboard/__tests__/blocks/block9.json
  frontend/leaderboard/__tests__/leaderboard_test.re
  frontend/leaderboard/bsconfig.json
  frontend/leaderboard/package.json
  frontend/leaderboard/src/Bindings.re
  frontend/leaderboard/src/Challenges.re
  frontend/leaderboard/src/Main.re
  frontend/leaderboard/src/Metrics.re
  frontend/leaderboard/src/Postgres.re
  frontend/leaderboard/src/Sheets.re
  frontend/leaderboard/src/Types.re
  frontend/leaderboard/src/UploadLeaderboardData.re
  frontend/leaderboard/src/UploadLeaderboardPoints.re
Labels: ci-build-me

#5578 Use Stable.Latest in packages
  src/lib/precomputed_values/gen_values/dune
  src/lib/precomputed_values/gen_values/gen_values.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5430 rosetta/dockerfile Add new dockerfile to build for rosetta
  dockerfiles/Dockerfile-rosetta
  scripts/build-rosetta-prod-from-git.sh
  scripts/build-rosetta-stages.sh
  scripts/select-opam-deps.sh
  src/app/rosetta/config.json
  src/app/rosetta/demo-config.json
  src/app/rosetta/docker-start.sh
  src/app/rosetta/docker-test-start.sh
  src/app/rosetta/lib/rosetta.ml
Labels: ci-build-me, ready-to-merge

#5581 Supports new snark and exit when tests stop
  src/app/rosetta/docker-test-start.sh
  src/app/rosetta/make-runtime-genesis.sh
  src/app/rosetta/run-demo.sh
  src/app/rosetta/start.sh
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/poke.ml
  src/app/rosetta/test-curl/account_list.sh
Labels: ci-build-me, ready-to-merge

#5584 Rosetta/dockerfile Final fixes
  dockerfiles/Dockerfile-rosetta
  scripts/build-and-test-rosetta-from-git.sh
  scripts/build-rosetta-prod-from-git.sh
  src/app/rosetta/demo-config.json
  src/app/rosetta/docker-test-start.sh
Labels: ci-build-me, ready-to-merge

#5586 demo mode bypass initialization
  src/lib/coda_intf/transition_frontier_components_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me, ready-to-merge

#5582 Fixes compare test signatures job
  buildkite/scripts/compare_test_signatures.sh
  buildkite/src/Command/OpamInit.dhall
  buildkite/src/Jobs/CompareSignatures.dhall
Labels: ci-build-me, ready-to-merge

#5569 Includes retry support in command config
  buildkite/src/Command/.Base.dhall.swp
  buildkite/src/Command/Base.dhall
  buildkite/src/External/Buildkite.dhall
Labels: ci-build-me, ready-to-merge

#5583 increase rpc connection timeout
  src/app/cli/src/init/coda_run.ml
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/daemon_rpcs/client.ml
  src/lib/snark_worker/functor.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5594 Snark coordinator without local snark worker process
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/config.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5579 snark pool batching
  src/lib/network_pool/intf.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5580 Keep track of all the snark jobs at the best tip
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/snark_worker/functor.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/work_selector/inputs.ml
  src/lib/work_selector/intf.ml
  src/lib/work_selector/random.ml
  src/lib/work_selector/sequence.ml
  src/lib/work_selector/test.ml
  src/lib/work_selector/work_lib.ml
  src/lib/work_selector/work_selector.ml
  src/lib/work_selector/work_selector.mli
Labels: ci-build-me, ready-to-merge-into-develop

#5532 upgrade libp2p version
  docs/testnet-guardian-runbook.md
  frontend/wallet/src/main/DaemonProcess.re
  frontend/wallet/src/render/CodaProcess.re
  frontend/website/pages/docs/cli-reference.mdx
  rfcs/0029-libp2p.md
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/lib/coda_net2/coda_net2.ml
  src/lib/coda_net2/coda_net2.mli
  src/lib/gossip_net/libp2p.ml
  src/lib/network_peer/peer.ml
  src/lib/node_addrs_and_ports/node_addrs_and_ports.ml
Labels: ci-build-me, ready-to-merge, ready-to-merge-into-develop

#5601 ensure docker-artifact build/release script shares pass/fail fate of embedded commands
  buildkite/scripts/docker-artifact.sh
Labels: ci-build-me

#5550 Add token commands to CLI
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/coda_graphql/coda_graphql.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5605 Fix buildkite CI before 3.3 branch cut
  buildkite/scripts/build-artifact.sh
  buildkite/src/Command/WithCargo.dhall
  buildkite/src/Jobs/ArchiveNode.dhall
  buildkite/src/Jobs/Sample.dhall
  buildkite/src/Jobs/Sample2.dhall
  dockerfiles/Dockerfile-rosetta
  scripts/build-rosetta-stages.sh
Labels: ci-build-me, ready-to-merge

#5598 Fail faster + cargo properly on build-artifacts
  buildkite/scripts/build-artifact.sh
Labels: ci-build-me

#5546 Plug together test framework
  src/app/test_executive/block_production_test.ml
  src/app/test_executive/block_production_test.mli
  src/app/test_executive/dune
  src/app/test_executive/network.ml
  src/app/test_executive/network_config.ml
  src/app/test_executive/test_executive.ml
  src/integration_test_cloud_engine.opam
  src/lib/block_time/block_time.ml
  src/lib/block_time/dune
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/integration_test_cloud_engine/dune
  src/lib/integration_test_cloud_engine/integration_test_cloud_engine.ml
  src/lib/integration_test_cloud_engine/integration_test_cloud_engine.mli
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/integration_test_cloud_engine/terraform.ml
  src/lib/integration_test_lib/block_production_test.ml
  src/lib/integration_test_lib/integration_test_lib.ml
  src/lib/integration_test_lib/stack_driver_log_engine.ml
  src/lib/integration_test_lib/test_intf.ml
  src/lib/timeout_lib/dune
  src/lib/timeout_lib/timeout_lib.ml
  src/timeout_lib.opam
Labels: ci-build-me, ready-to-merge-into-develop

#5609 Delete wallet page from the Docs and the repository
  frontend/website/pages/docs/gui-wallet.mdx
  frontend/website/src/components/DocsSideNav.re
Labels: ci-build-me, ready-to-merge

#5627 remove extraneous swap file
  buildkite/src/Command/.Base.dhall.swp
Labels: ci-build-me

#5620 Fixes fast demo test's failure
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/test-agent/agent.ml
Labels: ci-build-me, ready-to-merge

#5626 Fix build-artifact step with newly resolved permissions
  buildkite/scripts/build-artifact.sh
Labels: ci-build-me, ready-to-merge

#5631 Scaffolds Rosetta construction/derive endpoint
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/dune
  src/app/rosetta/lib/errors.ml
  src/app/rosetta/lib/rosetta.ml
  src/app/rosetta/models/enums.ml
  src/app/rosetta/start.sh
  src/app/rosetta/test-curl/con_derive.sh
  src/lib/cli_lib/commands.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/signature_lib/public_key.mli
Labels: ci-build-me, ready-to-merge

#5632 Rosetta scaffold inverted operations
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/dune
  src/app/rosetta/models/account_identifier.ml
  src/app/rosetta/models/amount.ml
  src/app/rosetta/models/currency.ml
  src/app/rosetta/models/dune
  src/app/rosetta/models/sub_account_identifier.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5618 Remove LIBP2P_NIXLESS
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  README-dev.md
  buildkite/agent.nix
  buildkite/docker.nix
  buildkite/shell.nix
  buildkite/src/Command/Libp2pHelperBuild.dhall
  buildkite/src/Jobs/ArchiveNode.dhall
  dockerfiles/Dockerfile-toolchain
  dockerfiles/Dockerfile-toolchain-libp2p
  scripts/librewrite-macos.sh
Labels: ci-build-me, ready-to-merge-into-develop

#5537 `to_input` for side loaded verification keys
  src/lib/pickles/common.ml
  src/lib/pickles/dune
  src/lib/pickles/marlin_checks/domain.ml
  src/lib/pickles/marlin_checks/dune
  src/lib/pickles/pairing_main.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/side_loaded_verification_key.ml
  src/lib/pickles/types_map.ml
  src/lib/pickles_types/abc.ml
  src/lib/pickles_types/at_most.ml
  src/lib/pickles_types/matrix_evals.ml
  src/lib/pickles_types/vector.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5635 Rosetta/test build rosetta dockerfile in ci
  buildkite/scripts/docker-artifact.sh
  buildkite/scripts/export-git-env-vars.sh
  buildkite/scripts/publish-deb.sh
  buildkite/src/Jobs/Artifact.dhall
  dockerfiles/Dockerfile-coda-daemon
  scripts/rebuild-deb.sh
  scripts/release-docker.sh
Labels: ci-build-me, ready-to-merge

#5600 [RFC] Rosetta Construction API Support
  rfcs/0038-rosetta-construction-api.md
Labels: ci-build-me, ready-to-merge

#5642 remove-deploy-env-override
  buildkite/DOCKER_DEPLOY_ENV
  dockerfiles/Dockerfile-coda-daemon
Labels: ci-build-me

#5652 Remove unused dyn_array lib
  src/dyn_array.opam
  src/lib/dyn_array/dune
  src/lib/dyn_array/dyn_array.ml
  src/lib/merkle_ledger/dune
  src/lib/merkle_mask/dune
Labels: ci-build-me, ready-to-merge-into-develop

#5643 Rosetta start.sh bad arg error
  src/app/rosetta/start.sh
Labels: ci-build-me, ready-to-merge

#5646 Add metadata endpoint
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/test-curl/con_metadata.sh
Labels: ci-build-me, ready-to-merge-into-develop

#5658 rosetta/add-docker-demo-start
  src/app/rosetta/docker-demo-start.sh
Labels: ci-build-me, ready-to-merge

#5662 Rosetta Preprocess endpoint
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/errors.ml
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/lib/user_command_info.ml
Labels: ci-build-me, ready-to-merge

#5660 set step scope of DOCKER_DEPLOY_ENV artifact download during docker artifact job
  buildkite/src/Command/DockerArtifact.dhall
Labels: ci-build-me

#5628 Do not download URS, snark keys from S3 on development profiles
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  buildkite/scripts/build-artifact.sh
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_frontend.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/fake_hash.mlh
  src/config/fuzz_medium.mlh
  src/config/fuzz_small.mlh
  src/config/nonconsensus_medium_curves.mlh
  src/config/print_versioned_types.mlh
  src/config/test_archive_processor.mlh
  src/config/test_postake.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_full_epoch.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_three_producers.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_producers.mlh
  src/config/testnet_postake_many_producers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/lib/key_cache/dune
  src/lib/key_cache/key_cache.ml
  src/lib/key_cache/key_cache.mli
  src/lib/snark_keys/gen_keys/gen_keys.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5685 add lint-opt job to Buildkite Coda pipeline
  buildkite/src/Command/Base.dhall
  buildkite/src/Jobs/Lint/Fast.dhall
  scripts/compare_pr_diff_items.py
Labels: ci-build-me

#5645 Snapp account prework
  src/lib/block_time/block_time.ml
  src/lib/block_time/block_time.mli
  src/lib/coda_base/account.ml
  src/lib/coda_base/account_timing.ml
  src/lib/coda_base/epoch_ledger.ml
  src/lib/coda_base/frozen_ledger_hash.mli
  src/lib/coda_base/frozen_ledger_hash0.ml
  src/lib/coda_base/import.ml
  src/lib/coda_base/ledger_hash.ml
  src/lib/coda_base/ledger_hash.mli
  src/lib/coda_base/ledger_hash0.ml
  src/lib/coda_base/ledger_hash0.mli
  src/lib/coda_base/ledger_hash_intf.ml
  src/lib/coda_base/ledger_hash_intf0.ml
  src/lib/coda_base/proof.ml
  src/lib/coda_base/receipt.ml
  src/lib/coda_base/staged_ledger_hash.ml
  src/lib/coda_base/staged_ledger_hash.mli
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/consensus/dune
  src/lib/consensus/proof_of_stake.ml
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/pickles/composition_types/bulletproof_challenge.ml
  src/lib/pickles/composition_types/composition_types.ml
  src/lib/pickles/composition_types/index.ml
  src/lib/pickles/composition_types/index.mli
  src/lib/pickles/limb_vector/constant.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/proof.ml
  src/lib/pickles/reduced_me_only.ml
  src/lib/pickles/side_loaded_verification_key.ml
  src/lib/pickles_types/dlog_marlin_types.ml
  src/lib/pickles_types/scalar_challenge.ml
  src/lib/pickles_types/vector.ml
  src/lib/random_oracle/dune
  src/lib/staged_ledger_diff/dune
  src/lib/staged_ledger_hash/dune
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark_scan_state/dune
  src/lib/with_hash/dune
  src/lib/with_hash/with_hash.ml
  src/lib/zexe_backend/zexe_backend_common/dlog_based_proof.ml
  src/nonconsensus/coda_base/account_timing.ml
  src/staged_ledger_hash.opam
Labels: ci-build-me, ready-to-merge-into-develop

#5640 Update Genesis Page copy for 3.3 release
  frontend/website/src/pages/Genesis.re
Labels: ci-build-me, ready-to-merge

#5689 Fix ambiguity in serialization of Random_oracle_input spec
  rfcs/0038-rosetta-construction-api.md
Labels: ci-build-me, ready-to-merge

#5706 migrate trace-tool build to buildkite ci and add tool rust linting step
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/Jobs/Lint/Rust.dhall
  buildkite/src/Jobs/TraceTool.dhall
Labels: ci-build-me

#5703 add default value for BASE_BRANCH var within compare_ci_diff scripts
  scripts/compare_ci_diff_binables.sh
  scripts/compare_ci_diff_types.sh
Labels: ci-build-me

#5656 Integration Test Error Collection
  src/app/logproc/dune
  src/app/test_executive/dune
  src/app/test_executive/test_executive.ml
  src/bash_colors.opam
  src/lib/bash_colors/bash_colors.ml
  src/lib/bash_colors/dune
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/integration_test_lib/integration_test_lib.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5686 Hex {en,de}coding for arbitrary bytes
  src/lib/hex/dune
  src/lib/hex/hex.ml
Labels: ci-build-me, ready-to-merge

#5644 timed accounts in genesis ledger
  src/lib/coda_base/account.ml
  src/lib/coda_numbers/dune
  src/lib/coda_numbers/intf.ml
  src/lib/coda_numbers/nat.ml
  src/lib/genesis_ledger/dune
  src/lib/genesis_ledger/fake_accounts.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger/intf.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
  src/nonconsensus/coda_numbers/dune
Labels: ci-build-me, ready-to-merge-into-develop

#5710 Rosetta, Unsigned_extended types for Yojson
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/user_command_info.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5707 Coding for random oracle serialize/deserialize
  src/lib/random_oracle_input/dune
  src/lib/random_oracle_input/random_oracle_input.ml
Labels: ci-build-me, ready-to-merge

#5708 Bump int test initialization timeout
  src/app/cli/src/tests/coda_processes.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5728 Ban senders of invalid snarks
  src/lib/coda_base/sok_message.ml
  src/lib/coda_base/sok_message.mli
  src/lib/network_peer/envelope.ml
  src/lib/network_peer/envelope.mli
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/snark_worker/functor.ml
  src/lib/verifier/dummy.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5731 Client SDK unit tests in CI
  .circleci/config.yml
  .circleci/config.yml.jinja
  .mergify.yml
  scripts/client-sdk-unit-tests.sh
  scripts/test.py
Labels: ci-build-me, ready-to-merge-into-develop

#5742 Buildkite CI: convert clientsdk job into client sdk build/(unit-)test and yarn deps install
  buildkite/scripts/build-client-sdk.sh
  buildkite/scripts/client-sdk-tool.sh
  buildkite/src/Jobs/ClientSdk.dhall
  scripts/client-sdk-unit-tests.sh
Labels: ci-build-me, infrastructure

#5740 add apt update to archive node CI postgres setup script
  buildkite/scripts/setup-database-for-archive-node.sh
Labels: ci-build-me

#5718 Website redesign/Icons file
  frontend/website-redesign/src/components/Icon.re
Labels: ci-build-me, ready-to-merge

#5747 Rosetta lib outside Rosetta app; more testing
  Makefile
  scripts/client-sdk-unit-tests.sh
  scripts/compare_test_signatures.sh
  src/app/client_sdk/client_sdk.ml
  src/app/client_sdk/dune
  src/app/client_sdk/tests/test_encodings.js
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/dune
  src/lib/rosetta_lib/coding.ml
  src/lib/rosetta_lib/dune
  src/lib/rosetta_lib/test/dune
  src/lib/rosetta_lib/test/test_encodings.ml
  src/lib/rosetta_lib/test/test_encodings.ml~
  src/nonconsensus/rosetta_lib/coding.ml
  src/nonconsensus/rosetta_lib/dune
  src/nonconsensus/rosetta_lib/test/dune
  src/nonconsensus/rosetta_lib/test/test_encodings.ml
  src/rosetta_lib.opam
  src/rosetta_lib_nonconsensus.opam
Labels: ci-build-me, ready-to-merge-into-develop

#5754 [Website] Token Productization Docs
  frontend/website/pages/docs/tokens.mdx
  frontend/website/src/components/DocsSideNav.re
Labels: ci-build-me, ready-to-merge

#5750 Remove emacs twiddle file
  src/lib/rosetta_lib/test/test_encodings.ml~
Labels: ci-build-me, ready-to-merge-into-develop

#5738 Implements hacky signature coding
  src/app/rosetta/lib/construction.ml
  src/hex_nonconsensus.opam
  src/lib/coda_base/signature.ml
  src/lib/coda_base/signature.mli
  src/nonconsensus/coda_base/dune
  src/nonconsensus/hex/dune
  src/nonconsensus/hex/hex.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5752 Use Rosetta lib coding for fields
  src/app/rosetta/lib/transaction.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5749 Adds submit endpoint
  src/app/rosetta/lib/construction.ml
  src/lib/coda_graphql/coda_graphql.ml
Labels: ci-build-me, ready-to-merge

#5763 Adds example curl for preprocess.sh
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-curl/con_preprocess.sh
Labels: ci-build-me, ready-to-merge-into-develop

#5751 To-spec encoding for Raw
  src/lib/coda_base/dune
  src/lib/coda_base/signature.ml
  src/lib/coda_base/signature.mli
  src/lib/rosetta_lib/coding.ml
  src/nonconsensus/coda_base/dune
  src/nonconsensus/snark_params/snark_params_nonconsensus.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5765 Begins support for construction in agent
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/dune
  src/app/rosetta/test-agent/offline.ml
  src/app/rosetta/test-agent/peek.ml
  src/app/rosetta/test-agent/poke.ml
  src/app/rosetta/test-agent/signer.ml
Labels: ci-build-me, ready-to-merge

#5748 add skip dhall Base Cmd config property
  buildkite/src/Command/Base.dhall
  buildkite/src/Jobs/Lint/Fast.dhall
Labels: ci-build-me

#5778 remove buildkite cmd soft-fail and skip examples from fast lint jobs
  buildkite/src/Jobs/Lint/Fast.dhall
  scripts/compare_ci_diff_binables.sh
  scripts/compare_ci_diff_types.sh
Labels: ci-build-me

#5766 Extends agent tests to payloads+parse
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/offline.ml
  src/lib/rosetta_models/coin_change.ml
  src/lib/rosetta_models/coin_identifier.ml
  src/lib/rosetta_models/enums.ml
  src/lib/rosetta_models/operation.ml
  src/lib/rosetta_models/operation_identifier.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5773 Website/leaderboard rebase
  frontend/leaderboard/__tests__/leaderboard_test.re
  frontend/leaderboard/src/Challenges.re
  frontend/leaderboard/src/Main.re
  frontend/leaderboard/src/Metrics.re
  frontend/leaderboard/src/Points.re
  frontend/leaderboard/src/Postgres.re
  frontend/leaderboard/src/Sheets.re
  frontend/leaderboard/src/Types.re
  frontend/leaderboard/src/UploadLeaderboardData.re
  frontend/leaderboard/src/UploadLeaderboardPoints.re
  frontend/website/public/static/img/LeaderboardAwardCommunityMVP.png
  frontend/website/public/static/img/LeaderboardAwardDoubleMVP.png
  frontend/website/public/static/img/LeaderboardAwardGenesisMember.png
  frontend/website/public/static/img/LeaderboardAwardTechnicalMVP.png
  frontend/website/public/static/img/LeaderboardEmpty.png
  frontend/website/public/static/img/star.svg
  frontend/website/src/components/Badge.re
  frontend/website/src/components/ChallengePointsTable.re
  frontend/website/src/components/Dropdown.re
  frontend/website/src/components/Leaderboard.re
  frontend/website/src/components/ProfileHero.re
  frontend/website/src/components/Summary.re
  frontend/website/src/components/Wrapped.re
  frontend/website/src/components/svg/Icons.re
  frontend/website/src/pages/LeaderboardPage.re
  frontend/website/src/pages/MemberProfilePage.re
  frontend/website/src/pages/Testnet.re
  frontend/website/yarn.lock
Labels: ci-build-me, ready-to-merge

#5720 Website redesign/buttons
  frontend/website-redesign/.gitignore
  frontend/website-redesign/pages/demo.js
  frontend/website-redesign/public/static/ButtonHoverDark.png
  frontend/website-redesign/public/static/ButtonHoverLight.png
  frontend/website-redesign/public/static/font/IBMPlexMono-Medium-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexMono-Medium-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexMono-SemiBold-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexMono-SemiBold-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-Bold-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-Bold-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-ExtraLight-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-ExtraLight-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-Italic-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-Italic-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-Light-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-Light-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-Medium-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-Medium-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-Regular-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-Regular-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-SemiBold-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-SemiBold-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-Text-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-Text-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSans-Thin-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSans-Thin-Latin1.woff2
  frontend/website-redesign/public/static/font/IBMPlexSerif-Medium-Latin1.woff
  frontend/website-redesign/public/static/font/IBMPlexSerif-Medium-Latin1.woff2
  frontend/website-redesign/public/static/font/d-dinexp-bold-webfont.woff
  frontend/website-redesign/public/static/font/d-dinexp-bold-webfont.woff2
  frontend/website-redesign/public/static/font/d-dinexp-webfont.woff
  frontend/website-redesign/public/static/font/d-dinexp-webfont.woff2
  frontend/website-redesign/public/static/font/metropolis-bold-webfont.woff
  frontend/website-redesign/public/static/font/metropolis-bold-webfont.woff2
  frontend/website-redesign/public/static/font/metropolis-extralight-webfont.woff
  frontend/website-redesign/public/static/font/metropolis-extralight-webfont.woff2
  frontend/website-redesign/public/static/font/metropolis-light-webfont.woff
  frontend/website-redesign/public/static/font/metropolis-light-webfont.woff2
  frontend/website-redesign/public/static/font/metropolis-regular-webfont.woff
  frontend/website-redesign/public/static/font/metropolis-regular-webfont.woff2
  frontend/website-redesign/public/static/font/metropolis-semibold-webfont.woff
  frontend/website-redesign/public/static/font/metropolis-semibold-webfont.woff2
  frontend/website-redesign/src/Theme.re
  frontend/website-redesign/src/components/Button.re
  frontend/website-redesign/src/components/Icon.re
  frontend/website-redesign/src/components/PromoButton.re
  frontend/website-redesign/src/pages/Demo.re
Labels: ci-build-me, ready-to-merge

#5597 Add ~tags argument to logs
  src/lib/logger/impl.ml
  src/lib/logger/impl.mli
  src/lib/logger/tags.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5781 Add delegations to Rosetta, client SDK
  src/app/client_sdk/client_sdk.ml
  src/app/rosetta/lib/construction.ml
  src/lib/rosetta_lib/transaction.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5772 End-to-end agent down to submit
  buildkite/scripts/build-artifact.sh
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/dune
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/dune
  src/app/rosetta/test-agent/offline.ml
  src/app/rosetta/test-agent/operation_expectation.ml
  src/app/rosetta/test-agent/peek.ml
  src/app/rosetta/test-agent/poke.ml
  src/app/rosetta/test-agent/signer.ml
  src/lib/cli_lib/commands.ml
  src/lib/cli_lib/dune
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/rosetta_lib/user_command_info.ml
  src/lib/signature_lib/public_key.mli
Labels: ci-build-me, ready-to-merge

#5791 Construction works end-to-end in test agent
  src/app/rosetta/test-agent/agent.ml
Labels: ci-build-me, ready-to-merge

#5787 Tokens CLI changes
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5794 Simpler signature eq test
  src/app/rosetta/test-agent/operation_expectation.ml
  src/app/rosetta/test-agent/signer.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5792 Delegations case in of_operations
  src/lib/rosetta_lib/errors.ml
  src/lib/rosetta_lib/user_command_info.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5796 Construction delegations in test agent
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/operation_expectation.ml
  src/app/rosetta/test-agent/poke.ml
  src/lib/rosetta_lib/transaction.ml
  src/lib/rosetta_lib/user_command_info.ml
Labels: ci-build-me, ready-to-merge

#5799 Nits in server config to get rosetta-cli started
  src/app/rosetta/lib/network.ml
  src/app/rosetta/lib/rosetta.ml
  src/app/rosetta/rosetta.conf
  src/lib/rosetta_lib/errors.ml
Labels: ci-build-me, ready-to-merge

#5800 Serves genesis block from /block
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/decoders.ml
  src/app/rosetta/lib/network.ml
Labels: ci-build-me, ready-to-merge

#5797 [Release branch] Tokens CLI changes
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
Labels: ci-build-me

#5803 Fixes schema for operations "type"
  src/app/rosetta/test-agent/poke.ml
  src/app/rosetta/test-curl/block.sh
  src/app/rosetta/test-curl/con_preprocess.sh
  src/lib/rosetta_models/operation.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5807 Connection pooling to fix sql resource errors
  src/app/rosetta/lib/rosetta.ml
Labels: ci-build-me, ready-to-merge

#5804 [Website] Announcement Bar
  frontend/website-redesign/public/static/AnnouncementBannerDesktop.png
  frontend/website-redesign/public/static/AnnouncementBannerMobile.png
  frontend/website-redesign/public/static/AnnouncementBannerTablet.png
  frontend/website-redesign/src/Theme.re
  frontend/website-redesign/src/components/AnnouncementBanner.re
  frontend/website-redesign/src/components/Icon.re
  frontend/website-redesign/src/pages/Demo.re
Labels: ci-build-me, ready-to-merge

#5816 [Leaderboard] Added top 200 points
  frontend/leaderboard/src/Challenges.re
Labels: ci-build-me, ready-to-merge

#5655 Snapp account types
  .circleci/config.yml
  scripts/test.py
  src/app/cli/src/tests/coda_processes.ml
  src/lib/coda_base/account.ml
  src/lib/coda_base/ledger_hash0.ml
  src/lib/coda_base/side_loaded_verification_key.ml
  src/lib/coda_base/snapp_account.ml
  src/lib/coda_base/snapp_basic.ml
  src/lib/coda_base/snapp_command.ml
  src/lib/coda_base/snapp_predicate.ml
  src/lib/coda_base/snapp_state.ml
  src/lib/coda_base/snapp_statement.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/currency/currency.ml
  src/lib/pickles/common.ml
  src/lib/pickles/dune
  src/lib/pickles/import.ml
  src/lib/pickles/marlin_checks/dune
  src/lib/pickles/marlin_checks/marlin_checks.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/side_loaded_verification_key.ml
  src/lib/pickles/types_map.ml
  src/lib/pickles/verification_key.ml
  src/lib/pickles_base/domain.ml
  src/lib/pickles_base/domains.ml
  src/lib/pickles_base/dune
  src/lib/pickles_base/side_loaded_verification_key.ml
  src/lib/pickles_types/dlog_marlin_types.ml
  src/nonconsensus/coda_base/dune
  src/nonconsensus/coda_base/frozen_ledger_hash0.ml
  src/nonconsensus/coda_base/ledger_hash0.ml
  src/nonconsensus/coda_base/side_loaded_verification_key.ml
  src/nonconsensus/coda_base/snapp_account.ml
  src/nonconsensus/coda_base/snapp_basic.ml
  src/nonconsensus/coda_base/snapp_state.ml
  src/nonconsensus/snark_params/dune
  src/nonconsensus/snark_params/snark_params_nonconsensus.ml
  src/pickles_base.opam
Labels: ci-build-me, ready-to-merge-into-develop

#5818 Add delegation to agent run
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/poke.ml
Labels: ci-build-me, ready-to-merge-into-develop
