Repository MinaProtocol/mina, pull requests merged in 2020-11, with the labels that each got.

#6564 Timed account payment integration test
  src/app/test_executive/block_production_test.ml
  src/app/test_executive/block_production_test_timed_accounts.ml
  src/app/test_executive/bootstrap_test.ml
  src/app/test_executive/mina_peers_test.ml
  src/app/test_executive/payments_timed_accounts.ml
  src/app/test_executive/send_payment_test.ml
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/integration_test_lib/integration_test_lib.ml
  src/lib/integration_test_lib/test_error.ml
Labels: ci-build-me, ready-to-merge

#6457 Website improvements: reduce size of home page images
  frontend/website-redesign/src/components/AlternatingSections.re
Labels: ci-build-me

#6578 Fixes, additions and tweaks for rust bindings
  src/lib/marlin_plonk_bindings/bigint_256/marlin_plonk_bindings_bigint_256.ml
  src/lib/marlin_plonk_bindings/bigint_384/marlin_plonk_bindings_bigint_384.ml
  src/lib/marlin_plonk_bindings/bn_382_fp/marlin_plonk_bindings_bn_382_fp.ml
  src/lib/marlin_plonk_bindings/bn_382_fp/vector/marlin_plonk_bindings_bn_382_fp_vector.ml
  src/lib/marlin_plonk_bindings/bn_382_fq/marlin_plonk_bindings_bn_382_fq.ml
  src/lib/marlin_plonk_bindings/bn_382_fq/vector/marlin_plonk_bindings_bn_382_fq_vector.ml
  src/lib/marlin_plonk_bindings/dune
  src/lib/marlin_plonk_bindings/marlin_plonk_bindings.ml
  src/lib/marlin_plonk_bindings/stubs/src/bigint_256.rs
  src/lib/marlin_plonk_bindings/stubs/src/bigint_384.rs
  src/lib/marlin_plonk_bindings/stubs/src/bn_382_fp.rs
  src/lib/marlin_plonk_bindings/stubs/src/bn_382_fq.rs
  src/lib/marlin_plonk_bindings/stubs/src/lib.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_oracles.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_verifier_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_oracles.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_verifier_index.rs
  src/lib/marlin_plonk_bindings/tweedle_fp/marlin_plonk_bindings_tweedle_fp.ml
  src/lib/marlin_plonk_bindings/tweedle_fp/vector/marlin_plonk_bindings_tweedle_fp_vector.ml
  src/lib/marlin_plonk_bindings/tweedle_fp_index/marlin_plonk_bindings_tweedle_fp_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fp_plonk_oracles/dune
  src/lib/marlin_plonk_bindings/tweedle_fp_plonk_oracles/marlin_plonk_bindings_tweedle_fp_oracles.ml
  src/lib/marlin_plonk_bindings/tweedle_fp_plonk_verifier_index/marlin_plonk_bindings_tweedle_fp_verifier_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fp_proof/dune
  src/lib/marlin_plonk_bindings/tweedle_fp_proof/marlin_plonk_bindings_tweedle_fp_proof.ml
  src/lib/marlin_plonk_bindings/tweedle_fq/marlin_plonk_bindings_tweedle_fq.ml
  src/lib/marlin_plonk_bindings/tweedle_fq/vector/marlin_plonk_bindings_tweedle_fq_vector.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_index/marlin_plonk_bindings_tweedle_fq_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_plonk_oracles/dune
  src/lib/marlin_plonk_bindings/tweedle_fq_plonk_oracles/marlin_plonk_bindings_tweedle_fq_oracles.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_plonk_verifier_index/marlin_plonk_bindings_tweedle_fq_verifier_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_proof/dune
  src/lib/marlin_plonk_bindings/tweedle_fq_proof/marlin_plonk_bindings_tweedle_fq_proof.ml
  src/lib/marlin_plonk_bindings/types/marlin_plonk_bindings_types.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6582 fix daemon puppeteered image
  dockerfiles/Dockerfile-coda-daemon-puppeteered
Labels: ci-build-me

#6581 do not verify scan statement while loading persistent frontier
  src/lib/block_producer/block_producer.ml
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_handler/breadcrumb_builder.ml
  src/lib/transition_handler/processor.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6585 Change default slot time to 3 minutes on develop
  src/config/testnet_postake_medium_curves.mlh
Labels: ci-build-me, ready-to-merge-into-develop

#6592 Telemetry crawler
  scripts/telemetry-crawl.py
Labels: ci-build-me, ready-to-merge

#6600 Website: Round 3 fixes
  frontend/website-redesign/pages/docs/architecture/snark-workers.mdx
  frontend/website-redesign/pages/docs/snarks/constructions.mdx
  frontend/website-redesign/public/static/img/SnarkDiagram.jpg
  frontend/website-redesign/public/static/img/SnarksOverview.jpg
  frontend/website-redesign/src/components/Constants.re
  frontend/website-redesign/src/components/Nav.re
Labels: ci-build-me, ready-to-merge

#6602 Default token contributes to total currency
  src/lib/consensus/proof_of_stake.ml
  src/lib/merkle_mask/maskable_merkle_tree.ml
Labels: ci-build-me, ready-to-merge

#6604 remove command overrides for Helm daemon container specs
  helm/archive-node/Chart.yaml
  helm/archive-node/templates/archive.yaml
  helm/block-producer/Chart.yaml
  helm/block-producer/templates/block-producer.yaml
  helm/seed-node/Chart.yaml
  helm/seed-node/templates/seed-node.yaml
  helm/snark-worker/Chart.yaml
  helm/snark-worker/templates/snark-coordinator.yaml
  scripts/archive/Dockerfile
Labels: ci-build-me, ready-to-merge, ready-to-merge-into-develop

#6593 Tool to consolidate best tips from multiple log files
  src/app/best_tip_merger/best_tip_merger.ml
  src/app/best_tip_merger/dune
  src/best_tip_merger.opam
  src/lib/transition_frontier/extensions/best_tip_diff.ml
  src/lib/transition_frontier/extensions/best_tip_diff.mli
Labels: ci-build-me, ready-to-merge

#6606 adding epoch_data to archive database
  src/app/archive/archive_lib/processor.ml
  src/app/archive/create_schema.sql
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me, ready-to-merge

#6614 destroy persisted epoch ledgers when genesis state changes
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/fake_network/fake_network.ml
  src/lib/file_system/file_system.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me, ready-to-merge

#6617 Trivial: Run Timer.log after aggregating timing information
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6615 check that deserialized points are on curve
  src/lib/zexe_backend/zexe_backend_common/curve.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6616 generate genesis ledger filename consistently
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ci-build-me, ready-to-merge

#6618 Rosetta, add epoch data columns to SQL
  src/app/archive/archive_lib/processor.ml
  src/app/rosetta/lib/block.ml
Labels: ci-build-me, ready-to-merge

#6583 Supports loading peers from a list file
  src/app/cli/src/coda.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6596 Website: carousel
  frontend/website-redesign/src/components/Carousel.re
  frontend/website-redesign/src/pages/Community.re
  frontend/website-redesign/src/pages/Genesis.re
Labels: ci-build-me, ready-to-merge

#6629 Fix "Could not read the URS from disk": Catch errors when reading/writing the key cache
  src/lib/key_cache/key_cache.ml
  src/lib/key_cache/key_cache.mli
  src/lib/pickles/cache.ml
  src/lib/zexe_backend/zexe_backend_common/dlog_plonk_based_keypair.ml
  src/lib/zexe_backend/zexe_backend_common/dlog_urs.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6637 Make delegation test fast again
  src/lib/runtime_config/runtime_config.ml
Labels: ci-build-me, ready-to-merge

#6635 Stop libp2p_helper logspam
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ci-build-me, ready-to-merge-into-develop

#6639 Parallel scan, use Latest module for bin_io
  src/lib/parallel_scan/parallel_scan.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6640 don't fail on epoch_ledger.json read error
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6273 Optimise genesis_ledger_total_currency for 100k accounts
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me, ready-to-merge

#6638 More flexible, more detailed go log parsing
  src/lib/coda_net2/coda_net2.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5734 generate-keypair-deb Just commit changes to rebuild-deb.sh
  buildkite/scripts/build-artifact.sh
  buildkite/scripts/export-git-env-vars.sh
  dockerfiles/Dockerfile-genkey
  dockerfiles/Dockerfile-rosetta
  scripts/rebuild-deb.sh
Labels: ci-build-me, consider-for-closing

#6634 Genesis epoch ledgers
  scripts/rebuild-deb.sh
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/replayer/replayer.ml
  src/lib/block_producer/block_producer.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_state/blockchain_state.ml
  src/lib/coda_state/blockchain_state.mli
  src/lib/coda_state/genesis_protocol_state.ml
  src/lib/coda_state/genesis_protocol_state.mli
  src/lib/coda_state/protocol_state.ml
  src/lib/coda_state/protocol_state.mli
  src/lib/consensus/genesis_epoch_data.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/fake_network/fake_network.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/sync_handler/sync_handler.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6656 Fix CODEOWNERS
  CODEOWNERS
Labels: ci-build-me, ready-to-merge-into-develop

#6657 Add mrmr1993 as a codeowner for src/external
  CODEOWNERS
Labels: ci-build-me, ready-to-merge-into-develop

#6659 use full field element for challenge in signature
  src/lib/signature_lib/schnorr.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6373 Use a sequence for precomputed blocks
  src/app/cli/src/coda.ml
  src/lib/block_producer/block_producer.ml
  src/lib/coda_lib/coda_lib.mli
Labels: ci-build-me, ready-to-merge-into-develop

#6620 Replayer generates epoch ledgers
  scripts/test-replayer.sh
  src/app/archive/archive_lib/processor.ml
  src/app/archive/drop_tables.sql
  src/app/replayer/replayer.ml
  src/app/replayer/sql.ml
  src/app/replayer/test/archive_db.sql
  src/app/replayer/test/input.json
Labels: ci-build-me, ready-to-merge

#6666 Telemetry, parallel map on deferred list
  src/lib/telemetry/telemetry.ml
Labels: ci-build-me, ready-to-merge

#6671 fix txn_global_slot in the replayer
  src/app/replayer/replayer.ml
  src/app/replayer/sql.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6439 add mina testnet component healthcheck named templates and probes
  buildkite/helm/buildkite-exporter/README.md
  buildkite/helm/buildkite-exporter/templates/_healthchecks.common.tpl
  buildkite/helm/buildkite-exporter/templates/_healthchecks.tpl
  buildkite/helm/buildkite-exporter/templates/buildkite-exporter.yaml
  buildkite/helm/buildkite-exporter/templates/exporter-service.yaml
  buildkite/helm/buildkite-exporter/values.yaml
  buildkite/scripts/helm-ci.sh
  buildkite/src/Jobs/Release/HelmRelease.dhall
  dockerfiles/Dockerfile-coda-daemon
  dockerfiles/scripts/healthcheck-utilities.sh
  helm/archive-node/Chart.yaml
  helm/archive-node/templates/_healthchecks.common.tpl
  helm/archive-node/templates/_healthchecks.tpl
  helm/archive-node/templates/archive.yaml
  helm/archive-node/templates/genesis-configmap.yaml
  helm/archive-node/values.yaml
  helm/block-producer/Chart.yaml
  helm/block-producer/templates/_healthchecks.common.tpl
  helm/block-producer/templates/_healthchecks.tpl
  helm/block-producer/templates/block-producer.yaml
  helm/block-producer/templates/genesis-configmap.yaml
  helm/block-producer/templates/secret.yaml
  helm/block-producer/values.yaml
  helm/common/Chart.yaml
  helm/common/templates/_healthchecks.tpl
  helm/common/values.yaml
  helm/seed-node/Chart.yaml
  helm/seed-node/templates/_healthchecks.common.tpl
  helm/seed-node/templates/_healthchecks.tpl
  helm/seed-node/templates/genesis-configmap.yaml
  helm/seed-node/templates/seed-node.yaml
  helm/seed-node/templates/seed-service.yaml
  helm/seed-node/values.yaml
  helm/snark-worker/Chart.yaml
  helm/snark-worker/templates/_healthchecks.common.tpl
  helm/snark-worker/templates/_healthchecks.tpl
  helm/snark-worker/templates/coordinator-service.yaml
  helm/snark-worker/templates/genesis-configmap.yaml
  helm/snark-worker/templates/snark-coordinator.yaml
  helm/snark-worker/templates/snark-worker.yaml
  helm/snark-worker/values.yaml
  scripts/release-docker.sh
Labels: ci-build-me

#6658 Add support for multiple -config-file arguments for daemon
  src/app/cli/src/coda.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6669 Epoch seed base58 serialization in archive db
  src/app/archive/archive_lib/processor.ml
  src/app/replayer/replayer.ml
Labels: ci-build-me, ready-to-merge

#6677 Add logging for proof batch sizes, add MAX_VERIFIER_BATCH_SIZE envvar
  src/lib/network_pool/batcher.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6665 Allow fee transfers with differing kinds in internal commands
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/archive/create_schema.sql
  src/app/rosetta/lib/block.ml
Labels: ci-build-me, ready-to-merge

#6692 Load wallets early in daemon startup
  src/app/cli/src/coda.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
Labels: ci-build-me, ready-to-merge-into-develop

#6689 Don't attempt to read password on stdin if stdin isn't a tty
  src/app/cli/src/coda.ml
  src/lib/secrets/keypair_common.ml
  src/lib/secrets/password.ml
  src/lib/secrets/privkey_error.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6696 Archive db, add valid_until to user commands
  src/app/archive/archive_lib/processor.ml
  src/app/archive/create_schema.sql
  src/app/replayer/replayer.ml
  src/app/replayer/sql.ml
  src/app/replayer/test/archive_db.sql
  src/app/replayer/test/input.json
  src/app/rosetta/lib/block.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6698 JSON-encode `Error.t`s when logging
  src/app/cli/src/coda.ml
  src/app/cli/src/dune
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/error_json.opam
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_lib/archive_client.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_net2/coda_net2.ml
  src/lib/coda_net2/dune
  src/lib/coda_networking/coda_networking.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/consensus/proof_of_stake_fuzzer.ml
  src/lib/error_json/dune
  src/lib/error_json/error_json.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/key_cache/dune
  src/lib/key_cache/key_cache.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/prover/prover.ml
  src/lib/secrets/wallets.ml
  src/lib/snark_worker/prod.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_router/initial_validator.ml
  src/lib/transition_router/transition_router.ml
  src/lib/verifier/prod.ml
  src/lib/web_client_pipe/dune
  src/lib/web_client_pipe/web_client_pipe.ml
  src/lib/work_selector/work_lib.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6702 Fix libp2p initial peers RPC is triggered now
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/lib/coda_net2/coda_net2.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6706 CLI docstring fixes
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/lib/cli_lib/flag.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6697 Memory corruption fixes
  src/lib/marlin_plonk_bindings/stubs/src/caml_vector.rs
  src/lib/marlin_plonk_bindings/stubs/src/plonk_gate.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_dee.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_dum.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_oracles.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_proof.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_verifier_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_oracles.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_proof.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_verifier_index.rs
Labels: ci-build-me, ready-to-merge-into-develop

#6709 Add Mina_user_error.raise
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/dune
  src/lib/mina_user_error/dune
  src/lib/mina_user_error/mina_user_error.ml
  src/mina_user_error.opam
Labels: ci-build-me, ready-to-merge-into-develop

#6685 Kill curl output logging, make all genesis ledger and cache loading logs level=trace
  src/lib/cache_dir/cache_dir.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/key_cache/key_cache.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6715 Add getPeers and addPeers to GraphQL and CLI
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/coda_networking.mli
Labels: ci-build-me, ready-to-merge-into-develop

#6712 Add allocation_stress_test tool
  src/lib/marlin_plonk_bindings/tools/allocation_stress_test/allocation_stress_test.ml
  src/lib/marlin_plonk_bindings/tools/allocation_stress_test/dune
Labels: ci-build-me, ready-to-merge-into-develop

#6710 Rpc error log
  src/app/cli/src/init/coda_run.ml
  src/lib/coda_base/rpc_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/gossip_net/libp2p.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6722 Timed accounts, don't check balance against minimum balance
  src/lib/coda_base/account.ml
Labels: ci-build-me, ready-to-merge

#6687 "Refusing to broadcast" messages at log level=trace
  src/lib/network_pool/network_pool_base.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6707 log rotate between 50 files
  src/app/best_tip_merger/best_tip_merger.ml
  src/app/cli/src/coda.ml
  src/lib/consensus/proof_of_stake_fuzzer.ml
  src/lib/logger/impl.ml
  src/lib/logger/impl.mli
  src/lib/logger/test.ml
  src/lib/prover/prover.ml
  src/lib/verifier/prod.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6664 fix block latency metrics
  src/lib/coda_metrics/coda_metrics.ml
  src/lib/coda_metrics/metric_generators.ml
Labels: ci-build-me, ready-to-merge

#6723 Trivial: add of_yojson derivers for snark inputs
  src/lib/blockchain_snark/blockchain.ml
  src/lib/blockchain_snark/blockchain.mli
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ci-build-me, ready-to-merge-into-develop

#6724 Add internal run-verifier command
  src/app/cli/src/coda.ml
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/ledger_proof/ledger_proof_intf.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6729 Trivial: Stop unnecessarily double-escaping log messages
  src/lib/logger/impl.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6688 a hack to fix catchup sync status
  src/lib/coda_commands/coda_commands.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6726 Export logs via CLI and GraphQL
  graphql_schema.json
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/conf_dir.ml
Labels: ci-build-me, ready-to-merge

#6730 Kill child processes on shutdown
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/tests/coda_worker.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6743 Remove receipt chain database
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/tests/coda_process.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_commands/dune
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/config.ml
  src/lib/coda_lib/dune
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/receipt_chain_database/dune
  src/lib/receipt_chain_database/intf.ml
  src/lib/receipt_chain_database/receipt_chain_database.ml
  src/lib/receipt_chain_database/receipt_chain_database.mli
  src/lib/receipt_chain_database/tree_node.ml
  src/receipt_chain_database.opam
Labels: ci-build-me, ready-to-merge

#6740 libp2p log change to debug
  src/lib/coda_net2/coda_net2.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6742 Temporarily disallow serialised type changes for 4.1 support on develop
  buildkite/src/Jobs/Lint/OCaml.dhall
  scripts/compare_ci_diff_types_develop.sh
Labels: ci-build-me, ready-to-merge-into-develop

#5630 Remove unused Vector.reverse
  src/lib/pickles_types/vector.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6725 Always copy data from OCaml to rust before using it
  src/lib/marlin_plonk_bindings/stubs/src/caml_vector.rs
  src/lib/marlin_plonk_bindings/stubs/src/lib.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_dee.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_dum.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_oracles.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_proof.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_urs.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_oracles.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_proof.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_urs.rs
Labels: ci-build-me, ready-to-merge-into-develop

#6701 Update Rosetta README Coda references to Mina
  src/app/rosetta/README.md
Labels: ci-build-me, ready-to-merge-into-develop

#6749 Implement allocation functor, wire up cli command and metrics
  src/allocation_functor.opam
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/lib/allocation_functor/dune
  src/lib/allocation_functor/functor.ml
  src/lib/allocation_functor/intf.ml
  src/lib/allocation_functor/table.ml
  src/lib/allocation_functor/table.mli
  src/lib/coda_metrics/coda_metrics.ml
  src/lib/coda_transition/dune
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me, ready-to-merge

#6734 Leaderboard: Update Current Release and Phase
  frontend/leaderboard/src/Challenges.re
  frontend/leaderboard/src/Metrics.re
  frontend/leaderboard/src/Postgres.re
  frontend/leaderboard/src/Sheets.re
  frontend/leaderboard/src/UploadLeaderboardPoints.re
Labels: ci-build-me, ready-to-merge

#6752 Fix dangling_mask during catchup
  src/lib/transition_handler/breadcrumb_builder.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6717 Async proving
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/blockchain_snark/blockchain_snark_state.mli
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/dune
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_proof.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_proof.rs
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/step.ml
  src/lib/pickles/wrap.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/prover/prover.ml
  src/lib/snark_worker/debug.ml
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/snark_worker/prod.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/zexe_backend/tweedle/dee_based_plonk.ml
  src/lib/zexe_backend/tweedle/dum_based_plonk.ml
  src/lib/zexe_backend/zexe_backend_common/plonk_dlog_proof.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6756 Compute object lifetime quartiles in allocation functor
  src/lib/allocation_functor/dune
  src/lib/allocation_functor/table.ml
  src/lib/allocation_functor/table.mli
  src/lib/coda_metrics/coda_metrics.ml
Labels: ci-build-me, ready-to-merge

#6759 Leaderboard: Postgres Query Fixes
  frontend/leaderboard/src/Challenges.re
  frontend/leaderboard/src/Main.re
  frontend/leaderboard/src/Postgres.re
Labels: ci-build-me, ready-to-merge

#6741 Use Mina_user_error for daemon bootup failures
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/app/rosetta/lib/signer.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/mina_user_error/mina_user_error.ml
  src/lib/secrets/dune
  src/lib/secrets/keypair.ml
  src/lib/secrets/keypair_common.ml
  src/lib/secrets/libp2p_keypair.ml
  src/lib/secrets/password.ml
  src/lib/secrets/password.mli
  src/lib/secrets/privkey_error.ml
  src/lib/secrets/secret_box.ml
  src/lib/secrets/secret_box.mli
  src/lib/secrets/secret_file.ml
  src/lib/secrets/secret_file.mli
Labels: ci-build-me, ready-to-merge-into-develop

#6703 Updated Rosetta API to encode random oracle input as hex string
  src/app/rosetta/test-curl/con_derive.sh
  src/app/rosetta/test-curl/con_metadata.sh
  src/app/rosetta/test-curl/con_parse.sh
  src/app/rosetta/test-curl/con_payloads.sh
  src/app/rosetta/test-curl/con_preprocess.sh
  src/lib/rosetta_lib/transaction.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6750 change libp2p warn logs to debug
  src/lib/coda_net2/coda_net2.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6771 Allow keys, urs to be read after an offset, to allow for a header
  src/lib/marlin_plonk_bindings/stubs/src/index_serialization.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_oracles.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_verifier_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_urs.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_oracles.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_verifier_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_urs.rs
  src/lib/marlin_plonk_bindings/tweedle_fp_index/marlin_plonk_bindings_tweedle_fp_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fp_plonk_verifier_index/marlin_plonk_bindings_tweedle_fp_verifier_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fp_urs/marlin_plonk_bindings_tweedle_fp_urs.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_index/marlin_plonk_bindings_tweedle_fq_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_plonk_verifier_index/marlin_plonk_bindings_tweedle_fq_verifier_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_urs/marlin_plonk_bindings_tweedle_fq_urs.ml
  src/lib/zexe_backend/zexe_backend_common/dlog_plonk_based_keypair.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6776 Regenerate the genesis proof if there is an error when reading it
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6784 Merge back develop
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6773 Allow keys, urs to be appended to a file instead of overwriting
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_verifier_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_urs.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_verifier_index.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_urs.rs
  src/lib/marlin_plonk_bindings/tweedle_fp_index/marlin_plonk_bindings_tweedle_fp_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fp_plonk_verifier_index/marlin_plonk_bindings_tweedle_fp_verifier_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fp_urs/marlin_plonk_bindings_tweedle_fp_urs.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_index/marlin_plonk_bindings_tweedle_fq_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_plonk_verifier_index/marlin_plonk_bindings_tweedle_fq_verifier_index.ml
  src/lib/marlin_plonk_bindings/tweedle_fq_urs/marlin_plonk_bindings_tweedle_fq_urs.ml
  src/lib/zexe_backend/zexe_backend_common/dlog_plonk_based_keypair.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6779 Add ready-to-merge-into-develop support for develop-until-4.1-hardfork branch
  .mergify.yml
  .mergify.yml.jinja
Labels: ci-build-me, ready-to-merge-into-develop

#6783 Cliff amount in account timings
  src/app/replayer/test/archive_db.sql
  src/app/replayer/test/input.json
  src/app/test_executive/block_production_test_timed_accounts.ml
  src/app/test_executive/mina_peers_test.ml
  src/app/test_executive/payments_timed_accounts.ml
  src/lib/coda_base/account.ml
  src/lib/coda_base/account_timing.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger/intf.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6781 Add ppx_version support to allocation functor; use in more places
  src/lib/allocation_functor/dune
  src/lib/allocation_functor/functor.ml
  src/lib/allocation_functor/intf.ml
  src/lib/allocation_functor/make.ml
  src/lib/blockchain_snark/blockchain.ml
  src/lib/blockchain_snark/blockchain.mli
  src/lib/coda_base/dune
  src/lib/coda_base/user_command.ml
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/prover/prover.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/root_data.ml
  src/lib/verifier/prod.ml
  src/lib/zexe_backend/tweedle/dee_based_plonk.ml
  src/lib/zexe_backend/tweedle/dum_based_plonk.ml
  src/lib/zexe_backend/zexe_backend_common/dune
  src/lib/zexe_backend/zexe_backend_common/plonk_dlog_proof.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6754 Remove transaction, external transition databases
  .circleci/config.yml
  graphql_schema.json
  scripts/test.py
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_archive_node_test.ml
  src/app/cli/src/tests/coda_archive_processor_test.ml
  src/app/cli/src/tests/coda_batch_payment_test.ml
  src/app/cli/src/tests/coda_process.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/app/cli/src/tests/full_test.ml
  src/app/mock_wallet_data/dune
  src/app/mock_wallet_data/mock_wallet_data.ml
  src/filtered_external_transition.opam
  src/lib/auxiliary_database/dune
  src/lib/auxiliary_database/external_transition_database.ml
  src/lib/auxiliary_database/external_transition_database.mli
  src/lib/auxiliary_database/intf.ml
  src/lib/auxiliary_database/pagination.ml
  src/lib/auxiliary_database/transaction_database.ml
  src/lib/auxiliary_database/transaction_database.mli
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_graphql/dune
  src/lib/coda_graphql/pagination.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/coda_subscriptions.ml
  src/lib/coda_lib/config.ml
  src/lib/coda_lib/dune
  src/lib/filtered_external_transition/dune
  src/lib/filtered_external_transition/filtered_external_transition.ml
  src/mock_wallet_data.opam
Labels: ci-build-me, ready-to-merge

#6757 Trivial: Stop rehashing genesis protocol state every Best_tip_prover.verify
  src/lib/best_tip_prover/best_tip_prover.ml
Labels: ci-build-me, ready-to-merge

#6661 Add header format for snark keys from RFC 0039
  src/lib/snark_keys_header/dune
  src/lib/snark_keys_header/snark_keys_header.ml
  src/snark_keys_header.opam
Labels: ci-build-me, ready-to-merge-into-develop

#6775 Leaderboard: Updated spreadsheet references and Postgres query refactor
  frontend/leaderboard/src/Main.re
  frontend/leaderboard/src/Postgres.re
  frontend/leaderboard/src/Sheets.re
  frontend/leaderboard/src/UploadLeaderboardData.re
Labels: ci-build-me, ready-to-merge

#6769 Snark keys header parsing
  src/lib/snark_keys_header/dune
  src/lib/snark_keys_header/snark_keys_header.ml
  src/snark_keys_header.opam
Labels: ci-build-me, ready-to-merge-into-develop

#6714 mina-generate-keypair Update dockerfile for generate-keypair
  dockerfiles/Dockerfile-genkey
Labels: ci-build-me, ready-to-merge-into-develop

#6751 Use Error.tag/tag_arg instead of stringifying errors
  src/app/replayer/replayer.ml
  src/lib/block_producer/block_producer.ml
  src/lib/cli_lib/arg_type.ml
  src/lib/coda_lib/archive_client.ml
  src/lib/coda_net2/coda_net2.ml
  src/lib/distributed_dsl/node.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/parallel_scan/parallel_scan.ml
  src/lib/secrets/keypair_common.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_router/transition_router.ml
  src/lib/web_client_pipe/web_client_pipe.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6758 Fix CI for external contributors: rosetta docker build failure
  buildkite/src/Jobs/Release/MinaArtifact.dhall
  dockerfiles/Dockerfile-rosetta
Labels: ci-build-me, ready-to-merge-into-develop

#6796 Mina lockfile
  src/app/cli/src/coda.ml
  src/lib/coda_lib/conf_dir.ml
Labels: ci-build-me, ready-to-merge

#6795 Expose commit_date and marlin, zexe commit information from Coda_version
  src/app/cli/src/coda.ml
  src/lib/coda_version/coda_version.mli
  src/lib/coda_version/gen.sh
Labels: ci-build-me, ready-to-merge-into-develop

#6807 Add libp2p_helper prometheus server and -libp2p-metrics-port flag
  scripts/run_local_network.sh
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/lib/coda_net2/coda_net2.ml
  src/lib/coda_net2/coda_net2.mli
  src/lib/gossip_net/libp2p.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6808 change Blake2 from BLAKE2s to BLAKE2b
  src/lib/blake2/blake2.ml
  src/lib/snarky_blake2/test/test.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6793 Be conservative with fill-if-empty, fixes #6772
  src/lib/coda_net2/coda_net2.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6652 Attempt to remove the deb-s3 lockfile if the command fails
  buildkite/scripts/publish-deb.sh
  scripts/archive/build-release-archives.sh
  scripts/clear-deb-s3-lockfile.sh
  scripts/publish-deb.sh
Labels: ci-build-me, ready-to-merge-into-develop

#6802 File log level for `coda.log`
  src/app/cli/src/coda.ml
  src/lib/cli_lib/flag.ml
  src/lib/cli_lib/flag.mli
Labels: ci-build-me, ready-to-merge-into-develop

#6806 Daemon lockfile for develop
  src/app/cli/src/coda.ml
  src/lib/coda_lib/conf_dir.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6810 properly skip verification
  src/lib/staged_ledger/staged_ledger.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6746 Feature/systemd user service
  scripts/mina.service
  scripts/rebuild-deb.sh
Labels: ci-build-me, ready-to-merge-into-develop

#6811 check if snarks are referenced before verifying them
  src/lib/network_pool/snark_pool.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6804 kill the libp2p helper periodically
  src/lib/coda_net2/coda_net2.ml
  src/lib/coda_net2/coda_net2.mli
  src/lib/gossip_net/libp2p.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6672 Add checked version of User_command_status.Failure.t
  src/lib/coda_base/user_command_status.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6188 Remove hard coded home directory
  scripts/macos-setup-brew.sh
Labels: ready-to-merge-into-develop

#6785 Add optional maxLength argument to GraphQL bestChain
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/transition_frontier/frontier_base/frontier_intf.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6338 go-libp2p-core v0.6.1 minimum go version: 1.13
  src/app/libp2p_helper/src/go.mod
Labels: ready-to-merge

#6813 Fix test_postake_three_producers integration test
  src/app/cli/src/tests/coda_worker_testnet.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6675 convert helm common utilities to chart library
  buildkite/scripts/helm-ci.sh
  helm/common/Chart.yaml
  helm/common/values.yaml
Labels: ci-build-me

#6721 Removes get initial peers for now
  src/app/libp2p_helper/src/codanet.go
  src/lib/coda_networking/coda_networking.ml
Labels: ci-build-me

#6814 Fix test--dev--coda-archive-node-test
  src/app/cli/src/tests/coda_archive_node_test.ml
  src/app/cli/src/tests/dune
Labels: ci-build-me, ready-to-merge

#6809 Quieter logs in unit tests (145,594 lines -> 2,134 lines)
  src/inline_test_quiet_logs.opam
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/consensus/dune
  src/lib/consensus/proof_of_stake.ml
  src/lib/inline_test_quiet_logs/dune
  src/lib/inline_test_quiet_logs/inline_test_quiet_logs.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/network_pool/batcher.ml
  src/lib/staged_ledger/dune
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/tests/transition_frontier_tests.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6833 Fix segfault: capture rust heap references before yeilding to OCaml
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_plonk_proof.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fp_vector.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_plonk_proof.rs
  src/lib/marlin_plonk_bindings/stubs/src/tweedle_fq_vector.rs
Labels: ci-build-me, ready-to-merge-into-develop

#6835 Process id in lockfileFeature/pid in lockfile
  src/lib/coda_lib/conf_dir.ml
Labels: ci-build-me, ready-to-merge

#6839 Trivial: Stop attempting to lint frontend/website in CI
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ci-build-me, ready-to-merge-into-develop

#6842 Trivial: Don't print the runtime configuration/full genesis ledger during startup
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6837 Block_stake_winner in consensus stake
  src/lib/consensus/proof_of_stake.ml
  src/lib/consensus/stake_proof.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6841 Return some telemetry data even when there is no frontier available
  src/lib/coda_lib/coda_lib.ml
Labels: ci-build-me, ready-to-merge

#6822 Fixes for turbo pickles (should improve catchup)
  src/lib/allocation_functor/table.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/mocks.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/test.ml
  src/lib/sync_handler/dune
  src/lib/sync_handler/sync_handler.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6832 replace symbolic link for common named templates with common utility library
  helm/archive-node/Chart.lock
  helm/archive-node/Chart.yaml
  helm/archive-node/charts/common-utilities-0.0.2.tgz
  helm/archive-node/charts/postgresql-10.1.0.tgz
  helm/archive-node/charts/postgresql-8.7.2.tgz
  helm/archive-node/templates/_healthchecks.common.tpl
  helm/block-producer/Chart.lock
  helm/block-producer/Chart.yaml
  helm/block-producer/charts/common-utilities-0.0.2.tgz
  helm/block-producer/templates/_healthchecks.common.tpl
  helm/seed-node/Chart.lock
  helm/seed-node/Chart.yaml
  helm/seed-node/charts/common-utilities-0.0.2.tgz
  helm/seed-node/templates/_healthchecks.common.tpl
  helm/snark-worker/Chart.lock
  helm/snark-worker/Chart.yaml
  helm/snark-worker/charts/common-utilities-0.0.2.tgz
  helm/snark-worker/templates/_healthchecks.common.tpl
Labels: ci-build-me

#6847 libp2p restarts if env variable is set
  src/lib/gossip_net/libp2p.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6848 4.1 turbo pickles -> MASTER
  .circleci/config.yml
  .circleci/config.yml.jinja
  helm/archive-node/Chart.lock
  helm/archive-node/Chart.yaml
  helm/archive-node/charts/common-utilities-0.0.2.tgz
  helm/archive-node/charts/postgresql-10.1.0.tgz
  helm/archive-node/charts/postgresql-8.7.2.tgz
  helm/archive-node/templates/_healthchecks.common.tpl
  helm/block-producer/Chart.lock
  helm/block-producer/Chart.yaml
  helm/block-producer/charts/common-utilities-0.0.2.tgz
  helm/block-producer/templates/_healthchecks.common.tpl
  helm/seed-node/Chart.lock
  helm/seed-node/Chart.yaml
  helm/seed-node/charts/common-utilities-0.0.2.tgz
  helm/seed-node/templates/_healthchecks.common.tpl
  helm/snark-worker/Chart.lock
  helm/snark-worker/Chart.yaml
  helm/snark-worker/charts/common-utilities-0.0.2.tgz
  helm/snark-worker/templates/_healthchecks.common.tpl
  src/inline_test_quiet_logs.opam
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/conf_dir.ml
  src/lib/consensus/dune
  src/lib/consensus/proof_of_stake.ml
  src/lib/daemon_rpcs/types.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/inline_test_quiet_logs/dune
  src/lib/inline_test_quiet_logs/inline_test_quiet_logs.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/network_pool/batcher.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/mocks.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/test.ml
  src/lib/staged_ledger/dune
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/tests/transition_frontier_tests.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
Labels: ci-build-me

#6843 Fix build archive CI job
  buildkite/scripts/export-git-env-vars.sh
  scripts/archive/build-release-archives.sh
Labels: ci-build-me, ready-to-merge-into-develop

#6716 fix/libp2p-disabe-decaying-tags Stop supporting the Decayer interface
  src/app/libp2p_helper/src/codanet.go
Labels: ci-build-me

#5842 Fix mac build again
  .circleci/config.yml
  .circleci/config.yml.jinja
  scripts/Brewfile
  scripts/artifacts.sh
  scripts/macos-portable.sh
  scripts/zexe-standardize.sh
  src/opam.export
Labels: ci-build-me, ready-to-merge-into-develop

#6747 Fix CI for external contributors
  frontend/ci-build-me/src/index.js
Labels: ci-build-me

#6855 Leaderboard: Fix Challenge #1 to be 1000 points.
  frontend/leaderboard/src/Challenges.re
Labels: ci-build-me, ready-to-merge

#6857 version info when exporting logs and coda version
  src/app/cli/src/coda.ml
  src/lib/coda_lib/conf_dir.ml
Labels: ci-build-me, ready-to-merge-into-develop

#6858 [HOTFIX] Libp2p async rpc handling
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ci-build-me

#6856 [HOTFIX] Add 30 sec timeout on NewStream identification protocol
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ci-build-me, not-ready-to-merge

#6863 Ignore repeated messages
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#6860 fix deb build in develop-until-4.1-harfork
  genesis_ledgers/phase_three/config.json
Labels: ci-build-me

#6873 Trivial: Use a bash for loop in connect-to-testnet script
  buildkite/scripts/connect-to-testnet-on-develop.sh
Labels: ci-build-me

#6878 Don't exit connect-to-testnet script if coda client status isn't ready yet
  buildkite/scripts/connect-to-testnet-on-develop.sh
Labels: ci-build-me

#6876 Merge master into develop by way of 4.1-turbo-pickles
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#6883 install jq (json processor) tool into daemon dockerfile
  dockerfiles/Dockerfile-coda-daemon
Labels: ci-build-me
