Repository MinaProtocol/mina, pull requests merged in 2020-07, with the labels that each got.

#5251 Optional -proof-level flag for snark worker
  src/lib/snark_worker/functor.ml
Labels: ready-to-merge-into-develop

#5166 [Tokens] Add Create_account to transaction_union with snark logic
  src/app/archive/create_schema.sql
  src/lib/coda_base/token_id.ml
  src/lib/coda_base/token_id.mli
  src/lib/coda_base/transaction_union_payload.ml
  src/lib/coda_base/transaction_union_tag.ml
  src/lib/coda_base/transaction_union_tag.mli
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge-into-develop

#5242 Website: Clean up team section
  frontend/website/public/static/img/morin.jpg
  frontend/website/src/components/TeamSection.re
Labels: ready-to-merge

#5246 Website: fix horizontal scroll on mobile
  frontend/website/pages/docs/my-first-transaction.mdx
  frontend/website/src/pages/Testnet.re
Labels: ready-to-merge

#5254 bazel support: initial minimal commit
  .bazelrc
  .gitignore
  BUILD.bazel
  WORKSPACE
Labels: ready-to-merge

#5258 Token commands
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/lib/auxiliary_database/external_transition_database.ml
  src/lib/auxiliary_database/filtered_external_transition.ml
  src/lib/auxiliary_database/pagination.ml
  src/lib/auxiliary_database/transaction_database.ml
  src/lib/coda_base/ledger.mli
  src/lib/coda_base/new_account_payload.ml
  src/lib/coda_base/new_token_payload.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/sparse_ledger.mli
  src/lib/coda_base/transaction.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/transaction_union_payload.ml
  src/lib/coda_base/transaction_validator.ml
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command.mli
  src/lib/coda_base/user_command_intf.ml
  src/lib/coda_base/user_command_payload.ml
  src/lib/coda_base/user_command_payload.mli
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_transition/external_transition.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/snark_worker/prod.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/nonconsensus/coda_base/new_account_payload.ml
  src/nonconsensus/coda_base/new_token_payload.ml
Labels: ready-to-merge-into-develop

#5268 update genesis terms and conditions
  frontend/website/pages/tcGenesis.mdx
  frontend/website/src/pages/MarkdownPage.re
Labels: ready-to-merge

#5228 Rosetta: Add models and network endpoints
  src/app/rosetta/README.md
  src/app/rosetta/cli.ml
  src/app/rosetta/dune
  src/app/rosetta/errors.ml
  src/app/rosetta/graphql.ml
  src/app/rosetta/models.opam
  src/app/rosetta/models/account_balance_request.ml
  src/app/rosetta/models/account_balance_response.ml
  src/app/rosetta/models/account_identifier.ml
  src/app/rosetta/models/allow.ml
  src/app/rosetta/models/amount.ml
  src/app/rosetta/models/block.ml
  src/app/rosetta/models/block_identifier.ml
  src/app/rosetta/models/block_request.ml
  src/app/rosetta/models/block_response.ml
  src/app/rosetta/models/block_transaction_request.ml
  src/app/rosetta/models/block_transaction_response.ml
  src/app/rosetta/models/construction_metadata_request.ml
  src/app/rosetta/models/construction_metadata_response.ml
  src/app/rosetta/models/construction_submit_request.ml
  src/app/rosetta/models/construction_submit_response.ml
  src/app/rosetta/models/currency.ml
  src/app/rosetta/models/dune
  src/app/rosetta/models/error.ml
  src/app/rosetta/models/mempool_request.ml
  src/app/rosetta/models/mempool_response.ml
  src/app/rosetta/models/mempool_transaction_request.ml
  src/app/rosetta/models/mempool_transaction_response.ml
  src/app/rosetta/models/metadata_request.ml
  src/app/rosetta/models/network_identifier.ml
  src/app/rosetta/models/network_list_response.ml
  src/app/rosetta/models/network_options_response.ml
  src/app/rosetta/models/network_request.ml
  src/app/rosetta/models/network_status_response.ml
  src/app/rosetta/models/operation.ml
  src/app/rosetta/models/operation_identifier.ml
  src/app/rosetta/models/operation_status.ml
  src/app/rosetta/models/partial_block_identifier.ml
  src/app/rosetta/models/peer.ml
  src/app/rosetta/models/sub_account_identifier.ml
  src/app/rosetta/models/sub_network_identifier.ml
  src/app/rosetta/models/timestamp.ml
  src/app/rosetta/models/transaction.ml
  src/app/rosetta/models/transaction_identifier.ml
  src/app/rosetta/models/version.ml
  src/app/rosetta/network.ml
  src/app/rosetta/rosetta.ml
Labels: ready-to-merge

#5265 Add token permissions to accounts
  src/app/archive/create_schema.sql
  src/lib/coda_base/account.ml
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/new_account_payload.ml
  src/lib/coda_base/new_token_payload.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/token_permissions.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/transaction_union.ml
  src/lib/coda_base/transaction_union_payload.ml
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command_payload.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/merkle_ledger_tests/test_stubs.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/nonconsensus/coda_base/token_permissions.ml
Labels: ready-to-merge-into-develop

#5272 Update Terms and Conditions of Genesis Program
  frontend/website/pages/tcGenesis.mdx
  frontend/website/src/pages/MarkdownPage.re
Labels: ready-to-merge

#5277 Buildkite CI: Build artifacts medium curves
  buildkite/scripts/build-artifact.sh
  buildkite/src/Command/OpamInit.dhall
  buildkite/src/Jobs/Artifact.dhall
  buildkite/src/Jobs/ClientSdk.dhall
  buildkite/src/Jobs/CompareSignatures.dhall
  buildkite/src/Jobs/Lint/OCaml.dhall
  buildkite/src/Jobs/Unit.dhall
Labels: ready-to-merge

#5112 Spec for integration test and infra interaction
  rfcs/res/test_exec.png
  rfcs/taskforce/0003-Integration-test-infrastructure-spec.md
Labels: ready-to-merge

#5283 Add bucklescript Client_sdk to CI, fix compilation
  .circleci/config.yml
  .circleci/config.yml.jinja
  frontend/client_sdk/src/CodaSDK.re
Labels: ready-to-merge-into-develop

#5293 Change for Genesis Terms and Conditions
  frontend/website/pages/tcGenesis.mdx
Labels: ready-to-merge

#5284 Hacky hack: Always use nonconsensus profile in merlin for nonconsensus
  src/app/client_sdk/src/config.mlh
  src/nonconsensus/src/config.mlh
Labels: ready-to-merge-into-develop

#5317 Fixes mac build
  src/app/rosetta/dune
  src/app/rosetta/start.sh
  src/lib/unsigned_extended/intf.ml
  src/lib/unsigned_extended/unsigned_extended.ml
  src/opam.export
Labels: ready-to-merge

#5299 Derive Dhall type for runtime config
  Makefile
  src/app/dhall_types/dump_dhall_types.ml
  src/app/dhall_types/dune
  src/dhall_types.opam
  src/lib/currency/currency.ml
  src/lib/currency/dune
  src/lib/currency/intf.ml
  src/lib/ppx_dhall_type/deriving.ml
  src/lib/ppx_dhall_type/dhall_type.ml
  src/lib/ppx_dhall_type/dune
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
  src/nonconsensus/currency/dune
  src/ppx_dhall_type.opam
Labels: ready-to-merge-into-develop

#5327 Website: Leaderboard Sorting, Filtering and Searching
  frontend/website/public/static/img/arrowDown.svg
  frontend/website/src/components/Leaderboard.re
  frontend/website/src/pages/LeaderboardPage.re
  rfcs/res/test_exec.png
Labels: ready-to-merge

#5329 Reject if there have been empty epochs since genesis
  src/lib/consensus/proof_of_stake.ml
Labels: ready-to-merge-into-develop

#5291 expose artifact paths
  buildkite/src/Command/Base.dhall
Labels: ci-build-me, ready-to-merge

#5315 Fix mac build again...
  scripts/macos-setup-brew.sh
Labels: ready-to-merge-into-develop

#5330 Throw an error containing the blockchain state if blockchain snark fails
  src/lib/coda_base/transition_system.ml
Labels: ready-to-merge-into-develop

#5323 Buildkite: More comprehensive client sdk job
  .circleci/config.yml
  .circleci/config.yml.jinja
  README-dev.md
  buildkite/scripts/build-client-sdk.sh
  buildkite/src/Constants/ContainerImages.dhall
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile-toolchain
Labels: Taskforce Iterate (C), ci-build-me

#5335 Force python3 reinstall for Mac CI
  scripts/macos-setup-brew.sh
Labels: ready-to-merge-into-develop

#5319 Checked equality functions for currency
  src/lib/currency/currency.ml
  src/lib/currency/intf.ml
Labels: ready-to-merge-into-develop

#5336 Fix coda-demo docker image
  src/config/testnet_postake_medium_curves.mlh
Labels: ready-to-merge-into-develop

#5279 Add token commands and token information to the GraphQL API
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_graphql/pagination.ml
  src/lib/graphql_lib/base_types.ml
  src/lib/graphql_lib/base_types.mli
Labels: ready-to-merge-into-develop

#5325 Add documentation entries to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-to-merge-into-develop

#5344 Expose all transactions directly from the pool for GraphQL
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ready-to-merge-into-develop

#5019 [RFC] Blockchain in hard fork
  rfcs/0032-blockchain-in-hard-fork
Labels: ready-to-merge-into-develop

#5186 [RFC] Scan state in hard forks
  rfcs/0033-blockchain-in-hard-fork.md
  rfcs/0034-reduce-scan-state-memory-usage.md
  rfcs/0035-scan-state-hard-fork.md
Labels: ready-to-merge-into-develop

#5285 Add runtime config bin_io serialisation, make it extractable from Precomputed_values
  src/lib/currency/currency.ml
  src/lib/currency/currency.mli
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5349 Re-add compile-time-constants command
  src/app/cli/src/init/client.ml
Labels: ready-to-merge-into-develop

#5286 Remove remaining explicit Test_genesis_ledger uses
  src/app/cli/src/tests/coda_archive_node_test.ml
  src/app/cli/src/tests/coda_archive_processor_test.ml
  src/app/cli/src/tests/coda_batch_payment_test.ml
  src/app/cli/src/tests/coda_bootstrap_test.ml
  src/app/cli/src/tests/coda_change_snark_worker_test.ml
  src/app/cli/src/tests/coda_delegation_test.ml
  src/app/cli/src/tests/coda_five_nodes_test.ml
  src/app/cli/src/tests/coda_long_fork.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_restart_node_test.ml
  src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml
  src/app/cli/src/tests/coda_shared_prefix_multiproducer_test.ml
  src/app/cli/src/tests/coda_shared_state_test.ml
  src/app/cli/src/tests/coda_txns_and_restart_non_producers.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge-into-develop

#5350 Make compile-time-constants fail less, disable logging
  src/app/cli/src/init/client.ml
Labels: ready-to-merge-into-develop

#5271 block production test
  src/lib/integration_test_lib/block_production_test.ml
  src/lib/integration_test_lib/test_intf.ml
Labels: ready-to-merge

#5355 Add logging for validation errors
  src/lib/transition_router/initial_validator.ml
Labels: ready-to-merge, ready-to-merge-into-develop

#5352 Adds working dev env for rosetta
  src/app/rosetta/README.md
  src/app/rosetta/create_schema.sql
  src/app/rosetta/make-db.sh
  src/app/rosetta/make-runtime-genesis.sh
  src/app/rosetta/rosetta.ml
  src/app/rosetta/run-demo.sh
  src/app/rosetta/start.sh
  src/lib/block_producer/block_producer.ml
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#5314 Buildkite/publish-debs
  Makefile
  buildkite/scripts/build-artifact.sh
  buildkite/scripts/publish-deb.sh
  buildkite/src/Jobs/Artifact.dhall
  scripts/rebuild-deb.sh
Labels: ci-build-me, ready-to-merge

#5230 port archive-node build and archive-node test
  buildkite/scripts/setup-database-for-archive-node.sh
  buildkite/src/Jobs/ArchiveNode.dhall
  buildkite/src/Jobs/CompareSignatures.dhall
Labels: ci-build-me, ready-to-merge

#5360 Partially fixes and verifies network routes
  src/app/rosetta/errors.ml
  src/app/rosetta/graphql.ml
  src/app/rosetta/network.ml
  src/app/rosetta/rosetta.ml
  src/app/rosetta/start.sh
  src/app/rosetta/test/README.md
  src/app/rosetta/test/lib.sh
  src/app/rosetta/test/network_list.sh
  src/app/rosetta/test/network_status.sh
Labels: ready-to-merge

#5367 Add genesis block command to GraphQL
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge-into-develop

#5362 Regens rosetta models
  src/app/rosetta/README.md
  src/app/rosetta/errors.ml
  src/app/rosetta/models/allow.ml
  src/app/rosetta/models/amount.ml
  src/app/rosetta/models/construction_combine_request.ml
  src/app/rosetta/models/construction_combine_response.ml
  src/app/rosetta/models/construction_derive_request.ml
  src/app/rosetta/models/construction_derive_response.ml
  src/app/rosetta/models/construction_hash_request.ml
  src/app/rosetta/models/construction_hash_response.ml
  src/app/rosetta/models/construction_metadata_response.ml
  src/app/rosetta/models/construction_parse_request.ml
  src/app/rosetta/models/construction_parse_response.ml
  src/app/rosetta/models/construction_payloads_request.ml
  src/app/rosetta/models/construction_payloads_response.ml
  src/app/rosetta/models/construction_preprocess_request.ml
  src/app/rosetta/models/construction_preprocess_response.ml
  src/app/rosetta/models/currency.ml
  src/app/rosetta/models/enums.ml
  src/app/rosetta/models/error.ml
  src/app/rosetta/models/mempool_request.ml
  src/app/rosetta/models/network_status_response.ml
  src/app/rosetta/models/operation.ml
  src/app/rosetta/models/operation_identifier.ml
  src/app/rosetta/models/operation_status.ml
  src/app/rosetta/models/public_key.ml
  src/app/rosetta/models/signature.ml
  src/app/rosetta/models/signing_payload.ml
  src/app/rosetta/models/sub_account_identifier.ml
  src/app/rosetta/models/transaction.ml
  src/app/rosetta/network.ml
Labels: ready-to-merge-into-develop, rosetta-data-api

#5369 Add async_ssl to opam dependencies
  src/opam.export
Labels: ready-to-merge-into-develop

#5298 Integration test deployments
  src/app/test_executive/dune
  src/app/test_executive/network.ml
  src/app/test_executive/network_config.ml
  src/app/test_executive/test_executive.ml
  src/lib/file_system/file_system.ml
Labels: ready-to-merge

#5288 Add 'add_genesis_winner' option to ledger runtime_config
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5290 Runtime config: JSON layout as types
  src/app/dhall_types/dump_dhall_types.ml
  src/lib/ppx_dhall_type/deriving.ml
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5321 opt sponge
  src/lib/pickles/opt_sponge.ml
Labels: ready-to-merge-into-develop

#5373 Revert links in leaderboard on Testnet page to Member Profiles
  frontend/website/src/components/Leaderboard.re
Labels: ready-to-merge

#5370 Supports structured errors
  src/app/rosetta/errors.ml
  src/app/rosetta/graphql.ml
  src/app/rosetta/network.ml
  src/app/rosetta/rosetta.ml
  src/app/rosetta/test/network_status_err.sh
Labels: ready-to-merge, ready-to-merge-into-develop, rosetta-data-api

#5372 Add `[@@deriving to_enum]` to generate `val to_enum : t -> int`
  src/lib/ppx_coda/dune
  src/lib/ppx_coda/ppx_to_enum/dune
  src/lib/ppx_coda/ppx_to_enum/ppx_to_enum.ml
  src/ppx_to_enum.opam
Labels: ready-to-merge-into-develop

#5368 Run archive unit tests on CI
  .circleci/config.yml
  .circleci/config.yml.jinja
  buildkite/src/Jobs/ArchiveNode.dhall
  src/app/archive/drop_tables.sql
Labels: ready-to-merge-into-develop

#5378 WORKSPACE: add local_repository for each submodule in src/external
  WORKSPACE
Labels: ready-to-merge-into-develop

#5374 Switches rosetta genesis block to graphql
  frontend/bot/src/Echo.re
  frontend/bot/src/Faucet.re
  frontend/bot/src/Repeater.re
  frontend/wallet/src/render/views/settings/AccountSettings.re
  frontend/wallet/src/render/views/transactions/Transactions.re
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/rosetta/network.ml
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge

#5395 Use CircleCIs pipeline.git.base_revision instead of a JSON query
  .circleci/config.yml
  .circleci/config.yml.jinja
  scripts/compare_ci_diff_binables.sh
  scripts/compare_ci_diff_types.sh
  scripts/compare_pr_diff_binables.py
  scripts/compare_pr_diff_items.py
  scripts/compare_pr_diff_types.py
Labels: ready-to-merge-into-develop

#5379 Add ppx_representatives
  src/lib/ppx_coda/dune
  src/lib/ppx_coda/ppx_representatives/dune
  src/lib/ppx_coda/ppx_representatives/ppx_representatives.ml
  src/lib/ppx_coda/ppx_representatives/runtime/dune
  src/lib/ppx_coda/ppx_representatives/runtime/ppx_representatives_runtime.ml
  src/ppx_representatives.opam
Labels: ready-to-merge-into-develop

#5401 Fix PR comparisons
  scripts/compare_pr_diff_items.py
Labels: ready-to-merge-into-develop

#5398 Implements Account API for Rosetta
  graphql_schema.json
  src/app/rosetta/account.ml
  src/app/rosetta/decoders.ml
  src/app/rosetta/errors.ml
  src/app/rosetta/network.ml
  src/app/rosetta/rosetta.ml
  src/app/rosetta/test/account_list.sh
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge, ready-to-merge-into-develop

#5400 [Trivial] Log the runtime configuration on startup
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ready-to-merge-into-develop

#5402 Updating pooled user commands CLI help text
  frontend/website/pages/docs/cli-reference.mdx
  src/app/cli/src/init/client.ml
Labels: ready-to-merge

#5346 Archive node pruning
  src/app/archive/archive.ml
  src/app/archive/archive_lib/dune
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/archive/create_schema.sql
  src/app/cli/src/tests/coda_archive_processor_test.ml
Labels: ready-to-merge-into-develop

#5403 Uses new goodies that @mrmr1993 has created
  src/app/rosetta/dune
  src/app/rosetta/lib/dune
  src/app/rosetta/lib/errors.ml
Labels: ready-to-merge, ready-to-merge-into-develop

#5404 Finishes up network allow
  src/app/rosetta/lib/network.ml
  src/app/rosetta/test/network_options.sh
Labels: ready-to-merge-into-develop

#5407 Add accounts query to GraphQL
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge-into-develop

#5405 Completes test coverage on network endpoints
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/errors.ml
  src/app/rosetta/lib/network.ml
  src/app/rosetta/lib/rosetta.ml
  src/app/rosetta/lib/test.ml
Labels: ready-to-merge

#5416 Partially implements Mempool API
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/lib/rosetta.ml
  src/app/rosetta/start.sh
  src/app/rosetta/test/mempool_all.sh
Labels: ready-to-merge-into-develop

#5410 Website: Leaderboard and Member Profile front end fixes from QA (new branch)
  frontend/website/src/components/ChallengePointsTable.re
  frontend/website/src/components/Leaderboard.re
  frontend/website/src/components/ProfileHero.re
  frontend/website/src/components/Summary.re
  frontend/website/src/components/Wrapped.re
  frontend/website/src/pages/LeaderboardPage.re
Labels: ready-to-merge

#5328 Change leaderboard copy styles
  frontend/website/src/pages/Testnet.re
Labels: ready-to-merge

#5420 fix for qa-net forking
  src/app/cli/src/coda.ml
  src/lib/block_producer/block_producer.ml
Labels: ready-to-merge

#5359 Update README.md
  README-dev.md
  README.md
Labels: ready-to-merge

#5422 Revert "Adding support for badges in Leaderboard "
  frontend/leaderboard/src/Sheets.re
  frontend/leaderboard/src/UploadLeaderboardData.re
  frontend/leaderboard/src/UploadLeaderboardPoints.re
  frontend/website/public/static/img/LeaderboardAwardCommunityMVP.png
  frontend/website/public/static/img/LeaderboardAwardDoubleMVP.png
  frontend/website/public/static/img/LeaderboardAwardGenesisMember.png
  frontend/website/public/static/img/LeaderboardAwardTechnicalMVP.png
  frontend/website/src/components/Badge.re
  frontend/website/src/components/ChallengePointsTable.re
  frontend/website/src/components/Leaderboard.re
  frontend/website/src/components/ProfileHero.re
  frontend/website/src/components/svg/Icons.re
  frontend/website/src/pages/MemberProfilePage.re
Labels: ready-to-merge

#5433 skip reboradcast log for internally generated blocks
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge

#5417 Carry the status of user commands with them once applied
  src/app/archive/archive_lib/diff.ml
  src/app/archive/archive_lib/dune
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/archive/create_schema.sql
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/lib/auxiliary_database/filtered_external_transition.ml
  src/lib/block_producer/block_producer.ml
  src/lib/coda_base/ledger.mli
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/transaction_validator.ml
  src/lib/coda_base/transaction_validator.mli
  src/lib/coda_base/user_command_status.ml
  src/lib/coda_base/with_status.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/staged_ledger/diff_creation_log.ml
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/staged_ledger_diff/staged_ledger_diff.ml
  src/lib/staged_ledger_diff/staged_ledger_diff.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transaction_status/transaction_status.ml
  src/lib/transaction_witness/transaction_witness.ml
  src/lib/transaction_witness/transaction_witness.mli
  src/lib/transition_frontier/extensions/best_tip_diff.ml
  src/lib/transition_frontier/extensions/best_tip_diff.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
Labels: ready-to-merge-into-develop

#5397 Fix CI: Use a Brewfile for Mac CI setup
  .circleci/config.yml
  .circleci/config.yml.jinja
  scripts/Brewfile
  scripts/macos-setup-brew.sh
Labels: ready-to-merge-into-develop

#5292 Inline config for bootstrap integration test
  .circleci/config.yml
  .circleci/config.yml.jinja
  .mergify.yml
  scripts/test.py
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/tests/coda_archive_node_test.ml
  src/app/cli/src/tests/coda_archive_processor_test.ml
  src/app/cli/src/tests/coda_batch_payment_test.ml
  src/app/cli/src/tests/coda_block_production_test.ml
  src/app/cli/src/tests/coda_bootstrap_test.ml
  src/app/cli/src/tests/coda_change_snark_worker_test.ml
  src/app/cli/src/tests/coda_delegation_test.ml
  src/app/cli/src/tests/coda_five_nodes_test.ml
  src/app/cli/src/tests/coda_long_fork.ml
  src/app/cli/src/tests/coda_peers_test.ml
  src/app/cli/src/tests/coda_process.ml
  src/app/cli/src/tests/coda_processes.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_restart_node_test.ml
  src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml
  src/app/cli/src/tests/coda_shared_prefix_multiproducer_test.ml
  src/app/cli/src/tests/coda_shared_prefix_test.ml
  src/app/cli/src/tests/coda_shared_state_test.ml
  src/app/cli/src/tests/coda_transitive_peers_test.ml
  src/app/cli/src/tests/coda_txns_and_restart_non_producers.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/config/test_postake_bootstrap.mlh
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5445 Expose creation fees paid and token created on transactions and in archive node
  src/app/archive/archive_lib/processor.ml
  src/app/archive/create_schema.sql
  src/lib/coda_base/token_id.ml
  src/lib/coda_base/token_id.mli
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/user_command_status.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/staged_ledger/staged_ledger.ml
Labels: ready-to-merge-into-develop

#5455 fix broadcast log
  src/lib/coda_networking/coda_networking.ml
Labels: ready-to-merge-into-develop

#5441 Use inline configs for split_snarkless profile integration tests
  .circleci/config.yml
  scripts/test.py
  src/app/cli/src/tests/coda_archive_node_test.ml
  src/app/cli/src/tests/coda_block_production_test.ml
  src/app/cli/src/tests/coda_change_snark_worker_test.ml
  src/app/cli/src/tests/coda_peers_test.ml
  src/app/cli/src/tests/coda_shared_prefix_test.ml
  src/app/cli/src/tests/coda_transitive_peers_test.ml
  src/config/test_postake_split_snarkless.mlh
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5466 Cached transaction hashes in the API
  src/lib/auxiliary_database/external_transition_database.ml
  src/lib/auxiliary_database/filtered_external_transition.ml
  src/lib/auxiliary_database/transaction_database.ml
  src/lib/auxiliary_database/transaction_database.mli
  src/lib/block_producer/block_producer.ml
  src/lib/coda_base/dune
  src/lib/coda_base/transaction_hash.ml
  src/lib/coda_base/transaction_hash.mli
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_subscriptions.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_status/transaction_status.ml
  src/lib/with_hash/with_hash.ml
Labels: ready-to-merge-into-develop

#5467 Add hashes to pooledUserCommands in GraphQL API
  src/lib/coda_base/transaction_hash.mli
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ready-to-merge-into-develop

#5348 [RFC] Creating a hard fork if there's a disaster
  rfcs/0036-hard-fork-disaster-recovery.md
Labels: ready-to-merge-into-develop

#5475 Use the given runtime config instead of inferring one
  src/app/cli/src/tests/coda_peers_test.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_transitive_peers_test.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/dune
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
Labels: ready-to-merge-into-develop

#5477 Inline config for delegation integration test
  .circleci/config.yml
  .mergify.yml
  scripts/test.py
  src/app/cli/src/tests/coda_delegation_test.ml
  src/config/test_postake_delegation.mlh
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5456 Allow statistics as a statistics provider
  src/app/validation/lib/architecture/statistic.ex
  src/app/validation/lib/coda/application.ex
  src/app/validation/lib/coda/statistics/block_production_rate.ex
  src/app/validation/lib/util.ex
  src/app/validation/test/architecture_tests/statistic_test.exs
Labels: ready-to-merge-into-develop

#5215 [RFC] Switch over from squash-and-merge to merge commits
  rfcs/0037-github-merging-strategy.md
Labels: ready-to-merge-into-develop

#5474 Fix: Re-enable some tests
  .circleci/config.yml
  .mergify.yml
  scripts/test.py
  src/app/cli/src/tests/coda_delegation_test.ml
  src/config/test_postake_delegation.mlh
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5488 Circle ci build me
  .circleci/config.yml
  .circleci/config.yml.jinja
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  frontend/ci-build-me/README.md
  frontend/ci-build-me/src/index.js
Labels: ci-build-me, ready-to-merge

#5451 Add coinbase amount and account creation fee to GraphQL
  src/lib/coda_graphql/coda_graphql.ml
Labels: ci-build-me, ready-to-merge

#5499 Dump the JSON that failed to parse in the runtime config
  src/lib/runtime_config/runtime_config.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5345 upload logs for unit tests
  buildkite/src/Jobs/ArchiveNode.dhall
  buildkite/src/Jobs/Unit.dhall
Labels: ci-build-me, ready-to-merge

#5429 Rosetta Block API
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/archive/create_schema.sql
  src/app/rosetta/drop_tables.sql
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/amount_of.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/errors.ml
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/lib/network.ml
  src/app/rosetta/lib/operation_statuses.ml
  src/app/rosetta/lib/operation_types.ml
  src/app/rosetta/lib/rosetta.ml
  src/app/rosetta/lib/these.ml
Labels: ci-build-me, ready for review, ready-to-merge

#5459 Real db support for block query
  src/app/archive/archive_lib/processor.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/dune
  src/app/rosetta/lib/errors.ml
  src/app/rosetta/lib/rosetta.ml
  src/app/rosetta/start.sh
  src/app/rosetta/test/block.sh
Labels: ci-build-me, ready-to-merge

#5503 Add basic plugin support
  src/app/cli/src/coda.ml
  src/app/cli/src/dune
  src/coda_plugins.opam
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_frontend.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/fake_hash.mlh
  src/config/fuzz_medium.mlh
  src/config/fuzz_small.mlh
  src/config/print_versioned_types.mlh
  src/config/test_archive_processor.mlh
  src/config/test_postake.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_full_epoch.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_three_producers.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_producers.mlh
  src/config/testnet_postake_many_producers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/lib/coda_plugins/coda_plugins.ml
  src/lib/coda_plugins/coda_plugins.mli
  src/lib/coda_plugins/dune
  src/lib/coda_plugins/examples/do_nothing/dune
  src/lib/coda_plugins/examples/do_nothing/plugin_do_nothing.ml
Labels: ci-build-me, ready-to-merge-into-develop

#5490 Switch over to merge for mergify
  .mergify.yml
  .mergify.yml.jinja
Labels: ci-build-me

#5506 Integer_js_stubs owned by protocol
  CODEOWNERS
Labels: ci-build-me, ready-to-merge-into-develop

#5516 Initial pass at Rosetta test-agent
  src/app/rosetta/agent.opam
  src/app/rosetta/start.sh
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/dune
  src/app/rosetta/test-agent/peek.ml
  src/app/rosetta/test-agent/poke.ml
  src/app/rosetta/test-curl/README.md
  src/app/rosetta/test-curl/account_list.sh
  src/app/rosetta/test-curl/block.sh
  src/app/rosetta/test-curl/lib.sh
  src/app/rosetta/test-curl/mempool_all.sh
  src/app/rosetta/test-curl/network_list.sh
  src/app/rosetta/test-curl/network_options.sh
  src/app/rosetta/test-curl/network_status.sh
  src/app/rosetta/test-curl/network_status_err.sh
Labels: ci-build-me, ready-to-merge

#5520 Create Snapps Doc Page
  frontend/website/pages/docs/snapps.mdx
  frontend/website/src/components/DocsSideNav.re
Labels: ci-build-me, ready-to-merge

#5528 Sane logging when no keys are on
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_graphql/dune
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me, ready-to-merge

#5533 Website: Fix typo in snapps docs page
  frontend/website/pages/docs/snapps.mdx
Labels: ci-build-me, ready-to-merge

#5529 Upgrades rosetta to 1.4.1 of the spec
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/network.ml
  src/app/rosetta/models/account_balance_response.ml
  src/app/rosetta/models/block.ml
  src/app/rosetta/models/coin.ml
  src/app/rosetta/models/coin_change.ml
  src/app/rosetta/models/coin_identifier.ml
  src/app/rosetta/models/enums.ml
  src/app/rosetta/models/error.ml
  src/app/rosetta/models/network_status_response.ml
  src/app/rosetta/models/operation.ml
  src/app/rosetta/models/sync_status.ml
  src/app/rosetta/models/transaction_identifier_response.ml
Labels: ci-build-me, ready-to-merge, ready-to-merge-into-develop

#5530 Implements initial check payment test via mempool
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/dune
  src/app/rosetta/test-agent/peek.ml
  src/app/rosetta/test-agent/poke.ml
Labels: ci-build-me, ready-to-merge-into-develop
