Repository MinaProtocol/mina, pull requests merged in 2020-05, with the labels that each got.

#4813 Combine genesis_state/ledger/hash/proof into Precomputed_values.t
  src/app/archive/archive_lib/test.ml
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/bootstrap_controller.mli
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_intf/transition_frontier_components_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/config.ml
  src/lib/coda_state/genesis_protocol_state.ml
  src/lib/coda_state/genesis_protocol_state.mli
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/keys_lib/keys.ml
  src/lib/keys_lib/keys.mli
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/precomputed_values/dune
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/prover/prover.ml
  src/lib/transaction_status/transaction_status.ml
  src/lib/transition_frontier/persistent_root/persistent_root.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_router/initial_validator.ml
  src/lib/transition_router/transition_router.ml
Labels: ready-to-merge

#4814 Scaffold for buildkite CI. Fixes #4801
  .buildkite/agent.nix
  .buildkite/pipeline.dhall
  .buildkite/scripts/generate-diff.sh
  .buildkite/src/External/Prelude.dhall
  .buildkite/src/Jobs.dhall
  .buildkite/src/Lib/Command.dhall
  .buildkite/src/Lib/JobSpec.dhall
  .buildkite/src/Lib/Pipeline.dhall
  .buildkite/src/Lib/Size.dhall
  .buildkite/src/Monorepo.dhall
  .buildkite/src/jobs/Sample/Pipeline.dhall
  .buildkite/src/jobs/Sample/Spec.dhall
  .buildkite/src/jobs/Sample2/Pipeline.dhall
  .buildkite/src/jobs/Sample2/Spec.dhall
  CODEOWNERS
Labels: ready-to-merge

#4763 Adds task-force RFC for buildkite-ci
  rfcs/taskforce/0000-template.md
  rfcs/taskforce/0001-buildkiteci.md
Labels: ready-to-merge

#4819 Lift versioned type out of snark pool, diff functors
  src/lib/gossip_net/message.ml
  src/lib/network_pool/intf.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/network_pool/test.ml
  src/lib/ppx_coda/versioned_type.ml
  src/lib/transaction_snark_work/transaction_snark_work.ml
Labels: ready-to-merge

#4823 Buildkite auto jobs and check dhall
  .buildkite/Makefile
  .buildkite/pipeline.dhall
  .buildkite/scripts/generate-jobs.sh
  .buildkite/src/Jobs.dhall
  .buildkite/src/Lib/TriggerCommand.dhall
  .buildkite/src/Monorepo.dhall
  .buildkite/src/Prepare.dhall
  .buildkite/src/gen/Jobs.dhall
  .buildkite/src/jobs/CheckDhall/Pipeline.dhall
  .buildkite/src/jobs/CheckDhall/Spec.dhall
Labels: Taskforce Iterate (C)

#4812 Data hash includes b58
  src/lib/base58_check/version_bytes.ml
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/data_hash.mli
  src/lib/coda_base/data_hash_intf.ml
  src/lib/coda_base/ledger_hash.ml
  src/lib/coda_base/ledger_hash_intf.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/receipt.ml
  src/lib/coda_base/receipt.mli
  src/lib/coda_base/state_body_hash.ml
  src/lib/coda_base/state_body_hash.mli
  src/lib/coda_base/state_hash.ml
  src/lib/coda_base/state_hash.mli
  src/lib/consensus/proof_of_stake.ml
  src/lib/currency/currency.ml
  src/lib/merkle_address/merkle_address.ml
Labels: ready-to-merge

#4701 Rename User_command.is_trivial to has_insufficient_fee
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command_intf.ml
  src/lib/coda_networking/coda_networking.ml
Labels: ready-to-merge

#4828 Add scaffold for leaderboard project
  frontend/leaderboard/.gitignore
  frontend/leaderboard/bsconfig.json
  frontend/leaderboard/package.json
  frontend/leaderboard/src/Main.re
  frontend/leaderboard/yarn.lock
Labels: ready-to-merge

#4834 Leaderboard: Add public key in subscription
  frontend/points-hack-april20/lib.js
Labels: ready-to-merge

#4837 Pending coinbase, hoist versioned types
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/pending_coinbase_intf.ml
  src/lib/staged_ledger_hash/staged_ledger_hash.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ready-to-merge

#4835 Hoist versioned Diff outside functor in Transaction_pool
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/gossip_net/message.ml
  src/lib/network_pool/dune
  src/lib/network_pool/intf.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ready-to-merge

#4844 Logger.Impl, use %%versioned_binable
  src/lib/logger/dune
  src/lib/logger/impl.ml
Labels: ready-to-merge

#4842 Allow flexible account JSON
  src/lib/account_config/account_config.ml
Labels: ready-to-merge

#4840 Move Binable.Of_stringable to versioned module
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/dune
Labels: ready-to-merge

#4841 Add %%versioned to Transaction_snark_scan_state.t
  src/lib/transaction_snark_scan_state/dune
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Labels: ready-to-merge

#4843 Fix update-branch-protection CI job
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#4830 Move runtime_genesis_ledger.exe logic into genesis_ledger_helper
  src/app/cli/src/coda.ml
  src/app/runtime_genesis_ledger/dune
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/genesis_ledger_helper/dune
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ready-to-merge

#4849 Perf_histograms, unversioned bin_io
  src/lib/perf_histograms/histogram.ml
Labels: ready-to-merge

#4833 Runtime proof-level
  src/app/archive/archive_lib/test.ml
  src/app/cli/src/coda.ml
  src/app/cli/src/init/snark_flame_graphs.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/runtime_genesis_ledger/gen/gen.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/blockchain_snark/blockchain_snark_state.mli
  src/lib/blockchain_snark/blockchain_transition.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/cache_dir/cache_dir.ml
  src/lib/coda_base/transition_system.ml
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/config.ml
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/keys_lib/keys.ml
  src/lib/keys_lib/keys.mli
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/test.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/prover/intf.ml
  src/lib/prover/prover.ml
  src/lib/snark_worker/debug.ml
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/snark_worker/prod.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_status/transaction_status.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
  src/lib/verifier/dummy.ml
  src/lib/verifier/prod.ml
  src/lib/verifier/verifier_intf.ml
Labels: ready-to-merge

#4698 protocol states for transactions in the scan state
  src/app/cli/src/tests/coda_bootstrap_test.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_intf/transition_frontier_components_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/coda_networking.mli
  src/lib/fake_network/fake_network.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/sync_handler/sync_handler.ml
  src/lib/sync_status/sync_status.ml
  src/lib/transaction_snark_scan_state/dune
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transition_chain_prover/transition_chain_prover.ml
  src/lib/transition_frontier/extensions/root_history.ml
  src/lib/transition_frontier/extensions/root_history.mli
  src/lib/transition_frontier/frontier_base/diff.ml
  src/lib/transition_frontier/frontier_base/diff.mli
  src/lib/transition_frontier/frontier_base/frontier_hash.ml
  src/lib/transition_frontier/frontier_base/frontier_intf.ml
  src/lib/transition_frontier/frontier_base/root_data.ml
  src/lib/transition_frontier/frontier_base/root_data.mli
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/full_frontier/full_frontier.mli
  src/lib/transition_frontier/persistent_frontier/database.ml
  src/lib/transition_frontier/persistent_frontier/database.mli
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
Labels: ready-to-merge

#4839 Move fake_accounts_target to genesis_constants
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/config/ledger_depth/full.mlh
  src/config/ledger_depth/small.mlh
  src/config/ledger_depth/tiny.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/lib/cache_dir/cache_dir.ml
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger/testnet_postake_ledger.ml
Labels: ready-to-merge

#4851 Remove serialization from Ledger_proof
  src/lib/work_selector/dune
  src/lib/work_selector/inputs.ml
Labels: ready-to-merge

#4848 Fix network pool rebroadcast loop
  src/lib/network_pool/network_pool_base.ml
Labels: ready-to-merge

#4847 Properly configure minimum tx fee
  src/config/amount_defaults/realistic.mlh
  src/config/amount_defaults/standard.mlh
  src/lib/coda_base/import.ml
  src/lib/coda_base/user_command.ml
  src/lib/coda_compile_config/coda_compile_config.ml
Labels: ready-to-merge

#4832 add a global_metadata to logger
  src/lib/gossip_net/libp2p.ml
  src/lib/logger/impl.ml
  src/lib/logger/impl.mli
Labels: ready-to-merge

#4852 Sorts leaderboard by current testnet, not total
  frontend/website/src/components/Leaderboard.re
Labels: ready-to-merge

#4649 [RFC] Sentry design
  rfcs/0031-sentry-architecture.md
Labels: ready-to-merge

#4846 Remove bin_io inside Location.Make
  src/lib/coda_base/ledger.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/dune
  src/lib/merkle_ledger/location.ml
  src/lib/merkle_ledger/location_intf.ml
  src/lib/merkle_ledger/util.ml
  src/lib/merkle_ledger_tests/test.ml
  src/lib/merkle_ledger_tests/test_database.ml
  src/lib/merkle_ledger_tests/test_mask.ml
  src/lib/merkle_mask/dune
  src/lib/merkle_mask/inputs_intf.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/merkle_mask/masking_merkle_tree_intf.ml
  src/lib/syncable_ledger/test.ml
Labels: ready-to-merge

#4854 Unrequire split_snarkless test, remove long-fork bootstrap test
  .circleci/config.yml
  .mergify.yml
  scripts/test.py
Labels: ready-to-merge

#4857 Disambiguate read/write response in metrics
  src/lib/perf_histograms/rpc.ml
Labels: ready-to-merge

#4797 Re-disable the libp2p publish messages
  src/app/decoder/decoder.ml
  src/app/decoder/dune
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/lib/coda_net2/coda_net2.ml
Labels: ready-to-merge

#4860 Carry the ledger depth in the ledger
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/ledger.mli
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/sparse_ledger.mli
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/transaction_validator.ml
  src/lib/empty_hashes/empty_hashes.ml
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger/intf.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/merkle_address/merkle_address.ml
  src/lib/merkle_address/merkle_address.mli
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_inputs_intf.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/database_intf.ml
  src/lib/merkle_ledger/graphviz.ml
  src/lib/merkle_ledger/location.ml
  src/lib/merkle_ledger/location_intf.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_ledger/syncable_intf.ml
  src/lib/merkle_ledger/util.ml
  src/lib/merkle_ledger_tests/test.ml
  src/lib/merkle_ledger_tests/test_database.ml
  src/lib/merkle_ledger_tests/test_mask.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/merkle_mask/masking_merkle_tree_intf.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/syncable_ledger/test.ml
  src/lib/test_genesis_ledger/test_genesis_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_root/persistent_root.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_router/transition_router.ml
Labels: ready-to-merge

#4824 BuildKite jobs in Docker
  .buildkite/Makefile
  .buildkite/agent.nix
  .buildkite/docker.nix
  .buildkite/hooks/post-checkout
  .buildkite/shell.nix
  .buildkite/src/Constants/ContainerImages.dhall
  .buildkite/src/Lib/Command.dhall
  .buildkite/src/Lib/Docker.dhall
  .buildkite/src/Monorepo.dhall
  .buildkite/src/Prepare.dhall
  .buildkite/src/jobs/CheckDhall/Pipeline.dhall
  .buildkite/src/jobs/Sample/Pipeline.dhall
  .buildkite/src/jobs/Sample2/Pipeline.dhall
Labels: ready-to-merge

#4864 Namespaces points hack
  frontend/points-hack-april20/lib.js
Labels: ready-to-merge

#4865 Fixes bad reference to variable in points-hack
  frontend/points-hack-april20/lib.js
Labels: ready-to-merge

#4863 Secret_box, rename Stable module
  src/lib/secrets/dune
  src/lib/secrets/secret_box.ml
  src/lib/secrets/secret_box.mli
Labels: ready-to-merge

#4855 Move protocol constant 'c' to Genesis_constants
  src/app/cli/src/coda.ml
  src/app/cli/src/init/snark_flame_graphs.ml
  src/app/cli/src/tests/coda_long_fork.ml
  src/app/cli/src/tests/coda_peers_test.ml
  src/app/cli/src/tests/coda_processes.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_transitive_peers_test.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/app/cli/src/tests/full_test.ml
  src/app/runtime_genesis_ledger/gen/gen.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/block_producer/block_producer.ml
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/blockchain_snark/blockchain_snark_state.mli
  src/lib/blockchain_snark/blockchain_transition.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/bootstrap_controller.mli
  src/lib/cache_dir/cache_dir.ml
  src/lib/coda_base/transition_system.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_intf/transition_frontier_components_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/config.ml
  src/lib/coda_state/genesis_protocol_state.ml
  src/lib/coda_state/genesis_protocol_state.mli
  src/lib/coda_state/protocol_state.ml
  src/lib/coda_state/protocol_state.mli
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/consensus/constants.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/keys_lib/keys.ml
  src/lib/keys_lib/keys.mli
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/prover/intf.ml
  src/lib/prover/prover.ml
  src/lib/transaction_status/transaction_status.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/full_frontier/full_frontier.mli
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_router/initial_validator.ml
  src/lib/transition_router/transition_router.ml
Labels: ready-to-merge

#4868 [TRIVIAL] Move ledger_depth into Genesis_constants.Constraint_constants.t
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/test_genesis_ledger/test_genesis_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
Labels: ready-to-merge

#4871 Snark_worker, versioned RPCs outside functors
  src/app/cli/src/init/coda_run.ml
  src/lib/snark_worker/debug.ml
  src/lib/snark_worker/dune
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/snark_worker/prod.ml
  src/lib/snark_worker/rpcs.ml
  src/lib/snark_worker/snark_worker.ml
Labels: ready-to-merge

#4872 Blake2, use %%versioned_binable
  src/lib/blake2/blake2.ml
  src/lib/blake2/dune
  src/lib/ppx_coda/versioned_module.ml
Labels: ready-to-merge

#4870 include a state_hash in broadcast log
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/coda_networking.mli
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
Labels: ready-to-merge

#4875 Update/remove outdated comments
  src/app/cli/src/init/coda_run.ml
  src/lib/ppx_coda/define_locally.ml
Labels: ready-to-merge

#4876 Remove some 27 errors-as-warnings
  src/lib/coda_base/account.ml
  src/lib/coda_base/user_command_payload.ml
  src/lib/pickles_types/dlog_marlin_types.ml
  src/lib/pickles_types/dune
  src/lib/pickles_types/hlist.ml
  src/lib/pickles_types/nat.ml
  src/lib/pickles_types/pairing_marlin_types.ml
  src/lib/pickles_types/pcs_batch.ml
  src/lib/pickles_types/vector.ml
Labels: ready-to-merge

#4869 Add functions to collect 3 more metrics for leaderboard
  frontend/leaderboard/src/Challenges.re
  frontend/leaderboard/src/Types.re
Labels: ready-to-merge

#4877 Lint versioned types in extension expressions
  src/lib/ppx_coda/lint_version_syntax.ml
  src/lib/transition_frontier/persistent_frontier/database.ml
  src/lib/verifier/prod.ml
Labels: ready-to-merge

#4878 Packaged modules may not have specific versions
  src/lib/ppx_coda/lint_version_syntax.ml
Labels: ready-to-merge

#4817 RFC: Network Utility Tool
  rfcs/taskforce/0002-network-utility.md
Labels: RFC

#4891 Pickles_types, don't include Stable.Latest
  src/lib/pickles_types/pairing_marlin_types.ml
Labels: ready-to-merge

#4895 Pickles_types, fix more Stable.Latest
  src/lib/pickles_types/abc.ml
  src/lib/pickles_types/dlog_marlin_types.ml
  src/lib/pickles_types/matrix_evals.ml
  src/lib/pickles_types/pairing_marlin_types.ml
  src/lib/pickles_types/scalar_challenge.ml
Labels: ready-to-merge

#4874 GraphQL: Add more detail to the coinbase transaction
  frontend/points-hack-april20/lib.js
  graphql_schema.json
  src/lib/auxiliary_database/filtered_external_transition.ml
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge

#4898 Lint include Stable.Latest
  src/lib/group_map/bw19.ml
  src/lib/group_map/group_map.ml
  src/lib/group_map/group_map.mli
  src/lib/ppx_coda/lint_version_syntax.ml
  src/lib/transition_frontier/frontier_base/diff.ml
Labels: ready-to-merge

#4897 Add functions to Leaderboard challenges: award top n points and 1st, 2nd.. place
  frontend/leaderboard/src/Challenges.re
Labels: ready-to-merge

#4896 docs: Fix SDK delegation typo
  frontend/client_sdk/src/CodaSDK.d.ts
  frontend/client_sdk/src/CodaSDK.re
Labels: ready-to-merge

#4867 Remove remaining `Coda_compile_config.ledger_depth` uses
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/block_producer/block_producer.ml
  src/lib/cache_dir/cache_dir.ml
  src/lib/coda_base/account.ml
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/ledger_hash.ml
  src/lib/coda_base/ledger_hash_intf.ml
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/location.ml
  src/lib/merkle_ledger/location_intf.ml
  src/lib/merkle_ledger_tests/test.ml
  src/lib/merkle_ledger_tests/test_database.ml
  src/lib/merkle_ledger_tests/test_mask.ml
  src/lib/snark_worker/debug.ml
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/snark_worker/prod.ml
  src/lib/syncable_ledger/test.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/vrf_lib/dune
  src/lib/vrf_lib/integrated.ml
  src/lib/vrf_lib/integrated_test.ml
Labels: ready-to-merge

#4909 Fix, move version ppx tests
  scripts/require-ppx-version.py
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/bad_version_syntax_missing_version.ml
  src/lib/ppx_coda/tests/dune
  src/lib/ppx_coda/tests/versioned_bad_contained_types.ml
  src/lib/ppx_coda/tests/versioned_bad_gadt.ml
  src/lib/ppx_coda/tests/versioned_bad_gadt_results.ml
  src/lib/ppx_coda/tests/versioned_bad_option.ml
  src/lib/ppx_coda/tests/versioned_bad_type_name.ml
  src/lib/ppx_coda/tests/versioned_bad_type_parameters.ml
  src/lib/ppx_coda/tests/versioned_good.ml
  src/lib/ppx_version/tests/Makefile
  src/lib/ppx_version/tests/bad_version_syntax_bin_io_in_functor.ml
  src/lib/ppx_version/tests/bad_version_syntax_extension.ml
  src/lib/ppx_version/tests/bad_version_syntax_missing_versioned.ml
  src/lib/ppx_version/tests/bad_version_syntax_multiple_errors.ml
  src/lib/ppx_version/tests/bad_version_syntax_version_in_functor.ml
  src/lib/ppx_version/tests/bad_versioned_in_functor.ml
  src/lib/ppx_version/tests/bad_versioned_in_nested_functor.ml
  src/lib/ppx_version/tests/dune
  src/lib/ppx_version/tests/good_version_syntax.ml
  src/lib/ppx_version/tests/versioned_bad_arrow_type.ml
  src/lib/ppx_version/tests/versioned_bad_contained_types.ml
  src/lib/ppx_version/tests/versioned_bad_module_name.ml
  src/lib/ppx_version/tests/versioned_bad_module_structure.ml
  src/lib/ppx_version/tests/versioned_bad_option.ml
  src/lib/ppx_version/tests/versioned_bad_type_name.ml
  src/lib/ppx_version/tests/versioned_bad_unnumbered.ml
  src/lib/ppx_version/tests/versioned_bad_version_name.ml
  src/lib/ppx_version/tests/versioned_bad_wrapped_module_structure.ml
  src/lib/ppx_version/tests/versioned_good.ml
  src/lib/ppx_version/tests/versioned_module_bad_missing_to_latest.ml
  src/lib/ppx_version/tests/versioned_module_bad_missing_type.ml
  src/lib/ppx_version/tests/versioned_module_bad_stable_name.ml
  src/lib/ppx_version/tests/versioned_module_bad_version_name.ml
  src/lib/ppx_version/tests/versioned_module_bad_version_order.ml
  src/lib/ppx_version/tests/versioned_module_good.ml
  src/lib/ppx_version/tests/versioned_sig_good.ml
Labels: ready-to-merge

#4910 Failwith when wrong version; rm wrapped, for_tests, unnumbered
  src/lib/ppx_version/versioned_module.ml
  src/lib/ppx_version/versioned_type.ml
Labels: ready-to-merge

#4912 Remove some more misplaced versioned types
  src/lib/blake2/intf.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/network_peer/peer.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
Labels: ready-to-merge

#4907 Adds function to filter blocks by time window
  frontend/leaderboard/src/Challenges.re
  frontend/leaderboard/src/Metrics.re
  frontend/leaderboard/src/Types.re
Labels: ready-to-merge

#4884 JSON runtime configuration
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  docs/daemon.md
  genesis_ledgers/phase_three/config.json
  scripts/rebuild-deb.sh
  src/app/cli/src/coda.ml
  src/app/runtime_genesis_ledger/dune
  src/app/runtime_genesis_ledger/gen/dune
  src/app/runtime_genesis_ledger/gen/gen.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/coda_runtime_config.opam
  src/lib/account_config/account_config.ml
  src/lib/account_config/account_config.mli
  src/lib/account_config/dune
  src/lib/cache_dir/cache_dir.ml
  src/lib/command_line_tests/command_line_tests.ml
  src/lib/command_line_tests/dune
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger_helper/dune
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/dune
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/test_genesis_ledger/test_genesis_ledger.ml
Labels: ready-to-merge

#4920 Fix dockerfile path
  dockerfiles/Dockerfile-coda-demo
  scripts/run-demo.sh
Labels: ready-to-merge

#4903 Separate compiled protocol state from unit test protocol state
  src/lib/coda_state/genesis_protocol_state.ml
  src/lib/coda_state/genesis_protocol_state.mli
  src/lib/precomputed_values/gen_values/gen_values.ml
Labels: ready-to-merge

#4700 Remove User_command.is_payment
  src/app/archive/archive_lib/processor.ml
  src/lib/coda_base/transaction_union_tag.ml
  src/lib/coda_base/transaction_union_tag.mli
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command_intf.ml
  src/lib/coda_base/user_command_payload.ml
  src/lib/coda_base/user_command_payload.mli
Labels: ready-to-merge

#4845 Testnet guardian runbook
  docs/testnet-guardian-runbook.md
Labels: ready-to-merge

#4908 minor nix fixups for README-dev
  README-dev.md
Labels: ready-to-merge

#4655 Include more debug information in test failures
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/lib/currency/currency.ml
  src/lib/currency/currency.mli
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/transaction_pool.ml
Labels: ready-to-merge

#4918 Leaderboard: Add function to combine two points maps for subchallenges
  frontend/leaderboard/src/Metrics.re
Labels: ready-to-merge

#4888 Remove unused test modules
  src/lib/merkle_ledger_tests/dune
  src/lib/merkle_ledger_tests/test_stubs.ml
Labels: ready-to-merge

#4923 Move Serialization to Ppx_version
  src/lib/blake2/blake2.ml
  src/lib/blake2/dune
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/dune
  src/lib/coda_base/proof.ml
  src/lib/coda_base/signature.ml
  src/lib/coda_base/target.ml
  src/lib/genesis_constants/dune
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/lite_base/dune
  src/lib/lite_base/public_key.ml
  src/lib/merkle_address/dune
  src/lib/merkle_address/merkle_address.ml
  src/lib/module_version/README-version-asserted.md
  src/lib/module_version/dune
  src/lib/non_zero_curve_point/dune
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/ppx_version/dune
  src/lib/ppx_version/serialization.ml
  src/lib/signature_lib/dune
  src/lib/signature_lib/private_key.ml
  src/lib/snarky_bn382_backend/dune
  src/lib/transaction_snark/dune
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/trust_system/banned_status.ml
  src/lib/trust_system/dune
  src/lib/unsigned_extended/dune
  src/lib/unsigned_extended/unsigned_extended.ml
  src/nonconsensus/non_zero_curve_point/dune
  src/nonconsensus/unsigned_extended/dune
Labels: ready-to-merge

#4922 Add genesis upload step to CI
  .circleci/config.yml
  .circleci/config.yml.jinja
  scripts/upload-genesis.sh
Labels: ready-to-merge

#4850 promote go log lines to logger messages
  src/lib/coda_net2/coda_net2.ml
Labels: ready-to-merge

#4652 Improve dune caching by breaking some dependencies on Coda_version
  src/app/runtime_genesis_ledger/dune
  src/lib/cache_dir/cache_dir.ml
  src/lib/cache_dir/dune
  src/lib/user_command_input/dune
Labels: ready-to-merge

#4902 Buildkite uses auto-generated type-bindings
  .buildkite/src/Command/Base.dhall
  .buildkite/src/Command/Docker/Type.dhall
  .buildkite/src/Command/Size.dhall
  .buildkite/src/Constants/ContainerImages.dhall
  .buildkite/src/External/Buildkite.dhall
  .buildkite/src/Lib/Command.dhall
  .buildkite/src/Monorepo.dhall
  .buildkite/src/Pipeline/Dsl.dhall
  .buildkite/src/Pipeline/JobSpec.dhall
  .buildkite/src/Pipeline/TriggerCommand.dhall
  .buildkite/src/Pipeline/Type.dhall
  .buildkite/src/Prepare.dhall
  .buildkite/src/gen/Jobs.dhall
  .buildkite/src/jobs/CheckDhall/Pipeline.dhall
  .buildkite/src/jobs/CheckDhall/Spec.dhall
  .buildkite/src/jobs/Sample/Pipeline.dhall
  .buildkite/src/jobs/Sample/Spec.dhall
  .buildkite/src/jobs/Sample2/Pipeline.dhall
  .buildkite/src/jobs/Sample2/Spec.dhall
  scripts/compare_pr_diff_items.py
Labels: ready-to-merge

#4899 cache opam dir outside container
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  README-dev.md
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile-toolchain
  scripts/setup-opam.sh
  scripts/test.py
Labels: ready-to-merge

#4915 Move compile-time fees to Genesis_constants
  src/app/archive/archive.ml
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/app/cli/src/tests/coda_archive_processor_test.ml
  src/lib/block_producer/block_producer.ml
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_base/coinbase.ml
  src/lib/coda_base/coinbase.mli
  src/lib/coda_base/ledger.mli
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/pending_coinbase_intf.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/sparse_ledger.mli
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/transaction_validator.ml
  src/lib/coda_base/transaction_validator.mli
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_subscriptions.ml
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/genesis_constants/dune
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/ledger_catchup/ledger_catchup.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/network_pool/test.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/staged_ledger_diff/staged_ledger_diff.ml
  src/lib/staged_ledger_diff/staged_ledger_diff.mli
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transaction_status/transaction_status.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/breadcrumb_builder.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
Labels: ready-to-merge

#4938 Inline inactivity_ms definition
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/coda_networking/coda_networking.ml
Labels: ready-to-merge

#4944 Points: Truncate the state hash in the block name
  frontend/points-hack-april20/lib.js
Labels: ready-to-merge

#4945 Skip genesis-upload if frontend/rfc
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#4941 Genesis ledger helper tweaks
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ready-to-merge

#4937 Move txn_capacity, work_delay to Constraint_constants
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transition_frontier/transition_frontier.ml
Labels: ready-to-merge

#4947 Structured event declarations
  src/lib/logging_events/dune
  src/lib/logging_events/event_declarations.ml
  src/lib/logging_events/structured_events.ml
  src/lib/logging_events/structured_events.mli
  src/lib/ppx_coda/dune
  src/lib/ppx_register_event/dune
  src/lib/ppx_register_event/register_event.ml
  src/logging_events.opam
  src/ppx_register_event.opam
Labels: ready-to-merge

#4958 Never fail if generated genesis isn't found
  scripts/upload-genesis.sh
Labels: ready-to-merge

#4956 Leaderboard: add coinbase receiver metric
  frontend/leaderboard/src/Metrics.re
  frontend/leaderboard/src/Types.re
Labels: ready-to-merge
