Repository MinaProtocol/mina, pull requests merged in 2020-06, with the labels that each got.

#4967 Runtime_config, fix typos in field names
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge

#5002 Include account layout information in genesis ledger filenames
  src/lib/coda_base/account.ml
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/sync_ledger.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ready-to-merge

#5003 Fix undo for timing changes from user commands
  src/lib/coda_base/ledger.mli
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/transaction_logic.ml
Labels: ready-to-merge

#5004 Increase size of transaction union tag
  src/lib/coda_base/transaction_union_tag.ml
Labels: ready-to-merge

#4914 Buildkite: Moves Lint jobs over
  .buildkite/Makefile
  .buildkite/hooks/post-checkout
  .buildkite/scripts/generate-jobs.sh
  .buildkite/src/Constants/ContainerImages.dhall
  .buildkite/src/Pipeline/TriggerCommand.dhall
  .buildkite/src/jobs/CheckDhall/Spec.dhall
  CODEOWNERS
  buildkite/Makefile
  buildkite/agent.nix
  buildkite/docker.nix
  buildkite/pipeline.dhall
  buildkite/scripts/generate-diff.sh
  buildkite/scripts/generate-jobs.sh
  buildkite/shell.nix
  buildkite/src/Command/Base.dhall
  buildkite/src/Command/Coda.dhall
  buildkite/src/Command/Docker/Type.dhall
  buildkite/src/Command/Size.dhall
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/External/Buildkite.dhall
  buildkite/src/External/Prelude.dhall
  buildkite/src/Jobs/CheckDhall/Pipeline.dhall
  buildkite/src/Jobs/CheckDhall/Spec.dhall
  buildkite/src/Jobs/Lint/Fast/Pipeline.dhall
  buildkite/src/Jobs/Lint/Fast/Spec.dhall
  buildkite/src/Jobs/Lint/OCaml/Pipeline.dhall
  buildkite/src/Jobs/Lint/OCaml/Spec.dhall
  buildkite/src/Jobs/Sample/Pipeline.dhall
  buildkite/src/Jobs/Sample/Spec.dhall
  buildkite/src/Jobs/Sample2/Pipeline.dhall
  buildkite/src/Jobs/Sample2/Spec.dhall
  buildkite/src/Lib/Decorate.dhall
  buildkite/src/Monorepo.dhall
  buildkite/src/Pipeline/Dsl.dhall
  buildkite/src/Pipeline/JobSpec.dhall
  buildkite/src/Pipeline/TriggerCommand.dhall
  buildkite/src/Pipeline/Type.dhall
  buildkite/src/Prepare.dhall
  buildkite/src/gen/Jobs.dhall
  scripts/check-snarky-submodule.sh
  scripts/lint_preprocessor_deps.sh
  scripts/require-ppx-version.py
  src/app/reformat/dune
Labels: ready-to-merge

#5007 Simple batch verification
  src/lib/network_pool/snark_pool.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/verifier/any.ml
  src/lib/verifier/any.mli
  src/lib/verifier/dummy.ml
  src/lib/verifier/prod.ml
  src/lib/verifier/verifier.ml
  src/lib/verifier/verifier.mli
  src/lib/verifier/verifier_intf.ml
Labels: ready-to-merge

#4959 Website: Update Team Bios
  frontend/website/public/static/img/el-bizri.jpg
  frontend/website/public/static/img/lin.jpg
  frontend/website/public/static/img/mercer.jpg
  frontend/website/public/static/img/mohan.jpg
  frontend/website/public/static/img/raines.jpg
  frontend/website/public/static/img/shahrokhi.jpg
  frontend/website/public/static/img/wilson.jpg
  frontend/website/src/components/TeamSection.re
Labels: ready-to-merge

#4524 Fix select and update range
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_intf/transition_frontier_components_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/consensus/slot.ml
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/ledger_catchup/ledger_catchup.mli
  src/lib/sync_handler/sync_handler.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_handler/validator.ml
  src/lib/transition_router/transition_router.ml
Labels: ready-to-merge

#5016 Website: Fix links to CoC
  frontend/website/pages/docs/contributing.mdx
Labels: ready-to-merge

#5030 Move misplaced version test, update another
  src/lib/ppx_version/tests/versioned_module_good.ml
  src/lib/ppx_version/tests/versioned_sig_good.mli
Labels: ready-to-merge

#5035 Use Ppxlib.Deriving.add for version, bin_io_unversioned
  scripts/compare_versioned_items.py
  src/app/archive/dune
  src/lib/auxiliary_database/dune
  src/lib/blockchain_snark/dune
  src/lib/cli_lib/dune
  src/lib/coda_net2/dune
  src/lib/daemon_rpcs/dune
  src/lib/ledger_proof/dune
  src/lib/merkle_ledger_tests/dune
  src/lib/module_version/registration.ml
  src/lib/pickles_types/dune
  src/lib/ppx_version/bin_io_unversioned.ml
  src/lib/ppx_version/dune
  src/lib/ppx_version/tests/dune
  src/lib/ppx_version/tests/good_version_syntax.ml
  src/lib/ppx_version/versioned_type.ml
  src/lib/receipt_chain_database/dune
  src/lib/sgn_type/dune
  src/lib/snark_work_lib/dune
  src/lib/sparse_ledger_lib/dune
  src/lib/staged_ledger_diff/dune
  src/lib/sync_status/dune
  src/lib/syncable_ledger/dune
  src/lib/transaction_protocol_state/dune
  src/lib/transaction_snark/dune
  src/lib/transaction_snark_work/dune
  src/lib/user_command_input/dune
  src/lib/with_hash/dune
Labels: ready-to-merge

#5021 Add +toplevel, +dynlink to client SDK build
  src/app/client_sdk/dune
  src/opam.export
Labels: ready-to-merge

#4930 3.2b docs staging branch
  frontend/website/pages/docs/getting-started.mdx
  frontend/website/pages/docs/gui-wallet.mdx
  frontend/website/pages/docs/index.mdx
  frontend/website/pages/docs/my-first-transaction.mdx
  frontend/website/pages/docs/node-operator.mdx
  frontend/website/public/static/js/leaderboard.js
  frontend/website/src/components/Leaderboard.re
Labels: ready-to-merge

#5036 Remove lite libs
  CODEOWNERS
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/dune
  src/app/cli/src/init/web_pipe.ml
  src/lib/coda_base/dune
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_graphql/dune
  src/lib/consensus/intf.ml
  src/lib/lite_base/account.ml
  src/lib/lite_base/block_time.ml
  src/lib/lite_base/blockchain_state.ml
  src/lib/lite_base/consensus_state.ml
  src/lib/lite_base/crypto_params.ml
  src/lib/lite_base/dune
  src/lib/lite_base/ledger_hash.ml
  src/lib/lite_base/ledger_hash.mli
  src/lib/lite_base/length.ml
  src/lib/lite_base/lite_chain.ml
  src/lib/lite_base/nat.ml
  src/lib/lite_base/pedersen.ml
  src/lib/lite_base/proof.ml
  src/lib/lite_base/proof.mli
  src/lib/lite_base/protocol_state.ml
  src/lib/lite_base/public_key.ml
  src/lib/lite_base/receipt.ml
  src/lib/lite_base/staged_ledger_hash.ml
  src/lib/lite_base/state_hash.ml
  src/lib/lite_base/state_hash.mli
  src/lib/lite_compat/dune
  src/lib/lite_compat/lite_compat.ml
  src/lib/lite_compat_algebra/dune
  src/lib/lite_compat_algebra/lite_compat_algebra.ml
  src/lib/lite_curve_choice/dune
  src/lib/lite_curve_choice/lite_curve_choice.ml
  src/lib/lite_lib/account.ml
  src/lib/lite_lib/dune
  src/lib/lite_lib/lite_lib.ml
  src/lib/lite_lib/merkle_path.ml
  src/lib/lite_lib/sparse_ledger.ml
  src/lib/lite_params/dune
  src/lib/lite_params/gen/dune
  src/lib/lite_params/gen/gen.ml
  src/lib/lite_params/lite_params.ml
  src/lib/lite_precomputed_values/dune
  src/lib/lite_precomputed_values/gen/dune
  src/lib/lite_precomputed_values/gen/gen.ml
Labels: ready-to-merge

#5040 MD5 digest for serialization tests
  src/lib/blake2/blake2.ml
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/proof.ml
  src/lib/coda_base/signature.ml
  src/lib/coda_base/target.ml
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/merkle_address/merkle_address.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/ppx_version/dune
  src/lib/ppx_version/serialization.ml
  src/lib/signature_lib/private_key.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/trust_system/banned_status.ml
  src/lib/unsigned_extended/unsigned_extended.ml
Labels: ready-to-merge

#5026 Adds better file selection, fixes #5001
  buildkite/src/Jobs/CheckDhall/Spec.dhall
  buildkite/src/Jobs/Lint/Fast/Spec.dhall
  buildkite/src/Jobs/Lint/OCaml/Spec.dhall
  buildkite/src/Jobs/Sample/Spec.dhall
  buildkite/src/Jobs/Sample2/Spec.dhall
  buildkite/src/Lib/SelectFiles.dhall
  buildkite/src/Monorepo.dhall
  buildkite/src/Pipeline/JobSpec.dhall
  buildkite/src/Prepare.dhall
Labels: ready-to-merge

#5049 Remove Module_version
  src/lib/blockchain_snark/dune
  src/lib/chunked_pedersen_lib/dune
  src/lib/coda_numbers/dune
  src/lib/consensus/dune
  src/lib/consensus/proof_of_stake.ml
  src/lib/currency/dune
  src/lib/merkle_ledger/dune
  src/lib/module_version/dune
  src/lib/module_version/registration.ml
  src/lib/network_peer/dune
  src/lib/one_or_two/dune
  src/lib/pickles_types/dune
  src/lib/ppx_version/versioned_type.ml
  src/lib/sgn_type/dune
  src/lib/sparse_ledger_lib/dune
  src/lib/staged_ledger/dune
  src/lib/state_or_error/dune
  src/lib/transaction_protocol_state/dune
  src/lib/transaction_snark_scan_state/dune
  src/module_version.opam
  src/nonconsensus/coda_numbers/dune
  src/nonconsensus/currency/dune
  src/nonconsensus/signature_lib/dune
Labels: ready-to-merge

#5039 Leaderboard - Bug fix and challenge header update
  frontend/leaderboard/src/Challenges.re
  frontend/leaderboard/src/Metrics.re
  frontend/leaderboard/src/Upload.re
  frontend/website/pages/docs/my-first-transaction.mdx
Labels: ready-to-merge

#5018 Fix doc string for telemetry cmd
  src/app/cli/src/init/client.ml
Labels: ready-to-merge

#4939 Move block_window_duration_ms out of Coda_compile_config
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/coda_networking.mli
  src/lib/consensus/constants.ml
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/transition_frontier/persistent_frontier/diff_buffer.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/persistent_frontier/sync.ml
  src/lib/transition_frontier/persistent_frontier/sync.mli
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_handler/processor.ml
Labels: ready-to-merge

#4929 Remove remaining uses of Test_genesis_ledger
  src/app/archive/archive_lib/test.ml
  src/app/cli/src/tests/coda_archive_node_test.ml
  src/app/cli/src/tests/coda_archive_processor_test.ml
  src/app/cli/src/tests/coda_bootstrap_test.ml
  src/app/cli/src/tests/coda_change_snark_worker_test.ml
  src/app/cli/src/tests/coda_delegation_test.ml
  src/app/cli/src/tests/coda_long_fork.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_restart_node_test.ml
  src/app/cli/src/tests/coda_shared_prefix_multiproducer_test.ml
  src/app/cli/src/tests/coda_shared_state_test.ml
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_state/genesis_protocol_state.ml
  src/lib/coda_state/genesis_protocol_state.mli
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/consensus/proof_of_stake_fuzzer.ml
  src/lib/fake_network/fake_network.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger/intf.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/ledger_catchup/ledger_catchup.mli
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/staged_ledger_hash/staged_ledger_hash.ml
  src/lib/test_genesis_ledger/test_genesis_ledger.ml
  src/lib/transaction_status/transaction_status.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/breadcrumb_builder.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
Labels: ready-to-merge

#5043 Remove pedersen
  CODEOWNERS
  src/app/cli/src/coda.ml
  src/chunked_pedersen_lib.opam
  src/lib/block_time/dune
  src/lib/blockchain_snark/blockchain_transition.ml
  src/lib/chunked_pedersen_lib/dune
  src/lib/chunked_pedersen_lib/pedersen.ml
  src/lib/chunked_pedersen_lib/pedersen.mli
  src/lib/chunked_pedersen_lib/pedersen_inputs_intf.ml
  src/lib/chunked_triples/chunk.ml
  src/lib/chunked_triples/dune
  src/lib/coda_base/data_hash.ml
  src/lib/coda_base/data_hash_intf.ml
  src/lib/coda_base/dune
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/ledger_hash.ml
  src/lib/coda_base/ledger_hash_intf.ml
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/pending_coinbase_intf.ml
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/state_body_hash.ml
  src/lib/coda_base/state_hash.ml
  src/lib/coda_base/sync_ledger.ml
  src/lib/coda_base/target.ml
  src/lib/coda_base/target.mli
  src/lib/coda_base/transition_system.ml
  src/lib/coda_state/protocol_state.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/crypto_params/chunk_table/chunk_table.ml
  src/lib/crypto_params/chunk_table/dune
  src/lib/crypto_params/crypto_params.ml
  src/lib/crypto_params/dune
  src/lib/crypto_params/gen/dune
  src/lib/crypto_params/gen/gen.ml
  src/lib/outside_hash_image/dune
  src/lib/outside_hash_image/outside_hash_image.ml
  src/lib/outside_pedersen_image/dune
  src/lib/outside_pedersen_image/gen_values/dune
  src/lib/outside_pedersen_image/gen_values/gen_values.ml
  src/lib/parallel_scan/dune
  src/lib/snark_params/dune
  src/lib/snark_params/snark_params.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/vrf_lib/integrated_test.ml
  src/nonconsensus/coda_base/dune
  src/nonconsensus/outside_hash_image/dune
  src/nonconsensus/outside_hash_image/outside_hash_image.ml
  src/nonconsensus/outside_pedersen_image/dune
  src/nonconsensus/outside_pedersen_image/gen_values/dune
  src/nonconsensus/outside_pedersen_image/gen_values/gen_values.ml
  src/outside_hash_image.opam
  src/outside_hash_image_nonconsensus.opam
  src/outside_pedersen_image_nonconsensus.opam
Labels: ready-to-merge

#4244 protocol state body in transaction snark
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/config/testnet_postake_medium_curves.mlh
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_base/ledger.mli
  src/lib/coda_base/pending_coinbase.ml
  src/lib/coda_base/pending_coinbase_intf.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/transaction_validator.ml
  src/lib/coda_base/transaction_validator.mli
  src/lib/coda_base/transaction_witness.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_state/protocol_state.ml
  src/lib/coda_state/protocol_state.mli
  src/lib/coda_transition/external_transition.ml
  src/lib/consensus/global_slot.ml
  src/lib/consensus/global_slot.mli
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/consensus/proof_of_stake_fuzzer.ml
  src/lib/snark_work_lib/work.ml
  src/lib/snark_worker/dune
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/snark_worker/prod.ml
  src/lib/snark_worker/rpcs.ml
  src/lib/snark_worker/snark_worker.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_protocol_state/dune
  src/lib/transaction_protocol_state/transaction_protocol_state.ml
  src/lib/transaction_protocol_state/transaction_protocol_state.mli
  src/lib/transaction_snark/dune
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark_scan_state/dune
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transaction_witness/dune
  src/lib/transaction_witness/transaction_witness.ml
  src/lib/transaction_witness/transaction_witness.mli
  src/lib/transition_frontier/extensions/root_history.ml
  src/lib/transition_frontier/extensions/snark_pool_refcount.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/full_frontier/full_frontier.mli
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/work_selector/inputs.ml
  src/lib/work_selector/intf.ml
  src/lib/work_selector/random.ml
  src/lib/work_selector/sequence.ml
  src/lib/work_selector/test.ml
  src/lib/work_selector/work_lib.ml
  src/lib/work_selector/work_selector.ml
  src/lib/work_selector/work_selector.mli
  src/transaction_witness.opam
Labels: ready-to-merge

#5085 Updates leaderboard link
  frontend/website/src/pages/Testnet.re
Labels: ready-to-merge

#5080 Pickles: one hot vector
  src/lib/pickles/dune
  src/lib/pickles/one_hot_vector/dune
  src/lib/pickles/one_hot_vector/one_hot_vector.ml
  src/pickles.opam
Labels: ready-to-merge

#5077 Pickles: composition types
  src/lib/pickles/composition_types/bulletproof_challenge.ml
  src/lib/pickles/composition_types/composition_types.ml
  src/lib/pickles/composition_types/dune
  src/lib/pickles/composition_types/spec.ml
Labels: ready-to-merge

#5082 Pickles: "Pseudo"
  src/lib/pickles/pseudo/dune
  src/lib/pickles/pseudo/pseudo.ml
Labels: ready-to-merge

#5078 Pickles: limb vector
  src/lib/pickles/limb_vector/challenge.ml
  src/lib/pickles/limb_vector/constant.ml
  src/lib/pickles/limb_vector/digest.ml
  src/lib/pickles/limb_vector/dune
  src/lib/pickles/limb_vector/limb_vector.ml
  src/lib/pickles/limb_vector/make.ml
Labels: ready-to-merge

#5083 Pickles: endomorphism optimization
  src/lib/pickles/common.ml
  src/lib/pickles/dune
  src/lib/pickles/endo.ml
  src/lib/pickles/import.ml
  src/lib/pickles/intf.ml
  src/lib/pickles/marlin_checks/domain.ml
  src/lib/pickles/marlin_checks/dune
  src/lib/pickles/marlin_checks/marlin_checks.ml
  src/lib/pickles/scalar_challenge.ml
  src/lib/pickles/timer.ml
  src/lib/pickles/timer.mli
  src/lib/pickles_types/abc.ml
Labels: ready-to-merge

#5086 Pickles: Impls
  src/lib/pickles/common.ml
  src/lib/pickles/impls.ml
  src/lib/pickles/type.ml
  src/lib/pickles/util.ml
Labels: ready-to-merge

#5088 Pickles: verification key
  src/lib/pickles/commitment_lengths.ml
  src/lib/pickles/common.ml
  src/lib/pickles/domains.ml
  src/lib/pickles/verification_key.ml
Labels: ready-to-merge

#5089 Pickles: caching
  src/lib/pickles/cache.ml
  src/lib/pickles/cache_handle.ml
  src/lib/pickles/dirty.ml
Labels: ready-to-merge

#5092 Simplify Pcs_batch.num_bits
  src/lib/pickles_types/pcs_batch.ml
Labels: ready-to-merge

#5104 Implement iteri for masks
  src/lib/merkle_mask/masking_merkle_tree.ml
Labels: ready-to-merge

#5081 Pickles: marlin checks
  src/lib/pickles/marlin_checks/marlin_checks.ml
Labels: ready-to-merge

#5093 Add ready-to-merge-into-develop to mergify
  .mergify.yml
  .mergify.yml.jinja
Labels: ready-to-merge

#5090 Pickles: sponge stuff
  src/lib/pickles/fp_sponge.ml
  src/lib/pickles/fq_sponge.ml
  src/lib/pickles/make_sponge.ml
  src/lib/pickles/sponge_inputs.ml
Labels: ready-to-merge

#5111 [Website FAQ] Added Block Producer FAQ
  frontend/website/pages/docs/faq.mdx
  frontend/website/public/static/img/faq/coda-singleton-forks.png
Labels: ready-to-merge

#5116 Pickles: random oracle convenience
  src/lib/pickles/ro.ml
Labels: ready-to-merge-into-develop

#5119 Pickles: pairing acc
  src/lib/pickles/pairing_acc.ml
Labels: ready-to-merge-into-develop

#5121 Pickles: dlog main functions
  src/lib/pickles/common.ml
  src/lib/pickles/dlog_main.ml
  src/lib/pickles/dune
Labels: ready-to-merge-into-develop

#5122 Pickles: pairing main functions
  src/lib/pickles/pairing_main.ml
Labels: ready-to-merge-into-develop

#5110 error message for duplicate account
  src/lib/coda_base/ledger.ml
Labels: ready-to-merge

#5046 Website/Leaderboard - Implemented radio buttons for filtering
  frontend/website/src/Theme.re
  frontend/website/src/components/ToggleButton.re
  frontend/website/src/pages/LeaderboardPage.re
Labels: ready-to-merge

#5067 Buildkite client sdk
  buildkite/scripts/cache-through.sh
  buildkite/scripts/opam-env.sh
  buildkite/src/Command/Base.dhall
  buildkite/src/Command/Coda.dhall
  buildkite/src/Command/OpamInit.dhall
  buildkite/src/Constants/ContainerEnvVars.dhall
  buildkite/src/Jobs/CheckDhall/Pipeline.dhall
  buildkite/src/Jobs/ClientSdk/Pipeline.dhall
  buildkite/src/Jobs/ClientSdk/Spec.dhall
  buildkite/src/Jobs/Lint/Fast/Pipeline.dhall
  buildkite/src/Jobs/Lint/OCaml/Pipeline.dhall
  buildkite/src/Jobs/Sample/Pipeline.dhall
  buildkite/src/Jobs/Sample2/Pipeline.dhall
  buildkite/src/Lib/Cmds.dhall
  buildkite/src/Lib/Decorate.dhall
  buildkite/src/Monorepo.dhall
  buildkite/src/Pipeline/TriggerCommand.dhall
  buildkite/src/Prepare.dhall
Labels: ready-to-merge

#5123 Pickles: plumbing
  src/lib/pickles/common.ml
  src/lib/pickles/dlog_proof.ml
  src/lib/pickles/inductive_rule.ml
  src/lib/pickles/per_proof_witness.ml
  src/lib/pickles/tag.ml
  src/lib/pickles/types_map.ml
  src/lib/pickles/unfinalized.ml
Labels: ready-to-merge-into-develop

#5032 Carry fee excesses for 2 tokens in each transition
  src/lib/coda_base/coinbase.ml
  src/lib/coda_base/coinbase.mli
  src/lib/coda_base/fee_excess.ml
  src/lib/coda_base/fee_transfer.ml
  src/lib/coda_base/fee_transfer.mli
  src/lib/coda_base/import.ml
  src/lib/coda_base/token_id.ml
  src/lib/coda_base/token_id.mli
  src/lib/coda_base/transaction.ml
  src/lib/coda_base/transaction_union.ml
  src/lib/coda_base/transaction_union_payload.ml
  src/lib/coda_base/user_command.ml
  src/lib/coda_base/user_command_intf.ml
  src/lib/coda_base/user_command_payload.ml
  src/lib/coda_base/user_command_payload.mli
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/currency/currency.ml
  src/lib/currency/signed_poly.ml
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/snark_worker/prod.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/nonconsensus/coda_base/fee_excess.ml
Labels: ready-to-merge-into-develop

#5126 Use Logproc_lib parsing for ppx_register_event and Logger.check_invariants
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/logger/impl.ml
  src/lib/ppx_register_event/dune
  src/lib/ppx_register_event/register_event.ml
Labels: ready-to-merge-into-develop

#5138 Deriving lens in Parallel_scan
  src/lib/parallel_scan/dune
  src/lib/parallel_scan/parallel_scan.ml
Labels: ready-to-merge-into-develop

#5129 Pickles: step main
  src/lib/pickles/requests.ml
  src/lib/pickles/step_main.ml
  src/lib/pickles/types_map.ml
Labels: ready-to-merge-into-develop

#5133 Pickles: wrap prover
  src/lib/pickles/common.ml
  src/lib/pickles/wrap.ml
Labels: ready-to-merge

#5128 Pickles: wrap main
  src/lib/pickles/full_signature.ml
  src/lib/pickles/requests.ml
  src/lib/pickles/wrap_main.ml
Labels: ready-to-merge-into-develop

#5130 Pickles: verify
  src/lib/pickles/common.ml
  src/lib/pickles/dummy.ml
  src/lib/pickles/proof.ml
  src/lib/pickles/reduced_me_only.ml
  src/lib/pickles/verify.ml
Labels: ready-to-merge-into-develop

#5146 Website: Update Testnet Challnges Link for 3.2b
  frontend/website/src/pages/Testnet.re
Labels: ready-to-merge

#5131 Pickles: step branch data
  src/lib/pickles/fix_domains.ml
  src/lib/pickles/step_branch_data.ml
  src/lib/pickles/wrap_domains.ml
Labels: ready-to-merge-into-develop

#5147 Add structured logs
  src/lib/block_producer/block_producer.ml
  src/lib/block_producer/dune
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/dune
  src/lib/child_processes/child_processes.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/dune
  src/lib/coda_net2/coda_net2.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/dune
  src/lib/logger/dune
  src/lib/logger/impl.ml
  src/lib/logger/impl.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/snark_worker/dune
  src/lib/snark_worker/functor.ml
  src/lib/syncable_ledger/dune
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/trust_system/dune
  src/lib/trust_system/peer_trust.ml
Labels: ready-to-merge-into-develop

#5132 Pickles: step prover
  src/lib/pickles/common.ml
  src/lib/pickles/step.ml
  src/lib/pickles/wrap.ml
Labels: ready-to-merge-into-develop

#5076 Use UInt64 for Token_id
  src/lib/coda_base/account.ml
  src/lib/coda_base/account_id.ml
  src/lib/coda_base/account_id.mli
  src/lib/coda_base/fee_excess.ml
  src/lib/coda_base/import.ml
  src/lib/coda_base/payment_payload.ml
  src/lib/coda_base/payment_payload.mli
  src/lib/coda_base/receipt.ml
  src/lib/coda_base/token_id.ml
  src/lib/coda_base/token_id.mli
  src/lib/coda_base/transaction_union_payload.ml
  src/lib/coda_base/user_command_payload.ml
  src/lib/coda_numbers/nat.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/unsigned_extended/intf.ml
  src/lib/unsigned_extended/unsigned_extended.ml
Labels: ready-to-merge-into-develop

#5134 Pickles: top level module
  src/lib/key_cache/key_cache.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/zexe_backend/dlog_based.ml
  src/lib/zexe_backend/pairing_based.ml
Labels: ready-to-merge-into-develop

#4699 Associate tokens with fee transfers
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/archive/create_schema.sql
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/auxiliary_database/external_transition_database.ml
  src/lib/auxiliary_database/filtered_external_transition.ml
  src/lib/coda_base/coinbase_fee_transfer.ml
  src/lib/coda_base/fee_transfer.ml
  src/lib/coda_base/fee_transfer.mli
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/coda_base/transaction_union.ml
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge-into-develop

#5071 Remove logic for paying account creation fees in non-default tokens
  src/lib/coda_base/sparse_ledger.ml
  src/lib/coda_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge-into-develop

#5150 Move docker jobs out of build-artifacts CI jobs
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge-into-develop

#4948 don't use Time.to_string without an explicit, fixed timezone!
  src/lib/daemon_rpcs/types.ml
  src/lib/genesis_constants/genesis_constants.ml
Labels: ready-to-merge-into-develop

#5164 Ppxlib.Deriving for register_event
  src/lib/ppx_register_event/dune
  src/lib/ppx_register_event/register_event.ml
Labels: ready-to-merge-into-develop

#5145 Leaderboard frontend: set up search bar
  frontend/website/src/components/Summary.re
  frontend/website/src/pages/LeaderboardPage.re
Labels: ready-to-merge

#5033 Leaderboard: Setup Cron
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#5171 Validate protocol versions in catchup
  src/lib/ledger_catchup/ledger_catchup.ml
Labels: ready-to-merge-into-develop

#5181 Fix mac builds on CI
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge-into-develop

#5158 Expose list of registered structured events
  src/lib/ppx_register_event/register_event.ml
  src/lib/structured_log_events/structured_log_events.ml
  src/lib/structured_log_events/structured_log_events.mli
Labels: ready-to-merge-into-develop

#5177 Use requests in transaction snark
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge-into-develop

#5167 Add missing metadata to log message
  src/lib/coda_lib/coda_lib.ml
Labels: ready-to-merge-into-develop

#5175 Leaderboard: fix tablet styles
  frontend/website/src/components/Summary.re
  frontend/website/src/pages/LeaderboardPage.re
Labels: ready-to-merge

#5183 Move proof_level into precomputed_values
  src/app/archive/archive_lib/test.ml
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/config.ml
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/test.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_status/transaction_status.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
Labels: ready-to-merge-into-develop

#5178 Separate init_stack from Pending_coinbase_stack_state
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/snark_worker/prod.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transaction_witness/transaction_witness.ml
  src/lib/transaction_witness/transaction_witness.mli
Labels: ready-to-merge-into-develop

#5185 Make proof-level configurable from the config file
  src/app/cli/src/coda.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5182 Website: Add grants link to footer
  frontend/website/src/components/Page.re
Labels: ready-to-merge

#5195 fix link in snark workers docs
  frontend/website/pages/docs/architecture/snark-workers.mdx
Labels: ready-to-merge

#5191 buildkite: flatten dhall filesystem by one directory
  buildkite/Makefile
  buildkite/src/Jobs/CheckDhall.dhall
  buildkite/src/Jobs/CheckDhall/Pipeline.dhall
  buildkite/src/Jobs/CheckDhall/Spec.dhall
  buildkite/src/Jobs/ClientSdk.dhall
  buildkite/src/Jobs/ClientSdk/Pipeline.dhall
  buildkite/src/Jobs/ClientSdk/Spec.dhall
  buildkite/src/Jobs/Lint/Fast.dhall
  buildkite/src/Jobs/Lint/Fast/Pipeline.dhall
  buildkite/src/Jobs/Lint/Fast/Spec.dhall
  buildkite/src/Jobs/Lint/OCaml.dhall
  buildkite/src/Jobs/Lint/OCaml/Pipeline.dhall
  buildkite/src/Jobs/Lint/OCaml/Spec.dhall
  buildkite/src/Jobs/Sample.dhall
  buildkite/src/Jobs/Sample/Pipeline.dhall
  buildkite/src/Jobs/Sample/Spec.dhall
  buildkite/src/Jobs/Sample2.dhall
  buildkite/src/Jobs/Sample2/Pipeline.dhall
  buildkite/src/Jobs/Sample2/Spec.dhall
  buildkite/src/Monorepo.dhall
Labels: ready-to-merge

#5198 Docker image for puppeteered daemons
  dockerfiles/Dockerfile-coda-daemon-puppeteered
  dockerfiles/coda_daemon_puppeteer.py
Labels: ready-to-merge

#5203 to_yojson per-field annotations for RPC type
  src/lib/coda_networking/coda_networking.ml
Labels: ready-to-merge-into-develop

#5188 Allow setting constraint constants from the config file
  src/app/cli/src/coda.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5211 %%versioned: for sig in scan state
  .mergify.yml
  scripts/test.py
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
Labels: ready-to-merge-into-develop

#5161 Leaderboard Filter Dropdown
  frontend/website/src/Theme.re
  frontend/website/src/components/Dropdown.re
  frontend/website/src/components/Summary.re
  frontend/website/src/components/ToggleButton.re
  frontend/website/src/pages/LeaderboardPage.re
Labels: ready-to-merge

#5212 Staged ledger use %%versioned in sig
  src/lib/staged_ledger/staged_ledger.mli
Labels: ready-to-merge-into-develop

#5109 Add basic rosetta dockerfile
  .dockerignore
  Makefile
  dockerfiles/Dockerfile-rosetta
  src/app/rosetta/dune
  src/app/rosetta/dune-project
  src/app/rosetta/rosetta.ml
  src/app/rosetta/rosetta.opam
  src/app/rosetta/start.sh
Labels: ready-to-merge

#5216 Readable event ids
  src/lib/ppx_register_event/dune
  src/lib/ppx_register_event/register_event.ml
Labels: ready-to-merge-into-develop

#5223 Add `coda.exe internal dump-structured-events` command
  src/app/cli/src/coda.ml
  src/app/cli/src/dune
  src/lib/ppx_register_event/register_event.ml
Labels: ready-to-merge-into-develop

#5209 Use snark statements directly in the transaction snark
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Labels: ready-to-merge-into-develop

#5224 Update benchmark build
  Makefile
  src/app/benchmarks/main.ml
Labels: ready-to-merge-into-develop

#4911 [RFC] Automated Validation
  rfcs/0032-automated-validation.md
  rfcs/res/automated_validation_init_architecture.conv.tex
  rfcs/res/automated_validation_init_architecture.conv.tex.png
  rfcs/res/automated_validation_runtime_architecture.conv.tex
  rfcs/res/automated_validation_runtime_architecture.conv.tex.png
Labels: ready-to-merge

#5196 port compare-test-signatures to buildkite
  buildkite/scripts/build-client-sdk.sh
  buildkite/src/Command/OpamInit.dhall
  buildkite/src/Jobs/ClientSdk.dhall
  buildkite/src/Jobs/CompareSignatures.dhall
Labels: ready-to-merge

#3980 [RFC] Reduce Scan State Memory Usage
  rfcs/0033-reduce-scan-state-memory-usage.md
  rfcs/res/compute_scan_state_memory_usage_graphs.sh
  rfcs/res/scan_state_memory_usage.csv
  rfcs/res/scan_state_memory_usage.png
  rfcs/res/scan_state_memory_usage.py
  rfcs/res/scan_state_memory_usage_depth_6.csv
  rfcs/res/scan_state_memory_usage_depth_6.png
  rfcs/res/scan_state_memory_usage_depth_9.csv
  rfcs/res/scan_state_memory_usage_depth_9.png
Labels: ready-to-merge

#5009 Feature/ci buildkite unit tests
  buildkite/scripts/cache-through.sh
  buildkite/src/Command/Libp2pHelperBuild.dhall
  buildkite/src/Jobs/Unit.dhall
Labels: Taskforce Iterate (C)

#5222 Stackdriver query engine for integration tests
  src/integration_test_lib.opam
  src/lib/integration_test_lib/dune
  src/lib/integration_test_lib/stack_driver_log_engine.ml
  src/lib/integration_test_lib/test_intf.ml
Labels: ready-to-merge

#5137 Automated Validation Service
  .gitignore
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/Jobs/Lint/ValidationService.dhall
  buildkite/src/Jobs/Test/ValidationService.dhall
  buildkite/src/Lib/Cmds.dhall
  buildkite/src/Projects/ValidationService.dhall
  src/app/validation/.credo.exs
  src/app/validation/.formatter.exs
  src/app/validation/README.md
  src/app/validation/config/config.exs
  src/app/validation/lib/architecture/alert_server.ex
  src/app/validation/lib/architecture/junction.ex
  src/app/validation/lib/architecture/log_filter.ex
  src/app/validation/lib/architecture/log_provider.ex
  src/app/validation/lib/architecture/resource.ex
  src/app/validation/lib/architecture/resource_set.ex
  src/app/validation/lib/architecture/statistic.ex
  src/app/validation/lib/architecture/timer.ex
  src/app/validation/lib/architecture/validation.ex
  src/app/validation/lib/class.ex
  src/app/validation/lib/cloud/google.ex
  src/app/validation/lib/cloud/google/log_pipeline.ex
  src/app/validation/lib/cloud/google/log_sink.ex
  src/app/validation/lib/cloud/google/subscription.ex
  src/app/validation/lib/cloud/google/topic.ex
  src/app/validation/lib/coda.ex
  src/app/validation/lib/coda/application.ex
  src/app/validation/lib/coda/providers/block_produced.ex
  src/app/validation/lib/coda/providers/transaction_pool_diff_received.ex
  src/app/validation/lib/coda/resource_classifier.ex
  src/app/validation/lib/coda/resources/block_producer.ex
  src/app/validation/lib/coda/resources/coda_node.ex
  src/app/validation/lib/coda/statistics/block_production_rate.ex
  src/app/validation/lib/coda/validations/block_production_rate.ex
  src/app/validation/lib/pretty_console_log.ex
  src/app/validation/lib/util.ex
  src/app/validation/mix.exs
  src/app/validation/mix.lock
  src/app/validation/test/architecture_tests/log_filter_test.exs
  src/app/validation/test/architecture_tests/resource_set_test.exs
  src/app/validation/test/architecture_tests/timer_test.exs
  src/app/validation/test/class_test.exs
  src/app/validation/test/test_helper.exs
Labels: ready-to-merge

#5243 Fix error where genesis ledger 'named' file already exists
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/runtime_config/runtime_config.ml
Labels: ready-to-merge-into-develop

#5245 [Tokens] Carry the next available token in the ledger
  src/lib/coda_base/ledger.ml
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_inputs_intf.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/intf.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_ledger/util.ml
  src/lib/merkle_ledger_tests/test_stubs.ml
  src/lib/merkle_mask/inputs_intf.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
Labels: ready-to-merge-into-develop

#5232 Leaderboard: Update Data Structures
  frontend/website/src/Theme.re
  frontend/website/src/bindings/Sheets.re
  frontend/website/src/components/Leaderboard.re
  frontend/website/src/components/Summary.re
  frontend/website/src/components/ToggleButton.re
  frontend/website/src/pages/LeaderboardPage.re
Labels: ready-to-merge
