Repository MinaProtocol/mina, pull requests merged in 2020-03, with the labels that each got.

#4467 GraphQL/CLI: Indicate which keys failed to stake in setStaking
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_graphql/coda_graphql.ml
Labels: ready-to-merge

#4482 Added git-lfs instructions to README.md
  frontend/website/README.md
Labels: ready-to-merge

#4495 Add process field to metadata for memstats
  src/app/cli/src/coda.ml
  src/lib/memory_stats/memory_stats.ml
  src/lib/prover/prover.ml
  src/lib/verifier/prod.ml
Labels: ready-to-merge

#4496 Peer, use %%versioned
  src/lib/network_peer/peer.ml
Labels: ready-to-merge

#4461 Telemetry, Part I
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/dune
  src/config/testnet_postake_medium_curves.mlh
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/coda_networking.mli
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/daemon_rpcs/dune
  src/lib/fake_network/fake_network.ml
  src/lib/telemetry/dune
  src/lib/telemetry/telemetry.ml
  src/telemetry.opam
Labels: ready-to-merge

#4508 Fix broken glossary link in docs
  frontend/website/pages/docs/my-first-transaction.mdx
Labels: ready-to-merge

#4463 staged-ledger diff-creation logs
  src/app/cli/src/coda.ml
  src/lib/block_producer/block_producer.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/config.ml
  src/lib/staged_ledger/diff_creation_log.ml
  src/lib/staged_ledger/dune
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
Labels: ready-to-merge

#4514 Private_key.gen for sample keypairs
  src/lib/coda_base/gen/gen.ml
Labels: ready-to-merge

#4499 Remove unused RPC serialization tests
  src/lib/coda_networking/rpc_tests.ml
Labels: ready-to-merge

#4494 Ledger_proof, use %%versioned ppx
  src/lib/coda_base/proof.ml
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/ledger_proof/ledger_proof.mli
  src/lib/ledger_proof/ledger_proof_intf.ml
Labels: ready-to-merge

#4513 decrease dht poll time, log how long validation took
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ready-to-merge

#4497 Add wiki link to website
  frontend/website/src/components/Page.re
Labels: ready-to-merge

#4532 Update CODEOWNERS
  CODEOWNERS
Labels: ready-to-merge

#4518 add snark worker docs
  frontend/website/pages/docs/architecture/snark-workers.mdx
  frontend/website/pages/docs/faq.mdx
  frontend/website/pages/docs/gui-wallet.mdx
  frontend/website/public/static/img/snark-diagram.png
  frontend/website/src/components/DocsComponents.re
  frontend/website/src/components/DocsSideNav.re
  frontend/website/src/pages/Docs.re
  frontend/website/src/pages/MarkdownPage.re
Labels: ready-to-merge

#4511 Add block-producer-password to CLI and daemon.json
  docs/daemon.md
  src/app/cli/src/coda.ml
Labels: ready-to-merge

#4118 [RFC] Update glossary RFC
  rfcs/0023-glossary-terms.md
Labels: RFC, ready-to-merge

#4531 Skip CI for RFCs
  .circleci/config.yml
  .circleci/config.yml.jinja
  scripts/skip_if_only_frontend_or_rfcs.sh
Labels: ready-to-merge

#4515 fixes #3457
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/network_pool/intf.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/network_pool/test.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_status/transaction_status.ml
Labels: ready-to-merge

#4548 Lint binable functor usage
  src/lib/ppx_coda/lint_version_syntax.ml
  src/lib/work_selector/inputs.ml
Labels: ready-to-merge

#4549 SDK: Allow use of numbers and fix stake delegation
  frontend/client_sdk/.gitignore
  frontend/client_sdk/README.md
  frontend/client_sdk/package.json
  frontend/client_sdk/src/CodaSDK.d.ts
  frontend/client_sdk/src/CodaSDK.re
  frontend/client_sdk/src/TSTypes.d.ts
  frontend/client_sdk/src/TSTypes.ts
  frontend/client_sdk/test/Test.ts
Labels: ready-to-merge

#4347 Add fork ID fields to External_transition
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/dune
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/dune
  src/app/cli/src/tests/full_test.ml
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_frontend.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/fake_hash.mlh
  src/config/fork_id/current.mlh
  src/config/fuzz_medium.mlh
  src/config/fuzz_small.mlh
  src/config/nonconsensus_medium_curves.mlh
  src/config/print_versioned_types.mlh
  src/config/test_postake.mlh
  src/config/test_postake_bootstrap.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_delegation.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_full_epoch.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_split_snarkless.mlh
  src/config/test_postake_three_producers.mlh
  src/config/test_postake_txns.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_producers.mlh
  src/config/testnet_postake_many_producers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/fork_id.opam
  src/lib/best_tip_prover/best_tip_prover.ml
  src/lib/block_producer/block_producer.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/config.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_transition/dune
  src/lib/coda_transition/external_transition.ml
  src/lib/coda_transition/external_transition_intf.ml
  src/lib/command_line_tests/command_line_tests.ml
  src/lib/fork_id/dune
  src/lib/fork_id/fork_id.ml
  src/lib/fork_id/fork_id.mli
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_router/initial_validator.ml
  src/lib/trust_system/trust_system.ml
Labels: ready-to-merge

#4458 Use new currency encoding in configs and genesis ledger
  dockerfiles/Dockerfile-coda-demo
  genesis_ledgers/phase_three/annotated_ledger.json
  genesis_ledgers/phase_three/genesis_ledger.json
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/config/account_creation_fee/high.mlh
  src/config/account_creation_fee/standard.mlh
  src/config/coinbase/standard.mlh
  src/lib/coda_base/ledger.ml
  src/lib/coda_base/user_command.ml
  src/lib/coda_compile_config/coda_compile_config.ml
  src/lib/consensus/constants.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/currency/currency.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/quickcheck_lib/quickcheck_lib.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ready-to-merge

#4560 Docs: add syntax highlighting
  frontend/website/next.config.js
  frontend/website/package.json
  frontend/website/public/static/css/a11y-light.css
  frontend/website/src/components/DocsComponents.re
  frontend/website/src/pages/Docs.re
  frontend/website/yarn.lock
Labels: ready-to-merge

#4568 Website: Genesis links open new tab
  frontend/website/src/components/StepButton.re
  frontend/website/src/pages/Genesis.re
Labels: ready-to-merge

#4567 Pickles type lib, cleanup versioning
  src/lib/pickles_types/abc.ml
  src/lib/pickles_types/dlog_marlin_types.ml
  src/lib/pickles_types/dune
  src/lib/pickles_types/matrix_evals.ml
  src/lib/pickles_types/pairing_marlin_types.ml
Labels: ready-to-merge

#4521 Website/genesis profiles
  frontend/website/public/static/img/Icon.Discord.svg
  frontend/website/public/static/img/Icon.Git.svg
  frontend/website/public/static/img/Icon.Twitter.svg
  frontend/website/public/static/img/Location.svg
  frontend/website/public/static/img/gareth.png
  frontend/website/src/ContentType.re
  frontend/website/src/Theme.re
  frontend/website/src/components/MemberProfile.re
  frontend/website/src/pages/Blog.re
  frontend/website/src/pages/BlogPost.re
  frontend/website/src/pages/Genesis.re
Labels: ready-to-merge

#4569 Double libp2p input buffer size
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ready-to-merge

#4544 CLI: Add `accounts export`, remove deprecated import commands
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/cli_lib/arg_type.ml
Labels: ready-to-merge

#4575 Print hashes in check_serialization when they differ
  src/lib/module_version/serialization.ml
Labels: ready-to-merge

#4578 Fix typo in archive test
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#4581 Set pipefail for CI commands using tee
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ready-to-merge

#4584 Add a fork_id to the archive test compile-time config
  src/config/test_archive_processor.mlh
Labels: ready-to-merge

#4579 Don't call cachix for make build if we won't be using it
  Makefile
Labels: ready-to-merge

#4588 Resurrect define_from_scope ppx
  src/lib/ppx_coda/define_from_scope.ml
  src/lib/ppx_coda/tests/Makefile
  src/lib/ppx_coda/tests/define_from_scope_good.ml
  src/lib/ppx_coda/tests/dune
Labels: ready-to-merge

#4590 Add Of_binableN functors to linter
  src/lib/ppx_coda/lint_version_syntax.ml
  src/lib/ppx_coda/versioned_type.ml
Labels: ready-to-merge

#4589 Fix the onboarding heading buttons- Chris approved
  frontend/wallet/src/render/components/HelpButton.re
Labels: ready-to-merge

#4512 Wallet: Managed Daemon Installation
  .circleci/config.yml
  .circleci/config.yml.jinja
  Makefile
  frontend/wallet/fastlane/Appfile
  frontend/wallet/fastlane/Fastfile
  frontend/wallet/package.json
  frontend/wallet/src/common/Bindings.re
  frontend/wallet/src/render/DownloadLogic.re
  frontend/wallet/src/render/Preload.re
  frontend/wallet/src/render/components/Downloader.re
  frontend/wallet/src/render/components/LoaderRing.re
  frontend/wallet/src/render/components/Modal.re
  frontend/wallet/src/render/components/RequestCodaModal.re
  frontend/wallet/src/render/views/onboarding/CustomSetupA.re
  frontend/wallet/src/render/views/onboarding/CustomSetupC.re
  frontend/wallet/src/render/views/onboarding/InstallCodaStep.re
  frontend/wallet/src/render/views/onboarding/Onboarding.re
  frontend/wallet/src/render/views/onboarding/OnboardingHeader.re
  frontend/wallet/src/render/views/onboarding/PortForwardErrorStep.re
  frontend/wallet/src/render/views/onboarding/RunNodeStep.re
  frontend/wallet/src/render/views/onboarding/SetupNodeStep.re
  frontend/wallet/src/render/views/onboarding/StakeCodaStep.re
  frontend/wallet/yarn.lock
  scripts/macos-portable.sh
Labels: ready-to-merge

#4603 Add peer id for node to telemetry I
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_networking/coda_networking.ml
  src/lib/coda_networking/coda_networking.mli
Labels: ready-to-merge

#4585 Wallet/decimals: Implement currency formatter to address decimals in wallet
  frontend/wallet/__tests__/wallet_test.re
  frontend/wallet/bsconfig.json
  frontend/wallet/package.json
  frontend/wallet/src/common/CurrencyFormatter.re
  frontend/wallet/src/render/Apollo.re
  frontend/wallet/src/render/components/AccountDropdownItem.re
  frontend/wallet/src/render/components/TextField.re
  frontend/wallet/src/render/views/footer/SendModal.re
  frontend/wallet/src/render/views/settings/DelegationSettings.re
  frontend/wallet/src/render/views/settings/SettingsPage.re
  frontend/wallet/src/render/views/sidebar/AccountItem.re
  frontend/wallet/src/render/views/transactions/TransactionCell.re
Labels: ready-to-merge

#4553 Transaction pool update by multiple clients
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/tests/coda_receipt_chain_test.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/cli_lib/default.ml
  src/lib/cli_lib/flag.ml
  src/lib/coda_base/user_command.mli
  src/lib/coda_base/user_command_payload.mli
  src/lib/coda_commands/coda_commands.ml
  src/lib/coda_commands/dune
  src/lib/coda_graphql/coda_graphql.ml
  src/lib/coda_graphql/dune
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/coda_lib.mli
  src/lib/coda_lib/dune
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/daemon_rpcs/dune
  src/lib/signature_lib/keypair.ml
  src/lib/signature_lib/keypair.mli
  src/lib/test_genesis_ledger/test_ledger.ml
  src/lib/user_command_input/dune
  src/lib/user_command_input/user_command_input.ml
  src/lib/user_command_input/user_command_input.mli
  src/user_command_input.opam
Labels: ready-to-merge, required-for-release

#4607 Updates to Contentful and Genesis Profile to include optional Github and image resizing
  frontend/website/src/ContentType.re
  frontend/website/src/components/MemberProfile.re
Labels: ready-to-merge

#4574 Linter requires %%versioned extension for versioned types
  src/lib/coda_lib/coda_lib.ml
  src/lib/logger/dune
  src/lib/logger/impl.ml
  src/lib/one_or_two/one_or_two.ml
  src/lib/parallel_scan/dune
  src/lib/ppx_coda/lint_version_syntax.ml
  src/lib/secrets/dune
  src/lib/transaction_snark_scan_state/dune
  src/lib/transaction_snark_work/dune
  src/lib/transaction_snark_work/transaction_snark_work.ml
  src/lib/transaction_status/transaction_status.ml
  src/lib/trust_system/banned_status.ml
  src/lib/unsigned_extended/dune
  src/nonconsensus/unsigned_extended/dune
Labels: ready-to-merge

#4517 Add explicit seed flag and handle libp2p connection error
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_process.ml
  src/app/cli/src/tests/coda_processes.ml
  src/app/cli/src/tests/coda_transitive_peers_test.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/coda_intf/transition_frontier_components_intf.ml
  src/lib/coda_lib/coda_lib.ml
  src/lib/coda_lib/config.ml
  src/lib/command_line_tests/command_line_tests.ml
  src/lib/transition_router/transition_router.ml
Labels: ready-to-merge, required-for-release
