Repository MinaProtocol/mina, pull requests merged in 2021-04, with the labels that each got.

#8444 Receiver balances in internal cmds, not balance ids
  src/app/archive/archive_lib/processor.ml
  src/app/extract_blocks/extract_blocks.ml
  src/app/extract_blocks/sql.ml
Labels: ci-build-me

#8362 specify container id in intg test framework
  src/app/test_executive/archive_node_test.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/test_config.ml
Labels: ci-build-me, ready-to-merge, waiting-for-gating

#8453 next staking ledger fix
  src/lib/mina_lib/mina_lib.ml
Labels: ci-build-me

#7807 Use structured logs, don't manually parse metadata
  src/lib/block_producer/block_producer.ml
  src/lib/integration_test_lib/event_type.ml
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/protocol_version/dune
  src/lib/protocol_version/protocol_version.ml
  src/lib/protocol_version/protocol_version.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/frontier_base/diff.ml
  src/lib/transition_frontier/frontier_base/diff.mli
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
Labels: ci-build-me, ready-to-merge

#8200 Improved error messages for rejection in sendRosettaTransaction
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/network_pool/intf.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#8390 Client SDK: Added wrapper for signedRosettaTransactionToSignedCommand
  frontend/client_sdk/package.json
  frontend/client_sdk/src/CodaSDK.d.ts
  frontend/client_sdk/src/CodaSDK.re
  frontend/client_sdk/test/Test.ts
Labels: ci-build-me, waiting-for-gating

#8446 Remove dead code in extract blocks
  src/app/extract_blocks/block.ml
  src/app/extract_blocks/extract_blocks.ml
  src/app/extract_blocks/sql.ml
Labels: ci-build-me

#8391 improve intg test readme
  src/app/test_executive/README.md
Labels: ci-build-me, ready-to-merge

#8532 Only accept valid UInt32/64 values in GraphQL
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#8509 Swap balances for combined fee transfers
  src/app/archive/archive_lib/processor.ml
Labels: ci-build-me, waiting-for-gating

#8550 include updated block production keys in node status
  src/lib/mina_lib/mina_lib.ml
Labels: ci-build-me

#8454 Use the same code and types for all proof_levels
  src/lib/ledger_proof/dune
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/ledger_proof/ledger_proof.mli
  src/lib/network_pool/mocks.ml
  src/lib/snark_worker/debug.ml
  src/lib/snark_worker/dune
  src/lib/snark_worker/snark_worker.ml
  src/lib/verifier/dummy.ml
  src/lib/verifier/dummy.mli
  src/lib/verifier/dune
  src/lib/verifier/verifier.ml
  src/lib/verifier/verifier.mli
Labels: ci-build-me

#8480 Mask `last_filled`, use Addr.compare
  src/lib/merkle_mask/masking_merkle_tree.ml
Labels: ci-build-me

#8475 Docs for ledgers
  src/lib/merkle_ledger/README.md
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
Labels: ci-build-me

#8472 Docs, minor changes to Base58_check
  src/lib/base58_check/README.md
  src/lib/base58_check/base58_check.ml
  src/lib/base58_check/base58_check.mli
  src/lib/base58_check/version_bytes.ml
  src/lib/secrets/hardware_wallets.ml
Labels: ci-build-me

#8457 App to poke and patch archive database
  CODEOWNERS
  Makefile
  src/app/patch_archive_test/dune
  src/app/patch_archive_test/patch_archive_test.ml
  src/patch_archive_test.opam
Labels: ci-build-me

#8191 include the height of a block in the precomputed block filename
  src/lib/mina_lib/coda_subscriptions.ml
Labels: Impact: Medium, Risk: Low

#8575 Merge back to compatible
  buildkite/scripts/publish-deb.sh
  scripts/archive/build-release-archives.sh
  src/app/archive/archive_lib/processor.ml
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/tests/coda_processes.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/child_processes/child_processes.ml
  src/lib/child_processes/child_processes.mli
  src/lib/child_processes/termination.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
Labels: ci-build-me

#8473 [Compatible] fix handling committed transactions
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#8497 Make compile-time genesis proof creation optional
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/app/cli/src/tests/coda_archive_processor_test.ml
  src/app/cli/src/tests/coda_block_production_test.ml
  src/app/cli/src/tests/coda_bootstrap_test.ml
  src/app/cli/src/tests/coda_change_snark_worker_test.ml
  src/app/cli/src/tests/coda_delegation_test.ml
  src/app/cli/src/tests/coda_five_nodes_test.ml
  src/app/cli/src/tests/coda_long_fork.ml
  src/app/cli/src/tests/coda_peers_test.ml
  src/app/cli/src/tests/coda_processes.ml
  src/app/cli/src/tests/coda_restart_node_test.ml
  src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml
  src/app/cli/src/tests/coda_shared_prefix_multiproducer_test.ml
  src/app/cli/src/tests/coda_shared_prefix_test.ml
  src/app/cli/src/tests/coda_shared_state_test.ml
  src/app/cli/src/tests/coda_transitive_peers_test.ml
  src/app/cli/src/tests/coda_txns_and_restart_non_producers.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/coda_worker_testnet.ml
  src/app/cli/src/tests/full_test.ml
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/devnet.mlh
  src/config/fake_hash.mlh
  src/config/fuzz_medium.mlh
  src/config/fuzz_small.mlh
  src/config/mainnet.mlh
  src/config/nonconsensus_medium_curves.mlh
  src/config/print_versioned_types.mlh
  src/config/test_archive_processor.mlh
  src/config/test_postake.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_full_epoch.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_three_producers.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_producers.mlh
  src/config/testnet_postake_many_producers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/mina_compile_config/mina_compile_config.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/precomputed_values/precomputed_values.mli
  src/lib/prover/prover.ml
Labels: ci-build-me

#8455 Use proof_level=none for integration tests
  src/app/archive/archive.opam
  src/config/integration_tests.mlh
Labels: ci-build-me, ready-to-merge, waiting-for-gating

#8584 Stop using hard-coded compile-time verification keys
  buildkite/scripts/check-graphql-schema.sh
  buildkite/scripts/export-git-env-vars.sh
  scripts/rebuild-deb.sh
  src/app/archive/archive_lib/test.ml
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/blockchain_snark/blockchain_snark_state.mli
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/command_line_tests/command_line_tests.ml
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/network_pool/batcher.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/test.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/precomputed_values/gen_values/dune
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/precomputed_values/precomputed_values.mli
  src/lib/prover/prover.ml
  src/lib/snark_keys/gen_keys/gen_keys.ml
  src/lib/snark_worker/prod.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/tests/full_frontier_tests.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
  src/lib/verifier/dummy.ml
  src/lib/verifier/prod.ml
  src/lib/verifier/verifier_intf.ml
Labels: ci-build-me

#8530 Check that compatible can connect to mainnet
  buildkite/scripts/build-artifact.sh
  buildkite/scripts/check-graphql-schema.sh
  buildkite/scripts/ci-archive-release.sh
  buildkite/scripts/connect-to-mainnet-on-compatible.sh
  buildkite/scripts/export-git-env-vars.sh
  buildkite/src/Command/ConnectToTestnet.dhall
  buildkite/src/Jobs/Release/ArchiveRedundancyTools.dhall
  dockerfiles/Dockerfile-coda-daemon
  dockerfiles/Dockerfile-coda-demo
  scripts/archive/build-release-archives.sh
  scripts/rebuild-deb.sh
  src/config/testnet_postake_medium_curves.mlh
  src/lib/hash_prefix_states/dune
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/mina_base.opam
  src/nonconsensus/hash_prefix_states/dune
Labels: ci-build-me

#8596 change min_over_time to avg_over_time for the nodes-out-of-sync alert
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: ci-build-me

#8606 Rename build_archive to build_archive_all_sigs
  buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
  src/archive_blocks.opam
Labels: ci-build-me

#8611 Scripts for patching swapped balances
  scripts/archive/find-swapped-balances.awk
  scripts/archive/fix-swapped-balances.sh
Labels: ci-build-me, waiting-for-gating

#8583 App to swap balances for combined fee transfers
  Makefile
  buildkite/scripts/ci-archive-release.sh
  buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
  buildkite/src/Jobs/Release/ArchiveRedundancyTools.dhall
  scripts/archive/build-release-archives.sh
  src/app/replayer/replayer.ml
  src/app/swap_bad_balances/dune
  src/app/swap_bad_balances/sql.ml
  src/app/swap_bad_balances/swap_bad_balances.ml
  src/swap_bad_balances.opam
Labels: ci-build-me, waiting-for-gating

#8605 minimum block reward
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/lib/block_producer/block_producer.ml
  src/lib/mina_lib/config.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_transition/external_transition.ml
  src/lib/staged_ledger_diff/staged_ledger_diff.ml
  src/lib/staged_ledger_diff/staged_ledger_diff.mli
Labels: ci-build-me

#8506 Use a try_with to catch any exceptions from verifier's Rpc_parallel worker
  src/lib/verifier/prod.ml
Labels: ci-build-me

#8488 more metadata in snark-pool error logs
  src/lib/network_pool/snark_pool.ml
Labels: ci-build-me, waiting-for-gating

#8486 Docs for child processes
  src/lib/child_processes/README.md
  src/lib/child_processes/caml_syslimits.c
  src/lib/child_processes/child_processes.ml
  src/lib/child_processes/syslimits.ml
  src/lib/child_processes/termination.ml
Labels: ci-build-me, ready-to-merge

#8428 Some docs for bin_io
  docs/specs/bin_io/README.md
Labels: ci-build-me, ready-to-merge

#8637 Change structured event parser generator to use maps instead of alists
  src/lib/ppx_register_event/register_event.ml
Labels: ci-build-me

#8645 metrics for different types of node-status errors
  automation/services/watchdog/node_status_metrics.py
  automation/services/watchdog/version.txt
  automation/services/watchdog/watchdog.py
Labels: ci-build-me

#8582 add rejected blocks metrics
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/mina_metrics/mina_metrics.ml
  src/lib/rose_tree/rose_tree.ml
  src/lib/rose_tree/rose_tree.mli
  src/lib/transition_handler/validator.ml
  src/lib/transition_router/initial_validator.ml
Labels: ci-build-me, ready-to-merge

#8691 fix alert rule parse error
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: ci-build-me

#8676 tweak common prefix test to make it slightly faster
  src/app/test_executive/common_prefix.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/intf.ml
Labels: ci-build-me, ready-to-merge

#8658 Feature: Add stagedLedgerProofEmitted to GraphQL
  graphql_schema.json
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#8554 Add support for choosing constraint constants in gen_keys, remove as dep
  src/app/runtime_genesis_ledger/dune
  src/lib/genesis_ledger_helper/dune
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_ledger_helper/lib/dune
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/precomputed_values/dune
  src/lib/precomputed_values/gen_values/dune
  src/lib/snark_keys/dune
  src/lib/snark_keys/gen_keys/dune
  src/lib/snark_keys/gen_keys/gen_keys.ml
Labels: ci-build-me

#8075 Add Pickles_types.Higher_kinded_poly
  src/lib/pickles/inductive_rule.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_main.ml
  src/lib/pickles/wrap_domains.ml
  src/lib/pickles_types/higher_kinded_poly.ml
  src/lib/pickles_types/hlist.ml
  src/lib/pickles_types/poly_types.ml
Labels: ci-build-me, ready-to-merge

#8689 More alert improvements
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: ci-build-me

#8503 Use formatted exception printing for prover/verifier sub-monitors
  src/lib/mina_lib/mina_lib.ml
Labels: ci-build-me, ready-to-merge

#8186 Dispatch transactions as they come in to send-rosetta-transaction
  src/app/cli/src/init/client.ml
Labels: ci-build-me, ready-to-merge

#8650 [master] Metric for all peers ever seen
  src/app/cli/src/init/client.ml
  src/app/cli/src/mina.ml
  src/app/cli/src/tests/coda_processes.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_metrics/mina_metrics.ml
  src/lib/mina_net2/dune
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
Labels: ci-build-me, waiting-for-gating

#8672 Stop generating/downloading snark keys during build
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/precomputed_values/precomputed_values.mli
Labels: ci-build-me

#7282 Support local filesystem and rest-server modes for `accounts import`, `accounts list`
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/dune
  src/app/cli/src/init/graphql_queries.ml
  src/lib/cli_lib/flag.ml
  src/lib/cli_lib/flag.mli
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#8640 adding alert to disconnected blocks
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: alerting and monitoring, ci-build-me

#7258 Catch errors when the ledger is full
  src/lib/block_producer/block_producer.ml
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_ledger_tests/test.ml
  src/lib/merkle_ledger_tests/test_database.ml
  src/lib/merkle_ledger_tests/test_mask.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/mina_base/ledger.ml
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/ledger_transfer.ml
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_base/transaction_validator.ml
  src/lib/syncable_ledger/test.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
Labels: ci-build-me

#8717 Update epoch ledger handling in replayer
  src/app/replayer/replayer.ml
  src/app/replayer/sql.ml
Labels: ci-build-me

#8664 fix stackdriver log metric
  automation/services/watchdog/metrics.py
  automation/services/watchdog/version.txt
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: alerting and monitoring, ci-build-me, ready-to-merge

#8447 check cli public keys
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/app/client_sdk/client_sdk.ml
  src/app/client_sdk/js_util.ml
  src/app/genesis_ledger_from_tsv/genesis_ledger_from_tsv.ml
  src/lib/cli_lib/arg_type.ml
  src/lib/graphql_lib/decoders.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/secrets/wallets.ml
  src/lib/signature_lib/public_key.mli
Labels: ci-build-me

#8707 slack integration for testnet warnings
  automation/terraform/modules/testnet-alerts/alerts.tf
  automation/terraform/modules/testnet-alerts/secrets.tf
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-receivers.yml.tpl
  buildkite/src/Jobs/Lint/TestnetAlerts.dhall
  buildkite/src/Jobs/Release/TestnetAlerts.dhall
Labels: ci-build-me

#8715 Add stable pipeline support to buildkite
  buildkite/src/Monorepo.dhall
  buildkite/src/Prepare.dhall
Labels: ci-build-me

#8733 Add stable pipeline support to buildkite (round 2)
  buildkite/src/Monorepo.dhall
  buildkite/src/Pipeline/Mode.dhall
  buildkite/src/Prepare.dhall
  buildkite/src/gen/Jobs.dhall
Labels: ci-build-me

#8720 Exit with code 1 if there is an error in `ledger export`
  src/app/cli/src/init/client.ml
Labels: ci-build-me, ready-to-merge

#8688 query all direct-connected peers for all seed nodes in watchdog
  automation/services/watchdog/make_report.py
  automation/services/watchdog/metrics.py
  automation/services/watchdog/node_status_metrics.py
  automation/services/watchdog/version.txt
Labels: alerting and monitoring, ci-build-me, ready-to-merge

#8678 Slightly better macOS dev setup experience
  README-dev.md
  scripts/Brewfile.lock.json
  scripts/macos-setup.sh
  scripts/setup-opam.sh
Labels: ci-build-me

#8739 Replayer, don't create epoch ledger if exists
  src/app/replayer/replayer.ml
Labels: ci-build-me, ready-to-merge

#8735 Delegation compliance app
  Makefile
  src/app/delegation_compliance/README.md
  src/app/delegation_compliance/delegation_compliance.ml
  src/app/delegation_compliance/dune
  src/app/delegation_compliance/input.json
  src/app/delegation_compliance/payout_addresses.ml
  src/app/delegation_compliance/sql.ml
  src/delegation_compliance.opam
Labels: ci-build-me

#7971 Publish libp2p metrics for peercount, msg size and connection count.
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/app/libp2p_helper/src/libp2p_helper/main_test.go
  src/app/libp2p_helper/src/libp2p_helper/methodidx_jsonenum.go
Labels: ci-build-me

#8751 Replayer and delegation compliance, undo bad optimization
  src/app/delegation_compliance/delegation_compliance.ml
  src/app/delegation_compliance/sql.ml
  src/app/replayer/replayer.ml
Labels: ci-build-me

#8732 improve-bad-balance-scripting Add fix-all-balances.sh script
  scripts/archive/find-swapped-balances.awk
  scripts/archive/fix-all-balances.sh
  scripts/archive/fix-swapped-balances.sh
Labels: ci-build-me

#8760 Audit trail, remove duplicate data in `delegation_compliance`
  src/app/delegation_compliance/delegation_compliance.ml
  src/app/delegation_compliance/input.json
  src/app/delegation_compliance/sql.ml
Labels: ci-build-me

#8683 Alert/node-crashed
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: alerting and monitoring, ready-to-merge
