Repository MinaProtocol/mina, pull requests merged in 2021-02, with the labels that each got.

#7633 Update libp2p gating logic for private ips
  helm/archive-node/templates/archive.yaml
  helm/block-producer/templates/block-producer.yaml
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ci-build-me

#7685 add buildkite prefix to CI prometheus metrics and enable export to grafanacloud
  automation/services/buildkite/prometheus-exporter/METRICS.md
  automation/services/buildkite/prometheus-exporter/exporter.py
  automation/services/buildkite/prometheus-exporter/requirements.txt
  automation/services/buildkite/prometheus-exporter/version.txt
  automation/terraform/infrastructure/us-central1.tf
  automation/terraform/infrastructure/us-east1.tf
  automation/terraform/infrastructure/us-east4.tf
  automation/terraform/infrastructure/us-west1.tf
  buildkite/helm/buildkite-exporter/CHANGELOG.md
  buildkite/helm/buildkite-exporter/Chart.yaml
  buildkite/helm/buildkite-exporter/values.yaml
Labels: ci-build-me

#7612 cli next-staking-ledger error msg
  src/app/cli/src/init/coda_run.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
Labels: ci-build-me

#7666 Reject invalid public keys from the snark pool and in snark pool diffs
  src/lib/mina_base/coinbase.ml
  src/lib/mina_base/coinbase.mli
  src/lib/mina_base/fee_transfer.ml
  src/lib/mina_base/fee_transfer.mli
  src/lib/mina_base/fee_with_prover.ml
  src/lib/mina_base/transaction.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
Labels: ci-build-me

#7759 Immediately update transaction pool when applying commands
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#7735 Add balances to extensional commands
  src/app/archive/archive_lib/extensional.ml
  src/app/archive/archive_lib/processor.ml
  src/app/missing_subchain/block.ml
  src/app/missing_subchain/dune
  src/app/missing_subchain/missing_subchain.ml
  src/app/missing_subchain/sql.ml
Labels: ci-build-me

#7608 Add script, terraform and helm changes for static peer ids
  automation/scripts/generate-keys-and-ledger.sh
  automation/scripts/upload-keys-k8s.sh
  automation/terraform/modules/kubernetes/testnet/helm.tf
  buildkite/src/Command/DeployTestnet.dhall
  helm/block-producer/CHANGELOG.md
  helm/block-producer/Chart.yaml
  helm/block-producer/templates/block-producer.yaml
  helm/block-producer/values.yaml
Labels: ci-build-me

#7504 Proposal implementation: Min window grace period
  src/lib/consensus/constants.ml
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me, ready-to-merge-into-develop

#7751 Max connections ocaml side
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/codanet_test.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/app/libp2p_helper/src/libp2p_helper/main_test.go
  src/lib/gossip_net/fake.ml
  src/lib/gossip_net/intf.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/mina_networking/mina_networking.mli
Labels: ci-build-me

#7744 add variable artifact_path to ci deploy job
  buildkite/src/Command/DeployTestnet.dhall
  buildkite/src/Jobs/Test/DeployTestnetAndDestroy.dhall
Labels: ci-build-me

#7766 Check balances in replayer
  src/app/replayer/dune
  src/app/replayer/replayer.ml
  src/app/replayer/sql.ml
  src/app/replayer/test/archive_db.sql
  src/app/replayer/test/input.json
Labels: ci-build-me

#7752 Implement watchdog metrics
  .gitignore
  automation/services/watchdog/Dockerfile
  automation/services/watchdog/check_libp2p/check_libp2p.go
  automation/services/watchdog/check_libp2p/go.mod
  automation/services/watchdog/check_libp2p/go.sum
  automation/services/watchdog/metrics.py
  automation/services/watchdog/requirements.txt
  automation/services/watchdog/telemetry_metrics.py
  automation/services/watchdog/util.py
  automation/services/watchdog/version.txt
  automation/services/watchdog/watchdog.py
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/testnets/watchdog-test/main.tf
  helm/watchdog/templates/watchdog.yaml
  helm/watchdog/values.yaml
Labels: ci-build-me, ready-to-merge

#7789 Add static peers to initial peers for seed nodes
  automation/terraform/modules/kubernetes/testnet/helm.tf
Labels: ci-build-me

#7787 Client SDK, return JS bool from verifiers
  src/app/client_sdk/client_sdk.ml
Labels: ci-build-me

#7767 Client SDK: Implement verifyPaymentSignature and verifyStakeDelegationSignature
  frontend/client_sdk/src/CodaSDK.d.ts
  frontend/client_sdk/src/CodaSDK.re
  frontend/client_sdk/test/Test.ts
Labels: ci-build-me

#7817 Key validation improvements
  src/app/client_sdk/client_sdk.ml
  src/app/client_sdk/js_util.ml
  src/lib/cli_lib/commands.ml
Labels: ci-build-me

#7810 Fix CI deploy testnet artifact upload logic
  buildkite/src/Command/DeployTestnet.dhall
Labels: ci-build-me

#7746 Feature: Expose Account Timing in GraphQL
  graphql_schema.json
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#7812 Use posix-style flags by default
  src/app/archive/archive.ml
  src/app/archive_blocks/archive_blocks.ml
  src/app/best_tip_merger/best_tip_merger.ml
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/app/cli/src/tests/coda_long_fork.ml
  src/app/cli/src/tests/coda_restarts_and_txns_holy_grail.ml
  src/app/cli/src/tests/coda_shared_prefix_multiproducer_test.ml
  src/app/cli/src/tests/coda_shared_prefix_test.ml
  src/app/reformat/reformat.ml
  src/app/rosetta/lib/rosetta.ml
  src/app/rosetta/ocaml-signer/signer.ml
  src/app/rosetta/test-agent/agent.ml
  src/lib/cli_lib/flag.ml
  src/lib/snark_worker/functor.ml
Labels: ci-build-me

#7827 Client SDK: Added verifyKeypair()
  frontend/client_sdk/src/CodaSDK.d.ts
  frontend/client_sdk/src/CodaSDK.re
  frontend/client_sdk/test/Test.ts
Labels: ci-build-me

#7835 Fix duplicate flag in archive
  src/app/archive/archive.ml
Labels: ci-build-me

#7848 Adds more allowed-for-mainnet unblockers
  frontend/ci-build-me/src/index.js
Labels: ci-build-me

#7841 Fix addPeers graphql endpoint and command
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#7856 fix peer exchange bugs
  src/app/libp2p_helper/src/codanet.go
Labels: ci-build-me

#7858 Move ledger dumps to ledger subcommand
  src/app/cli/src/coda.ml
  src/app/cli/src/init/client.ml
  src/lib/cli_lib/flag.ml
  src/lib/cli_lib/flag.mli
Labels: ci-build-me

#7871 Add advanced command for computing receipt chain hash
  src/app/cli/src/init/client.ml
Labels: ci-build-me

#7866 Add max observed unvalidated block hight to metrics and status
  src/lib/daemon_rpcs/types.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_metrics/mina_metrics.ml
  src/lib/transition_router/initial_validator.ml
Labels: ci-build-me

#7859 more information in next block production timing
  graphql_schema.json
  src/lib/block_producer/block_producer.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/daemon_rpcs/types.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
Labels: ci-build-me

#7877 fix block user command query
  src/app/archive/archive_lib/processor.ml
Labels: ci-build-me

#7888 remove non-monotonic assertion
  src/lib/trust_system/record.ml
Labels: ci-build-me

#7889 Missing subchain, allow specified start block
  src/app/missing_subchain/missing_subchain.ml
  src/app/missing_subchain/sql.ml
Labels: ci-build-me

#7893 Print ledger hashes
  src/app/cli/src/init/client.ml
  src/lib/cli_lib/flag.ml
Labels: ci-build-me

#7896 Print currency totals in exported ledgers
  src/app/cli/src/init/client.ml
Labels: ci-build-me

#7844 fix buildkite exporter (ensure proper metric port casting) and update helm chart
  automation/services/buildkite/prometheus-exporter/exporter.py
  automation/services/buildkite/prometheus-exporter/version.txt
  automation/terraform/buildkite/buildkite-ci/monitoring.tf
  buildkite/helm/buildkite-exporter/CHANGELOG.md
  buildkite/helm/buildkite-exporter/Chart.lock
  buildkite/helm/buildkite-exporter/Chart.yaml
  buildkite/helm/buildkite-exporter/charts/common-utilities-0.0.8.tgz
  buildkite/helm/buildkite-exporter/templates/_healthchecks.common.tpl
  buildkite/helm/buildkite-exporter/templates/_healthchecks.tpl
  buildkite/helm/buildkite-exporter/templates/_helpers.tpl
  buildkite/helm/buildkite-exporter/templates/buildkite-exporter.yaml
  buildkite/helm/buildkite-exporter/templates/exporter-service.yaml
  buildkite/helm/buildkite-exporter/values.yaml
Labels: ci-build-me

#7837 add Buildkite "if" command-step property to base command config
  buildkite/src/Command/Base.dhall
Labels: ci-build-me

#7826 refactor dhall/CI DeployTestnet Command to make use of deploy spec
  buildkite/src/Command/DeployTestnet.dhall
  buildkite/src/Jobs/Test/DeployTestnetAndDestroy.dhall
Labels: ci-build-me

#7892 New Integration Terraform Module
  automation/terraform/modules/o1-integration/inputs.tf
  automation/terraform/modules/o1-integration/locals.tf
  automation/terraform/modules/o1-integration/secrets.tf
  automation/terraform/modules/o1-integration/testnet.tf
  src/app/test_executive/README.md
  src/config/integration_tests.mlh
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/integration_test_cloud_engine/terraform.ml
Labels: ci-build-me

#7904 change peers_snapshot to refresh every 30s
  src/lib/gossip_net/libp2p.ml
Labels: ci-build-me, ready-to-merge

#7339 Leaderboard: Current Testworld Fixes
  frontend/leaderboard/Dockerfile
  frontend/leaderboard/__tests__/leaderboard_test.re
  frontend/leaderboard/bsconfig.json
  frontend/leaderboard/helm/CHANGELOG.md
  frontend/leaderboard/helm/templates/leaderboard-cron-job.yaml
  frontend/leaderboard/helm/values.yaml
  frontend/leaderboard/package.json
  frontend/leaderboard/src/Challenges.re
  frontend/leaderboard/src/Main.re
  frontend/leaderboard/src/Metrics.re
  frontend/leaderboard/src/Points.re
  frontend/leaderboard/src/Postgres.re
  frontend/leaderboard/src/Types.re
  frontend/leaderboard/src/UploadLeaderboardData.re
  frontend/leaderboard/src/UploadLeaderboardPoints.re
Labels: ci-build-me

#7918 Migrate required circleci tests to buildkite
  .circleci/config.yml
  .circleci/config.yml.jinja
  buildkite/scripts/old_integration_tests/test_bootstrap.sh
  buildkite/scripts/old_integration_tests/test_delegation.sh
  buildkite/scripts/old_integration_tests/test_postake_snarkless.sh
  buildkite/scripts/old_integration_tests/test_postake_split.sh
  buildkite/scripts/old_integration_tests/test_shared_state.sh
  buildkite/src/Jobs/Test/MigratedIntegrationTests.dhall
Labels: ci-build-me, ready-to-merge

#7923 make super catchup the default
  src/app/cli/src/coda.ml
Labels: ci-build-me

#7922 peers list url
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
Labels: ci-build-me

#7900 Telemetry with connections limit
  automation/services/watchdog/make_report.py
  automation/services/watchdog/telemetry_metrics.py
  scripts/telemetry-crawl.py
  src/app/cli/src/init/client.ml
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/codanet_test.go
  src/app/libp2p_helper/src/generate_methodidx/main.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/app/libp2p_helper/src/libp2p_helper/main_test.go
  src/app/libp2p_helper/src/libp2p_helper/methodidx_jsonenum.go
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/gossip_net/any.ml
  src/lib/gossip_net/fake.ml
  src/lib/gossip_net/intf.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_networking/mina_networking.mli
  src/lib/sync_status/sync_status.ml
  src/lib/telemetry/telemetry.ml
Labels: ci-build-me

#7921 Modify some fees in realistic configs
  src/config/account_creation_fee/low.mlh
  src/config/account_creation_fee/realistic.mlh
  src/config/amount_defaults/realistic.mlh
  src/config/coinbase/realistic.mlh
  src/config/dev.mlh
Labels: ci-build-me

#7907 Multiple seeds with DNS for seed nodes
  .gitignore
  automation/scripts/bake.sh
  automation/scripts/generate-keys-and-ledger.sh
  automation/scripts/make-seeds-list.sh
  automation/scripts/upload-keys-k8s.sh
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/kubernetes/testnet/outputs.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/modules/o1-testnet/files.tf
  automation/terraform/modules/o1-testnet/inputs.tf
  automation/terraform/modules/o1-testnet/locals.tf
  automation/terraform/modules/o1-testnet/scripts.tf
  automation/terraform/modules/o1-testnet/testnet.tf
  automation/terraform/testnets/multiple-seeds-test/community_fast_locked_keys.json
  automation/terraform/testnets/multiple-seeds-test/fish.json
  automation/terraform/testnets/multiple-seeds-test/genesis_ledger.json
  automation/terraform/testnets/multiple-seeds-test/main.tf
  automation/terraform/testnets/multiple-seeds-test/whales.json
  automation/terraform/testnets/zenith/community_fast_locked_keys.json
  automation/terraform/testnets/zenith/fish.json
  automation/terraform/testnets/zenith/genesis_ledger.json
  automation/terraform/testnets/zenith/main.tf
  automation/terraform/testnets/zenith/qanet3.json
  automation/terraform/testnets/zenith/whales.json
  automation/terraform/testnets/zenith/zenith.json
  automation/terraform/testnets/zenith/zenith_seeds.txt
  helm/archive-node/templates/archive.yaml
  helm/block-producer/templates/block-producer.yaml
  helm/seed-node/Chart.yaml
  helm/seed-node/templates/genesis-configmap.yaml
  helm/seed-node/templates/seed-node.yaml
  helm/seed-node/templates/seed-service.yaml
Labels: ci-build-me, ready-to-merge

#7928 update for zenith
  genesis_ledgers/zenith.json
  scripts/rebuild-deb.sh
Labels: ci-build-me

#7914 Missing subchain, fail when no chain with start block
  src/app/missing_subchain/missing_subchain.ml
Labels: ci-build-me

#7894 Generate ledger JSON from spreadsheet
  Makefile
  src/app/genesis_ledger_from_tsv/dune
  src/app/genesis_ledger_from_tsv/genesis_ledger_from_tsv.ml
  src/genesis_ledger_from_tsv.opam
Labels: ci-build-me

#7743 create CI dhall components for building and caching the test-executive and executing integration tests
  automation/scripts/make-seeds-list.sh
  automation/terraform/buildkite/buildkite-ci/us-central1.tf
  automation/terraform/buildkite/buildkite-ci/us-east1.tf
  automation/terraform/buildkite/buildkite-ci/us-east4.tf
  automation/terraform/infrastructure/us-central1.tf
  automation/terraform/infrastructure/us-east1.tf
  automation/terraform/infrastructure/us-east4.tf
  automation/terraform/modules/kubernetes/buildkite-agent/aws.tf
  automation/terraform/modules/kubernetes/buildkite-agent/google_cloud.tf
  automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
  buildkite/scripts/build-test-executive.sh
  buildkite/src/Command/TestExecutive.dhall
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  helm/archive-node/CHANGELOG.md
  helm/archive-node/Chart.yaml
  helm/archive-node/templates/archive.yaml
  helm/block-producer/CHANGELOG.md
  helm/block-producer/Chart.yaml
  helm/block-producer/templates/block-producer.yaml
  helm/seed-node/CHANGELOG.md
  helm/seed-node/Chart.yaml
  helm/seed-node/templates/seed-node.yaml
  helm/snark-worker/CHANGELOG.md
  helm/snark-worker/Chart.yaml
  helm/snark-worker/templates/snark-coordinator.yaml
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
Labels: ci-build-me

#7936 fix datetime.now usage and update infra janitor to remove all violating testnets in mina-integration
  automation/services/watchdog/scripts/network-utilities.py
  automation/services/watchdog/version.txt
  automation/terraform/infrastructure/us-east4.tf
Labels: ci-build-me

#7937 0.4 fixes
  genesis_ledgers/zenith.json
  src/app/cli/src/coda.ml
  src/app/rosetta/lib/construction.ml
  src/lib/consensus/constants.ml
Labels: ci-build-me

#7946 skip integration test execution while failures are investigated
  buildkite/src/Command/TestExecutive.dhall
Labels: ci-build-me

#7852 Feature: Auto Publish Client SDK to npm
  automation/terraform/modules/kubernetes/buildkite-agent/aws.tf
  automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
  buildkite/scripts/client-sdk-tool.sh
  buildkite/src/Jobs/Release/ClientSdk.dhall
  frontend/client_sdk/package.json
Labels: ci-build-me

#7940 add cloud-platform oauth scope to buildkite clusters for compute resource management
  automation/terraform/infrastructure/us-central1.tf
  automation/terraform/infrastructure/us-east1.tf
  automation/terraform/infrastructure/us-east4.tf
  automation/terraform/modules/kubernetes/buildkite-agent/aws.tf
Labels: ci-build-me

#7957 update testnet k8s module helm chart versions and refactor ci deploy steps
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/o1-testnet/testnet.tf
  buildkite/src/Command/DeployTestnet.dhall
Labels: ci-build-me

#7941 Add a field to protocolStateProof, update graphql schema
  graphql_schema.json
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_transition/external_transition_intf.ml
Labels: ci-build-me

#7881 second graphql server with limited queries
  src/app/cli/src/coda.ml
  src/app/cli/src/init/coda_run.ml
  src/lib/cli_lib/flag.ml
  src/lib/cli_lib/flag.mli
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#7974 Remove offline timeout shutdown, log instead
  src/lib/mina_lib/mina_lib.ml
Labels: ci-build-me

#7994 More pending public keys, pretty output
  src/app/genesis_ledger_from_tsv/genesis_ledger_from_tsv.ml
Labels: ci-build-me

#7983 Re-enable int test block production CI job
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/modules/o1-integration/locals.tf
  automation/terraform/modules/o1-integration/secrets.tf
  automation/terraform/modules/o1-integration/testnet.tf
  buildkite/src/Command/TestExecutive.dhall
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  helm/seed-node/templates/seed-node.yaml
  src/app/test_executive/README.md
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/integration_test_lib/event_router.ml
  src/lib/integration_test_lib/wait_condition.ml
Labels: ci-build-me

#7961 Alert metrics
  automation/terraform/infrastructure/templates/testnet-alerts.yml.tpl
  src/lib/consensus/intf.ml
  src/lib/mina_metrics/mina_metrics.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
Labels: ci-build-me

#8005 Add make reports posting to discord back to the new watchdog
  automation/services/watchdog/make_report.py
  automation/services/watchdog/version.txt
  automation/terraform/testnets/watchdog-test/main.tf
  automation/terraform/testnets/watchdog-test/watchdog-test_seeds.txt
  automation/terraform/testnets/zenith/main.tf
  automation/terraform/testnets/zenith/zenith_seeds.txt
  helm/watchdog/templates/watchdog.yaml
Labels: ci-build-me

#8010 add terraform v0.14.7 to shared buildkite agent DIR
  automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
Labels: ci-build-me

#7988 Add buildkite job for libp2p unit tests
  .circleci/config.yml
  .circleci/config.yml.jinja
  README-dev.md
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/Jobs/Test/DaemonUnitTest.dhall
  buildkite/src/Jobs/Test/Libp2pUnitTest.dhall
  dockerfiles/Dockerfile
  dockerfiles/Dockerfile-toolchain
  src/app/libp2p_helper/src/codanet_test.go
  src/app/libp2p_helper/src/libp2p_helper/main_test.go
Labels: ci-build-me

#8029 Epoch ledger sync fix
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
Labels: ci-build-me

#7993 flesh out readme a bit
  .gitignore
  src/app/test_executive/README.md
  src/lib/integration_test_cloud_engine/coda_automation.ml
Labels: ci-build-me, ready-to-merge, ready-to-merge-into-develop

#8017 Devnet
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/modules/o1-testnet/testnet.tf
  automation/terraform/testnets/devnet/community_fast_locked_keys.json
  automation/terraform/testnets/devnet/devnet_seeds.txt
  automation/terraform/testnets/devnet/fish.json
  automation/terraform/testnets/devnet/genesis_ledger.json
  automation/terraform/testnets/devnet/main.tf
  automation/terraform/testnets/devnet/whales.json
  helm/seed-node/templates/seed-node.yaml
Labels: ci-build-me, ready-to-merge

#8013 add buildkite ci jobs for building and uploading as artifacts archive-redundancy tools
  buildkite/scripts/ci-archive-release.sh
  buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
  buildkite/src/Jobs/Release/ArchiveRedundancyTools.dhall
  scripts/archive/build-release-archives.sh
Labels: ci-build-me

#8042 set base CI terraform version to 0.14.7 and update infra + testnet minimum supported versions
  automation/terraform/buildkite/buildkite-experimental/main.tf
  automation/terraform/infrastructure/main.tf
  automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
  automation/terraform/testnets/bug-net/main.tf
  automation/terraform/testnets/bugspray/main.tf
  automation/terraform/testnets/ci-net/main.tf
  automation/terraform/testnets/multiple-seeds-test/main.tf
  automation/terraform/testnets/nightly/main.tf
  automation/terraform/testnets/static-peers-net/main.tf
  automation/terraform/testnets/testworld/main.tf
  automation/terraform/testnets/watchdog-test/main.tf
  automation/terraform/testnets/zenith/main.tf
Labels: ci-build-me

#7594 GraphQL: Add field for Staged Ledger proof emission
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#8039 fail intg test if any internal errors
  src/app/test_executive/test_executive.ml
Labels: ci-build-me, ready-to-merge

#8022 Adding logs when drop blocks
  src/lib/transition_router/initial_validator.ml
Labels: ci-build-me

#8046 add CI common retry on git checkout errors and retry on deb pkg build on libp2p error
  buildkite/src/Command/Base.dhall
  buildkite/src/Jobs/Release/MinaArtifact.dhall
Labels: ci-build-me

#8031 Versioned types for pickles
  src/lib/dummy_values/gen_values/gen_values.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/mina_base/proof.ml
  src/lib/mina_base/side_loaded_verification_key.ml
  src/lib/mina_base/snapp_account.ml
  src/lib/mina_base/snapp_command.ml
  src/lib/mina_base/snapp_predicate.ml
  src/lib/mina_base/snapp_state.ml
  src/lib/mina_transition/external_transition_sample_precomputed_block.ml
  src/lib/pedersen_lib/dune
  src/lib/pedersen_lib/pedersen.ml
  src/lib/pedersen_lib/pedersen.mli
  src/lib/pickles/cache.ml
  src/lib/pickles/composition_types/bulletproof_challenge.ml
  src/lib/pickles/composition_types/composition_types.ml
  src/lib/pickles/composition_types/digest.ml
  src/lib/pickles/composition_types/index.ml
  src/lib/pickles/composition_types/index.mli
  src/lib/pickles/dune
  src/lib/pickles/intf.ml
  src/lib/pickles/limb_vector/challenge.ml
  src/lib/pickles/limb_vector/constant.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/proof.ml
  src/lib/pickles/reduced_me_only.ml
  src/lib/pickles/side_loaded_verification_key.ml
  src/lib/pickles_base/side_loaded_verification_key.ml
  src/lib/pickles_types/at_most.ml
  src/lib/pickles_types/dune
  src/lib/pickles_types/hlist.ml
  src/lib/pickles_types/vector.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/zexe_backend/pasta/basic.ml
  src/lib/zexe_backend/pasta/pallas_based_plonk.ml
  src/lib/zexe_backend/pasta/vesta_based_plonk.ml
Labels: ci-build-me

#8053 soft-fail testnet alert jobs while terraform state is updated to support 0.14.x terraform wersions
  buildkite/src/Jobs/Lint/TestnetAlerts.dhall
  buildkite/src/Jobs/Release/TestnetAlerts.dhall
Labels: ci-build-me

#8066 Remove Pedersen dead code
  src/lib/pedersen_lib/dune
  src/lib/pedersen_lib/pedersen.ml
  src/lib/pedersen_lib/pedersen.mli
  src/pedersen_lib.opam
Labels: ci-build-me

#8067 Remove dirty message from buildkite artifact versions
  buildkite/src/Jobs/Release/MinaArtifact.dhall
  src/lib/mina_version/gen.sh
Labels: ci-build-me

#7781 enable custom and multiple testnet deployment archive-node setups
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/kubernetes/testnet/kubernetes.tf
  automation/terraform/modules/kubernetes/testnet/locals.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/modules/o1-integration/testnet.tf
  automation/terraform/modules/o1-testnet/inputs.tf
  automation/terraform/modules/o1-testnet/locals.tf
  automation/terraform/modules/o1-testnet/outputs.tf
  automation/terraform/modules/o1-testnet/scripts.tf
  automation/terraform/modules/o1-testnet/testnet.tf
  automation/terraform/testnets/ci-net/main.tf
  buildkite/src/Command/DeployTestnet.dhall
  helm/archive-node/CHANGELOG.md
  helm/archive-node/Chart.yaml
  helm/archive-node/templates/_healthchecks.tpl
  helm/archive-node/templates/_helpers.tpl
  helm/archive-node/templates/archive-service.yaml
  helm/archive-node/templates/archive.yaml
  helm/archive-node/templates/db-bootstrap.yaml
  helm/archive-node/values.yaml
  helm/block-producer/CHANGELOG.md
  helm/block-producer/Chart.yaml
  helm/block-producer/templates/block-producer.yaml
  helm/block-producer/values.yaml
  helm/seed-node/CHANGELOG.md
  helm/seed-node/Chart.yaml
  helm/seed-node/templates/seed-node.yaml
  helm/seed-node/values.yaml
  helm/snark-worker/CHANGELOG.md
  helm/snark-worker/Chart.yaml
  helm/snark-worker/templates/snark-coordinator.yaml
  helm/snark-worker/values.yaml
Labels: ci-build-me

#8060 Catch and log all callback timeouts in Initial_validator
  src/lib/transition_router/initial_validator.ml
Labels: ci-build-me

#8012 Enforce version, binable changes linting
  buildkite/src/Jobs/Lint/Fast.dhall
  buildkite/src/Jobs/Lint/OCaml.dhall
Labels: ci-build-me

#8058 move testnet alert setup from global infra to testnet modules/infra
  automation/terraform/infrastructure/secrets.tf
  automation/terraform/modules/testnet-alerts/alerts.tf
  automation/terraform/modules/testnet-alerts/inputs.tf
  automation/terraform/modules/testnet-alerts/locals.tf
  automation/terraform/modules/testnet-alerts/outputs.tf
  automation/terraform/modules/testnet-alerts/secrets.tf
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-receivers.yml.tpl
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
  automation/terraform/monitoring/o1-testnet-alerts.tf
  buildkite/src/Jobs/Lint/TestnetAlerts.dhall
  buildkite/src/Jobs/Release/TestnetAlerts.dhall
Labels: ci-build-me

#8069 add required archive vars to block-producer and seed-node specs in o1-integration module
  automation/terraform/modules/o1-integration/testnet.tf
Labels: ci-build-me
