Repository MinaProtocol/mina, pull requests merged in 2021-12, with the labels that each got.

#9883 show file read errors when unlocking keys
  src/app/cli/src/init/client.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/secrets/privkey_error.ml
  src/lib/secrets/secret_file.ml
  src/lib/secrets/wallets.ml
  src/lib/secrets/wallets.mli
Labels: ci-build-me

#9872 Feature: Mina-Signer TypeScript/JavaScript library
  frontend/mina-signer/.gitignore
  frontend/mina-signer/README.md
  frontend/mina-signer/jest.config.ts
  frontend/mina-signer/package-lock.json
  frontend/mina-signer/package.json
  frontend/mina-signer/src/MinaSigner.ts
  frontend/mina-signer/src/TSTypes.ts
  frontend/mina-signer/tests/client.test.ts
  frontend/mina-signer/tests/keypair.test.ts
  frontend/mina-signer/tests/message.test.ts
  frontend/mina-signer/tests/payment.test.ts
  frontend/mina-signer/tests/rosetta.test.ts
  frontend/mina-signer/tests/stake-delegation.test.ts
  frontend/mina-signer/tsconfig.json
Labels: ci-build-me

#9769 event type refactor
  dockerfiles/puppeteer-context/mina_daemon_puppeteer.py
  src/app/test_executive/reliability_test.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/integration_test_lib/event_type.ml
  src/lib/integration_test_lib/event_type.mli
  src/lib/integration_test_lib/puppeteer_message.ml
Labels: ci-build-me

#9481 Catchup intg test
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  dockerfiles/puppeteer-context/mina_daemon_puppeteer.py
  src/app/test_executive/reliability_test.ml
  src/app/test_executive/short_bootstrap.ml
  src/app/test_executive/short_bootstrap.mli
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/integration_test_lib/event_type.ml
  src/lib/integration_test_lib/event_type.mli
  src/lib/integration_test_lib/network_state.ml
  src/lib/integration_test_lib/puppeteer_message.ml
Labels: ci-build-me

#9890 Rosetta, rename queries
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
Labels: ci-build-me

#9896 Rosetta, log Postgresql connection, locks data
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/lib/network.ml
  src/app/rosetta/lib/pg_data.ml
  src/app/rosetta/lib/rosetta.ml
Labels: ci-build-me

#9899 Exit codes for missing blocks auditor
  src/app/missing_blocks_auditor/missing_blocks_auditor.ml
Labels: ci-build-me

#9887 fix fee excess for parties transaction
  src/lib/mina_base/parties_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#9904 Rosetta, fix pending blocks balance query
  src/app/missing_blocks_auditor/missing_blocks_auditor.ml
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/network.ml
Labels: ci-build-me

#9903 Updated mina signature RFC for Pasta Pallas curves
  docs/specs/signatures/description.md
Labels: ci-build-me

#9750 snapps snark worker changes
  src/app/archive/archive_lib/processor.ml
  src/app/cli/src/tests/coda_process.ml
  src/app/trivial_snapp_txn_gen/dune
  src/app/trivial_snapp_txn_gen/trivial_snapp_txn_gen.ml
  src/lib/logger/logger.ml
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/parties.ml
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/signature.ml
  src/lib/mina_base/signature.mli
  src/lib/mina_base/snapp_statement.ml
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_base/transaction.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/prover/prover.ml
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/prod.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_snark/dune
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transaction_witness/transaction_witness.ml
  src/lib/transaction_witness/transaction_witness.mli
  src/lib/verifier/common.ml
  src/trivial_snapp_txn_gen.opam
Labels: ci-build-me

#9908 Set chain status when adding intermediate blocks
  src/app/archive/archive_lib/processor.ml
Labels: ci-build-me

#9505 add account snapp state field to graphql
  graphql_schema.json
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#9914 [Fix CI] Update clear-deb-s3-lockfile script for multi-distro releases
  scripts/clear-deb-s3-lockfile.sh
Labels: ci-build-me

#9912 Add increment_nonce to archive db
  src/app/archive/archive_lib/processor.ml
  src/app/archive/snapp_tables.sql
Labels: ci-build-me

#9913 [Crypto] Additional rust binding tests
  src/lib/marlin_plonk_bindings/bigint_256/marlin_plonk_bindings_bigint_256.ml
  src/lib/marlin_plonk_bindings/pasta_fp/marlin_plonk_bindings_pasta_fp.ml
  src/lib/marlin_plonk_bindings/pasta_fp/vector/dune
  src/lib/marlin_plonk_bindings/pasta_fp/vector/marlin_plonk_bindings_pasta_fp_vector.ml
  src/lib/marlin_plonk_bindings/pasta_fp_index/marlin_plonk_bindings_pasta_fp_index.ml
  src/lib/marlin_plonk_bindings/pasta_fp_proof/marlin_plonk_bindings_pasta_fp_proof.ml
  src/lib/marlin_plonk_bindings/pasta_fq/marlin_plonk_bindings_pasta_fq.ml
  src/lib/marlin_plonk_bindings/pasta_fq/vector/dune
  src/lib/marlin_plonk_bindings/pasta_fq/vector/marlin_plonk_bindings_pasta_fq_vector.ml
  src/lib/marlin_plonk_bindings/pasta_fq_index/marlin_plonk_bindings_pasta_fq_index.ml
  src/lib/marlin_plonk_bindings/pasta_fq_proof/marlin_plonk_bindings_pasta_fq_proof.ml
  src/lib/marlin_plonk_bindings/pasta_pallas/marlin_plonk_bindings_pasta_pallas.ml
  src/lib/marlin_plonk_bindings/pasta_vesta/marlin_plonk_bindings_pasta_vesta.ml
Labels: ci-build-me

#9927 Move Caqti code to mina_caqti library
  graphql_schema.json
  src/app/archive/archive_lib/dune
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/archive/create_schema.sql
  src/app/delegation_compliance/delegation_compliance.ml
  src/app/delegation_compliance/dune
  src/app/delegation_compliance/sql.ml
  src/app/extract_blocks/dune
  src/app/extract_blocks/sql.ml
  src/app/replayer/dune
  src/app/replayer/sql.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/dune
  src/lib/mina_caqti/dune
  src/lib/mina_caqti/mina_caqti.ml
  src/mina_caqti.opam
Labels: ci-build-me

#9923 Snapps, some renamings
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/archive/snapp_tables.sql
  src/lib/mina_base/parties.ml
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/snapp_generators.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#9891 Split reliability test
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  src/app/test_executive/chain_reliability_test.ml
  src/app/test_executive/chain_reliability_test.mli
  src/app/test_executive/peers_reliability_test.ml
  src/app/test_executive/peers_reliability_test.mli
  src/app/test_executive/test_executive.ml
Labels: ci-build-me, acceptance-automation

#9911 Lk86/support ubuntu20.04 in Rosetta staged dockerfile
  dockerfiles/stages/1-build-deps-ubuntu
  dockerfiles/stages/2-opam-deps
  dockerfiles/stages/3-builder
  dockerfiles/stages/3-toolchain
  dockerfiles/stages/4-deb-builder
  dockerfiles/stages/4-prod-ubuntu
  dockerfiles/stages/4-production
  scripts/release-docker.sh
Labels: ci-build-me

#9598 Snapp Transaction Pool: #9501
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/lib/graphql_lib/decoders.ml
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#9855 Party protocol state predicate
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/archive/create_schema.sql
  src/app/archive/snapp_tables.sql
  src/lib/mina_base/parties.ml
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/snapp_generators.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_witness/transaction_witness.ml
  src/lib/transaction_witness/transaction_witness.mli
  src/lib/verifier/common.ml
Labels: ci-build-me

#9819 Toggle full commitment for snapp commands
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/archive/snapp_tables.sql
  src/lib/mina_base/parties.ml
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/snapp_generators.ml
  src/lib/mina_base/snapp_predicate.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_state/local_state.ml
  src/lib/mina_transition/external_transition_sample_precomputed_block.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#9818 Remove deleted tables from drop_tables.sql
  src/app/archive/drop_tables.sql
Labels: ci-build-me, Proj - snapps protocol work

#9827 Snapp generators, nonce from ledger
  src/lib/mina_base/snapp_generators.ml
Labels: ci-build-me

#9948 snapps: merkle root mismatch fix
  src/lib/mina_base/parties.ml
Labels: ci-build-me, Proj - snapps protocol work

#9954 Rosetta, return error if no account
  src/app/archive/archive_lib/processor.ml
  src/app/rosetta/lib/account.ml
Labels: ci-build-me

#9889 catchup failure cases unit tests
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
Labels: ready for review, ci-build-me

#9664 Ring-signature tests for transaction snark
  src/lib/command_line_tests/command_line_tests.ml
  src/lib/transaction_snark/test/dune
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/test/util.mli
  src/lib/transaction_snark/transaction_snark.mli
Labels: ci-build-me

#9953 check for replays
  src/lib/mina_base/ledger.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me
