Repository MinaProtocol/mina, pull requests merged in 2021-05, with the labels that each got.

#8768 Test replayer in CI
  buildkite/scripts/replayer-test.sh
  buildkite/src/Command/ReplayerTest.dhall
  buildkite/src/Jobs/Test/ReplayerTest.dhall
  scripts/replayer-test.sh
  scripts/test-replayer.sh
  src/app/replayer/test/input.json
Labels: ci-build-me

#8783 fix a typo in testnet-alert-rules
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: ci-build-me

#8752 Increase the missing log time period
  automation/services/watchdog/metrics.py
  automation/services/watchdog/version.txt
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: ci-build-me

#8740 receiver configuration for warnings
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-receivers.yml.tpl
Labels: ci-build-me

#7884 Intg test: Gossip consistency test
  automation/terraform/modules/kubernetes/testnet/locals.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/modules/o1-integration/testnet.tf
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  helm/archive-node/templates/archive.yaml
  helm/archive-node/values.yaml
  helm/block-producer/templates/block-producer.yaml
  helm/block-producer/values.yaml
  helm/seed-node/templates/seed-node.yaml
  helm/seed-node/values.yaml
  helm/snark-worker/templates/snark-coordinator.yaml
  helm/snark-worker/values.yaml
  src/app/test_executive/common_prefix.ml
  src/app/test_executive/gossip_consistency.ml
  src/app/test_executive/payments_timed_accounts_test.ml
  src/app/test_executive/send_payment_test.ml
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/dsl.ml
  src/lib/integration_test_lib/dune
  src/lib/integration_test_lib/event_type.ml
  src/lib/integration_test_lib/event_type.mli
  src/lib/integration_test_lib/gossip_state.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/malleable_error.ml
  src/lib/integration_test_lib/network_state.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/ledger_proof/ledger_proof_intf.ml
  src/lib/mina_base/fee_with_prover.ml
  src/lib/network_pool/intf.ml
  src/lib/network_pool/priced_proof.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/pickles/pickles.mli
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ci-build-me, ready for review, ready-to-merge

#8792 Delegation compliance, simplified
  src/app/delegation_compliance/delegation_compliance.ml
  src/app/delegation_compliance/input.json
  src/app/delegation_compliance/sql.ml
Labels: ci-build-me

#8809 Log monitor chain on long async cycles
  src/app/cli/src/cli_entrypoint/dune
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/find_ip.ml
  src/app/cli/src/tests/coda_process.ml
  src/app/cli/src/tests/dune
  src/app/rosetta/lib/graphql.ml
  src/app/test_executive/test_executive.ml
  src/lib/cache_dir/cache_dir.ml
  src/lib/cache_dir/dune
  src/lib/child_processes/child_processes.ml
  src/lib/child_processes/dune
  src/lib/child_processes/termination.ml
  src/lib/cli_lib/exceptions.ml
  src/lib/daemon_rpcs/client.ml
  src/lib/exit_handlers/dune
  src/lib/exit_handlers/exit_handlers.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/gossip_net/dune
  src/lib/gossip_net/libp2p.ml
  src/lib/graphql_lib/client.ml
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/mina_lib/coda_subscriptions.ml
  src/lib/mina_lib/conf_dir.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/prover/prover.ml
  src/lib/secrets/secret_file.ml
  src/lib/secrets/wallets.ml
  src/lib/snark_worker/dune
  src/lib/snark_worker/prod.ml
  src/lib/transition_handler/breadcrumb_builder.ml
  src/lib/verifier/dune
  src/lib/verifier/prod.ml
Labels: ci-build-me

#8779 Merkle_ledger, code descriptions
  src/lib/merkle_ledger/README.md
  src/lib/merkle_ledger/merkle_ledger_intf.ml
  src/lib/merkle_ledger/merkle_path.ml
  src/lib/merkle_ledger/util.ml
  src/lib/syncable_ledger/syncable_ledger.ml
Labels: ci-build-me

#8758 fix make_report
  automation/services/watchdog/make_report.py
Labels: ci-build-me, ready-to-merge

#8263 Refactor Mina dockerfiles entrypoint setup
  dockerfiles/Dockerfile-coda-daemon
  dockerfiles/Dockerfile-coda-demo
  dockerfiles/Dockerfile-mina-archive
  dockerfiles/auxiliary_entrypoints/01-override-genesis-ledger.sh
  dockerfiles/auxiliary_entrypoints/01-override-peers-list.sh
  dockerfiles/auxiliary_entrypoints/01-run-demo.sh
  dockerfiles/scripts/archive-entrypoint.sh
  dockerfiles/scripts/cron_job_dump_ledger.sh
  dockerfiles/scripts/daemon-entrypoint.sh
  helm/staking-ledger-cron/mainnet-dump-staking-ledger-cronjob.yaml
  scripts/archive/build-release-archives.sh
  scripts/release-docker.sh
  scripts/run-demo.sh
Labels: ci-build-me

#8769 Watchdog/gather number of queries
  automation/services/watchdog/make_report.py
  automation/services/watchdog/node_status_metrics.py
  automation/services/watchdog/version.txt
  automation/services/watchdog/watchdog.py
Labels: ci-build-me, ready-to-merge

#8776 sync local state even if we can't download best tip from peers
  src/lib/consensus/proof_of_stake.ml
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me, ready-to-merge

#8852 Increase node status timeout
  src/app/libp2p_helper/src/codanet.go
Labels: ci-build-me, ready-to-merge

#8810 unit tests for transaction undo
  src/app/archive/archive_lib/test.ml
  src/lib/mina_base/coinbase.ml
  src/lib/mina_base/coinbase.mli
  src/lib/mina_base/coinbase_fee_transfer.ml
  src/lib/mina_base/coinbase_fee_transfer.mli
  src/lib/mina_base/fee_transfer.ml
  src/lib/mina_base/fee_transfer.mli
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#8764 Don't generate genesis proof at startup
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/rosetta/test-agent/agent.ml
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/block_producer/block_producer.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/integration_test_lib/event_type.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_transition/external_transition.ml
  src/lib/precomputed_values/gen_values/gen_values.ml
  src/lib/prover/intf.ml
  src/lib/prover/prover.ml
Labels: ci-build-me

#8861 Omit alerts from private testnets
  automation/README.md
  automation/terraform/monitoring/o1-testnet-alerts.tf
Labels: ci-build-me

#8871 Add missing runbooks
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: ci-build-me

#8844 Export snarked ledger
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
Labels: ci-build-me

#8873 CSV file output for compliance
  src/app/delegation_compliance/delegation_compliance.ml
Labels: ci-build-me

#8849 Consolidate more integration tests
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  src/app/test_executive/common_prefix.ml
  src/app/test_executive/gossip_consistency.ml
  src/app/test_executive/gossip_consistency.mli
  src/app/test_executive/payments_test.ml
  src/app/test_executive/payments_test.mli
  src/app/test_executive/payments_timed_accounts_test.ml
  src/app/test_executive/reliability_test.ml
  src/app/test_executive/send_payment_test.ml
  src/app/test_executive/send_payment_test.mli
  src/app/test_executive/test_executive.ml
Labels: ci-build-me

#8869 only exec commands on running pods
  automation/services/watchdog/metrics.py
Labels: ci-build-me, ready-to-merge

#6650 Pull puppeteer script directly from context
  dockerfiles/Dockerfile-coda-daemon-puppeteered
  dockerfiles/puppeteer-context/coda_daemon_puppeteer.py
  scripts/release-docker.sh
Labels: ci-build-me, ready-to-merge

#8854 Re-enable libp2p metrics; remove per-peer metrics
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ci-build-me

#8705 [DOCS] Protocol Interface
  src/lib/mina_networking/README.md
Labels: ci-build-me

#8884 Delegation compliance, count all blocks in epoch
  src/app/delegation_compliance/delegation_compliance.ml
  src/app/delegation_compliance/sql.ml
Labels: ci-build-me

#8721 add message length prefix to stream
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/app/libp2p_helper/src/libp2p_helper/main_test.go
Labels: ci-build-me

#8880 Add pprof to libp2p_helper metrics server
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ci-build-me

#8793 Rebroadcast snark work until it is included in a block
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/network_pool/mocks.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/transition_frontier/extensions/snark_pool_refcount.ml
  src/lib/transition_frontier/extensions/snark_pool_refcount.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
Labels: ci-build-me

#8907 Fix libp2p metrics unit tests
  src/app/libp2p_helper/src/libp2p_helper/main_test.go
Labels: ci-build-me

#8814 Vrf evaluation commands
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/lib/cli_lib/commands.ml
  src/lib/consensus/dune
  src/lib/consensus/proof_of_stake.ml
  src/lib/consensus/vrf/consensus_vrf.ml
  src/lib/consensus/vrf/dune
  src/lib/graphql_lib/base_types.ml
  src/lib/graphql_lib/base_types.mli
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/vrf_lib/standalone.ml
  src/lib/vrf_lib/tests/standalone_test.ml
Labels: ci-build-me

#8923 Delegation compliance, CSV stitching
  src/app/delegation_compliance/delegation_compliance.ml
Labels: ci-build-me

#8926 Fix flaky tests: ensure all async jobs have completed before asserting
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#8947 [Release] Don't look for genesis proof file at startup
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ci-build-me

#8917 Catch RPC and WNOHANG errors
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/tests/coda_processes.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/lib/child_processes/termination.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_metrics/mina_metrics.ml
  src/lib/mina_net2/dune
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/verifier/prod.ml
Labels: ci-build-me

#8952 devnet catchup failure fix
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/transition_frontier/full_catchup_tree.ml
Labels: ci-build-me

#8900 [docker] added dev flow
  .gitignore
  dev/Makefile
  dev/README.md
  dev/docker-compose.yml
  src/app/reformat/reformat.ml
Labels: ci-build-me, ready-to-merge
