Repository MinaProtocol/mina, pull requests merged in 2021-01, with the labels that each got.

#7056 fix graphql ports in the integration tests
  graphql_schema.json
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/lib/network.ml
  src/app/test_executive/payments_timed_accounts.ml
  src/app/test_executive/peers_test.ml
  src/app/test_executive/send_payment_test.ml
  src/app/test_executive/test_executive.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/daemon_rpcs/types.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/integration_test_lib/integration_test_lib.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/network_peer/peer.ml
Labels: ci-build-me, ready-to-merge, ready-to-merge-into-develop

#7276 Distinguish Could_not_construct from Sexp in Error.t
  src/lib/error_json/error_json.ml
Labels: ci-build-me, ready-to-merge

#7325 add finer grained argument for skipping staged ledger verification
  src/lib/block_producer/block_producer.ml
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_handler/processor.ml
Labels: ci-build-me, ready-to-merge-into-develop

#7229 Buildkite commands and jobs for running nightlies
  buildkite/nightly.txt
  buildkite/scripts/deploy-nightly.sh
  buildkite/scripts/generate-diff.sh
  buildkite/src/Command/DeployNightly.dhall
  buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
  buildkite/src/Jobs/Release/MinaArtifact.dhall
  buildkite/src/Jobs/Test/Nightly.dhall
Labels: ci-build-me

#7334 set testnet component envvar CONNECT_PRIVATE_IPS=true
  helm/archive-node/Chart.yaml
  helm/archive-node/templates/archive.yaml
  helm/block-producer/Chart.yaml
  helm/block-producer/templates/block-producer.yaml
  helm/seed-node/Chart.yaml
  helm/seed-node/templates/seed-node.yaml
  helm/snark-worker/Chart.yaml
  helm/snark-worker/templates/snark-coordinator.yaml
Labels: ci-build-me

#7340 Fix nightly dirtywhen bug in dhall
  buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
  buildkite/src/Jobs/Release/MinaArtifact.dhall
  buildkite/src/Jobs/Test/Nightly.dhall
Labels: ci-build-me

#7343 update helm chart Mina logo/icon metadata
  frontend/bot/helm/Chart.yaml
  frontend/leaderboard/helm/Chart.yaml
  helm/archive-node/Chart.yaml
  helm/block-producer/Chart.yaml
  helm/common/Chart.yaml
  helm/seed-node/Chart.yaml
  helm/snark-worker/Chart.yaml
Labels: ci-build-me

#7352 Revert nightlies so builds work
  buildkite/nightly.txt
  buildkite/scripts/deploy-nightly.sh
  buildkite/scripts/generate-diff.sh
  buildkite/src/Command/DeployNightly.dhall
  buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
  buildkite/src/Jobs/Release/MinaArtifact.dhall
  buildkite/src/Jobs/Test/Nightly.dhall
Labels: ci-build-me

#7336 Transactions in missing subchains; compatible JSON output
  src/app/archive/archive_lib/extensional.ml
  src/app/archive/archive_lib/processor.ml
  src/app/missing_subchain/block.ml
  src/app/missing_subchain/dune
  src/app/missing_subchain/missing_subchain.ml
  src/app/missing_subchain/sql.ml
  src/app/rosetta/lib/block.ml
Labels: ci-build-me, ready-to-merge

#7355 Move ledger hash to blockchain state
  Makefile
  src/app/missing_subchain/block.ml
Labels: ci-build-me, ready-to-merge

#7357 Retry archive RPCs
  src/lib/mina_lib/archive_client.ml
  src/lib/mina_lib/archive_client.mli
Labels: ci-build-me, ready-to-merge

#6870 [Plugin] OCaml toplevel running inside daemon
  src/lib/coda_plugins/examples/toplevel/dune
  src/lib/coda_plugins/examples/toplevel/plugin_toplevel.ml
Labels: ci-build-me, ready-to-merge-into-develop

#7365 Don't exit on failed GraphQL requests in archive-precomputed-blocks
  src/app/cli/src/init/client.ml
Labels: ci-build-me, ready-to-merge-into-develop

#7384 Fix dangling mask error
  src/lib/merkle_mask/masking_merkle_tree.ml
Labels: ci-build-me

#7381 Merge master into develop
  .circleci/config.yml
  .circleci/config.yml.jinja
  src/app/cli/src/coda.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/downloader.opam
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/bootstrap_controller.mli
  src/lib/daemon_rpcs/types.ml
  src/lib/downloader/downloader.ml
  src/lib/downloader/dune
  src/lib/gossip_net/any.ml
  src/lib/gossip_net/fake.ml
  src/lib/gossip_net/intf.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/ledger_catchup/best_tip_lru.ml
  src/lib/ledger_catchup/best_tip_lru.mli
  src/lib/ledger_catchup/catchup_jobs.ml
  src/lib/ledger_catchup/dune
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/ledger_catchup/ledger_catchup.mli
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/mina_base/sync_ledger.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_lib/coda_subscriptions.ml
  src/lib/mina_lib/config.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_networking/dune
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_networking/mina_networking.mli
  src/lib/network_pool/batcher.ml
  src/lib/network_pool/batcher.mli
  src/lib/pipe_lib/strict_pipe.ml
  src/lib/pipe_lib/strict_pipe.mli
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/transition_chain_verifier/transition_chain_verifier.ml
  src/lib/transition_frontier/catchup_tree.ml
  src/lib/transition_frontier/dune
  src/lib/transition_frontier/full_catchup_tree.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_handler/processor.ml
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me

#7373 Uptime buckets in network health report
  automation/services/coda-network-services/make_report.py
Labels: ci-build-me, ready-to-merge

#7396 Compatible
  automation/services/coda-network-services/make_report.py
Labels: ci-build-me

#7399 Bump version, automation net services
  automation/services/coda-network-services/version.txt
Labels: ci-build-me, ready-to-merge

#7398 Extensional blocks output for missing subchains
  src/app/archive/archive_lib/extensional.ml
  src/app/missing_subchain/missing_subchain.ml
Labels: ci-build-me, ready-to-merge

#7403 Compatible
  src/app/archive/archive_lib/extensional.ml
  src/app/missing_subchain/missing_subchain.ml
Labels: ci-build-me

#7406 update coda-network-service's Dockerfile random_restart script ADD directive
  automation/services/coda-network-services/Dockerfile
Labels: ci-build-me

#7388 Set compatibility checks to run on compatible, not on develop
  buildkite/scripts/connect-to-testnet-on-develop.sh
  scripts/compare_ci_diff_types_develop.sh
Labels: ci-build-me

#7397 add CI job for building/releasing mina-toolchain Docker image
  buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall
  dockerfiles/Dockerfile-toolchain
Labels: ci-build-me

#7390 add buildkite agent entrypoint for gcloud/gke cluster setup
  automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
Labels: ci-build-me

#7425 Peer count in client status
  src/lib/daemon_rpcs/types.ml
Labels: ci-build-me, ready-to-merge

#7351 filter private addresses in CodaGatingState
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/codanet_test.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
Labels: ci-build-me

#7348 add Helm chart changelog (CHANGELOG.md and ArtifactHub change annotations) + shared Makefile
  buildkite/helm/buildkite-exporter/CHANGELOG.md
  buildkite/helm/buildkite-exporter/Chart.yaml
  buildkite/helm/buildkite-exporter/Makefile
  buildkite/helm/buildkite-exporter/README.md
  frontend/bot/helm/CHANGELOG.md
  frontend/bot/helm/Chart.yaml
  frontend/bot/helm/Makefile
  frontend/bot/helm/README.md
  frontend/leaderboard/helm/CHANGELOG.md
  frontend/leaderboard/helm/Chart.yaml
  frontend/leaderboard/helm/Makefile
  frontend/leaderboard/helm/README.md
  helm/archive-node/CHANGELOG.md
  helm/archive-node/Chart.yaml
  helm/archive-node/Makefile
  helm/archive-node/README.md
  helm/block-producer/CHANGELOG.md
  helm/block-producer/Chart.yaml
  helm/block-producer/Makefile
  helm/block-producer/README.md
  helm/common/CHANGELOG.md
  helm/common/Chart.yaml
  helm/common/Makefile
  helm/seed-node/CHANGELOG.md
  helm/seed-node/Chart.yaml
  helm/seed-node/Makefile
  helm/seed-node/README.md
  helm/snark-worker/CHANGELOG.md
  helm/snark-worker/Chart.yaml
  helm/snark-worker/Makefile
  helm/snark-worker/README.md
Labels: ci-build-me

#7427 build toolchain image on xlarge agents (up from large)
  buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall
Labels: ci-build-me

#7383 [HOTFIX] super catchup restart libp2p upload blocks
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/lib/downloader/downloader.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/network_pool/intf.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me

#7430 migrate automation alerting/monitoring from coda-automation
  automation/terraform/infrastructure/secrets.tf
  automation/terraform/infrastructure/templates/testnet-alert-receivers.yml.tpl
  automation/terraform/infrastructure/templates/testnet-alerts.yml.tpl
  automation/terraform/infrastructure/testnet-alerts.tf
  automation/terraform/infrastructure/us-central1.tf
  automation/terraform/infrastructure/us-east1.tf
  automation/terraform/infrastructure/us-east4.tf
  automation/terraform/infrastructure/us-west1.tf
Labels: ci-build-me

#7431 Add terraform to coda-toolchain
  dockerfiles/Dockerfile-toolchain
Labels: ci-build-me

#7447 Fix archive-precomputed-blocks
  src/lib/pickles/limb_vector/constant.ml
Labels: ci-build-me

#7441 Max observed block height
  src/lib/daemon_rpcs/types.ml
Labels: ci-build-me, ready-to-merge

#7445 Update constants file for new coda toolchain
  buildkite/src/Constants/ContainerImages.dhall
Labels: ci-build-me

#7277 Improve error printing
  src/app/cli/src/init/coda_run.ml
  src/lib/error_json/error_json.ml
Labels: ci-build-me, consider-for-release-candidate

#7356 Use patched OCaml compiler to log allocation size before out-of-memory messages
  dockerfiles/Dockerfile-rosetta
  scripts/setup-opam.sh
  src/opam.export
Labels: ci-build-me

#7248 Use a single hash in genesis ledger filenames for accounts
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: ci-build-me, consider-for-release-candidate

#7346 Fix transaction replacements
  src/app/cli/src/init/client.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/user_command_input/user_command_input.ml
  src/lib/user_command_input/user_command_input.mli
Labels: ci-build-me

#7470 Merge back to develop
  src/app/cli/src/init/client.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/user_command_input/user_command_input.ml
  src/lib/user_command_input/user_command_input.mli
Labels: ci-build-me

#7476 change all Ivar.fill to Ivar.fill_if_empty
  src/lib/block_producer/block_producer.ml
  src/lib/cache_lib/impl.ml
  src/lib/child_processes/child_processes.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/distributed_dsl/distributed_dsl.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/network_pool/batcher.ml
  src/lib/pipe_lib/broadcast_pipe.ml
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/timeout_lib/timeout_lib.ml
  src/lib/transition_frontier/extensions/transition_registry.ml
  src/lib/transition_frontier_controller/dune
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/processor.ml
Labels: ci-build-me

#7467 Hotfix/super catchup stall fix
  src/lib/downloader/downloader.ml
  src/lib/fake_network/fake_network.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_networking/mina_networking.mli
  src/lib/pipe_lib/broadcast_pipe.ml
  src/lib/pipe_lib/broadcast_pipe.mli
  src/lib/pipe_lib/strict_pipe.ml
  src/lib/pipe_lib/strict_pipe.mli
  src/lib/sync_handler/sync_handler.ml
  src/lib/transition_frontier/full_catchup_tree.ml
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me

#7483 Ivar.fill_if_empty -> Ivar.fill
  src/lib/block_producer/block_producer.ml
  src/lib/cache_lib/impl.ml
  src/lib/child_processes/child_processes.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/distributed_dsl/distributed_dsl.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/network_pool/batcher.ml
  src/lib/pipe_lib/broadcast_pipe.ml
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/timeout_lib/dune
  src/lib/timeout_lib/timeout_lib.ml
  src/lib/transition_frontier/extensions/transition_registry.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/processor.ml
Labels: ci-build-me

#7485 remove min fee delta for snarks
  src/lib/network_pool/snark_pool_diff.ml
Labels: ci-build-me

#7492 Fix: Don't use successor when calculating the ledger nonce
  src/lib/mina_lib/mina_lib.ml
Labels: ci-build-me

#7489 Fix CI: Bump opam cache version number
  .circleci/config.yml
  .circleci/config.yml.jinja
Labels: ci-build-me

#7494 Hotfix/long fork fix
  src/lib/consensus/global_slot.ml
  src/lib/consensus/global_slot.mli
  src/lib/consensus/proof_of_stake.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_networking/mina_networking.mli
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me

#7500 fix max observed block length
  src/lib/mina_commands/mina_commands.ml
  src/lib/network_pool/network_pool_base.ml
Labels: ci-build-me

#7493 Archive extensional blocks
  graphql_schema.json
  src/app/archive/archive_lib/extensional.ml
  src/app/archive/archive_lib/graphql_query/base_types.ml
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/rpc.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/missing_subchain/missing_subchain.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/archive_client.ml
  src/lib/mina_lib/archive_client.mli
Labels: ci-build-me, ready-to-merge

#7473 Add flags to log successful and failed blocks archive-precomputed-blocks
  src/app/cli/src/init/client.ml
Labels: ci-build-me

#7514 Inform user when CODA_PRIVKEY_PASS used
  src/app/generate_keypair/generate_keypair.ml
  src/lib/cli_lib/commands.ml
Labels: ci-build-me, ready-to-merge

#7516 Print or log when private-key password from env var
  src/app/cli/src/coda.ml
  src/lib/secrets/keypair_common.ml
Labels: ci-build-me, ready-to-merge

#7518 fix for catchup issue
  src/lib/ledger_catchup/super_catchup.ml
Labels: ci-build-me

#7519 User error for some faulty peer multiaddresses
  src/app/cli/src/coda.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
Labels: ci-build-me, ready-to-merge

#7533 OCaml memory stats, add fragments, mention bytes
  src/lib/memory_stats/memory_stats.ml
Labels: ci-build-me, ready-to-merge

#7532 Dune 2.8.1, no .merlin files
  Makefile
  README-dev.md
  scripts/merlin-fixup.sh
  src/opam.4.08.0.export
  src/opam.export
Labels: ci-build-me

#7546 Don't interpolate precomputed block
  src/lib/mina_lib/coda_subscriptions.ml
Labels: ci-build-me, ready-to-merge

#7537 OCaml heap fragments in metrics
  src/lib/mina_metrics/mina_metrics.ml
Labels: ci-build-me, ready-to-merge

#7554 Fix lints CI job
  scripts/compare_pr_diff_items.py
Labels: ci-build-me

#7562 fix a bug in downloader
  src/lib/downloader/downloader.ml
Labels: ci-build-me

#7557 Add a CI script to check PRs on compatible for conflicts with develop
  buildkite/scripts/merges-cleanly-to-develop.sh
  buildkite/src/Jobs/Lint/Merge.dhall
Labels: ci-build-me

#7568 do not invalidate cached item twice
  src/lib/transition_handler/processor.ml
Labels: ci-build-me

#7575 Ivar.fill crash fix: Remove outstanding_requests ivars during libp2p_helper shutdown/restart
  src/lib/mina_net2/mina_net2.ml
Labels: ci-build-me

#7561 Update and fix integration test framework
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/kubernetes/testnet/testnet-artifacts.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/app/test_executive/peers_test.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/key_cache/key_cache.ml
Labels: ci-build-me

#7551 call Gc.compact periodically
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/fake_hash.mlh
  src/config/fuzz_medium.mlh
  src/config/fuzz_small.mlh
  src/config/nonconsensus_medium_curves.mlh
  src/config/print_versioned_types.mlh
  src/config/test_archive_processor.mlh
  src/config/test_postake.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_full_epoch.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_three_producers.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_producers.mlh
  src/config/testnet_postake_many_producers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/lib/block_producer/block_producer.ml
  src/lib/mina_compile_config/mina_compile_config.ml
  src/lib/mina_lib/mina_lib.ml
Labels: ci-build-me, ready-to-merge

#7548 Block query in GraphQL
  graphql_schema.json
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me, ready-to-merge

#7583 Print version in generate-keypair
  src/app/cli/src/coda.ml
  src/app/generate_keypair/dune
  src/app/generate_keypair/generate_keypair.ml
  src/lib/mina_version/dune
  src/lib/mina_version/gen.sh
  src/lib/mina_version/mina_version.mli
Labels: ci-build-me, ready-to-merge

#7511 Fixes for one command deploy
  automation/scripts/generate-keys-and-ledger.sh
  automation/scripts/upload-keys-k8s.sh
  automation/terraform/modules/kubernetes/testnet/testnet-artifacts.tf
Labels: ci-build-me

#7592 Height input to block query
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me, ready-to-merge

#7603 update default CI k8s ctx and tooling
  automation/terraform/modules/kubernetes/buildkite-agent/google_cloud.tf
  automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
  automation/terraform/modules/kubernetes/buildkite-agent/secrets.tf
  automation/terraform/modules/kubernetes/buildkite-agent/variables.tf
Labels: ci-build-me

#7602 Mina integration nonpreemptibles
  automation/terraform/infrastructure/alerts.tf
  automation/terraform/infrastructure/us-west1.tf
Labels: ci-build-me

#7605 log file for rejected blocks
  src/app/cli/src/coda.ml
  src/lib/block_producer/block_producer.ml
  src/lib/logger/impl.ml
  src/lib/logger/impl.mli
  src/lib/logger/logger.ml
  src/lib/transition_frontier/extensions/best_tip_diff.ml
  src/lib/transition_router/initial_validator.ml
Labels: ci-build-me

#7595 Watchdog
  automation/scripts/restart-coda-network-services.sh
  automation/services/coda-network-services/Makefile
  automation/services/coda-network-services/README.md
  automation/services/coda-network-services/version.txt
  automation/services/watchdog/Dockerfile
  automation/services/watchdog/Makefile
  automation/services/watchdog/README.md
  automation/services/watchdog/entrypoints/00-gcloud-auth-setup.sh
  automation/services/watchdog/main.sh
  automation/services/watchdog/make_report.py
  automation/services/watchdog/requirements.txt
  automation/services/watchdog/scripts/entrypoint.sh
  automation/services/watchdog/scripts/network-utilities.py
  automation/services/watchdog/version.txt
  automation/terraform/infrastructure/us-east4.tf
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/kubernetes/testnet/testnet-artifacts.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/testnets/watchdog-test/community_fast_locked_keys.json
  automation/terraform/testnets/watchdog-test/fish.json
  automation/terraform/testnets/watchdog-test/genesis_ledger.json
  automation/terraform/testnets/watchdog-test/main.tf
  automation/terraform/testnets/watchdog-test/whales.json
  helm/seed-node/templates/seed-node.yaml
  helm/watchdog/.helmignore
  helm/watchdog/CHANGELOG.md
  helm/watchdog/Chart.lock
  helm/watchdog/Chart.yaml
  helm/watchdog/Makefile
  helm/watchdog/README.md
  helm/watchdog/charts/common-utilities-0.0.7.tgz
  helm/watchdog/templates/watchdog.yaml
  helm/watchdog/values.yaml
Labels: ci-build-me, ready-to-merge

#7599 Make next_producer_timing calculations async
  src/lib/block_producer/block_producer.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me

#7611 Handle WNOHANG exceptions from verifier and libp2p_helper processes
  src/lib/child_processes/child_processes.ml
  src/lib/child_processes/child_processes.mli
  src/lib/child_processes/dune
  src/lib/mina_net2/mina_net2.ml
  src/lib/verifier/prod.ml
Labels: ci-build-me

#7544 Wait for improvements
  src/app/test_executive/block_production_test.ml
  src/app/test_executive/block_production_test_timed_accounts.ml
  src/app/test_executive/bootstrap_test.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/integration_test_lib/integration_test_lib.ml
Labels: ci-build-me, ready-to-merge

#7604 Add validatePayment command to GraphQL + validate signed payments in rosetta
  graphql_schema.json
  src/app/rosetta/lib/construction.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/rosetta_lib/errors.ml
Labels: ci-build-me

#7617 Validate keypair app and command
  buildkite/scripts/build-artifact.sh
  scripts/rebuild-deb.sh
  src/app/cli/src/init/client.ml
  src/app/validate_keypair/dune
  src/app/validate_keypair/validate_keypair.ml
  src/lib/cli_lib/commands.ml
  src/validate_keypair.opam
Labels: ci-build-me, ready-to-merge

#7609 minor changes to intg tests
  src/app/test_executive/peers_test.ml
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
Labels: ci-build-me, ready-to-merge

#7637 fix intg timing bug
  src/app/test_executive/peers_test.ml
  src/lib/integration_test_cloud_engine/coda_automation.ml
Labels: ci-build-me, ready-to-merge

#7646 Missing subchains, use new schema
  src/app/archive/archive_lib/processor.ml
  src/app/missing_subchain/missing_subchain.ml
Labels: ci-build-me, ready-to-merge

#7512 Client SDK: Added functionality to get public key from private key
  frontend/client_sdk/src/CodaSDK.d.ts
  frontend/client_sdk/src/CodaSDK.re
  frontend/client_sdk/test/Test.ts
Labels: ci-build-me, ready-to-merge

#7635 Add list of levels to -log-level
  src/lib/cli_lib/flag.ml
Labels: ci-build-me

#7673 Fix for local net script, redux
  automation/scripts/testnet-keys.py
  scripts/run_local_network.sh
  src/config/dev.mlh
Labels: ci-build-me, ready-to-merge

#7672 Verify cmds before recursively adding to the pool, throw useful errors
  src/lib/network_pool/indexed_pool.ml
Labels: ci-build-me

#7693 [Trivial] Add commit_id to error_to_json
  src/lib/error_json/dune
  src/lib/error_json/error_json.ml
Labels: ci-build-me

#7696 Explain some terminating signals
  src/app/cli/src/coda.ml
  src/lib/child_processes/termination.ml
Labels: ci-build-me, ready-to-merge

#7695 Archive_blocks app
  Makefile
  buildkite/scripts/ci-archive-release.sh
  scripts/archive/build-release-archives.sh
  src/app/archive/archive_lib/processor.ml
  src/app/archive_blocks/archive_blocks.ml
  src/app/archive_blocks/dune
  src/archive_blocks.opam
Labels: ci-build-me, ready-to-merge

#6133 [Snapps] Fix: Don't throw an exception on snapp commands with zero transfer
  src/lib/network_pool/indexed_pool.ml
Labels: ci-build-me

#7669 Fix a segfault: Use reference counted pointers for CamlPointer
  src/lib/marlin_plonk_bindings/stubs/src/caml_pointer.rs
Labels: ci-build-me

#7607 Add buildkite dhall command for deploying testnets and ci deployment test
  automation/scripts/generate-keys-and-ledger.sh
  automation/scripts/upload-keys-k8s.sh
  automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
  automation/terraform/modules/kubernetes/testnet/testnet-artifacts.tf
  automation/terraform/testnets/ci-net/main.tf
  buildkite/src/Command/DeployTestnet.dhall
  buildkite/src/Jobs/Release/ArchiveNodeArtifact.dhall
  buildkite/src/Jobs/Release/MinaArtifact.dhall
  buildkite/src/Jobs/Test/ConnectToTestnet.dhall
  buildkite/src/Jobs/Test/DeployTestnetAndDestroy.dhall
  helm/block-producer/values.yaml
Labels: ci-build-me

#7705 Fix error when expired transactions are replaced in the pool
  src/lib/network_pool/indexed_pool.ml
Labels: ci-build-me

#7644 add installation of NodeJS tooling and build of coda-network tool to Buildkite agents
  automation/terraform/modules/kubernetes/buildkite-agent/helm.tf
Labels: ci-build-me

#7704 Upgrade to dune 2.8.2
  src/opam.export
Labels: ci-build-me, ready-to-merge

#7722 Adds mina-pr-gating to required status in mergify.yml
  .mergify.yml
  scripts/test.py
Labels: ci-build-me, ready-to-merge

#7717 Async list map for `best_chain` GraphQL query
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me, ready-to-merge

#7707 archive node retries
  src/app/archive/archive_lib/processor.ml
  src/app/archive_blocks/archive_blocks.ml
Labels: ci-build-me

#7698 Add validate-transaction command
  src/app/cli/src/init/client.ml
  src/lib/cli_lib/commands.ml
  src/lib/cli_lib/dune
  src/lib/rosetta_lib/errors.ml
  src/lib/rosetta_lib/user_command_info.ml
Labels: ci-build-me

#7710 use terraform workspaces for managing CI deployment states
  automation/scripts/generate-keys-and-ledger.sh
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/modules/kubernetes/testnet/testnet-artifacts.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/testnets/ci-net/main.tf
  buildkite/src/Command/DeployTestnet.dhall
  buildkite/src/Jobs/Test/DeployTestnetAndDestroy.dhall
Labels: ci-build-me

#7677 Add a prometheus metric for recent cluster crashes to watchdog
  automation/services/watchdog/metrics.py
  automation/services/watchdog/requirements.txt
  automation/services/watchdog/util.py
  automation/services/watchdog/version.txt
  automation/services/watchdog/watchdog.py
  automation/terraform/modules/kubernetes/testnet/helm.tf
  automation/terraform/testnets/watchdog-test/main.tf
  helm/watchdog/templates/watchdog.yaml
  helm/watchdog/values.yaml
Labels: ci-build-me, ready-to-merge
