Repository MinaProtocol/mina, pull requests merged in 2022-04, with the labels that each got.

#10596 [zkApps renaming] snapp_account
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/app/replayer/replayer.ml
  src/app/test_executive/zkapps.ml
  src/app/test_executive/zkapps_timing.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/app/zkapp_test_transaction/zkapp_test_transaction.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/mina_base/account.ml
  src/lib/mina_base/ledger_hash0.mli
  src/lib/mina_base/mina_base.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/snapp_predicate.ml
  src/lib/mina_base/transaction_status.ml
  src/lib/mina_base/zkapp_account.ml
  src/lib/mina_generators/snapp_generators.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/transaction_consistency_tests/transaction_consistency_tests.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_snark/test/account_timing/account_timing.ml
  src/lib/transaction_snark/test/fee_payer/fee_payer.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/snapp_deploy/snapp_deploy.ml
  src/lib/transaction_snark/test/snapp_payments/snapp_payments.ml
  src/lib/transaction_snark/test/test_snapp_update.ml
  src/lib/transaction_snark/test/transaction_union/transaction_union.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/test/verification_key/verification_key.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/nonconsensus/mina_base/mina_base_nonconsensus.ml
  src/nonconsensus/mina_base/snapp_account.ml
Labels: ci-build-me

#10583 zkApps basic functionality test
  src/lib/transaction_snark/test/zkapps_examples/empty_update/dune
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/zkapps_examples/empty_update/dune
  src/lib/zkapps_examples/empty_update/zkapps_empty_update.ml
Labels: ci-build-me

#10597 [zkApps renaming] snapp_generators and snapp_version
  src/app/archive/archive_lib/test.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/mina_base/zkapp_account.ml
  src/lib/mina_generators/parties_generators.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/mina_numbers/mina_numbers.ml
  src/lib/mina_numbers/zkapp_version.ml
  src/lib/mina_numbers/zkapp_version.mli
  src/lib/network_pool/transaction_pool.ml
  src/lib/runtime_config/runtime_config.ml
  src/nonconsensus/mina_numbers/snapp_version.ml
  src/nonconsensus/mina_numbers/zkapp_version.ml
  src/nonconsensus/mina_numbers/zkapp_version.mli
Labels: ci-build-me

#10673 fix gossip consistency
  src/app/test_executive/gossip_consistency.ml
Labels: ci-build-me

#10599 [zkApps renaming] snapp test update
  src/lib/transaction_snark/test/app_state/app_state.ml
  src/lib/transaction_snark/test/delegate/delegate.ml
  src/lib/transaction_snark/test/permissions/permissions.ml
  src/lib/transaction_snark/test/test_zkapp_update.ml
  src/lib/transaction_snark/test/token_symbol/token_symbol.ml
  src/lib/transaction_snark/test/verification_key/verification_key.ml
  src/lib/transaction_snark/test/voting_for/voting_for.ml
  src/lib/transaction_snark/test/zkapp_uri/zkapp_uri.ml
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/zkapps_examples/empty_update/zkapps_empty_update.ml
Labels: ci-build-me

#10600 [zkApps renaming] snapp_ppredicate
  src/app/archive/archive_lib/processor.ml
  src/app/archive/drop_tables.sql
  src/app/archive/zkapp_tables.sql
  src/app/client_sdk/client_sdk.ml
  src/app/client_sdk/js_util.ml
  src/app/replayer/replayer.ml
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/mina_base/mina_base.ml
  src/lib/mina_base/parties.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/sparse_ledger_base.ml
  src/lib/mina_base/sparse_ledger_base.mli
  src/lib/mina_base/zkapp_precondition.ml
  src/lib/mina_generators/parties_generators.ml
  src/lib/mina_ledger/ledger.mli
  src/lib/mina_state/protocol_state.ml
  src/lib/mina_state/protocol_state.mli
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/transaction_union/transaction_union.ml
  src/lib/transaction_snark/test/zkapp_deploy/dune
  src/lib/transaction_snark/test/zkapp_deploy/zkapp_deploy.ml
  src/lib/transaction_snark/test/zkapp_payments/dune
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/transaction_snark/transaction_validator.mli
  src/lib/verifier/common.ml
  src/lib/zkapps_examples/empty_update/zkapps_empty_update.ml
Labels: ci-build-me

#10658 [zkApps renaming] account fields
  src/app/test_executive/zkapps.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/mina_base/account.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_base/zkapp_account.ml
  src/lib/mina_base/zkapp_precondition.ml
  src/lib/mina_generators/parties_generators.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_logic/parties_logic.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10660 [zkApps renaming] graphQL, cli, snapps-test-tool
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/test_executive/test_common.ml
  src/app/test_executive/zkapps.ml
  src/app/test_executive/zkapps_timing.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/app/zkapp_test_transaction/zkapp_test_transaction.ml
  src/lib/generated_graphql_queries/gen/gen.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#10661 [zkApps renaming] random oracle prefixes
  buildkite/src/Command/MinaArtifact.dhall
  helm/archive-node/values.yaml
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/signed_command_memo.ml
  src/lib/mina_base/zkapp_account.ml
Labels: ci-build-me

#10696 fail zkapps test sooner
  src/app/test_executive/test_common.ml
  src/app/test_executive/zkapps.ml
Labels: ci-build-me

#10703 Update links in description.md
  docs/specs/signatures/description.md
Labels: ci-build-me

#10672 Add zkApps timing tests
  src/lib/mina_base/state_hash.ml
  src/lib/transaction_snark/test/account_timing/account_timing.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/test/util.mli
  src/lib/transaction_snark/test/zkapp_deploy/zkapp_deploy.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
Labels: ci-build-me

#10705 Merge georgeee/bitswap new topics to develop
  docs/specs/signatures/description.md
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/app.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/message_id_test.go
  src/app/libp2p_helper/src/libp2p_helper/multinode_test.go
  src/app/libp2p_helper/src/libp2p_helper/pubsub_msg.go
  src/app/libp2p_helper/src/libp2p_helper/pubsub_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/upcall_test.go
  src/lib/cli_lib/arg_type.ml
  src/lib/cli_lib/default.ml
  src/lib/cli_lib/dune
  src/lib/gossip_net/any.ml
  src/lib/gossip_net/fake.ml
  src/lib/gossip_net/intf.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/mina_net2/tests/all_ipc.ml
  src/lib/mina_net2/tests/tests.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_networking/mina_networking.mli
  src/libp2p_ipc/ipc.ml
  src/libp2p_ipc/libp2p_ipc.capnp
  src/libp2p_ipc/libp2p_ipc.ml
  src/libp2p_ipc/libp2p_ipc.mli
Labels: ci-build-me

#10649 Bitswap: support new and old gossip topics simultaneously
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/app.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/multinode_test.go
  src/app/libp2p_helper/src/libp2p_helper/pubsub_msg.go
  src/app/libp2p_helper/src/libp2p_helper/pubsub_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/upcall_test.go
  src/lib/cli_lib/arg_type.ml
  src/lib/cli_lib/default.ml
  src/lib/cli_lib/dune
  src/lib/gossip_net/any.ml
  src/lib/gossip_net/fake.ml
  src/lib/gossip_net/intf.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/mina_net2/tests/all_ipc.ml
  src/lib/mina_net2/tests/tests.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_networking/mina_networking.mli
  src/libp2p_ipc/ipc.ml
  src/libp2p_ipc/libp2p_ipc.capnp
  src/libp2p_ipc/libp2p_ipc.ml
  src/libp2p_ipc/libp2p_ipc.mli
Labels: ci-build-me

#10695 [RFC] Add zkApp information to archive database
  rfcs/0045-zkapp-balance-data-in-archive.md
Labels: ci-build-me

#9712 Delegation backend: new storage structure
  src/app/delegation_backend/README.md
  src/app/delegation_backend/src/constants.go
  src/app/delegation_backend/src/data.go
  src/app/delegation_backend/src/delegation_backend/main.go
  src/app/delegation_backend/src/delegation_backend_migrate/main.go
  src/app/delegation_backend/src/delegation_backend_migrate/main_test.go
  src/app/delegation_backend/src/go.mod
  src/app/delegation_backend/src/go.sum
  src/app/delegation_backend/src/sheets.go
  src/app/delegation_backend/src/submit.go
  src/app/delegation_backend/src/submit_test.go
Labels: ci-build-me

#10683 [zkApps renaming] account and protocol state predicates
  frontend/mina-signer/tests/party.test.ts
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/archive/drop_tables.sql
  src/app/archive/zkapp_tables.sql
  src/app/client_sdk/client_sdk.ml
  src/app/client_sdk/js_util.ml
  src/app/replayer/replayer.ml
  src/app/test_executive/zkapps.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/mina_base/parties.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/zkapp_precondition.ml
  src/lib/mina_generators/parties_generators.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_logic/parties_logic.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/verifier/common.ml
  src/lib/zkapps_examples/empty_update/zkapps_empty_update.ml
Labels: ci-build-me

#10713 Merge georgeee/remove valid callback out of block to develop
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/bootstrap_controller.mli
  src/lib/bootstrap_controller/dune
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_handler/validator.ml
  src/lib/transition_router/initial_validator.ml
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me

#10684 Remove validation_callback out of block type
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/bootstrap_controller.mli
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_handler/validator.ml
  src/lib/transition_router/initial_validator.ml
  src/lib/transition_router/transition_router.ml
Labels: ci-build-me

#10706 Remove Party.Predicated
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/archive/create_schema.sql
  src/app/archive/zkapp_tables.sql
  src/app/client_sdk/client_sdk.ml
  src/app/client_sdk/js_util.ml
  src/app/replayer/replayer.ml
  src/app/test_executive/zkapps.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/mina_base/parties.ml
  src/lib/mina_base/party.ml
  src/lib/mina_generators/parties_generators.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/verifier/common.ml
  src/lib/zkapps_examples/empty_update/zkapps_empty_update.ml
Labels: ci-build-me

#10665 handle duplicate transactions in the pool
  src/app/test_executive/zkapps.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#10718 Merge compatible into develop
  src/app/delegation_backend/README.md
  src/app/delegation_backend/src/constants.go
  src/app/delegation_backend/src/data.go
  src/app/delegation_backend/src/delegation_backend/main.go
  src/app/delegation_backend/src/delegation_backend_migrate/main.go
  src/app/delegation_backend/src/delegation_backend_migrate/main_test.go
  src/app/delegation_backend/src/go.mod
  src/app/delegation_backend/src/go.sum
  src/app/delegation_backend/src/sheets.go
  src/app/delegation_backend/src/submit.go
  src/app/delegation_backend/src/submit_test.go
Labels: ci-build-me

#10723 Breadcrumb wait for develop
  src/app/test_executive/delegation_test.ml
  src/app/test_executive/dune
  src/app/test_executive/gossip_consistency.ml
  src/app/test_executive/payments_test.ml
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/dune
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/dune
  src/lib/integration_test_lib/event_type.ml
  src/lib/integration_test_lib/event_type.mli
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/network_state.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me

#10702 breadcrumb wait for not working
  src/app/test_executive/delegation_test.ml
  src/app/test_executive/gossip_consistency.ml
  src/app/test_executive/payments_test.ml
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/event_type.ml
  src/lib/integration_test_lib/event_type.mli
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/network_state.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me

#10654 Make Client SDK work w/o Wasm
  Makefile
  src/app/client_sdk/dune
  src/app/client_sdk/tests/test_hash.js
  src/lib/crypto/kimchi_bindings/js/chrome/dune
  src/lib/crypto/kimchi_bindings/js/js_backend/bigint256.js
  src/lib/crypto/kimchi_bindings/js/js_backend/bigint_helpers.js
  src/lib/crypto/kimchi_bindings/js/js_backend/dune
  src/lib/crypto/kimchi_bindings/js/js_backend/elliptic_curve.js
  src/lib/crypto/kimchi_bindings/js/js_backend/finite_field.js
  src/lib/crypto/kimchi_bindings/js/js_backend/vector.js
  src/lib/mina_base/proof.ml
  src/lib/pickles/side_loaded_verification_key.ml
  src/lib/pickles/step.ml
  src/lib/pickles/unfinalized.ml
  src/lib/random_oracle/dune
  src/lib/random_oracle/permutation/dune
  src/lib/random_oracle/permutation/external/dune
  src/lib/random_oracle/permutation/external/random_oracle_permutation.ml
  src/lib/random_oracle/permutation/ocaml/dune
  src/lib/random_oracle/permutation/ocaml/random_oracle_permutation.ml
  src/lib/random_oracle/permutation/random_oracle_permutation.mli
  src/lib/random_oracle/random_oracle.ml
Labels: ci-build-me

#10655 Expose verifier index and proof as JSON via GraphQL
  graphql_schema.json
  src/lib/mina_base/proof.ml
  src/lib/mina_base/proof.mli
  src/lib/mina_graphql/dune
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/pickles/pickles.mli
  src/lib/pickles/proof.ml
  src/lib/pickles/verification_key.ml
  src/lib/pickles_base/domains.ml
  src/lib/verifier/dummy.ml
  src/lib/verifier/prod.ml
  src/lib/verifier/verifier_intf.ml
Labels: ci-build-me

#10679 Add merkle path GraphQL endpoint
  graphql_schema.json
  src/lib/mina_graphql/mina_graphql.ml
Labels: ready-to-merge, ci-build-me

#10566 [nix prep] libp2p: allow disabling MDNS test
  src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
Labels: ci-build-me, Tweag

#10574 frontend/leaderboard: update yarn.lock
  frontend/leaderboard/.npmignore
  frontend/leaderboard/package.json
  frontend/leaderboard/src/Bindings.re
  frontend/leaderboard/yarn.lock
Labels: ci-build-me, Tweag

#10737 Wait for snark coordinator initialization in zkapps test
  src/app/test_executive/zkapps.ml
Labels: ci-build-me

#10742 bump berkeley genesis timestamp
  genesis_ledgers/berkeley.json
Labels: ci-build-me

#10743 Add `previous_empty_accounts` to `Parties_applied.t`
  src/lib/mina_ledger/ledger.mli
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
Labels: ci-build-me

#10686 Test expired zkapp
  src/app/test_executive/zkapps.ml
  src/app/test_executive/zkapps_timing.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/mina_base/zkapp_precondition.ml
  src/lib/network_pool/dune
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_snark/test/account_timing/account_timing.ml
  src/lib/transaction_snark/test/fee_payer/fee_payer.ml
  src/lib/transaction_snark/test/test_zkapp_update.ml
  src/lib/transaction_snark/test/zkapp_deploy/zkapp_deploy.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/verifier/common.ml
  src/lib/verifier/dummy.ml
  src/lib/verifier/prod.ml
  src/lib/verifier/verifier_intf.ml
Labels: ci-build-me

#10745 Merge `georgeee/split-block-header-body` to `develop`
  frontend/leaderboard/.npmignore
  frontend/leaderboard/package.json
  frontend/leaderboard/src/Bindings.re
  frontend/leaderboard/yarn.lock
  src/app/archive/archive_lib/diff.ml
  src/app/archive/archive_lib/processor.ml
  src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
  src/lib/block_producer/block_producer.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/gossip_net/message.ml
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_transition/block.ml
  src/lib/mina_transition/block.mli
  src/lib/mina_transition/body.ml
  src/lib/mina_transition/body.mli
  src/lib/mina_transition/body_reference.ml
  src/lib/mina_transition/body_reference.mli
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/mina_transition/header.ml
  src/lib/mina_transition/header.mli
  src/lib/protocol_version/dune
  src/lib/protocol_version/protocol_version.ml
  src/lib/protocol_version/protocol_version.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/persistent_frontier/database.ml
  src/lib/uptime_service/uptime_service.ml
Labels: ci-build-me

#10741 Add `accounts_accessed`, `accounts_created` to archive RPC
  rfcs/0045-zkapp-balance-data-in-archive.md
  src/app/archive/archive_lib/diff.ml
  src/app/archive/archive_lib/extensional.ml
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/archive/create_schema.sql
  src/app/archive/zkapp_tables.sql
  src/app/archive_blocks/archive_blocks.ml
  src/app/extract_blocks/extract_blocks.ml
  src/app/extract_blocks/sql.ml
  src/app/replayer/replayer.ml
  src/lib/block_producer/block_producer.ml
  src/lib/mina_base/transaction_status.ml
  src/lib/mina_caqti/mina_caqti.ml
  src/lib/mina_ledger/ledger.mli
  src/lib/mina_lib/archive_client.ml
  src/lib/mina_lib/archive_client.mli
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/mina_lib/mina_subscriptions.ml
  src/lib/mina_transition/dune
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/mina_transition/external_transition_sample_precomputed_block.ml
  src/lib/parallel_scan/parallel_scan.ml
  src/lib/parallel_scan/parallel_scan.mli
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
Labels: ci-build-me

#10642 Test/insufficient funds for zkapps
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/test/util.mli
  src/lib/transaction_snark/test/zkapp_payments/dune
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
Labels: ci-build-me

#10757 Merge fix replayer test to develop
  buildkite/scripts/connect-to-mainnet-on-compatible.sh
  buildkite/scripts/replayer-test.sh
Labels: ci-build-me

#10758 Try to fix replayer and conenct to mainnet tests
  buildkite/scripts/connect-to-mainnet-on-compatible.sh
  buildkite/scripts/replayer-test.sh
Labels: ci-build-me

#10715 Remove balances and account creation fees from Transaction_status.t
  rfcs/0045-zkapp-balance-data-in-archive.md
  src/app/archive/archive_lib/diff.ml
  src/app/archive/archive_lib/extensional.ml
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/test.ml
  src/app/archive/create_schema.sql
  src/app/archive/zkapp_tables.sql
  src/app/archive_blocks/archive_blocks.ml
  src/app/extract_blocks/extract_blocks.ml
  src/app/extract_blocks/sql.ml
  src/app/replayer/replayer.ml
  src/lib/block_producer/block_producer.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/mina_base/transaction_status.ml
  src/lib/mina_caqti/mina_caqti.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_ledger/ledger.mli
  src/lib/mina_lib/archive_client.ml
  src/lib/mina_lib/archive_client.mli
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/mina_lib/mina_subscriptions.ml
  src/lib/mina_transition/dune
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/mina_transition/external_transition_sample_precomputed_block.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/parallel_scan/parallel_scan.ml
  src/lib/parallel_scan/parallel_scan.mli
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/staged_ledger_diff/staged_ledger_diff.ml
  src/lib/staged_ledger_diff/staged_ledger_diff.mli
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_snark/test/account_timing/account_timing.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
Labels: ci-build-me

#10727 Introduce a new block type
  src/app/archive/archive_lib/diff.ml
  src/app/archive/archive_lib/processor.ml
  src/lib/block_producer/block_producer.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/gossip_net/message.ml
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_transition/block.ml
  src/lib/mina_transition/block.mli
  src/lib/mina_transition/body.ml
  src/lib/mina_transition/body.mli
  src/lib/mina_transition/body_reference.ml
  src/lib/mina_transition/body_reference.mli
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/mina_transition/header.ml
  src/lib/mina_transition/header.mli
  src/lib/protocol_version/dune
  src/lib/protocol_version/protocol_version.ml
  src/lib/protocol_version/protocol_version.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/persistent_frontier/database.ml
  src/lib/uptime_service/uptime_service.ml
Labels: ci-build-me

#10733 Deb s3 atomic upload compatible
  buildkite/src/Constants/ContainerImages.dhall
  dockerfiles/stages/3-toolchain
Labels: ci-build-me, Tweag

#10768 Use LLD as a linker / develop
  buildkite/src/Constants/ContainerImages.dhall
  dockerfiles/stages/1-build-deps
  src/dune.flags.inc
  src/external/ocaml-rocksdb/dune
  src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
Labels: ci-build-me

#10762 Use LLD as a linker
  buildkite/src/Constants/ContainerImages.dhall
  dockerfiles/stages/1-build-deps
  src/dune.flags.inc
  src/external/ocaml-rocksdb/dune
  src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
Labels: ci-build-me

#10657 [Trivial] Fixup demo mode
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
Labels: ci-build-me

#10584 Test/insufficient fee and invalid proof
  src/app/test_executive/payments_test.ml
  src/app/test_executive/zkapps.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
Labels: ci-build-me

#10770 Temporarily revert LLD linking
  src/dune.flags.inc
  src/external/ocaml-rocksdb/dune
  src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
Labels: ci-build-me

#10771 Temporarily revert LLD linking, develop
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/dune.flags.inc
  src/external/ocaml-rocksdb/dune
  src/external/ocaml-rocksdb/rocks_linker_flags_gen.ml
Labels: ci-build-me

#10774 Fixup replay protection logic
  src/lib/mina_base/party.ml
  src/lib/mina_base/transaction_status.ml
  src/lib/mina_base/zkapp_basic.ml
  src/lib/mina_base/zkapp_precondition.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_logic/parties_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10779 Merge catchup double cache invalidation fix into develop
  src/lib/cache_lib/impl.ml
  src/lib/cache_lib/intf.ml
  src/lib/transition_frontier/full_catchup_tree.ml
  src/lib/transition_handler/unprocessed_transition_cache.ml
Labels: ci-build-me

#10751 extra genesis accounts for intg test framework DEVELOP
  src/app/test_executive/block_production_priority.ml
  src/app/test_executive/chain_reliability_test.ml
  src/app/test_executive/delegation_test.ml
  src/app/test_executive/gossip_consistency.ml
  src/app/test_executive/payments_test.ml
  src/app/test_executive/peers_reliability_test.ml
  src/app/test_executive/zkapps.ml
  src/app/test_executive/zkapps_timing.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/test_config.ml
Labels: ci-build-me

#10739 extra genesis accounts for intg test framework
  src/app/test_executive/block_production_priority.ml
  src/app/test_executive/chain_reliability_test.ml
  src/app/test_executive/delegation_test.ml
  src/app/test_executive/gossip_consistency.ml
  src/app/test_executive/payments_test.ml
  src/app/test_executive/peers_reliability_test.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/test_config.ml
Labels: ci-build-me

#10769 Fix catchup double cache invalidation
  src/lib/cache_lib/impl.ml
  src/lib/cache_lib/intf.ml
  src/lib/transition_frontier/full_catchup_tree.ml
  src/lib/transition_handler/unprocessed_transition_cache.ml
Labels: ci-build-me

#10775 Uptime service, retry on connection errors when sending block
  src/lib/uptime_service/uptime_service.ml
Labels: ci-build-me

#10736 Rework how the parties commitments are computed
  src/app/client_sdk/client_sdk.ml
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/mina_base/parties.ml
  src/lib/mina_generators/parties_generators.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_logic/parties_logic.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/verifier/common.ml
Labels: ci-build-me

#10663 Add bitswap block encoding/decoding to ocaml (merge into develop)
  src/app/libp2p_helper/src/libp2p_helper/bitswap_block.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_block_test.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_msg.go
  src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go
  src/app/libp2p_helper/src/libp2p_helper/msg.go
  src/lib/blake2/blake2.ml
  src/lib/blake2/dune
  src/lib/blake2/intf.ml
  src/lib/mina_net2/bitswap_block.ml
  src/lib/mina_net2/dune
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/uptime_service/uptime_service.ml
  src/libp2p_ipc/dune
  src/libp2p_ipc/libp2p_ipc.capnp
  src/libp2p_ipc/libp2p_ipc.ml
  src/libp2p_ipc/rpcs.ml
  src/libp2p_ipc/rpcs.mli
Labels: ci-build-me, proj-network-stability

#10568 [nix prep] trace-tool: use newer cargo version, update Cargo.lock
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/Jobs/Lint/Rust.dhall
  buildkite/src/Jobs/Release/TraceTool.dhall
  src/app/trace-tool/Cargo.lock
Labels: ci-build-me, Tweag

#10579 Add bitswap block encoding/decoding to ocaml
  src/app/libp2p_helper/src/libp2p_helper/bitswap_block.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_block_test.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_msg.go
  src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go
  src/app/libp2p_helper/src/libp2p_helper/msg.go
  src/lib/blake2/blake2.ml
  src/lib/blake2/dune
  src/lib/blake2/intf.ml
  src/lib/mina_net2/bitswap_block.ml
  src/lib/mina_net2/dune
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/libp2p_ipc/dune
  src/libp2p_ipc/libp2p_ipc.capnp
  src/libp2p_ipc/libp2p_ipc.ml
  src/libp2p_ipc/rpcs.ml
  src/libp2p_ipc/rpcs.mli
Labels: ci-build-me, proj-network-stability

#10790 Merge "Fix duplicate block bug" into develop
  src/lib/transition_frontier/full_frontier/full_frontier.ml
Labels: ci-build-me

#10735 Fix duplicate block bug
  src/lib/transition_frontier/full_frontier/full_frontier.ml
Labels: bug, ci-build-me

#10783 zkapps account and protocol state precondition tests
  src/app/test_executive/zkapps.ml
  src/app/test_executive/zkapps_timing.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/mina_base/permissions.ml
  src/lib/mina_base/zkapp_precondition.ml
  src/lib/mina_generators/parties_generators.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_snark/test/account_timing/account_timing.ml
  src/lib/transaction_snark/test/fee_payer/fee_payer.ml
  src/lib/transaction_snark/test/party_preconditions/dune
  src/lib/transaction_snark/test/party_preconditions/party_preconditions.ml
  src/lib/transaction_snark/test/test_zkapp_update.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/test/util.mli
  src/lib/transaction_snark/test/zkapp_deploy/zkapp_deploy.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ci-build-me

#10567 [nix prep] buildkite: allow passing --privileged to docker
  buildkite/src/Command/Docker/Type.dhall
  buildkite/src/Lib/Cmds.dhall
Labels: ci-build-me, Tweag

#10791 Distinguish docs in "zkapp-account-key" uses
  src/app/zkapp_test_transaction/lib/commands.ml
  src/app/zkapp_test_transaction/zkapp_test_transaction.ml
Labels: ci-build-me

#10802 fix unit test in develop
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/Jobs/Lint/Rust.dhall
  buildkite/src/Jobs/Release/TraceTool.dhall
  src/app/trace-tool/Cargo.lock
  src/app/trace-tool/Cargo.toml
  src/lib/transaction_snark/test/party_preconditions/party_preconditions.ml
Labels: ci-build-me

#10803 Explicit genesis configs dev
  README-dev.md
  buildkite/src/Command/Docker/Type.dhall
  buildkite/src/Lib/Cmds.dhall
  src/app/test_executive/README.md
  src/app/test_executive/payments_test.ml
  src/app/test_executive/zkapps.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/wait_condition.ml
Labels: ci-build-me

#10805 Merge back to develop
  buildkite/src/Command/Docker/Type.dhall
  buildkite/src/Lib/Cmds.dhall
Labels: ci-build-me

#10785 Explicit genesis configs
  README-dev.md
  src/app/test_executive/README.md
  src/app/test_executive/payments_test.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/test_config.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/runtime_config/runtime_config.ml
Labels: ci-build-me
