Repository MinaProtocol/mina, pull requests merged in 2022-06, with the labels that each got.

#11014 Refactor pickles to delay prev proof processing
  src/lib/pickles/pickles.ml
  src/lib/pickles/requests.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_main.ml
Labels: ci-build-me

#11016 Remove `main_value` function from pickles inductive rules
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/pickles/inductive_rule.ml
  src/lib/pickles/per_proof_witness.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/requests.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_main.ml
  src/lib/pickles/types_map.ml
  src/lib/pickles_types/hlist.ml
  src/lib/pickles_types/hlist.mli
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/zkapps_examples/empty_update/zkapps_empty_update.ml
  src/lib/zkapps_examples/initialize_state/zkapps_initialize_state.ml
Labels: ci-build-me

#11112 Dhall in toolchain develop
  dockerfiles/stages/3-toolchain
Labels: ci-build-me, Tweag

#11093 [RFC] Versioning changes for hard fork
  rfcs/0046-version-other-serializations.md
  rfcs/0047-versioning-changes-for-hard-fork.md
Labels: ci-build-me

#11156 Remove archive-processor-test from test.py
  scripts/test.py
Labels: ci-build-me

#10959 Token tests in transaction snark
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/mina_generators/dune
  src/lib/mina_generators/parties_generators.ml
  src/lib/mina_ledger/dune
  src/lib/mina_ledger/ledger.ml
  src/lib/parties_builder/dune
  src/lib/parties_builder/parties_builder.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
  src/lib/transaction_snark/test/zkapp_tokens/dune
  src/lib/transaction_snark/test/zkapp_tokens/zkapp_tokens.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/parties_builder.opam
Labels: ci-build-me

#11155 Remove vestiges of coda-archive-processor-test
  buildkite/src/Jobs/Test/ArchiveNodeUnitTest.dhall
  scripts/test.py
Labels: ci-build-me

#11157 Steven ledger gen fix
  automation/README.md
  automation/scripts/generate-keys-and-ledger.sh
Labels: planning-for-testnet, documentation, testnet, testnet-bug, ci-build-me

#11044 Add dhall to toolchain
  dockerfiles/stages/3-toolchain
Labels: ci-build-me, Tweag

#11164 Remove `feature_tokens`, `feature_zkapps` flags in configurations
  src/config/features/dev.mlh
  src/config/features/mainnet.mlh
  src/config/features/public_testnet.mlh
  src/lib/mina_base/account.ml
  src/lib/staged_ledger/staged_ledger.ml
Labels: ci-build-me

#11097 Hack for flexible width
  src/lib/pickles/common.ml
  src/lib/pickles/composition_types/composition_types.ml
  src/lib/pickles/dummy.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/ro.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_main_inputs.ml
  src/lib/pickles/step_verifier.ml
  src/lib/pickles/verify.ml
  src/lib/pickles/wrap.ml
  src/lib/pickles/wrap_hack.ml
  src/lib/pickles/wrap_main.ml
  src/lib/pickles/wrap_main_inputs.ml
  src/lib/pickles/wrap_verifier.ml
Labels: ci-build-me

#11175 frontend/mina-signer: add 'jest' dev-dependency to run tests in CI
  frontend/mina-signer/package-lock.json
  frontend/mina-signer/package.json
Labels: ci-build-me, Tweag

#11166 Enable `whole_program` compilation for SnarkyJS
  scripts/build-snarkyjs-node.sh
  src/dune.linker.inc
  src/lib/crypto/kimchi_bindings/dune
  src/lib/crypto/kimchi_bindings/js/chrome/dune
  src/lib/crypto/kimchi_bindings/js/node_js/dune
  src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
  src/lib/crypto/kimchi_bindings/stubs/dune
  src/lib/crypto/kimchi_bindings/wasm/dune
  src/lib/dummy_values/gen_values/dune
  src/lib/pickles/plonk_checks/gen_scalars/dune
  src/lib/snarky_js_bindings/dune
Labels: ci-build-me

#11192 Change codeowner for pickles{,_types,_base} from protocol to crypto
  CODEOWNERS
Labels: ci-build-me

#11203 Merge back to develop
  frontend/mina-signer/package-lock.json
  frontend/mina-signer/package.json
Labels: ci-build-me

#11185 Dynamic lagrange commitment selection
  src/app/replayer/test/archive_db.sql
  src/lib/crypto/kimchi_bindings/stubs/binding_generation/src/main.rs
  src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
  src/lib/crypto/kimchi_bindings/stubs/src/srs.rs
  src/lib/crypto/kimchi_bindings/wasm/src/srs.rs
  src/lib/pickles/composition_types/branch_data.ml
  src/lib/pickles/composition_types/branch_data.mli
  src/lib/pickles/one_hot_vector/one_hot_vector.ml
  src/lib/pickles/one_hot_vector/one_hot_vector.mli
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/side_loaded_verification_key.ml
  src/lib/pickles/step_main.ml
  src/lib/pickles/step_verifier.ml
  src/lib/pickles/types_map.ml
  src/lib/pickles_base/dune
  src/lib/pickles_base/proofs_verified.ml
  src/lib/pickles_base/side_loaded_verification_key.ml
  src/lib/pickles_types/vector.ml
  src/lib/verifier/prod.ml
Labels: ci-build-me

#11201 Better intg test exit codes dev
  src/app/test_executive/README.md
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/dsl.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/malleable_error.ml
  src/lib/integration_test_lib/test_error.ml
  src/lib/integration_test_lib/util.ml
Labels: ci-build-me

#11196 Better intg test exit codes
  src/app/test_executive/README.md
  src/app/test_executive/test_executive.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/dsl.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/malleable_error.ml
  src/lib/integration_test_lib/test_error.ml
  src/lib/integration_test_lib/util.ml
Labels: ci-build-me

#11204 Token integration test
  src/app/test_executive/dune
  src/app/test_executive/snarkyjs.ml
  src/app/test_executive/zkapps.ml
  src/app/test_executive/zkapps_timing.ml
  src/lib/integration_test_lib/dune
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/wait_condition.ml
Labels: ci-build-me

#11173 dune: add (sandbox none) to mina_version, ocaml-rocksdb
  src/external/ocaml-rocksdb/dune
  src/lib/mina_version/normal/dune
  src/lib/zexe_backend/zexe_backend_common/dune
Labels: ci-build-me, Tweag

#11205 Merge `compatible` to `develop`
  src/external/ocaml-rocksdb/dune
  src/lib/mina_version/normal/dune
Labels: ci-build-me

#11012 [Develop] Pass validation_callback through catchup process
  src/lib/ledger_catchup/dune
  src/lib/ledger_catchup/ledger_catchup.mli
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transition_frontier/dune
  src/lib/transition_frontier/full_catchup_tree.ml
  src/lib/transition_handler/breadcrumb_builder.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
Labels: ci-build-me

#10895 Pass validation_callback through catchup process
  src/lib/ledger_catchup/dune
  src/lib/ledger_catchup/ledger_catchup.mli
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/transition_frontier/dune
  src/lib/transition_frontier/full_catchup_tree.ml
  src/lib/transition_handler/breadcrumb_builder.ml
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
Labels: ci-build-me, code-freeze-1.3.2-eligible

#11174 [develop] dune: add (sandbox none) to mina_version, ocaml-rocksdb
  src/lib/crypto/kimchi_backend/common/dune
Labels: ci-build-me, Tweag

#11187 Nix CI (develop)
  flake.lock
  flake.nix
  nix/checks.nix
  nix/modules/mina.nix
  nix/ocaml.nix
  src/lib/command_line_tests/command_line_tests.ml
Labels: ci-build-me, Tweag

#11221 Archive Node support for Local network runner
  scripts/run_local_network.sh
Labels: infrastructure, ci-build-me, Local

#10956 Support txns with multiple nonce increments in txn pool
  src/lib/mina_base/parties.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/network_pool/dune
  src/lib/network_pool/f_sequence.ml
  src/lib/network_pool/f_sequence.mli
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/user_command_input/user_command_input.ml
Labels: ci-build-me

#10928 Verify party proofs before attempting to include in a block
  src/app/archive/archive_lib/test.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/mina_base/parties.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_generators/dune
  src/lib/mina_generators/parties_generators.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_ledger/ledger.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/staged_ledger/diff_creation_log.ml
  src/lib/staged_ledger/dune
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger_diff/staged_ledger_diff.ml
  src/lib/transaction/transaction.ml
  src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
  src/lib/transaction_inclusion_status/transaction_inclusion_status.mli
  src/lib/transaction_snark/test/transaction_union/transaction_union.ml
  src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/verifier/common.ml
  src/lib/verifier/dune
Labels: ready-to-merge, ci-build-me

#11207 Fix nix build on macOS Big Sur
  flake.lock
  nix/overlay.nix
Labels: ci-build-me

#11077 zkApps integration tests w/ large numbers
  src/app/test_executive/dune
  src/app/test_executive/test_common.ml
  src/app/test_executive/zkapps.ml
  src/app/test_executive/zkapps_timing.ml
  src/lib/integration_test_lib/wait_condition.ml
Labels: ci-build-me

#11222 [Develop] Minimize transaction replacement fee
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#11211 Minimize transaction replacement fee
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#11259 Fix for `unknown flag -ccopt=ocamllsp`
  src/dune.flags.inc
  src/dune.linker.inc
Labels: ci-build-me, dune

#11246 More tokens tests in zkApps integration test
  src/app/test_executive/zkapps.ml
  src/lib/parties_builder/parties_builder.ml
Labels: ci-build-me

#11263 Use exit code 20 for integration test node initialization failures
  src/app/test_executive/README.md
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/dsl.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/malleable_error.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/integration_test_lib/wait_condition.mli
Labels: ci-build-me

#11264 Use exit code 20 for integration test node initialization failures
  src/app/test_executive/README.md
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/dsl.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/malleable_error.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/integration_test_lib/wait_condition.mli
Labels: ci-build-me

#11254 Nix: switch to google cloud storage substituter
  flake.lock
  flake.nix
Labels: ci-build-me

#11265 Fix for building procedure on macOS
  src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
  src/lib/crypto/kimchi_bindings/stubs/dllwires_15_stubs.so
  src/lib/crypto/kimchi_bindings/stubs/dune
Labels: ci-build-me, macOS, build

#11152 Metrics/gossip data collection
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/mina_metrics/mina_metrics.mli
  src/lib/mina_metrics/no_metrics/mina_metrics.ml
  src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
  src/lib/mina_net2/validation_callback.ml
  src/lib/transition_frontier/dune
  src/lib/transition_frontier/persistent_frontier/dune
  src/lib/transition_frontier/persistent_frontier/worker.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me

#11279 Retry `apt-get update` after 10s in dockerfiles
  dockerfiles/Dockerfile-genkey
  dockerfiles/Dockerfile-mina-archive
  dockerfiles/Dockerfile-mina-daemon
  dockerfiles/Dockerfile-zkapp-test-transaction
Labels: ci-build-me

#11281 Version Kimchi bigint type
  src/lib/crypto/kimchi_backend/common/bigint.ml
Labels: ci-build-me

#11092 [Nix] package snarkyjs, client_sdk, mina-signer
  flake.lock
  flake.nix
  nix/impure-shell.nix
  nix/ocaml.nix
  nix/overlay.nix
  src/lib/crypto/Cargo.lock
  src/lib/crypto/Cargo.toml
  src/lib/crypto/kimchi_bindings/js/chrome/build.sh
  src/lib/crypto/kimchi_bindings/js/chrome/dune
  src/lib/crypto/kimchi_bindings/js/node_js/build.sh
  src/lib/crypto/kimchi_bindings/js/node_js/dune
  src/lib/crypto/kimchi_bindings/stubs/cargo_target_dir/cargo_target_dir.ml
  src/lib/crypto/kimchi_bindings/stubs/cargo_target_dir/dune
  src/lib/crypto/kimchi_bindings/stubs/dune
Labels: ci-build-me, Tweag

#10898 Nix-based CI
  flake.lock
  flake.nix
  nix/checks.nix
  nix/modules/mina.nix
  nix/ocaml.nix
  src/lib/command_line_tests/command_line_tests.ml
Labels: ci-build-me, Tweag

#11293 Triple number of transactions in zkapps test
  src/app/test_executive/zkapps.ml
Labels: ci-build-me

#11292 More workers for faster proofs
  src/lib/crypto/kimchi_bindings/js/node_js/node_backend.js
Labels: ci-build-me

#11282 Return values from pickles
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/blockchain_snark/blockchain_snark_state.mli
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/parties_builder/parties_builder.ml
  src/lib/pickles/inductive_rule.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/requests.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_branch_data.ml
  src/lib/pickles/step_main.ml
  src/lib/pickles/types_map.ml
  src/lib/pickles/verify.ml
  src/lib/pickles/wrap.ml
  src/lib/pickles/wrap_domains.ml
  src/lib/pickles_types/hlist.ml
  src/lib/pickles_types/hlist.mli
  src/lib/pickles_types/poly_types.ml
  src/lib/prover/prover.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/test/util.mli
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/transaction_snark/test/zkapps_examples/initialize_state/initialize_state.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/verifier/dune
  src/lib/verifier/prod.ml
  src/lib/zkapps_examples/zkapps_examples.ml
Labels: ci-build-me

#11314 nix: fix error about wasm-bindgen-rayon
  nix/overlay.nix
Labels: ci-build-me, Tweag

#10722 Fix misc error logging issues
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/logger/impl.ml
  src/lib/logger/logger.ml
  src/lib/mina_net2/libp2p_helper.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
Labels: ci-build-me, code-freeze-1.3.2-eligible

#11322 [develop] Nix: add lsp shell
  README-dev.md
  flake.nix
  nix/README.md
  nix/ocaml.nix
Labels: ci-build-me, Tweag

#11311 Add nix lsp to devShell, improve nix/README.md
  README-dev.md
  flake.nix
  nix/README.md
  nix/ocaml.nix
Labels: ci-build-me, Tweag

#11326 Extract Currency.Amount.t into a separate, compatible library (develop)
  src/lib/currency/currency.ml
  src/lib/currency/dune
  src/lib/mina_wire_types/currency.ml
  src/lib/mina_wire_types/currency.mli
  src/lib/mina_wire_types/dune
  src/lib/mina_wire_types/index.mld
  src/lib/mina_wire_types/utils.ml
  src/mina_wire_types.opam
  src/nonconsensus/currency/dune
Labels: ci-build-me, Tweag

#11256 Extract Currency.Amount.t into a separate, compatible library
  src/lib/currency/currency.ml
  src/lib/currency/dune
  src/lib/mina_wire_types/currency.ml
  src/lib/mina_wire_types/currency.mli
  src/lib/mina_wire_types/dune
  src/lib/mina_wire_types/index.mld
  src/lib/mina_wire_types/utils.ml
  src/mina_wire_types.opam
  src/nonconsensus/currency/dune
Labels: ci-build-me, Tweag

#11323 Make compilation of SnarkyJS inductive rules type-safe
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
Labels: ci-build-me

#11330 bump berkeley genesis timestamp
  genesis_ledgers/berkeley.json
Labels: ci-build-me

#11336 [nix] Correct check for impure switch (develop)
  nix/impure-shell.nix
Labels: ci-build-me, Tweag

#11329 [nix] Correct check for impure switch
  nix/impure-shell.nix
Labels: ci-build-me, Tweag

#11317 Update existing tests to return the zkApp statement
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/transaction_snark/test/zkapps_examples/initialize_state/initialize_state.ml
  src/lib/zkapps_examples/zkapps_examples.ml
Labels: ci-build-me

#11340 Special-case 'self' `Typ.t` in SnarkyJS bindings
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
Labels: ci-build-me

#11342 Revert and adapt #11259
  src/dune.flags.inc
  src/dune.linker.inc
Labels: ci-build-me, Tweag

#11348 Nix: fix darwin build on develop
  nix/overlay.nix
Labels: ci-build-me, Tweag

#11356 Nix CI: don't sign or push (since we run a daemon that does that)
  flake.nix
Labels: ci-build-me, Tweag

#11352 Nix: fix mina_tests by importing sql dump correctly
  nix/ocaml.nix
Labels: ci-build-me, Tweag

#11337 Nix: change binary cache key
  flake.nix
Labels: ci-build-me

#11353 Nix: fix lsp shell after ocaml 4.14 upgrade
  flake.lock
  nix/ocaml.nix
Labels: ci-build-me, Tweag

#11354 Nix CI: skip pointless checkouts
  flake.nix
Labels: ci-build-me, Tweag

#11358 Nix: get rid of unbuildable packages (develop)
  flake.lock
  flake.nix
  nix/ocaml.nix
Labels: ci-build-me, Tweag

#11355 Nix: remove unbuildable impure-shell package
  flake.nix
Labels: ci-build-me, Tweag

#11334 Retry buildkite jobs at least once for all infra errors
  buildkite/src/Command/Base.dhall
  buildkite/src/Command/MinaArtifact.dhall
Labels: ci-build-me

#11372 Fix nix build on macOS Big Sur
  flake.lock
  nix/overlay.nix
Labels: ci-build-me, Tweag

#11379 Paths fix in Nix Readme
  nix/README.md
Labels: documentation, ci-build-me

#11072 graphql encoders - develop
  buildkite/src/Constants/ContainerImages.dhall
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/test_executive/delegation_test.ml
  src/app/test_executive/payments_test.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/graphql_wrapper.opam
  src/lib/graphql_wrapper/dune
  src/lib/graphql_wrapper/graphql_wrapper.ml
  src/lib/graphql_wrapper/json.ml
  src/lib/integration_test_cloud_engine/dune
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/mina_graphql/dune
  src/lib/mina_graphql/mina_graphql.ml
  src/opam.export
Labels: ci-build-me, Tweag

#11158 graphql encoders - compatible
  buildkite/src/Constants/ContainerImages.dhall
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/test_executive/delegation_test.ml
  src/graphql_wrapper.opam
  src/lib/graphql_wrapper/dune
  src/lib/graphql_wrapper/graphql_wrapper.ml
  src/lib/graphql_wrapper/json.ml
  src/lib/integration_test_cloud_engine/dune
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/mina_graphql/dune
  src/lib/mina_graphql/mina_graphql.ml
  src/opam.export
Labels: ci-build-me, Tweag

#11018 [Pickles] Pass previous proof inputs from circuit logic
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/blockchain_snark/blockchain_snark_state.mli
  src/lib/data_hash_lib/data_hash.ml
  src/lib/data_hash_lib/data_hash_intf.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/pickles/inductive_rule.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/requests.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_main.ml
  src/lib/prover/prover.ml
  src/lib/snark_worker/prod.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
  src/lib/zkapps_examples/zkapps_examples.ml
Labels: ci-build-me

#11083 [Pickles] Pass previous proofs from circuit logic
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/blockchain_snark/blockchain_snark_state.mli
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/parties_builder/parties_builder.ml
  src/lib/pickles/inductive_rule.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/pickles/requests.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_main.ml
  src/lib/prover/prover.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/test/zkapps_examples/empty_update/empty_update.ml
  src/lib/transaction_snark/test/zkapps_examples/initialize_state/initialize_state.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/zkapps_examples/zkapps_examples.ml
Labels: ci-build-me

#11375 Feature/retry for all infra errors comp
  buildkite/src/Command/Base.dhall
  buildkite/src/Command/MinaArtifact.dhall
Labels: ci-build-me

#11312 Fixup compilation of dump_blocks tool
  src/app/dump_blocks/dump_blocks.ml
  src/app/dump_blocks/dune
Labels: ci-build-me

#11313 Improve rust error message for `Field.of_bigint`
  src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fp.rs
  src/lib/crypto/kimchi_bindings/stubs/src/arkworks/pasta_fq.rs
Labels: ci-build-me

#11377 Fix for `batch_txn_tool`
  src/app/batch_txn_tool/Dockerfile_txn_burst
  src/app/batch_txn_tool/batch_txn_tool.ml
  src/app/batch_txn_tool/dune
  src/app/batch_txn_tool/txn_tool_graphql.ml
Labels: ci-build-me, codebase-catch-up

#11386 Nix related direnv information (compatible)
  .gitignore
  nix/README.md
Labels: documentation, ci-build-me

#11397 exit code 6 for failure to create subscription
  src/app/test_executive/README.md
  src/app/test_executive/test_executive.ml
Labels: ci-build-me

#11410 Nix related direnv information (develop)
  .gitignore
  nix/README.md
Labels: ci-build-me

#11214 New gossipqa deployment, compatible
  .gitignore
  automation/scripts/gen-keys-ledger.sh
  automation/scripts/generate-keys-and-ledger.sh
  automation/scripts/upload-keys-k8s-simplified.sh
  automation/terraform/modules/kubernetes/testnet/locals.tf
  automation/terraform/modules/kubernetes/testnet/variables.tf
  automation/terraform/modules/o1-testnet/files.tf
  automation/terraform/modules/o1-testnet/locals.tf
  automation/terraform/modules/o1-testnet/scripts.tf
  automation/terraform/modules/o1-testnet/testnet.tf
  automation/terraform/testnets/gossipqa/bots.accounts.json
  automation/terraform/testnets/gossipqa/community_fast_unlock.accounts.json
  automation/terraform/testnets/gossipqa/fish.accounts.json
  automation/terraform/testnets/gossipqa/genesis_ledger.json
  automation/terraform/testnets/gossipqa/gossipqa_seeds.txt
  automation/terraform/testnets/gossipqa/main.tf
  automation/terraform/testnets/gossipqa/readme.md
  automation/terraform/testnets/gossipqa/whales.accounts.json
  automation/terraform/testnets/test-labels/main.tf
  helm/cron_jobs/gossipqa-txn-burst-cronjob.yaml
  src/app/batch_txn_tool/Dockerfile_txn_burst
  src/app/batch_txn_tool/txn_tool_graphql.ml
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/mina_metrics/mina_metrics.mli
  src/lib/mina_metrics/no_metrics/mina_metrics.ml
  src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
  src/lib/mina_net2/validation_callback.ml
  src/lib/transition_frontier/dune
  src/lib/transition_frontier/persistent_frontier/dune
  src/lib/transition_frontier/persistent_frontier/worker.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me

#11415 JSON-version extensional blocks
  src/app/archive/archive_lib/chain_status.ml
  src/app/archive/archive_lib/extensional.ml
  src/app/archive/archive_lib/processor.ml
  src/app/archive/archive_lib/rpc.ml
  src/app/archive_blocks/archive_blocks.ml
  src/app/extract_blocks/extract_blocks.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/mina_base/transaction_status.ml
  src/lib/mina_block/precomputed_block.mli
  src/lib/mina_state/local_state.ml
  src/lib/ppx_version/versioned_module.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
Labels: ci-build-me

#11384 Update ocaml-graphql-server - develop
  buildkite/src/Constants/ContainerImages.dhall
  src/lib/fields_derivers_graphql/fields_derivers_graphql.ml
  src/lib/fields_derivers_zkapps/fields_derivers_zkapps.ml
  src/opam.export
Labels: ci-build-me, Tweag

#11383 Update ocaml-graphql-server - compatible
  buildkite/src/Constants/ContainerImages.dhall
  src/opam.export
Labels: ci-build-me, Tweag

#11357 Upgrade dune to 3.3.1, factorize graph-ppx configuration (develop)
  buildkite/src/Constants/ContainerImages.dhall
  src/app/cli/src/dune-project
  src/app/cli/src/init/dune
  src/app/rosetta/dune-project
  src/app/rosetta/lib/dune
  src/dune-project
  src/dune.flags.inc
  src/graphql-ppx-config.inc
  src/lib/integration_test_cloud_engine/dune
  src/opam.export
Labels: ci-build-me, Tweag
