Repository MinaProtocol/mina, pull requests merged in 2022-08, with the labels that each got.

#11589 Fix pack_to_fields
  src/app/replayer/test/archive_db.sql
  src/lib/random_oracle_input/random_oracle_input.ml
Labels: ci-build-me

#11596 Minor pickles tidy-ups
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/pickles.mli
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
  src/lib/transaction_snark/test/multisig_account/multisig_account.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/zkapps_examples/zkapps_examples.ml
Labels: ci-build-me

#11588 Add %%versioned_rpc to ppx_version
  src/lib/consensus/proof_of_stake.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/ppx_version/versioned_module.ml
  src/lib/ppx_version/versioned_type.ml
  src/lib/ppx_version/versioned_util.ml
  src/lib/snark_worker/dune
  src/lib/snark_worker/snark_worker.ml
Labels: ci-build-me

#11602 Mrmr1993/merge back to develop
  src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
  src/lib/crypto/kimchi_bindings/stubs/src/main.rs
  src/lib/crypto/kimchi_bindings/stubs/src/srs.rs
  src/lib/crypto/kimchi_bindings/stubs/src/urs_utils.rs
  src/lib/crypto/kimchi_bindings/wasm/src/srs.rs
  src/lib/crypto/kimchi_bindings/wasm/src/urs_utils.rs
  src/lib/pickles/pickles.ml
  src/lib/pickles/verify.ml
  src/lib/pickles/wrap_main_inputs.ml
Labels: ci-build-me

#11603 Mrmr1993/merge back to compatible
  src/lib/marlin_plonk_bindings/pasta_fp_urs/marlin_plonk_bindings_pasta_fp_urs.ml
  src/lib/marlin_plonk_bindings/pasta_fq_urs/marlin_plonk_bindings_pasta_fq_urs.ml
  src/lib/marlin_plonk_bindings/stubs/src/pasta_fp_urs.rs
  src/lib/marlin_plonk_bindings/stubs/src/pasta_fq_urs.rs
  src/lib/marlin_plonk_bindings/stubs/src/urs_utils.rs
  src/lib/pickles/opt_sponge.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/verify.ml
  src/lib/pickles/wrap_main_inputs.ml
Labels: ci-build-me

#11592 Lk86/merge in master 1.3.2
  src/lib/marlin_plonk_bindings/pasta_fp_urs/marlin_plonk_bindings_pasta_fp_urs.ml
  src/lib/marlin_plonk_bindings/pasta_fq_urs/marlin_plonk_bindings_pasta_fq_urs.ml
  src/lib/marlin_plonk_bindings/stubs/src/pasta_fp_urs.rs
  src/lib/marlin_plonk_bindings/stubs/src/pasta_fq_urs.rs
  src/lib/marlin_plonk_bindings/stubs/src/urs_utils.rs
  src/lib/pickles/opt_sponge.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/verify.ml
  src/lib/pickles/wrap_main_inputs.ml
Labels: ci-build-me

#11587 add a parameter for num of trials
  buildkite/scripts/fuzzy-zkapp-test.sh
  buildkite/src/Jobs/Test/FuzzyZkappTest.dhall
  src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
Labels: ci-build-me

#11604 Mrmr1993/merge back to develop
  src/lib/crypto/kimchi_bindings/js/bindings.js
  src/lib/crypto/kimchi_bindings/wasm/src/srs.rs
  src/lib/crypto/kimchi_bindings/wasm/src/urs_utils.rs
  src/lib/pickles/pickles.ml
Labels: ci-build-me

#11610 Fix Result module in register_event parser
  src/lib/ppx_register_event/register_event.ml
Labels: ci-build-me

#11599 Fix bitrot in benchmarks
  Makefile
  scripts/benchmarks.sh
  src/app/benchmarks/benchmarks.ml
  src/app/benchmarks/dune
  src/app/benchmarks/dune-project
Labels: ci-build-me

#11605 Fix flakiness of client_sdk unit tests
  src/app/client_sdk/tests/client_sdk.js
Labels: ci-build-me

#11615 Fix out-of-snark precondition checks on empty account.zkapp
  src/lib/mina_base/zkapp_precondition.ml
Labels: ci-build-me

#11614 Log snark work failures in the daemon, expose them in the test executive
  src/app/cli/src/init/coda_run.ml
  src/app/test_executive/zkapps.ml
  src/lib/integration_test_lib/dune
  src/lib/integration_test_lib/event_type.ml
  src/lib/integration_test_lib/event_type.mli
  src/lib/mina_metrics/mina_metrics.mli
  src/lib/mina_metrics/no_metrics/mina_metrics.ml
  src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
  src/lib/snark_worker/dune
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/snark_worker/rpcs.ml
  src/lib/snark_worker/snark_worker.ml
  src/lib/snark_worker/snark_worker.mli
Labels: ci-build-me

#11580 Declare graphql scalars - develop
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/decoders.ml
  src/app/rosetta/lib/dune
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/lib/network.ml
  src/graphql-ppx-config.inc
  src/graphql_basic_scalars.opam
  src/lib/block_time/block_time.ml
  src/lib/block_time/block_time.mli
  src/lib/block_time/unix/dune
  src/lib/block_time/unix/graphql_scalars.ml
  src/lib/cli_lib/graphql_types.ml
  src/lib/consensus/consensus.ml
  src/lib/consensus/consensus.mli
  src/lib/consensus/dune
  src/lib/consensus/graphql_scalars.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/currency/unix/dune
  src/lib/currency/unix/graphql_scalars.ml
  src/lib/filtered_external_transition/unix/dune
  src/lib/filtered_external_transition/unix/graphql_scalars.ml
  src/lib/graphql_basic_scalars/dune
  src/lib/graphql_basic_scalars/graphql_basic_scalars.ml
  src/lib/graphql_lib/base_types.ml
  src/lib/graphql_lib/base_types.mli
  src/lib/graphql_lib/decoders.ml
  src/lib/graphql_lib/dune
  src/lib/graphql_lib/scalars.ml
  src/lib/graphql_lib/serializing.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/mina_base/unix/dune
  src/lib/mina_base/unix/graphql_scalars.ml
  src/lib/mina_block/unix/dune
  src/lib/mina_block/unix/graphql_scalars.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_numbers/unix/dune
  src/lib/mina_numbers/unix/graphql_scalars.ml
  src/lib/signature_lib/unix/dune
  src/lib/signature_lib/unix/graphql_scalars.ml
  src/lib/transaction/unix/dune
  src/lib/transaction/unix/graphql_scalars.ml
Labels: ci-build-me, Tweag

#11574 Declare graphql scalars - compatible
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/decoders.ml
  src/app/rosetta/lib/dune
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/lib/network.ml
  src/graphql-ppx-config.inc
  src/graphql_basic_scalars.opam
  src/lib/block_time/block_time.ml
  src/lib/block_time/block_time.mli
  src/lib/block_time/unix/dune
  src/lib/block_time/unix/graphql_scalars.ml
  src/lib/cli_lib/graphql_types.ml
  src/lib/consensus/consensus.ml
  src/lib/consensus/consensus.mli
  src/lib/consensus/dune
  src/lib/consensus/graphql_scalars.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/currency/unix/dune
  src/lib/currency/unix/graphql_scalars.ml
  src/lib/filtered_external_transition/unix/dune
  src/lib/filtered_external_transition/unix/graphql_scalars.ml
  src/lib/graphql_basic_scalars/dune
  src/lib/graphql_basic_scalars/graphql_basic_scalars.ml
  src/lib/graphql_lib/base_types.ml
  src/lib/graphql_lib/base_types.mli
  src/lib/graphql_lib/decoders.ml
  src/lib/graphql_lib/dune
  src/lib/graphql_lib/scalars.ml
  src/lib/graphql_lib/serializing.ml
  src/lib/integration_test_cloud_engine/dune
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/mina_base/unix/dune
  src/lib/mina_base/unix/graphql_scalars.ml
  src/lib/mina_block/unix/dune
  src/lib/mina_block/unix/graphql_scalars.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_numbers/unix/dune
  src/lib/mina_numbers/unix/graphql_scalars.ml
  src/lib/signature_lib/unix/dune
  src/lib/signature_lib/unix/graphql_scalars.ml
Labels: ci-build-me, Tweag

#11624 Remove 'generating' debug prints
  src/lib/parties_builder/parties_builder.ml
Labels: ci-build-me

#11630 [Pickles] Rename me_only to messages_for_next_{step,wrap}_proof
  src/lib/pickles/common.ml
  src/lib/pickles/composition_types/composition_types.ml
  src/lib/pickles/per_proof_witness.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/proof.ml
  src/lib/pickles/reduced_messages_for_next_proof_over_same_field.ml
  src/lib/pickles/requests.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_main.ml
  src/lib/pickles/step_verifier.ml
  src/lib/pickles/verify.ml
  src/lib/pickles/wrap.ml
  src/lib/pickles/wrap_hack.ml
  src/lib/pickles/wrap_main.ml
Labels: ci-build-me

#11607 [Pickles] Use wrap_vk's domain generator in the step prover
  src/lib/pickles/step.ml
Labels: ci-build-me

#11616 [Pickles] Use the same 'permutation shifts' between different domains
  src/lib/pickles/pseudo/pseudo.ml
  src/lib/pickles/step_verifier.ml
  src/lib/pickles/wrap_main.ml
Labels: ci-build-me

#11619 [Pickles] Allow side-loaded proofs to use different wrap domains
  src/lib/pickles/pickles.ml
  src/lib/pickles/requests.ml
  src/lib/pickles/step.ml
  src/lib/pickles/verify.ml
  src/lib/pickles/wrap.ml
  src/lib/pickles/wrap_domains.ml
  src/lib/pickles/wrap_main.ml
  src/lib/pickles/wrap_verifier.ml
Labels: ci-build-me

#11643 Events checked push, pop invertibility
  src/lib/mina_base/zkapp_account.ml
Labels: ci-build-me

#11644 Print Wasm errors in JS console
  src/lib/crypto/kimchi_bindings/wasm/src/pasta_fp_plonk_index.rs
  src/lib/crypto/kimchi_bindings/wasm/src/pasta_fq_plonk_index.rs
  src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs
Labels: ci-build-me

#11639 deriver for network state view, expose in snarkyjs
  src/lib/mina_base/zkapp_precondition.ml
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
Labels: ci-build-me

#11655 shift sequence events once per block and if there are events
  src/lib/transaction_logic/parties_logic.ml
Labels: ci-build-me

#11662 Nix fixes
  flake.nix
  nix/README.md
Labels: ci-build-me, Tweag

#11650 Add documentation generation via odoc
  flake.nix
  nix/ocaml.nix
  src/opam.export
Labels: ci-build-me, Tweag

#11668 Fix Nix devShells by reusing existing shellHook
  flake.nix
Labels: ci-build-me, Tweag

#11653 [crypto] add base64 serialization methods to wasm
  src/lib/crypto/kimchi_bindings/wasm/Cargo.lock
  src/lib/crypto/kimchi_bindings/wasm/Cargo.toml
  src/lib/crypto/kimchi_bindings/wasm/src/pasta_fp_plonk_index.rs
  src/lib/crypto/kimchi_bindings/wasm/src/pasta_fq_plonk_index.rs
  src/lib/crypto/kimchi_bindings/wasm/src/plonk_proof.rs
Labels: ci-build-me

#11656 remove todo_zkapps
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/mina_base/util/mina_base_util.ml
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#11438 Remove dead code
  CODEOWNERS
  scripts/archive/ocaml/dune
  scripts/archive/ocaml/dune-project
  scripts/archive/ocaml/json_stitch.ml
  scripts/archive/ocaml/stitch_introspection.ml
  scripts/archive/ocaml/stitch_introspection.opam
  src/lib/pokolog/dune
  src/lib/pokolog/group_intf.ml
  src/lib/pokolog/hash_intf.ml
  src/lib/pokolog/inputs_intf.ml
  src/lib/pokolog/intf.ml
  src/lib/pokolog/pokolog.ml
  src/lib/pokolog/proof.ml
  src/lib/pokolog/scalar_intf.ml
  src/lib/pokolog/variable_base_instance.ml
  src/lib/snark_keys/dune
  src/lib/snark_keys/gen_keys/dune
  src/lib/snark_keys/gen_keys/gen_keys.ml
  src/lib/snark_keys/remove_snark_keys_trigger/clear_keys/clear_keys.ml
  src/lib/snark_keys/remove_snark_keys_trigger/clear_keys/dune
  src/lib/snark_keys/remove_snark_keys_trigger/dune
  src/lib/snarky_log/examples/election/dune
  src/lib/snarky_log/examples/election/election.ml
  src/lib/snarky_log/examples/election/election_main.ml
  src/lib/snarky_log/examples/election/impl.ml
  src/lib/snarky_log/examples/election/import.ml
  src/lib/snarky_log/examples/election/knapsack_hash.ml
  src/lib/snarky_log/examples/election/knapsack_hash.mli
  src/lib/snarky_pairing/dune
  src/lib/snarky_pairing/final_exponentiation.ml
  src/lib/snarky_pairing/g1_precomputation.ml
  src/lib/snarky_pairing/g2_precomputation.ml
  src/lib/snarky_pairing/miller_loop.ml
  src/lib/snarky_verifier/bowe_gabizon.ml
  src/lib/snarky_verifier/dune
  src/lib/snarky_verifier/groth.ml
  src/lib/snarky_verifier/groth_maller.ml
  src/lib/snarky_verifier/inputs.ml
  src/lib/snarky_verifier/summary.ml
Labels: ci-build-me, Tweag

#11688 Compatible -> develop
  flake.nix
  nix/README.md
  nix/ocaml.nix
  src/opam.export
Labels: ci-build-me

#11672 Listen for GraphQL requests on all NICs (Compatible)
  scripts/run_local_network.sh
Labels: enhancement, ci-build-me, Local

#11673 Listen for GraphQL requests on all NICs (Develop)
  scripts/run_local_network.sh
Labels: enhancement, ci-build-me, Local

#11669 Make the nixos-container run mina demo
  flake.nix
  nix/README.md
Labels: ci-build-me, Tweag

#11253 Bump libp2p version to the latest
  buildkite/src/Constants/ContainerImages.dhall
  dockerfiles/stages/1-build-deps
  flake.lock
  nix/impure-shell.nix
  nix/ocaml.nix
  nix/overlay.nix
  nix/vend/default.nix
  nix/vend/remove_tidy.patch
  scripts/build-go-helper.sh
  src/app/libp2p_helper/src/bitswap_storage.go
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/app.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_test.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg.go
  src/app/test_executive/block_production_priority.ml
  src/libp2p_ipc/Makefile
  src/libp2p_ipc/go.mod
  src/libp2p_ipc/go.sum
Labels: ci-build-me

#11699 Larger init balances in SNARK profiler
  src/app/cli/src/init/transaction_snark_profiler.ml
Labels: ci-build-me

#11373 Report failures to include transactions in blocks
  src/app/cli/src/cli_entrypoint/dune
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/tests/coda_worker.ml
  src/lib/block_producer/block_producer.ml
  src/lib/block_producer/dune
  src/lib/mina_lib/dune
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/node_error_service/dune
  src/lib/node_error_service/node_error_service.ml
  src/lib/node_error_service/node_error_service.mli
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
Labels: ci-build-me

#11701 Fix libp2p stream leak
  src/app/libp2p_helper/src/libp2p_helper/bitswap.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_block.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/stream_msg.go
Labels: ci-build-me

#11679 Nix: refactor by splitting out overlays per-language (develop)
  flake.nix
  nix/go.nix
  nix/misc.nix
  nix/ocaml.nix
  nix/overlay.nix
  nix/rust.nix
  nix/vend/default.nix
  src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
  src/lib/crypto/kimchi_bindings/wasm/Cargo.lock
Labels: ci-build-me, Tweag

#11678 Nix: refactor by splitting out overlays per-language
  flake.nix
  nix/go.nix
  nix/misc.nix
  nix/ocaml.nix
  nix/rust.nix
Labels: ci-build-me, Tweag

#11512 make parties_generator create new zkapp accounts
  src/app/archive/archive_lib/dune
  src/app/archive/archive_lib/test.ml
  src/lib/mina_generators/dune
  src/lib/mina_generators/parties_generators.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/network_pool/dune
  src/lib/network_pool/transaction_pool.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
Labels: ci-build-me

#11697 Fixed number of elements for app state, sequence state
  src/app/archive/archive_lib/load_data.ml
  src/app/archive/archive_lib/processor.ml
  src/app/archive/zkapp_tables.sql
  src/app/replayer/test/archive_db.sql
Labels: ci-build-me

#11711 Add protocol major version to chain id
  src/app/cli/src/cli_entrypoint/dune
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/mina_commands/dune
  src/lib/mina_commands/mina_commands.ml
  src/lib/protocol_version/dune
  src/lib/protocol_version/protocol_version.ml
  src/lib/protocol_version/protocol_version.mli
Labels: ci-build-me

#11570 check opam switch - develop
  Makefile
  README-dev.md
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall
  dockerfiles/stages/2-opam-deps
  nix/README.md
  nix/checks.nix
  nix/impure-shell.nix
  nix/ocaml.nix
  opam.export
  scripts/select-opam-deps.sh
Labels: ci-build-me, Tweag

#11569 check opam switch - compatible
  Makefile
  README-dev.md
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall
  dockerfiles/stages/2-opam-deps
  nix/README.md
  nix/checks.nix
  nix/impure-shell.nix
  nix/ocaml.nix
  opam.export
  scripts/select-opam-deps.sh
Labels: ci-build-me, Tweag

#11685 Pass around a `Context` module instead of multiple arguments
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/tests/coda_worker.ml
  src/lib/best_tip_prover/best_tip_prover.ml
  src/lib/best_tip_prover/dune
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/bootstrap_controller.mli
  src/lib/bootstrap_controller/dune
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/fake_network/dune
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/ledger_catchup/dune
  src/lib/ledger_catchup/ledger_catchup.ml
  src/lib/ledger_catchup/ledger_catchup.mli
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/mina_block/validation.ml
  src/lib/mina_block/validation.mli
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_lib/dune
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_networking/dune
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_networking/mina_networking.mli
  src/lib/sync_handler/dune
  src/lib/sync_handler/sync_handler.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/full_frontier/full_frontier.mli
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
  src/lib/transition_frontier_controller/dune
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_handler/validator.ml
  src/lib/transition_router/transition_router.ml
  src/lib/vrf_evaluator/vrf_evaluator.ml
Labels: ci-build-me

#11716 Make rust target-feature flag customisable with an env var
  src/lib/crypto/kimchi_bindings/stubs/dune
Labels: ci-build-me

#11724 Mina Local Network Manager extraction and documentation (Compatible)
  .gitignore
  scripts/mina-local-network/README.md
  scripts/mina-local-network/generate-mina-local-network-ledger.py
  scripts/mina-local-network/mina-local-network.sh
  scripts/mina-local-network/requirements.txt
  scripts/run_local_network.sh
Labels: documentation, enhancement, ci-build-me, Local

#11725 Mina Local Network Manager extraction and documentation (Develop)
  .gitignore
  scripts/mina-local-network/README.md
  scripts/mina-local-network/generate-mina-local-network-ledger.py
  scripts/mina-local-network/mina-local-network.sh
  scripts/mina-local-network/requirements.txt
  scripts/run_local_network.sh
Labels: documentation, enhancement, ci-build-me, Local

#11675 add boolean condition for nightly fuzzy zkapp test
  buildkite/scripts/fuzzy-zkapp-test.sh
  buildkite/src/Jobs/Test/FuzzyZkappTest.dhall
  src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
Labels: ci-build-me

#11320 Revalidate transaction pool off of ledger state when updating best tip
  src/lib/block_producer/block_producer.ml
  src/lib/mina_base/account.ml
  src/lib/mina_base/dune
  src/lib/mina_base/parties.ml
  src/lib/network_pool/dune
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/mocks.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me

#11737 Better error message when check_opam_switch is missing
  Makefile
Labels: ci-build-me, Tweag

#11744 Protocol version 3.0
  src/config/protocol_version/current.mlh
Labels: ci-build-me

#11403 Transaction pool parties async bug fix
  src/app/test_executive/zkapps.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/network_pool/batcher.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/pool_sink.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool_diff.ml
  src/lib/network_pool/transaction_pool.ml
Labels: ci-build-me
