Repository MinaProtocol/mina, pull requests merged in 2022-01, with the labels that each got.

#9967 Rosetta, making block queries deterministic
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/network.ml
Labels: ci-build-me

#9969 Rosetta, limit max height of block queries
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/network.ml
Labels: ci-build-me

#9964 Replayer, update for Snapps
  src/app/archive/archive_lib/extensional.ml
  src/app/archive/archive_lib/processor.ml
  src/app/archive/create_schema.sql
  src/app/archive/snapp_tables.sql
  src/app/extract_blocks/extract_blocks.ml
  src/app/extract_blocks/sql.ml
  src/app/replayer/dune
  src/app/replayer/replayer.ml
  src/app/replayer/sql.ml
  src/app/rosetta/lib/block.ml
  src/lib/consensus/intf.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/snapp_predicate.ml
  src/lib/mina_caqti/mina_caqti.ml
Labels: ci-build-me

#9626 Bitswap support in Libp2p helper
  buildkite/src/Jobs/Test/Libp2pUnitTest.dhall
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/libp2p_helper/BUILD.bazel
  src/app/libp2p_helper/LICENSE
  src/app/libp2p_helper/Makefile
  src/app/libp2p_helper/WORKSPACE.bazel
  src/app/libp2p_helper/bzl/libp2p/BUILD.bazel
  src/app/libp2p_helper/bzl/libp2p/deps.bzl
  src/app/libp2p_helper/default.nix
  src/app/libp2p_helper/src/BUILD.bazel
  src/app/libp2p_helper/src/bitswap_storage.go
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/BUILD.bazel
  src/app/libp2p_helper/src/libp2p_helper/app.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_block.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_block_test.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_msg.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_test.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/data.go
  src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go
  src/app/libp2p_helper/src/libp2p_helper/main.go
  src/app/libp2p_helper/src/libp2p_helper/main_test.go
  src/app/libp2p_helper/src/libp2p_helper/msg.go
  src/app/libp2p_helper/src/libp2p_helper/multinode_test.go
  src/app/libp2p_helper/src/libp2p_helper/peer_msg.go
  src/app/libp2p_helper/src/libp2p_helper/peer_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/pubsub_msg.go
  src/app/libp2p_helper/src/libp2p_helper/pubsub_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/stream_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/upcall_test.go
  src/app/libp2p_helper/src/libp2p_helper/util_test.go
  src/app/libp2p_helper/src/tools.go
  src/lib/cli_lib/default.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/mina_net2/tests/all_ipc.ml
  src/lib/mina_net2/tests/tests.ml
  src/libp2p_ipc/libp2p_ipc.capnp
  src/libp2p_ipc/libp2p_ipc.ml
  src/libp2p_ipc/libp2p_ipc.mli
Labels: ci-build-me

#9955 Utility file intg tests
  src/app/test_executive/chain_reliability_test.ml
  src/app/test_executive/peers_reliability_test.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/util.ml
Labels: ci-build-me

#9963 specific permission related errors
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_base/transaction_status.ml
  src/lib/mina_transition/external_transition_sample_precomputed_block.ml
Labels: ready-to-merge, ci-build-me, Proj - snapps protocol work

#9970 gen protocol state predicate
  src/lib/mina_base/snapp_generators.ml
Labels: ci-build-me

#9782 Optimize staged ledger diff application
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/merkle_mask/masking_merkle_tree_intf.ml
  src/lib/mina_base/dune
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/pending_coinbase.ml
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_base/transaction_logic.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
Labels: ready-to-merge, ci-build-me

#10001 Don't require a valid proof for genesis blocks
  src/lib/best_tip_prover/best_tip_prover.ml
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/transition_router/initial_validator.ml
Labels: ci-build-me

#8327 Choose the best VRF evaluation rather than the first
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/vrf_evaluator/vrf_evaluator.ml
Labels: ci-build-me

#10007 Remove unnecessary verbose logging
  src/app/libp2p_helper/src/libp2p_helper/pubsub_msg.go
Labels: ci-build-me

#10009 Fix block production race condition in integration test
  src/lib/block_producer/block_producer.ml
Labels: ci-build-me

#10011 Split generated other parties in two
  src/lib/mina_base/control.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/snapp_generators.ml
Labels: ci-build-me

#9895 Fix SetGatingConfig RPC endpoint
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/stream_msg_test.go
  src/lib/best_tip_prover/best_tip_prover.ml
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/mina_transition/external_transition.ml
  src/lib/mina_transition/external_transition_intf.ml
  src/lib/transition_router/initial_validator.ml
Labels: ci-build-me

#10018 Revert breaking change to versioned type
  src/lib/mina_base/pending_coinbase.ml
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/staged_ledger/staged_ledger.ml
Labels: ci-build-me

#10010 Merge back to develop
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/libp2p_helper/pubsub_msg.go
  src/app/libp2p_helper/src/libp2p_helper/stream_msg_test.go
  src/app/test_executive/chain_reliability_test.ml
  src/app/test_executive/peers_reliability_test.ml
  src/lib/block_producer/block_producer.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/util.ml
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/merkle_mask/masking_merkle_tree_intf.ml
  src/lib/mina_base/dune
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_base/transaction_logic.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/vrf_evaluator/vrf_evaluator.ml
Labels: ci-build-me

#9898 Staged ledger Snapp test
  src/app/archive/archive_lib/test.ml
  src/lib/mina_base/account.ml
  src/lib/mina_base/control.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/permissions.ml
  src/lib/mina_base/permissions.mli
  src/lib/mina_base/snapp_generators.ml
  src/lib/mina_base/snapp_predicate.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_base/user_command_generators.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/staged_ledger/staged_ledger.ml
Labels: ci-build-me

#10019 Rosetta offline network endpoints
  src/app/rosetta/lib/network.ml
  src/app/rosetta/lib/rosetta.ml
Labels: ci-build-me

#10021 Unrevert change to Sparse_ledger, propagate version
  src/app/archive/archive_lib/diff.ml
  src/app/archive/archive_lib/rpc.ml
  src/lib/mina_base/pending_coinbase.ml
  src/lib/mina_base/pending_coinbase_intf.ml
  src/lib/mina_base/pending_coinbase_witness.ml
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_transition/internal_transition.ml
  src/lib/prover/prover.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transition_frontier/frontier_base/root_data.ml
Labels: ci-build-me

#9977 reproducing peer graph check
  helm/block-producer/templates/block-producer.yaml
  helm/seed-node/templates/seed-node.yaml
  src/app/test_executive/archive_node_test.ml
  src/app/test_executive/chain_reliability_test.ml
  src/app/test_executive/gossip_consistency.ml
  src/app/test_executive/payments_test.ml
  src/app/test_executive/peers_reliability_test.ml
  src/graph_algorithms.opam
  src/lib/graph_algorithms/dune
  src/lib/graph_algorithms/graph_algorithms.ml
  src/lib/graph_algorithms/nat.ml
  src/lib/integration_test_lib/dune
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/util.ml
Labels: ci-build-me

#9984 Use hash-based message id function
  src/app/libp2p_helper/Makefile
  src/app/libp2p_helper/src/libp2p_helper/config_msg.go
  src/app/libp2p_helper/src/libp2p_helper/message_id_test.go
  src/app/libp2p_helper/src/libp2p_helper/multinode_test.go
  src/app/libp2p_helper/src/libp2p_helper/upcall_test.go
  src/app/libp2p_helper/src/libp2p_helper/util_test.go
Labels: ci-build-me

#10043 Add with_label annotations to transaction snark asserts
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10054 Snapps GraphQL, derive from JSON
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/replayer/replayer.ml
  src/app/snapp_test_transaction/dune
  src/app/snapp_test_transaction/snapp_test_transaction.ml
  src/lib/mina_base/parties.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/snapp_generators.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/verifier/common.ml
Labels: ci-build-me

#9936 use range check for currency and numbers
  src/lib/block_time/block_time.ml
  src/lib/block_time/block_time.mli
  src/lib/block_time/dune
  src/lib/consensus/constants.ml
  src/lib/consensus/global_slot.ml
  src/lib/consensus/global_slot.mli
  src/lib/consensus/global_sub_window.ml
  src/lib/consensus/global_sub_window.mli
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/consensus/slot.ml
  src/lib/consensus/vrf/consensus_vrf.ml
  src/lib/currency/currency.ml
  src/lib/currency/currency.mli
  src/lib/currency/intf.ml
  src/lib/mina_base/account.ml
  src/lib/mina_base/fee_excess.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/payment_payload.ml
  src/lib/mina_base/protocol_constants_checked.ml
  src/lib/mina_base/signed_command_payload.ml
  src/lib/mina_base/snapp_command.ml
  src/lib/mina_base/snapp_predicate.ml
  src/lib/mina_base/token_id.ml
  src/lib/mina_base/transaction_union_payload.ml
  src/lib/mina_numbers/intf.ml
  src/lib/mina_numbers/nat.ml
  src/lib/mina_state/blockchain_state.ml
  src/lib/mina_state/blockchain_state.mli
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10045 mockSnapp GraphQL endpoint
  graphql_schema.json
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#9952 Update `make clean`
  Makefile
Labels: ci-build-me

#10016 More staged ledger Snapp unit tests
  src/lib/staged_ledger/staged_ledger.ml
Labels: ci-build-me

#10095 Debug intgtest
  dockerfiles/Dockerfile-mina-daemon
Labels: ci-build-me

#10094 Valid output for Full predicate
  dockerfiles/Dockerfile-mina-daemon
  src/app/snapp_test_transaction/snapp_test_transaction.ml
Labels: ci-build-me

#9966 Fix: use correct protocol state commitments in verifier
  src/lib/mina_base/snapp_generators.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/verifier/common.ml
Labels: ci-build-me

#10104 update integration test docs
  src/app/test_executive/README.md
Labels: ci-build-me

#10110 Move get_account, set_account, and check_inclusion out of Parties_logic effects
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10112 Replace Party_token effect with function
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10113 Move `Global_slot` type and accessors out of effects
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10114 Add `add_check` helper function to Parties_logic, use it for `Check_fee_excess`
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10115 Check transaction verification in Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10116 Move replay checks into `Parties_logic`
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10121 Lk86/simpler optimized staged ledger compatible
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/merkle_mask/masking_merkle_tree_intf.ml
  src/lib/mina_base/dune
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_base/transaction_logic.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
Labels: ci-build-me

#10101 WIP Optimize staged ledger apply diff
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/merkle_mask/masking_merkle_tree_intf.ml
  src/lib/mina_base/dune
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_base/transaction_logic.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
Labels: ci-build-me
