Repository MinaProtocol/mina, pull requests merged in 2022-09, with the labels that each got.

#11702 Optimize parties transaction hashing
  src/lib/transaction/transaction_hash.ml
Labels: ci-build-me

#11707 Parties txn metrics and logs
  src/app/cli/src/init/coda_run.ml
  src/lib/mina_metrics/mina_metrics.mli
  src/lib/mina_metrics/no_metrics/mina_metrics.ml
  src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/snark_work_lib/work.ml
  src/lib/snark_worker/functor.ml
  src/lib/snark_worker/intf.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
Labels: ci-build-me

#11708 Limit size of Parties.t in gossip, txn pool, blocks
  src/app/test_executive/zkapps.ml
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/gossip_net/dune
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/mina_base/parties.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_compile_config/mina_compile_config.ml
  src/lib/mina_generators/parties_generators.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
  src/lib/transaction/transaction.ml
  src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
  src/lib/transition_handler/block_sink.ml
  src/lib/transition_handler/block_sink.mli
  src/lib/transition_handler/dune
Labels: ci-build-me

#11759 Factor out sequence state update logic
  src/lib/mina_generators/parties_generators.ml
  src/lib/mina_ledger/dune
  src/lib/mina_ledger/ledger.mli
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_logic/parties_logic.ml
Labels: ci-build-me

#11700 Remove custom connection logic
  nix/go.nix
  nix/libp2p_helper.json
  nix/update-libp2p-hashes.sh
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/config_msg.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go
  src/app/libp2p_helper/src/libp2p_helper/main_test.go
  src/app/libp2p_helper/src/libp2p_helper/multinode_test.go
  src/app/libp2p_helper/src/libp2p_helper/peer_msg.go
  src/app/libp2p_helper/src/libp2p_helper/util_test.go
  src/lib/block_storage/block_storage.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/fake_network/dune
  src/lib/fake_network/fake_network.ml
  src/lib/fake_network/fake_network.mli
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_net2/libp2p_helper.ml
  src/lib/mina_net2/libp2p_helper.mli
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/mina_net2/tests/all_ipc.ml
  src/lib/mina_net2/tests/tests.ml
  src/lib/trust_system/peer_trust.ml
  src/lib/trust_system/peer_trust.mli
  src/lib/trust_system/trust_system.ml
  src/libp2p_ipc/libp2p_ipc.capnp
  src/libp2p_ipc/libp2p_ipc.ml
  src/libp2p_ipc/libp2p_ipc.mli
Labels: ci-build-me

#11761 Add missig dependency to batch_txn_tool
  src/app/batch_txn_tool/dune
Labels: ci-build-me, Tweag, MinaFoundation

#11715 Update nixpkgs
  Makefile
  flake.lock
  flake.nix
  nix/go.nix
  src/external/ocaml-rocksdb/rocks_options.ml
Labels: ci-build-me, Tweag, MinaFoundation

#11754 Fixes missing graphql fields
  README-dev.md
  graphql_schema.json
  src/lib/consensus/dune
  src/lib/consensus/proof_of_stake.ml
  src/lib/mina_base/pending_coinbase.ml
  src/lib/mina_base/pending_coinbase_intf.ml
  src/lib/mina_base/staged_ledger_hash.ml
  src/lib/mina_base/staged_ledger_hash.mli
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#11772 Nix: Add back vend
  nix/go.nix
Labels: ci-build-me, Tweag

#11714 Update nixpkgs
  flake.lock
  flake.nix
  nix/go.nix
  nix/ocaml.nix
  nix/vend/default.nix
  nix/vend/remove_tidy.patch
  src/external/ocaml-rocksdb/rocks_options.ml
Labels: ci-build-me, Tweag, MinaFoundation

#11696 Update graphql schema
  CHANGES
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/construction.ml
  src/app/rosetta/lib/mempool.ml
  src/app/rosetta/lib/network.ml
  src/graphql-ppx-config.inc
  src/lib/blake2/blake2.ml
  src/lib/blake2/intf.ml
  src/lib/consensus/body_reference.ml
  src/lib/consensus/body_reference.mli
  src/lib/consensus/graphql_scalars.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/mina_base/pending_coinbase.ml
  src/lib/mina_base/pending_coinbase_intf.ml
  src/lib/mina_base/staged_ledger_hash.ml
  src/lib/mina_base/staged_ledger_hash.mli
  src/lib/mina_base/unix/graphql_scalars.ml
  src/lib/mina_graphql/dune
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me, Tweag, MinaFoundation

#11763 Nix: fix snarkyjs build
  flake.nix
  src/app/client_sdk/tests/client_sdk.js
Labels: ci-build-me, Tweag, MinaFoundation

#11783 Fix a bug and re-enable TestBitswapSmoke
  flake.nix
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/bitswap.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_test.go
Labels: ci-build-me

#11790 Fix for go.mod hash mismatch
  nix/libp2p_helper.json
  src/app/libp2p_helper/README.md
Labels: ci-build-me, build, nix

#11793 Update src/app/batch_txn_tool after GraphQL schema change
  src/app/batch_txn_tool/batch_txn_tool.ml
  src/app/batch_txn_tool/dune
  src/app/batch_txn_tool/txn_tool_graphql.ml
Labels: ci-build-me, Tweag, MinaFoundation

#11746 adding nightly env variable
  buildkite/src/Constants/ContainerEnvVars.dhall
Labels: ci-build-me

#11792 Update nix-npm-buildpackage
  flake.lock
Labels: ci-build-me, Tweag

#11755 fix generation of zkapp_test coverage
  src/app/archive/archive_lib/load_data.ml
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me, Tweag, MinaFoundation, Confidence

#11762 Fix generation of zkapp_test coverage (compatible)
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me, Tweag, MinaFoundation, Confidence

#11765 Documentation improvements
  CONTRIBUTING.md
  Makefile
  README-branching.md
  README-ci-failures.md
  README-dev.md
  README.md
  docs/res/branching_flow.png
  scripts/web.sh
Labels: ci-build-me, Tweag

#11801 Nix: update nix-npm-buildpackage [compatible]
  flake.lock
  flake.nix
Labels: ci-build-me, Tweag

#11632 Simplify zkApp examples API
  src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
  src/lib/zkapps_examples/add_events/zkapps_add_events.ml
  src/lib/zkapps_examples/empty_update/zkapps_empty_update.ml
  src/lib/zkapps_examples/initialize_state/zkapps_initialize_state.ml
  src/lib/zkapps_examples/sequence_events/zkapps_sequence_events.ml
  src/lib/zkapps_examples/zkapps_examples.ml
Labels: ci-build-me

#11806 Fix for Docker image Demo-mode (Develop).
  dockerfiles/auxiliary_entrypoints/01-run-demo.sh
Labels: bug, ci-build-me, docker-image

#11445 zkApp composability test
  src/lib/mina_base/zkapp_call_forest.ml
  src/lib/transaction_snark/test/zkapps_examples/calls/calls.ml
  src/lib/transaction_snark/test/zkapps_examples/calls/dune
  src/lib/zkapps_examples/calls/dune
  src/lib/zkapps_examples/calls/zkapps_calls.ml
  src/lib/zkapps_examples/zkapps_examples.ml
Labels: ci-build-me

#11742 Wait to load persisted frontier in peers test
  graphql_schema.json
  src/app/test_executive/peers_reliability_test.ml
  src/app/test_executive/zkapps.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_lib/dune
  src/lib/integration_test_lib/event_type.ml
  src/lib/integration_test_lib/event_type.mli
  src/lib/integration_test_lib/gossip_state.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/integration_test_lib/wait_condition.mli
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
Labels: ci-build-me

#11758 interface for kimchi_backend
  src/lib/crypto/kimchi_backend/common/bigint.mli
  src/lib/crypto/kimchi_backend/common/dune
  src/lib/crypto/kimchi_backend/common/kimchi_backend_common.ml
  src/lib/crypto/kimchi_backend/common/kimchi_backend_common.mli
  src/lib/crypto/kimchi_backend/common/scalar_challenge.mli
  src/lib/crypto/kimchi_backend/dune
  src/lib/crypto/kimchi_backend/kimchi_backend.ml
  src/lib/crypto/kimchi_backend/kimchi_backend.mli
  src/lib/crypto/kimchi_backend/pasta/dune
  src/lib/crypto/kimchi_backend/pasta/kimchi_pasta.ml
  src/lib/crypto/kimchi_backend/pasta/kimchi_pasta.mli
  src/lib/crypto/kimchi_backend/pasta/pasta.ml
  src/lib/crypto/kimchi_backend/pasta/pasta.mli
  src/lib/crypto/kimchi_backend/pasta/precomputed.mli
Labels: ci-build-me

#11788 zkapp transaction metrics
  src/app/cli/src/init/mina_run.ml
  src/lib/mina_metrics/mina_metrics.mli
  src/lib/mina_metrics/no_metrics/mina_metrics.ml
  src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/snark_worker/functor.ml
Labels: ci-build-me

#11749 Base64 for transaction ids
  graphql_schema.json
  src/app/cli/src/init/client.ml
  src/lib/cli_lib/arg_type.ml
  src/lib/codable/codable.ml
  src/lib/codable/dune
  src/lib/graphql_basic_scalars/graphql_basic_scalars.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/mina_base/signed_command.ml
  src/lib/mina_base/signed_command_intf.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_base/zkapp_command.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/transaction/transaction_id.ml
  src/lib/transaction/unix/graphql_scalars.ml
Labels: ci-build-me

#11823 Use serialized value for hashing signed commands
  src/lib/transaction/transaction_hash.ml
  src/lib/transaction_snark/test/account_timing/account_timing.ml
Labels: ci-build-me

#11825 Fix tests by passing MINA_LIBP2P_PASS to mina
  nix/ocaml.nix
Labels: ci-build-me, Tweag

#11807 Fix for Docker image Demo-mode
  dockerfiles/auxiliary_entrypoints/01-run-demo.sh
Labels: ci-build-me, docker-image

#11811 Add .direnv to reformat's trusted list
  src/app/reformat/reformat.ml
Labels: ci-build-me, Tweag

#11824 rename zkapp_precondition_accounts -> account_precondition_values
  src/app/archive/archive_lib/load_data.ml
  src/app/archive/archive_lib/processor.ml
  src/app/archive/drop_tables.sql
  src/app/archive/zkapp_tables.sql
  src/app/replayer/test/archive_db.sql
Labels: ci-build-me

#11818 [crypto] document wasm
  src/lib/crypto/kimchi_bindings/wasm/README.md
  src/lib/crypto/kimchi_bindings/wasm/src/wasm_flat_vector.rs
Labels: ci-build-me

#11832 Lazy verification key and prover in zkapp_test_transaction
  src/app/zkapp_test_transaction/lib/commands.ml
Labels: ci-build-me

#11826 Automatically deserialize TransactionId scalars with graphql_ppx
  src/app/cli/src/init/client.ml
  src/graphql-ppx-config.inc
  src/lib/codable/codable.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
Labels: ci-build-me, Tweag, MinaFoundation

#11833 Fix wrapping behaviour when parsing unsigned integers for GraphQL scalars
  src/lib/graphql_basic_scalars/graphql_basic_scalars.ml
Labels: ci-build-me, Tweag

#11834 [crypto][wasm] add more to the README
  src/lib/crypto/kimchi_bindings/wasm/README.md
Labels: ci-build-me

#11841 Parties limit based on a cost function
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/mina_base/zkapp_command.ml
  src/lib/mina_compile_config/mina_compile_config.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ci-build-me

#11844 Build the `batch_txn_tool` binary in nix CI
  nix/ocaml.nix
Labels: ci-build-me, Tweag, MinaFoundation

#11851 Make Base64 coding available for verification keys
  src/app/archive/archive_lib/load_data.ml
  src/app/archive/archive_lib/processor.ml
  src/lib/pickles/pickles_intf.ml
  src/lib/pickles/side_loaded_verification_key.ml
Labels: ci-build-me

#11820 adding $githash value to docker image tags
  scripts/release-docker.sh
Labels: ci-build-me

#11747 Update references to Mina's docs
  .xrefcheck.yaml
  CONTRIBUTING.md
  README-dev.md
  README.md
  automation/services/echo/README.md
  automation/services/faucet/README.md
  src/app/rosetta/README.md
Labels: ci-build-me, Tweag, MinaFoundation

#11785 Properly exposes pending coinbase aux
  graphql_schema.json
  src/graphql-ppx-config.inc
  src/lib/mina_base/staged_ledger_hash.ml
  src/lib/mina_base/staged_ledger_hash.mli
  src/lib/mina_base/unix/graphql_scalars.ml
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#11871 Raise with error string on application
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
Labels: ci-build-me

#11853 Specify node resources for testnet nodes
  automation/scripts/gen-keys-ledger.sh
  automation/terraform/modules/o1-testnet/inputs.tf
  automation/terraform/modules/o1-testnet/testnet.tf
  automation/terraform/testnets/berkeley/main.tf
Labels: ci-build-me

#11859 Fix --version output
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
Labels: ci-build-me, Tweag

#11799 Nix: Improve requireSubmodules warning
  flake.nix
Labels: ci-build-me, Tweag

#11621 Adds Rosetta zkApps RFC
  rfcs/0048-rosetta-zkapps.md
Labels: ci-build-me

#11680 Test/generate token accounts
  src/app/archive/archive_lib/dune
  src/app/archive/archive_lib/test.ml
  src/lib/mina_base/account_update.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/mina_generators/zkapp_command_generators.ml
  src/lib/mina_generators/zkapp_command_generators.mli
  src/lib/network_pool/transaction_pool.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
Labels: ci-build-me

#11854 Filter out account ids on failed transactions
  src/app/cli/src/init/transaction_snark_profiler.ml
  src/lib/filtered_external_transition/filtered_external_transition.ml
  src/lib/mina_base/signed_command.ml
  src/lib/mina_base/signed_command_intf.ml
  src/lib/mina_base/signed_command_payload.ml
  src/lib/mina_base/signed_command_payload.mli
  src/lib/mina_base/user_command.ml
  src/lib/mina_base/zkapp_command.ml
  src/lib/mina_block/block.ml
  src/lib/mina_ledger/ledger.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction/transaction.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_snark/test/account_timing/account_timing.ml
  src/lib/transaction_snark/test/transaction_union/transaction_union.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me, berkeley-rampup

#11888 Rename typ columns to command_type
  src/app/archive/create_schema.sql
  src/app/archive/lib/.ocamlformat
  src/app/archive/lib/archive_lib.opam
  src/app/archive/lib/ast.ml
  src/app/archive/lib/chain_status.ml
  src/app/archive/lib/diff.ml
  src/app/archive/lib/dune
  src/app/archive/lib/dune-project
  src/app/archive/lib/extensional.ml
  src/app/archive/lib/graphql_query.opam
  src/app/archive/lib/graphql_query/base_types.ml
  src/app/archive/lib/graphql_query/blocks.ml
  src/app/archive/lib/graphql_query/clear_data.ml
  src/app/archive/lib/graphql_query/dune
  src/app/archive/lib/graphql_query/fee_transfers.ml
  src/app/archive/lib/graphql_query/graphql_query.ml
  src/app/archive/lib/graphql_query/public_keys.ml
  src/app/archive/lib/graphql_query/user_commands.ml
  src/app/archive/lib/load_data.ml
  src/app/archive/lib/metrics.ml
  src/app/archive/lib/processor.ml
  src/app/archive/lib/rpc.ml
  src/app/archive/lib/test.ml
  src/app/extract_blocks/extract_blocks.ml
  src/app/replayer/sql.ml
  src/app/replayer/test/archive_db.sql
  src/app/rosetta/lib/block.ml
  src/lib/block_time/block_time.ml
Labels: ci-build-me, berkeley-rampup

#11873 Include location of assert_ failures
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_logic/zkapp_command_logic.ml
  src/lib/transaction_snark/dune
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me, berkeley-rampup

#11902 Parties limit based on a cost function [develop]
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/mina_base/zkapp_command.ml
  src/lib/mina_compile_config/mina_compile_config.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ci-build-me

#11645 Fail with meaningful message once empty data passed to 'validate-transaction' (Compatible)
  src/lib/cli_lib/commands.ml
Labels: enhancement, ci-build-me

#11903 [crypto] pin once_cell to specific version (fix for compatible)
  src/lib/marlin_plonk_bindings/stubs/Cargo.lock
  src/lib/marlin_plonk_bindings/stubs/dune
Labels: ci-build-me

#11936 Take median value instead of minimum for some flaky alerts
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: ci-build-me

#11720 Fix most compilation errors
  src/app/best_tip_merger/best_tip_merger.ml
  src/app/best_tip_merger/dune
  src/app/client_sdk/dune
  src/app/client_sdk/tests/dune
  src/app/delegation_compliance/delegation_compliance.ml
  src/app/display_public_key/display_public_key.ml
  src/app/display_public_key/dune
  src/app/genesis_ledger_from_tsv/dune
  src/app/genesis_ledger_from_tsv/genesis_ledger_from_tsv.ml
  src/app/runtime_genesis_ledger/dune
  src/app/snark_work_debugger/snark_work_debugger.ml
  src/external/dune
  src/lib/coda_plugins/examples/toplevel/dune
  src/lib/crypto/kimchi_bindings/js/test/bindings_js_test.ml
  src/lib/crypto/kimchi_bindings/js/test/chrome/dune
  src/lib/crypto/kimchi_bindings/js/test/nodejs/dune
  src/lib/ppx_mina/dune
  src/lib/ppx_mina/tests/dune-project
  src/lib/ppx_version/dune
  src/lib/ppx_version/test/dune-project
  src/nonconsensus/currency/dune
  src/nonconsensus/data_hash_lib/dune
  src/nonconsensus/fields_derivers_zkapps/dune
  src/nonconsensus/hash_prefix_states/dune
  src/nonconsensus/hex/dune
  src/nonconsensus/mina_base/dune
  src/nonconsensus/mina_base/import/dune
  src/nonconsensus/mina_base/util/dune
  src/nonconsensus/mina_compile_config/dune
  src/nonconsensus/mina_numbers/dune
  src/nonconsensus/non_zero_curve_point/dune
  src/nonconsensus/outside_hash_image/dune
  src/nonconsensus/quickcheck_lib/dune
  src/nonconsensus/random_oracle/dune
  src/nonconsensus/rosetta_coding/dune
  src/nonconsensus/rosetta_lib/dune
  src/nonconsensus/rosetta_lib/test/dune
  src/nonconsensus/sgn/dune
  src/nonconsensus/signature_lib/dune
  src/nonconsensus/snark_bits/dune
  src/nonconsensus/snark_params/dune
  src/nonconsensus/string_sign/dune
  src/nonconsensus/transaction/dune
  src/nonconsensus/unsigned_extended/dune
Labels: ci-build-me

#11870 Fix nightly fuzzy zkapp
  src/lib/mina_generators/zkapp_command_generators.ml
  src/lib/mina_generators/zkapp_command_generators.mli
  src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
Labels: ci-build-me

#11943 expose dummy proof to Snarkyjs
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
Labels: ci-build-me
