Repository MinaProtocol/mina, pull requests merged in 2022-02, with the labels that each got.

#10135 Update gitattributes to ignore automation/ for language detection
  .gitattributes
Labels: ci-build-me

#10136 Remove unused snarked `Transaction_status.Failure`
  src/lib/mina_base/transaction_status.ml
Labels: ci-build-me

#10117 Move account consistency checks into `Parties_logic`
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10139 Remove dynamic block producer keypair swapping
  dockerfiles/stages/3-builder
  dockerfiles/stages/4-deb-builder
  graphql_schema.json
  scripts/build-and-test-rosetta-from-git.sh
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/rosetta/README.md
  src/app/rosetta/docker-test-start.sh
  src/app/rosetta/start.sh
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/dune
  src/app/rosetta/test-agent/offline.ml
  src/app/rosetta/test-agent/operation_expectation.ml
  src/app/rosetta/test-agent/peek.ml
  src/app/rosetta/test-agent/poke.ml
  src/lib/block_producer/block_producer.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/config.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
Labels: ci-build-me

#10120 Snapp integration test
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  graphql_schema.json
  src/app/test_executive/snapps_test.ml
  src/app/test_executive/test_executive.ml
  src/lib/block_time/block_time.ml
  src/lib/integration_test_cloud_engine/dune
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/wait_condition.ml
  src/lib/mina_base/account.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/pickles/pickles.ml
  src/lib/snarky_log/snarky_log.ml
Labels: ci-build-me

#10145 Nonstrict inequality for token symbol length; rm dynamic block producer code
  dockerfiles/stages/4-builder
  dockerfiles/stages/4-deb-builder
  graphql_schema.json
  scripts/build-and-test-rosetta-from-git.sh
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/coda_run.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/cli/src/tests/coda_worker.ml
  src/app/cli/src/tests/full_test.ml
  src/app/rosetta/README.md
  src/app/rosetta/docker-test-start.sh
  src/app/rosetta/start.sh
  src/app/rosetta/test-agent/agent.ml
  src/app/rosetta/test-agent/dune
  src/app/rosetta/test-agent/offline.ml
  src/app/rosetta/test-agent/operation_expectation.ml
  src/app/rosetta/test-agent/peek.ml
  src/app/rosetta/test-agent/poke.ml
  src/lib/block_producer/block_producer.ml
  src/lib/daemon_rpcs/daemon_rpcs.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/config.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
Labels: ci-build-me

#10148 [Housekeeping] Make nonconsensus code its own dune project
  src/nonconsensus/currency_nonconsensus.opam
  src/nonconsensus/data_hash_lib_nonconsensus.opam
  src/nonconsensus/dune-project
  src/nonconsensus/hash_prefix_states_nonconsensus.opam
  src/nonconsensus/hex_nonconsensus.opam
  src/nonconsensus/mina_base_nonconsensus.opam
  src/nonconsensus/mina_compile_config_nonconsensus.opam
  src/nonconsensus/mina_numbers_nonconsensus.opam
  src/nonconsensus/non_zero_curve_point_nonconsensus.opam
  src/nonconsensus/outside_hash_image_nonconsensus.opam
  src/nonconsensus/quickcheck_lib_nonconsensus.opam
  src/nonconsensus/random_oracle_nonconsensus.opam
  src/nonconsensus/rosetta_coding_nonconsensus.opam
  src/nonconsensus/rosetta_lib/test/dune
  src/nonconsensus/rosetta_lib_nonconsensus.opam
  src/nonconsensus/sgn_nonconsensus.opam
  src/nonconsensus/signature_lib_nonconsensus.opam
  src/nonconsensus/snark_bits_nonconsensus.opam
  src/nonconsensus/snark_params_nonconsensus.opam
  src/nonconsensus/string_sign_nonconsensus.opam
  src/nonconsensus/unsigned_extended_nonconsensus.opam
Labels: ci-build-me

#10161 Make Truth.t cases exhaustive
  src/lib/mina_transition/external_transition.ml
  src/lib/transition_handler/processor.ml
  src/lib/truth/truth.ml
  src/lib/truth/truth.mli
Labels: ci-build-me

#10166 Add non-circuit equivalent functions to Currency, add missing functions
  src/lib/currency/currency.ml
  src/lib/currency/currency.mli
  src/lib/currency/intf.ml
Labels: ci-build-me

#10133 lk86/fix-merges-cleanly-job Check mergeability against all upstream branches
  buildkite/scripts/merges-cleanly-to-develop.sh
  buildkite/scripts/merges-cleanly.sh
  buildkite/src/Jobs/Lint/Merge.dhall
Labels: ci-build-me

#10092 Removed duplicate constants from consensus code
  src/lib/consensus/constants.ml
  src/lib/consensus/epoch.ml
  src/lib/consensus/global_slot.ml
  src/lib/consensus/proof_of_stake.ml
Labels: ci-build-me

#10159 Remove peer reliability temp
  .mergify.yml
  .mergify.yml.jinja
  buildkite/src/Command/MinaArtifact.dhall
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
Labels: ci-build-me, ready-to-merge-into-compatible

#10176 Remove linearization on verification key
  src/lib/crypto/kimchi_bindings/stubs/binding_generation/src/main.rs
  src/lib/crypto/kimchi_bindings/stubs/src/lib.rs
  src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
  src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
  src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
  src/lib/pickles/side_loaded_verification_key.ml
  src/lib/pickles/verification_key.ml
Labels: ci-build-me

#10157 Feature/snapps protocol refactor stacks
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_base/with_stack_hash.ml
  src/lib/mina_state/local_state.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_witness/transaction_witness.ml
  src/lib/transaction_witness/transaction_witness.mli
Labels: ci-build-me

#10160 Feature/snapps protocol refactor party or stack
  src/lib/hash_prefix_states/hash_prefix_states.ml
  src/lib/hash_prefix_states/hash_prefix_states.mli
  src/lib/hash_prefixes/hash_prefixes.ml
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/parties.ml
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/snapp_generators.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_state/local_state.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/test/ring_sig.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_witness/transaction_witness.ml
  src/lib/transaction_witness/transaction_witness.mli
  src/lib/verifier/common.ml
Labels: ci-build-me

#10178 Move timing update into combined transaction logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10150 Merge back to develop
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/merkle_mask/masking_merkle_tree_intf.ml
  src/lib/mina_base/dune
  src/lib/mina_base/ledger.mli
  src/lib/mina_base/pending_coinbase.ml
  src/lib/mina_base/pending_coinbase_intf.ml
  src/lib/mina_base/pending_coinbase_witness.ml
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/sparse_ledger.mli
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_transition/internal_transition.ml
  src/lib/prover/prover.ml
  src/lib/sparse_ledger_lib/sparse_ledger.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.mli
  src/lib/transition_frontier/frontier_base/root_data.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
Labels: ci-build-me

#10190 Copy password when importing key
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#10006 snapp txn tool protocol state predicate
  src/app/snapp_test_transaction/snapp_test_transaction.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ready-to-merge, ci-build-me

#10198 Remove linearization on verification key
  src/lib/crypto/kimchi_bindings/stubs/binding_generation/src/main.rs
  src/lib/crypto/kimchi_bindings/stubs/src/lib.rs
  src/lib/crypto/kimchi_bindings/stubs/src/oracles.rs
  src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_index.rs
  src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_proof.rs
  src/lib/crypto/kimchi_bindings/stubs/src/pasta_fp_plonk_verifier_index.rs
  src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_index.rs
  src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_proof.rs
  src/lib/crypto/kimchi_bindings/stubs/src/pasta_fq_plonk_verifier_index.rs
  src/lib/crypto/kimchi_bindings/stubs/src/plonk_verifier_index.rs
  src/lib/pickles/side_loaded_verification_key.ml
  src/lib/pickles/verification_key.ml
Labels: ci-build-me

#10201 Revive run local network script
  .gitignore
  scripts/generate-local-network-ledger.py
  scripts/run_local_network.sh
Labels: ci-build-me

#10209 lk86/remove-snapps-protocol-merge-check
  buildkite/src/Jobs/Lint/Merge.dhall
Labels: ci-build-me

#10183 Add set_voting_for permission, allow snapp commands to set voting_for
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/archive/snapp_tables.sql
  src/app/replayer/replayer.ml
  src/app/snapp_test_transaction/snapp_test_transaction.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/graphql_lib/decoders.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/mina_base/account.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/permissions.ml
  src/lib/mina_base/permissions.mli
  src/lib/mina_base/snapp_command.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/mina_base/transaction_status.ml
  src/lib/mina_base/user_command_generators.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10211 fix verification key json format in parties
  src/lib/pickles/side_loaded_verification_key.ml
Labels: ci-build-me

#10212 Lk86/ubuntu focal etc support develop
  buildkite/src/Command/DockerImage.dhall
  buildkite/src/Command/MinaArtifact.dhall
  buildkite/src/Command/RunInToolchain.dhall
  buildkite/src/Constants/ContainerImages.dhall
  buildkite/src/Constants/DebianVersions.dhall
  buildkite/src/Jobs/Release/MinaArtifactBionic.dhall
  buildkite/src/Jobs/Release/MinaArtifactBullseye.dhall
  buildkite/src/Jobs/Release/MinaArtifactFocal.dhall
  buildkite/src/Jobs/Release/MinaRosettaUbuntu.dhall
  buildkite/src/Jobs/Release/MinaToolchainArtifact.dhall
  dockerfiles/Dockerfile-mina-archive
  dockerfiles/Dockerfile-mina-daemon
  dockerfiles/Dockerfile-snapp-test-transaction
  dockerfiles/stages/1-build-deps
  dockerfiles/stages/1-build-deps-ubuntu
  dockerfiles/stages/2-opam-deps
  dockerfiles/stages/3-builder
  dockerfiles/stages/3-toolchain
  dockerfiles/stages/4-prod-ubuntu
  dockerfiles/stages/4-production
  scripts/archive/build-release-archives.sh
  scripts/rebuild-deb.sh
  scripts/release-docker.sh
  src/app/rosetta/README.md
Labels: ci-build-me

#10186 Snapp integration test, add valid snapp and payment
  src/app/test_executive/snapps_test.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/intf.ml
  src/lib/integration_test_lib/malleable_error.ml
  src/lib/integration_test_lib/network_state.ml
  src/lib/integration_test_lib/util.ml
  src/lib/mina_base/snapp_generators.ml
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#10236 Remove verifier memory stats logging
  src/lib/verifier/prod.ml
Labels: ci-build-me

#10237 Fix Super Catchup Async Loop
  src/lib/downloader/downloader.ml
Labels: ci-build-me

#10240 [Trivial] Remove unused type parameter in kimchi constraint system
  src/lib/crypto/kimchi_backend/common/dlog_plonk_based_keypair.ml
  src/lib/crypto/kimchi_backend/common/plonk_constraint_system.ml
  src/lib/pickles/fix_domains.ml
Labels: ci-build-me

#10242 lk86/improve-docker-entrypoint
  dockerfiles/scripts/daemon-entrypoint.sh
Labels: ci-build-me

#10179 Move balance update into combined transaction logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/permissions.ml
  src/lib/mina_base/permissions.mli
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10219 Rosetta: Replaces "Pending" status with null
  src/app/rosetta/README.md
  src/app/rosetta/test-curl/con_preprocess.sh
  src/lib/rosetta_lib/operation_statuses.ml
  src/lib/rosetta_lib/user_command_info.ml
Labels: ci-build-me

#10245 lk86/fix-entrypoint Make entrypoint backward compatible
  dockerfiles/scripts/daemon-entrypoint.sh
Labels: ci-build-me

#10214 Move timing checks to parties logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10216 Move verification_key update into Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10217 Move sequence state update into Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10218 Move remaining snapp account state logic into Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10221 Move snapp URI updates into Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10222 Move token-symbol updates to Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10223 Move delegate update to Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10224 Move nonce update logic to Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10225 Move voting_for update to Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10226 Move permissions update to Parties_logic
  src/lib/mina_base/parties_logic.ml
  src/lib/mina_base/transaction_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me

#10097 Move Token_id to Mina_numbers
  src/lib/mina_base/token_id.ml
  src/lib/mina_base/token_id.mli
  src/lib/mina_numbers/dune
  src/lib/mina_numbers/mina_numbers.ml
  src/lib/mina_numbers/token_id.ml
  src/lib/mina_numbers/token_id.mli
  src/nonconsensus/mina_numbers/token_id.ml
  src/nonconsensus/mina_numbers/token_id.mli
Labels: ci-build-me

#10232 [pickles] Document Hlist
  src/lib/pickles_types/hlist.ml
  src/lib/pickles_types/hlist.mli
  src/lib/pickles_types/hlist0.ml
  src/lib/pickles_types/poly_types.ml
Labels: ready-to-merge, ci-build-me

#10257 Rosetta: Accepts empty string status
  src/lib/rosetta_lib/user_command_info.ml
Labels: ci-build-me

#10093 handle expiring predicates in the tx pool
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/mina_compile_config/mina_compile_config.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/network_pool/test.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
Labels: ready-to-merge, ci-build-me

#10254 Snapps test tool unit test
  buildkite/src/Jobs/Test/SnappTestToolUnitTest.dhall
  src/app/snapp_test_transaction/.ocamlformat
  src/app/snapp_test_transaction/dune
  src/app/snapp_test_transaction/dune-project
  src/app/snapp_test_transaction/lib/commands.ml
  src/app/snapp_test_transaction/lib/dune
  src/app/snapp_test_transaction/snapp_test_transaction.ml
  src/app/snapp_test_transaction/snapp_test_transaction.opam
  src/app/snapp_test_transaction/snapp_test_transaction_lib.opam
Labels: ci-build-me

#10099 Break out `Util` and `Import` from `Mina_base`
  src/lib/mina_base/account.ml
  src/lib/mina_base/account_id.ml
  src/lib/mina_base/account_id.mli
  src/lib/mina_base/coinbase.ml
  src/lib/mina_base/coinbase.mli
  src/lib/mina_base/coinbase_fee_transfer.ml
  src/lib/mina_base/coinbase_fee_transfer.mli
  src/lib/mina_base/dune
  src/lib/mina_base/fee_excess.ml
  src/lib/mina_base/fee_transfer.ml
  src/lib/mina_base/fee_transfer.mli
  src/lib/mina_base/import/dune
  src/lib/mina_base/import/mina_base_import.ml
  src/lib/mina_base/ledger_hash.ml
  src/lib/mina_base/mina_base.ml
  src/lib/mina_base/minting_payload.ml
  src/lib/mina_base/new_account_payload.ml
  src/lib/mina_base/new_token_payload.ml
  src/lib/mina_base/party.ml
  src/lib/mina_base/payment_payload.mli
  src/lib/mina_base/pending_coinbase.ml
  src/lib/mina_base/permissions.ml
  src/lib/mina_base/signed_command.ml
  src/lib/mina_base/signed_command.mli
  src/lib/mina_base/signed_command_intf.ml
  src/lib/mina_base/signed_command_payload.mli
  src/lib/mina_base/snapp_basic.ml
  src/lib/mina_base/sok_message.ml
  src/lib/mina_base/sok_message.mli
  src/lib/mina_base/sparse_ledger.ml
  src/lib/mina_base/staged_ledger_hash.ml
  src/lib/mina_base/transaction_union_tag.ml
  src/lib/mina_base/util/dune
  src/lib/mina_base/util/mina_base_util.ml
  src/nonconsensus/mina_base/dune
  src/nonconsensus/mina_base/import.ml
  src/nonconsensus/mina_base/import/dune
  src/nonconsensus/mina_base/import/mina_base_import.ml
  src/nonconsensus/mina_base/mina_base_nonconsensus.ml
  src/nonconsensus/mina_base/util.ml
  src/nonconsensus/mina_base/util/dune
  src/nonconsensus/mina_base/util/mina_base_util.ml
Labels: ci-build-me

#10261 fix snapp proof verification failure
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark.mli
Labels: ready-to-merge, ci-build-me

#10265 lk86/berkeley-ci Build berkeley images in CI
  buildkite/src/Command/MinaArtifact.dhall
  genesis_ledgers/berkeley.json
  scripts/rebuild-deb.sh
Labels: ci-build-me

#10266 Integration test using constructed Snapps
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  src/app/archive/archive_lib/graphql_query/user_commands.ml
  src/app/archive/archive_lib/processor.ml
  src/app/cli/src/init/graphql_queries.ml
  src/app/extract_blocks/extract_blocks.ml
  src/app/replayer/replayer.ml
  src/app/test_executive/snapps_constructed.ml
  src/app/test_executive/snapps_generated.ml
  src/app/test_executive/test_executive.ml
  src/lib/mina_base/signed_command_memo.ml
  src/lib/mina_base/signed_command_memo.mli
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#10274 Break out snapp generators from `mina_base`
  src/app/archive/archive_lib/dune
  src/app/archive/archive_lib/test.ml
  src/app/snapp_test_transaction/lib/commands.ml
  src/app/snapp_test_transaction/lib/dune
  src/app/test_executive/dune
  src/app/test_executive/snapps_generated.ml
  src/lib/mina_base/mina_base.ml
  src/lib/mina_generators/dune
  src/lib/mina_generators/snapp_generators.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/network_pool/dune
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/staged_ledger/dune
  src/lib/staged_ledger/staged_ledger.ml
  src/mina_generators.opam
Labels: ci-build-me

#10273 snapps test transaction tool ux improvements
  src/app/snapp_test_transaction/lib/commands.ml
  src/app/snapp_test_transaction/snapp_test_transaction.ml
Labels: ci-build-me

#10272 Add more fields to accounts in graphql
  graphql_schema.json
  src/app/snapp_test_transaction/lib/commands.ml
  src/app/snapp_test_transaction/snapp_test_transaction.ml
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#10286 Increase 'short bootstrap' timeout for chain reliability test
  src/app/test_executive/chain_reliability_test.ml
Labels: ci-build-me

#10284 Fix uint64 comparing in JS
  src/lib/integers_stubs_js/runtime.js
Labels: ci-build-me

#10285 Fix `dune utop` in `mina_base` and friends
  src/lib/crypto/kimchi_bindings/stubs/Cargo.toml
Labels: ci-build-me

#10301 Use ** blob specifier for linguist-vendored
  .gitattributes
Labels: ci-build-me

#10290 Increase timeout in snapps integration test
  src/app/test_executive/snapps_constructed.ml
Labels: ci-build-me

#10185 Remove Both authorisation kind
  graphql_schema.json
  src/app/archive/archive_lib/processor.ml
  src/app/snapp_test_transaction/lib/commands.ml
  src/app/snapp_test_transaction/snapp_test_transaction.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/mina_base/permissions.ml
  src/lib/mina_base/permissions.mli
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/runtime_config/runtime_config.ml
Labels: ci-build-me

#10253 add docs and comments to supercatchup
  src/lib/ledger_catchup/README.md
  src/lib/ledger_catchup/super_catchup.ml
Labels: ci-build-me

#10119 Fix/qa net deployments
  automation/bake/Dockerfile
  automation/scripts/bake.sh
  automation/scripts/generate-keys-and-ledger.sh
  automation/terraform/modules/o1-testnet/locals.tf
  automation/terraform/modules/o1-testnet/testnet.tf
  automation/terraform/testnets/test-labels/community_fast_unlock.accounts.json
  automation/terraform/testnets/test-labels/fish.accounts.json
  automation/terraform/testnets/test-labels/genesis_ledger.json
  automation/terraform/testnets/test-labels/whales.accounts.json
  automation/terraform/testnets/test-snapps/README.md
  automation/terraform/testnets/test-snapps/community_fast_unlock.accounts.json
  automation/terraform/testnets/test-snapps/fish.accounts.json
  automation/terraform/testnets/test-snapps/genesis_ledger.json
  automation/terraform/testnets/test-snapps/main.tf
  automation/terraform/testnets/test-snapps/test-snapps_seeds.txt
  automation/terraform/testnets/test-snapps/whales.accounts.json
  genesis_ledgers/test-snapps.json
  helm/archive-node/templates/archive.yaml
  helm/block-producer/templates/block-producer.yaml
  helm/plain-node/templates/plain-node.yaml
  helm/seed-node/templates/seed-node.yaml
  helm/snark-worker/templates/snark-coordinator.yaml
Labels: ci-build-me

#10303 replace Marlin_plonk_bindings_pasta_fp with State_body_hash in super catchup
  src/lib/ledger_catchup/super_catchup.ml
Labels: ci-build-me

#9910 Rfc/node status backend
  rfcs/0044-node-status-and-node-error-backend.md
  rfcs/res/aws_stack.png
  rfcs/res/gcloud_logging.png
Labels: ci-build-me
