Repository MinaProtocol/mina, pull requests merged in 2022-10, with the labels that each got.

#11954 Change argument name to tokenId
  graphql_schema.json
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me

#11955 Lookup token accounts after filtering on token id
  helm/archive-node/templates/db-bootstrap.yaml
  src/lib/mina_graphql/mina_graphql.ml
Labels: ci-build-me, berkeley-mainnet

#7106 Tweak Inline_test_quiet_logs to write to stdout directly upon failures
  src/lib/inline_test_quiet_logs/inline_test_quiet_logs.ml
Labels: ci-build-me

#11941 Rosetta: Fetch genesis block height from GraphQL.
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/network.ml
Labels: required-for-release, ci-build-me, rosetta, MinaFoundation

#11965 Version-tag transaction ids
  src/lib/base58_check/version_bytes.ml
  src/lib/mina_base/payment_payload.ml
  src/lib/mina_base/payment_payload.mli
  src/lib/mina_base/signed_command.ml
  src/lib/mina_base/signed_command_intf.ml
  src/lib/mina_base/signed_command_payload.ml
  src/lib/mina_base/signed_command_payload.mli
  src/lib/mina_base/unix/graphql_scalars.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_base/zkapp_command.ml
Labels: ci-build-me

#11966 Remove Base58Check chunking
  src/lib/base58_check/base58_check.ml
Labels: ci-build-me

#11977 Nix: build a deb package
  flake.lock
  flake.nix
  nix/debian.nix
Labels: ci-build-me, Tweag, MinaFoundation

#11938 Sparse ledger, no location for empty account
  src/lib/mina_base/sparse_ledger_base.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
Labels: ci-build-me, berkeley-rampup

#11969 Fix kimchi_bindings lockfile
  src/lib/crypto/kimchi_bindings/stubs/Cargo.lock
Labels: ci-build-me, MinaFoundation

#11972 Nix CI: Pre-fetch derivations from cache if missing
  flake.lock
  flake.nix
Labels: ci-build-me, MinaFoundation

#11980 Nix: fix findlib warnings & completions in utop
  flake.lock
Labels: ci-build-me, MinaFoundation

#11968 don't check for fee excess for empty account update zkapp commands
  src/lib/transaction_logic/zkapp_command_logic.ml
Labels: ci-build-me

#11886 Add a README chapter on running the Mina in dev environment.
  README-dev.md
  src/app/rosetta/README.md
Labels: documentation, ci-build-me, MinaFoundation

#11918 Subtract account creation fees from supply increase
  src/lib/integration_test_lib/event_type.ml
  src/lib/mina_base/sparse_ledger_base.ml
  src/lib/mina_base/sparse_ledger_base.mli
  src/lib/mina_base/transaction_status.ml
  src/lib/mina_block/sample_precomputed_block.ml
  src/lib/mina_ledger/ledger.mli
  src/lib/mina_ledger/sparse_ledger.ml
  src/lib/mina_state/local_state.ml
  src/lib/snark_worker/prod.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_logic/zkapp_command_logic.ml
  src/lib/transaction_snark/test/transaction_union/transaction_union.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transaction_snark/test/zkapp_deploy/zkapp_deploy.ml
  src/lib/transaction_snark/test/zkapp_payments/zkapp_payments.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: ci-build-me, berkeley-rampup, berkeley-mainnet

#11843 Update the contribution guide.
  CONTRIBUTING.md
Labels: documentation, ci-build-me, MinaFoundation

#12002 [Trivial] Remove unused `Insecure` library
  src/lib/mina_base/insecure.ml
  src/lib/mina_base/mina_base.ml
Labels: ci-build-me

#11960 Fix /block endpoint in Rosetta
  src/app/rosetta/lib/block.ml
Labels: bug, required-for-release, testnet-bug, ci-build-me, rosetta, MinaFoundation

#12011 Update opam-nix
  flake.lock
Labels: ci-build-me, MinaFoundation

#12013 Add `rosetta-cli` to the nix development shells.
  flake.nix
  nix/go.nix
  nix/impure-shell.nix
Labels: ci-build-me, MinaFoundation

#12012 Add top version tag for Base58Check signatures
  frontend/mina-signer/package.json
  frontend/mina-signer/tests/party.test.ts
  src/lib/mina_base/signature.ml
  src/lib/mina_base/signature_poly.ml
  src/lib/mina_block/sample_precomputed_block.ml
Labels: ci-build-me, berkeley-rampup

#11964 Add optional assertion failure messages to SnarkyJS methods
  src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml
Labels: ci-build-me

#11942 add cancelled status to zkapp commands
  src/lib/mina_base/transaction_status.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_snark/test/account_timing/account_timing.ml
  src/lib/transaction_snark/test/zkapp_fuzzy/zkapp_fuzzy.ml
Labels: ci-build-me

#12018 Nix: rework documentation
  nix/README.md
Labels: ci-build-me, nix-ci, MinaFoundation

#12019 Add a README on setting up sandbox networks manually.
  README-sandbox.md
Labels: documentation, ci-build-me, MinaFoundation

#12022 Remove Signature_poly
  src/lib/mina_base/mina_base.ml
  src/lib/mina_base/signature.ml
  src/lib/mina_base/signature_poly.ml
  src/nonconsensus/mina_base/mina_base_nonconsensus.ml
  src/nonconsensus/mina_base/signature_poly.ml
Labels: ci-build-me

#12023 Update README-sandbox typos
  README-sandbox.md
Labels: ci-build-me

#12021 Generate hash from arbitrary transaction id
  src/app/archive/lib/extensional.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/init/dune
  src/lib/base58_check/version_bytes.ml
  src/lib/crypto/kimchi_backend/common/field.ml
  src/lib/currency/currency.ml
  src/lib/currency/intf.ml
  src/lib/mina_base/account.ml
  src/lib/mina_base/account_id.ml
  src/lib/mina_base/account_id_intf.ml
  src/lib/mina_base/account_update.ml
  src/lib/mina_base/fee_excess.ml
  src/lib/mina_base/fee_transfer.ml
  src/lib/mina_base/fee_transfer_intf.ml
  src/lib/mina_base/payment_payload.ml
  src/lib/mina_base/payment_payload.mli
  src/lib/mina_base/signature.ml
  src/lib/mina_base/signature.mli
  src/lib/mina_base/signed_command.ml
  src/lib/mina_base/signed_command_intf.ml
  src/lib/mina_base/signed_command_memo.ml
  src/lib/mina_base/signed_command_memo.mli
  src/lib/mina_base/signed_command_memo_intf.ml
  src/lib/mina_base/signed_command_payload.ml
  src/lib/mina_base/signed_command_payload.mli
  src/lib/mina_base/stake_delegation.ml
  src/lib/mina_base/token_id.ml
  src/lib/mina_base/zkapp_command.ml
  src/lib/mina_block/precomputed_block.ml
  src/lib/mina_block/precomputed_block.mli
  src/lib/mina_numbers/intf.ml
  src/lib/mina_numbers/nat.ml
  src/lib/mina_wire_types/mina_base/mina_base_account_update.ml
  src/lib/mina_wire_types/mina_base/mina_base_fee_transfer.ml
  src/lib/mina_wire_types/mina_base/mina_base_fee_transfer.mli
  src/lib/mina_wire_types/mina_base/mina_base_minting_payload.ml
  src/lib/mina_wire_types/mina_base/mina_base_new_account_payload.ml
  src/lib/mina_wire_types/mina_base/mina_base_payment_payload.ml
  src/lib/mina_wire_types/mina_base/mina_base_signed_command_payload.ml
  src/lib/mina_wire_types/mina_base/mina_base_token_id.ml
  src/lib/mina_wire_types/test/type_equalities.ml
  src/lib/non_zero_curve_point/non_zero_curve_point.ml
  src/lib/ppx_version/versioned_module.ml
  src/lib/signature_lib/public_key.mli
  src/lib/transaction/dune
  src/lib/transaction/transaction_hash.ml
  src/lib/transaction/transaction_hash.mli
  src/lib/transaction_logic/zkapp_command_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_witness/transaction_witness.ml
  src/lib/transaction_witness/transaction_witness.mli
  src/lib/unsigned_extended/unsigned_extended.ml
  src/lib/unsigned_extended/unsigned_extended.mli
Labels: ci-build-me

#12017 Update nix README on "ignoring untrusted substituter" warning
  nix/README.md
Labels: ci-build-me, MinaFoundation

#12026 Fix use of Format in printers
  src/app/cli/src/init/client.ml
  src/lib/cli_lib/commands.ml
  src/lib/mina_metrics/prometheus_metrics/mina_metrics.ml
  src/lib/snark_worker/standalone/run_snark_worker.ml
  src/lib/transaction_consistency_tests/transaction_consistency_tests.ml
  src/lib/transaction_snark/transaction_snark.ml
Labels: refactor, cleanup, ci-build-me

#11961 Minor updates for flake
  flake.nix
  nix/README.md
Labels: ci-build-me, nix

#11962 Remove warning 16
  src/app/archive/lib/test.ml
  src/lib/mina_base/coinbase.ml
  src/lib/mina_base/coinbase_fee_transfer.ml
  src/lib/mina_base/coinbase_fee_transfer_intf.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.mli
  src/lib/transition_frontier/transition_frontier.ml
Labels: ci-build-me

#12035 9332 properly fix ci for rosetta ensure tests are running and passing on all prs
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/network.ml
Labels: ci-build-me, rosetta, MinaFoundation

#12043 Tests for latest command versions
  src/lib/mina_base/signed_command.ml
  src/lib/mina_base/zkapp_command.ml
Labels: ci-build-me

#12049 lk86/deploy-new-alert-rules
  automation/terraform/modules/testnet-alerts/templates/testnet-alert-rules.yml.tpl
Labels: ci-build-me

#12036 JS crypto revived
  Makefile
  frontend/mina-signer/package.json
  frontend/mina-signer/src/MinaSigner.ts
  src/app/client_sdk/dune
  src/app/client_sdk/tests/client_sdk.js
  src/app/client_sdk/tests/run_unit_tests.js
  src/app/client_sdk/tests/test_encodings.js
  src/app/client_sdk/tests/test_hash.js
  src/app/client_sdk/tests/test_signatures.js
  src/lib/crypto/kimchi_bindings/js/js_backend/bigint256.js
  src/lib/crypto/kimchi_bindings/js/js_backend/bigint_helpers.js
  src/lib/crypto/kimchi_bindings/js/js_backend/dune
  src/lib/crypto/kimchi_bindings/js/js_backend/elliptic_curve.js
  src/lib/crypto/kimchi_bindings/js/js_backend/finite_field.js
  src/lib/crypto/kimchi_bindings/js/js_backend/vector.js
  src/lib/pickles/step.ml
  src/lib/pickles/unfinalized.ml
Labels: ci-build-me

#11667 Add roundtrip test for GraphQL scalar types
  src/lib/blake2/blake2.ml
  src/lib/blake2/intf.ml
  src/lib/block_time/unix/dune
  src/lib/block_time/unix/graphql_scalars.ml
  src/lib/consensus/dune
  src/lib/consensus/graphql_scalars.ml
  src/lib/currency/unix/dune
  src/lib/currency/unix/graphql_scalars.ml
  src/lib/data_hash_lib/unix/dune
  src/lib/data_hash_lib/unix/graphql_scalars.ml
  src/lib/filtered_external_transition/dune
  src/lib/filtered_external_transition/filtered_external_transition.ml
  src/lib/filtered_external_transition/unix/dune
  src/lib/filtered_external_transition/unix/graphql_scalars.ml
  src/lib/graphql_basic_scalars/dune
  src/lib/graphql_basic_scalars/graphql_basic_scalars.ml
  src/lib/graphql_basic_scalars/testing.ml
  src/lib/graphql_basic_scalars/utils.ml
  src/lib/graphql_lib/dune
  src/lib/mina_base/staged_ledger_hash.ml
  src/lib/mina_base/staged_ledger_hash_intf.ml
  src/lib/mina_base/unix/dune
  src/lib/mina_base/unix/graphql_scalars.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_block/unix/dune
  src/lib/mina_block/unix/graphql_scalars.ml
  src/lib/mina_numbers/unix/dune
  src/lib/mina_numbers/unix/graphql_scalars.ml
  src/lib/pickles/unix/dune
  src/lib/pickles/unix/graphql_scalars.ml
  src/lib/signature_lib/unix/dune
  src/lib/signature_lib/unix/graphql_scalars.ml
  src/lib/snark_params/snark_params.ml
  src/lib/snark_params/unix/dune
  src/lib/snark_params/unix/graphql_scalars.ml
  src/lib/transaction/unix/dune
  src/lib/transaction/unix/graphql_scalars.ml
  src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml
Labels: ci-build-me, MinaFoundation

#12027 [nix] update ocaml-lsp
  flake.lock
  nix/ocaml.nix
Labels: ci-build-me

#12034 Add Rosetta Unit Tests
  buildkite/src/Jobs/Test/RosettaUnitTest.dhall
Labels: ci-build-me, rosetta, MinaFoundation

#11985 Add `Zkapp_examples` tests for delegate calls
  src/lib/transaction_snark/test/zkapps_examples/calls/calls.ml
  src/lib/zkapps_examples/calls/dune
  src/lib/zkapps_examples/calls/zkapps_calls.ml
  src/lib/zkapps_examples/zkapps_examples.ml
Labels: ci-build-me
