Repository MinaProtocol/mina, pull requests merged in 2022-11, with the labels that each got.

#12052 Add minimal interface files to modules in library pickles_types
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/pickles/composition_types/composition_types.ml
  src/lib/pickles/intf.ml
  src/lib/pickles_types/abc.ml
  src/lib/pickles_types/abc.mli
  src/lib/pickles_types/at_most.ml
  src/lib/pickles_types/at_most.mli
  src/lib/pickles_types/dune
  src/lib/pickles_types/higher_kinded_poly.ml
  src/lib/pickles_types/hlist0.ml
  src/lib/pickles_types/hlist0.mli
  src/lib/pickles_types/matrix_evals.ml
  src/lib/pickles_types/nat.ml
  src/lib/pickles_types/nat.mli
  src/lib/pickles_types/or_infinity.mli
  src/lib/pickles_types/plonk_types.ml
  src/lib/pickles_types/plonk_types.mli
  src/lib/pickles_types/plonk_verification_key_evals.ml
  src/lib/pickles_types/plonk_verification_key_evals.mli
  src/lib/pickles_types/poly_types.mli
  src/lib/pickles_types/shifted_value.ml
  src/lib/pickles_types/shifted_value.mli
  src/lib/pickles_types/sigs.mli
  src/lib/pickles_types/vector.ml
  src/lib/pickles_types/vector.mli
Labels: refactor, ready for review, cleanup, ci-build-me

#12006 Rosetta: add operation types related to zkApps.
  src/lib/rosetta_lib/operation_types.ml
Labels: required-for-release, ci-build-me, rosetta, MinaFoundation

#12098 Fix pickles compilation errors
  src/lib/crypto/kimchi_backend/pasta/kimchi_pasta.ml
  src/lib/crypto/kimchi_backend/pasta/kimchi_pasta.mli
  src/lib/pickles/precomputed/gen_values/gen_values.ml
Labels: ci-build-me

#12008 Move zkapp_uri to Zkapp_account
  src/app/archive/lib/load_data.ml
  src/app/archive/lib/processor.ml
  src/app/replayer/test/archive_db.sql
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/mina_base/account.ml
  src/lib/mina_base/account_update.ml
  src/lib/mina_base/zkapp_account.ml
  src/lib/mina_block/sample_precomputed_block.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/transaction_logic/mina_transaction_logic.ml
  src/lib/transaction_logic/zkapp_command_logic.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark_intf.ml
Labels: ci-build-me, berkeley-rampup

#12039 Avoid using List.length in comparing the length of a list
  src/app/swap_bad_balances/dune
  src/app/swap_bad_balances/swap_bad_balances.ml
  src/app/test_executive/block_production_priority.ml
  src/app/test_executive/dune
  src/app/test_executive/test_common.ml
  src/app/test_executive/test_executive.ml
  src/lib/bootstrap_controller/dune
  src/lib/bootstrap_controller/transition_cache.ml
  src/lib/consensus/dune
  src/lib/consensus/proof_of_stake_fuzzer.ml
  src/lib/genesis_ledger_helper/lib/dune
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/integration_test_cloud_engine/dune
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
  src/lib/merkle_ledger_tests/dune
  src/lib/merkle_ledger_tests/test_database.ml
  src/lib/merkle_ledger_tests/test_mask.ml
  src/lib/mina_lib/dune
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_net2/tests/all_ipc.ml
  src/lib/mina_net2/tests/dune
  src/lib/mina_stdlib/dune
  src/lib/mina_stdlib/list.ml
  src/lib/mina_stdlib/list.mli
  src/lib/mina_stdlib/sigs.mli
  src/lib/ppx_version/bin_io_unversioned.ml
  src/lib/ppx_version/versioned_type.ml
  src/lib/rosetta_coding/coding.ml
  src/lib/rosetta_coding/dune
  src/lib/rosetta_lib/dune
  src/lib/rosetta_lib/user_command_info.ml
  src/lib/snark_bits/bits.ml
  src/lib/snark_bits/dune
  src/lib/snarky_blake2/dune
  src/lib/snarky_blake2/uint32.ml
  src/mina_stdlib.opam
Labels: enhancement, ready for review, ci-build-me

#11890 Nix: rework docker image building & uploading (develop)
  flake.nix
  nix/docker.nix
  nix/ocaml.nix
Labels: ci-build-me, nix-ci, MinaFoundation

#12069 Rosetta: Add instructions and config to run rosetta-cli tests.
  README-sandbox.md
  src/app/rosetta/README.md
  src/app/rosetta/rosetta-cli-config/README.md
  src/app/rosetta/rosetta-cli-config/config.json
  src/app/rosetta/rosetta-cli-config/mina.ros
Labels: ci-build-me, rosetta, MinaFoundation

#11898 Add interface files to `lib/pickles_base`
  src/lib/pickles_base/domain.mli
  src/lib/pickles_base/domains.mli
  src/lib/pickles_base/proofs_verified.ml
  src/lib/pickles_base/proofs_verified.mli
  src/lib/pickles_base/side_loaded_verification_key.ml
  src/lib/pickles_base/side_loaded_verification_key.mli
Labels: refactor, cleanup, ci-build-me, code quality

#12054 Change node imports for builtin modules that use an absolute URL
  flake.nix
  frontend/mina-signer/package-lock.json
  frontend/mina-signer/package.json
  src/app/client_sdk/dune
  src/lib/crypto/kimchi_bindings/js/js_backend/finite_field.js
  src/lib/snarky_js_bindings/test_module/cached.js
Labels: ci-build-me

#11651 Bump ledger depth
  src/config/devnet.mlh
  src/config/ledger_depth/full.mlh
  src/config/mainnet.mlh
Labels: P0, ci-build-me, berkeley-rampup

#12107 Activate warnings for library `Pickles_base`
  src/lib/pickles_base/domain.ml
  src/lib/pickles_base/dune
  src/lib/pickles_base/proofs_verified.ml
  src/lib/pickles_base/proofs_verified.mli
  src/lib/pickles_base/side_loaded_verification_key.ml
Labels: refactor, cleanup, code quality

#11698 Fix for recursion when max_proofs_verified = 1
  src/app/test_executive/dune
  src/app/test_executive/zkapps.ml
  src/lib/integration_test_lib/event_type.ml
  src/lib/pickles/pickles.ml
  src/lib/pickles/requests.ml
  src/lib/pickles/step.ml
  src/lib/pickles/step_branch_data.ml
  src/lib/pickles/step_main.ml
  src/lib/pickles/step_verifier.ml
  src/lib/pickles/unfinalized.ml
  src/lib/pickles/util.ml
  src/lib/pickles/verify.ml
  src/lib/pickles/wrap.ml
  src/lib/pickles/wrap_hack.ml
  src/lib/pickles/wrap_main.ml
  src/lib/pickles/wrap_verifier.ml
  src/lib/pickles_base/proofs_verified.ml
  src/lib/pickles_types/vector.ml
  src/lib/pickles_types/vector.mli
  src/lib/snark_worker/prod.ml
Labels: ci-build-me

#11958 Update the generated code.
  src/lib/crypto/kimchi_bindings/stubs/kimchi_bindings.ml
  src/lib/crypto/kimchi_bindings/stubs/kimchi_types.ml
  src/lib/pickles/plonk_checks/scalars.ml
Labels: ci-build-me, MinaFoundation

#12227 Remove redundant authorization kind
  src/app/archive/drop_tables.sql
  src/app/archive/lib/processor.ml
  src/app/archive/zkapp_tables.sql
  src/app/replayer/replayer.ml
  src/lib/mina_base/account_update.ml
  src/lib/mina_base/control.ml
  src/lib/mina_wire_types/mina_base/mina_base_account_update.ml
Labels: berkeley-rampup

#12010 Rosetta: endpoint changes to support legacy tx support.
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
Labels: ci-build-me, rosetta, MinaFoundation

#12163 Rosetta: Expand the documentation on running rosetta-cli tool.
  src/app/rosetta/rosetta-cli-config/README.md
  src/app/rosetta/rosetta-cli-config/config.json
Labels: documentation, rosetta, MinaFoundation

#12164 Rosetta: fix transaction_exists sql query
  src/app/rosetta/lib/construction.ml
Labels: rosetta, MinaFoundation

#12215 mina-signer - Bump version to 1.6.0
  frontend/mina-signer/package-lock.json
  frontend/mina-signer/package.json
Labels: ci-build-me

#12233 Update opam-nix, add per-editor instructions to Nix readme
  flake.lock
  nix/README.md
  nix/ocaml.nix
Labels: ci-build-me, MinaFoundation

#12204 11194 - Rosetta - Pull archive backup to older days if today does not exit
  src/app/rosetta/init-db.sh
Labels: ci-build-me, rosetta, MinaFoundation

#12251 12250 - Update Rosetta CLI Config, to handle offline mode
  src/app/rosetta/rosetta-cli-config/config.json
Labels: ci-build-me, rosetta, MinaFoundation

#12265 12099 - Create Integration test scripts for Rosetta API
  buildkite/scripts/rosetta-integration-tests.sh
Labels: ci-build-me, rosetta, MinaFoundation

#12197 Fix warnings 16
  src/app/archive/lib/test.ml
  src/lib/mina_base/fee_transfer.ml
  src/lib/mina_base/fee_transfer_intf.ml
  src/lib/mina_base/payment_payload.ml
  src/lib/mina_base/payment_payload.mli
  src/lib/mina_base/signed_command_payload.ml
Labels: refactor, code quality

#12287 Nix: split overlays further, improve documentation
  flake.nix
  nix/README.md
  nix/javascript.nix
  nix/misc.nix
  nix/ocaml.nix
  nix/pin.sh
  nix/rust.nix
Labels: ci-build-me, MinaFoundation

#11971 Sync ledger for epoch ledger download
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/app/cli/src/tests/coda_processes.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/child_processes/README.md
  src/lib/child_processes/child_processes.ml
  src/lib/child_processes/child_processes.mli
  src/lib/cli_lib/flag.mli
  src/lib/consensus/consensus_intf.ml
  src/lib/consensus/dune
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_base/epoch_seed.ml
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_ledger/ledger.ml
  src/lib/mina_ledger/sync_ledger.ml
  src/lib/mina_lib/dune
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/mina_lib/tests/dune
  src/lib/mina_lib/tests/tests.ml
  src/lib/mina_net2/libp2p_helper.ml
  src/lib/mina_net2/libp2p_helper.mli
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/mina_net2/multiaddr.ml
  src/lib/mina_net2/multiaddr.mli
  src/lib/mina_net2/tests/all_ipc.ml
  src/lib/mina_net2/tests/tests.ml
  src/lib/mina_networking/mina_networking.ml
  src/lib/mina_networking/mina_networking.mli
  src/lib/network_pool/snark_pool.ml
  src/lib/network_pool/snark_pool.mli
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/transition_router/transition_router.ml
  src/mina_lib_tests.opam
Labels: berkeley-rampup

#11473 Gcp cleanups
  src/lib/integration_test_cloud_engine/kubernetes_network.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_cloud_engine/stack_driver_log_engine.ml
Labels: ci-build-me
