Repository MinaProtocol/mina, pull requests merged in 2023-12, with the labels that each got.

#14285 Improve fork config generation for develop.
  src/lib/mina_graphql/dune
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
Labels: hard fork, MinaFoundation

#14702 Berkeley migration test imprv
  src/app/berkeley_migration/berkeley_migration.ml
  src/app/berkeley_migration/precomputed_block.ml
Labels: berkeley-mainnet

#14138 [RFC] Stop processing transactions and stop network after certain slots
  rfcs/0055-stop-transaction-processing.md
Labels: berkeley-mainnet

#14731 Fix genesis ledger directory growing in size
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
Labels: MinaFoundation

#14558 Small package of fixes for migration process
  src/app/archive/lib/processor.ml
  src/app/archive/lib/test.ml
  src/app/berkeley_migration/berkeley_migration.ml
  src/lib/base58_check/version_bytes.ml
  src/lib/blake2/blake2.ml
  src/lib/blake2/intf.ml
  src/lib/transaction/transaction_hash.ml
  src/lib/transaction/transaction_hash.mli
Labels: berkeley-mainnet
