Repository MinaProtocol/mina, pull requests merged in 2024-10, with the labels that each got.

#16145 Refactor transition router
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/bootstrap_controller.mli
  src/lib/bootstrap_controller/transition_cache.ml
  src/lib/bootstrap_controller/transition_cache.mli
  src/lib/mina_block/header.ml
  src/lib/mina_block/header_intf.ml
  src/lib/mina_block/mina_block.ml
  src/lib/mina_block/validation.ml
  src/lib/mina_block/validation.mli
  src/lib/mina_block/validation_types.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_router/transition_router.ml
Labels: bitswap

#16206 Work_selector: small cleanup
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/work_selector/intf.ml
  src/lib/work_selector/random.ml
  src/lib/work_selector/random_offset.ml
  src/lib/work_selector/sequence.ml
  src/lib/work_selector/test.ml
  src/lib/work_selector/work_lib.ml
  src/lib/work_selector/work_selector.ml
  src/lib/work_selector/work_selector.mli
Labels: code quality

#16164 Use headers for v1 pubsub block topic
  src/lib/best_tip_prover/best_tip_prover.ml
  src/lib/block_producer/block_producer.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/bootstrap_controller/bootstrap_controller.mli
  src/lib/gossip_net/fake.ml
  src/lib/gossip_net/intf.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/gossip_net/message.ml
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/mina_block/mina_block.ml
  src/lib/mina_block/validation.ml
  src/lib/mina_block/validation.mli
  src/lib/mina_block/validation_types.ml
  src/lib/mina_commands/mina_commands.ml
  src/lib/mina_intf/transition_frontier_components_intf.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/mina_lib/tests/tests.ml
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier_controller/dune
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/block_sink.ml
  src/lib/transition_handler/block_sink.mli
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
  src/lib/transition_handler/validator.ml
  src/lib/transition_router/initial_validator.ml
  src/lib/transition_router/transition_router.ml
Labels: bitswap

#16222 Block_producer: move code outside of run
  src/lib/block_producer/block_producer.ml
Labels: bitswap, code quality

#16072 Bitswap: rename `deleteXX` to `removeXX`, add tag to IPC
  src/app/libp2p_helper/src/libp2p_helper/bitswap.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_delete.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_msg.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_test.go
  src/app/libp2p_helper/src/libp2p_helper/error.go
  src/app/libp2p_helper/src/libp2p_helper/incoming_msg.go
  src/app/libp2p_helper/src/libp2p_helper/msg.go
  src/lib/mina_net2/libp2p_helper.ml
  src/libp2p_ipc/libp2p_ipc.capnp
  src/libp2p_ipc/libp2p_ipc.ml
  src/libp2p_ipc/libp2p_ipc.mli
Labels: bitswap

#16073 Add referencing for safe removal of unused Bitswap blocks
  nix/libp2p_helper.json
  src/app/libp2p_helper/Makefile
  src/app/libp2p_helper/src/bitswap_storage.go
  src/app/libp2p_helper/src/codanet.go
  src/app/libp2p_helper/src/go.mod
  src/app/libp2p_helper/src/go.sum
  src/app/libp2p_helper/src/libp2p_helper/bitswap.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_delete.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader.go
  src/app/libp2p_helper/src/libp2p_helper/bitswap_downloader_test.go
  src/app/libp2p_helper/src/libp2p_helper/config_msg_test.go
  src/app/libp2p_helper/src/libp2p_helper/util_test.go
Labels: bitswap

#16232 Remove dead block storage library
  src/lib/block_storage/block_storage.ml
  src/lib/block_storage/block_storage.mli
  src/lib/block_storage/dune
Labels: bitswap

#16233 Remove unused block window duration arguments
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/client.ml
  src/lib/gossip_net/libp2p.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/tests/tests.ml
  src/lib/mina_net2/mina_net2.ml
  src/lib/mina_net2/mina_net2.mli
  src/lib/mina_net2/subscription.ml
  src/lib/mina_net2/subscription.mli
  src/lib/mina_net2/tests/all_ipc.ml
  src/lib/mina_net2/tests/tests.ml
  src/lib/mina_net2/validation_callback.ml
  src/lib/mina_net2/validation_callback.mli
  src/lib/network_pool/network_pool_base.ml
  src/lib/network_pool/pool_sink.ml
  src/lib/transition_handler/block_sink.ml
  src/lib/transition_handler/block_sink.mli
  src/lib/transition_handler/catchup_scheduler.ml
  src/lib/transition_handler/processor.ml
Labels: bitswap

#16055 Optimize the non-present zkapp uri hashing
  src/lib/mina_base/zkapp_account.ml
  src/lib/mina_base/zkapp_call_forest.ml
  src/lib/mina_ledger/ledger.ml
Labels: performance
