Repository MinaProtocol/mina, pull requests merged in 2024-01, with the labels that each got.

#14644 Soft limit zkApp commands per block
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/devnet.mlh
  src/config/fake_hash.mlh
  src/config/fork.mlh
  src/config/fork_at_3757.mlh
  src/config/fuzz_medium.mlh
  src/config/fuzz_small.mlh
  src/config/integration_tests.mlh
  src/config/lightnet.mlh
  src/config/mainnet.mlh
  src/config/nonconsensus_mainnet.mlh
  src/config/nonconsensus_medium_curves.mlh
  src/config/print_versioned_types.mlh
  src/config/test_archive_processor.mlh
  src/config/test_postake.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_full_epoch.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_three_producers.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_producers.mlh
  src/config/testnet_postake_many_producers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/config/txpool_size.mlh
  src/lib/block_producer/block_producer.ml
  src/lib/mina_base/test/helpers/dune
  src/lib/mina_base/test/helpers/test_account.ml
  src/lib/mina_base/test/helpers/zkapp_cmd_builder.ml
  src/lib/mina_compile_config/mina_compile_config.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_ledger/test/helpers/dune
  src/lib/mina_ledger/test/helpers/ledger_helpers.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/staged_ledger.mli
  src/lib/staged_ledger/test/dune
  src/lib/staged_ledger/test/main.ml
  src/lib/staged_ledger/test/txn_application_test.ml
  src/lib/transaction_logic/test/dune
  src/lib/transaction_logic/test/helpers.ml
  src/lib/transaction_logic/test/predicates.ml
  src/lib/transaction_logic/test/transaction_logic/dune
  src/lib/transaction_logic/test/transaction_logic/transaction_logic.ml
  src/lib/transaction_logic/test/zkapp_logic.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
Labels: daemon, MinaFoundation

#14137 Remove delegation integration test
  buildkite/src/Jobs/Test/TestnetIntegrationTests.dhall
  src/app/test_executive/delegation_test.ml
  src/app/test_executive/delegation_test.mli
  src/app/test_executive/payments_test.ml
  src/app/test_executive/test_executive.ml
Labels: dev velocity

#14785 Fix duplicated rows in zkapp_account_precondition table
  scripts/archive/zkapp_duplicated_precondition/add_constraint.sql
  scripts/archive/zkapp_duplicated_precondition/remove_duplicated_zkapp_account_precondition_rows.sh
  src/app/archive/zkapp_tables.sql
Labels: priority-high, itn3, Testworld-2-0-archive-node

#14402 Reset feature flags before assertion
  src/lib/pickles/step.ml
Labels: berkeley-incentivized

#14637 Pickles: use Alcotest for unit tests of module `Wrap`
  src/lib/pickles/test/main.ml
  src/lib/pickles/test/test_wrap.ml
  src/lib/pickles/wrap.ml
  src/lib/pickles/wrap.mli
Labels: tests, pickles

#9073 Add comment with reference for VRF
  src/lib/vrf_lib/integrated.ml
  src/lib/vrf_lib/standalone.ml
Labels: ci-build-me

#14720 refactor to merge replayer and berkeley_account_tables app
  buildkite/scripts/build-artifact.sh
  scripts/archive/build-release-archives.sh
  src/app/berkeley_account_tables/berkeley_account_tables.ml
  src/app/berkeley_account_tables/dune
  src/app/berkeley_account_tables/sql.ml
  src/app/replayer/replayer.ml
  src/dune-project
Labels: P0

#14835 Fix rosetta block query
  src/app/rosetta/lib/block.ml
Labels: bug, P0, rosetta, MinaFoundation

#14797 [develop] Script to generate ledger tar from config with accounts
  CODEOWNERS
  scripts/generate_ledgers_tar_from_config.sh
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/runtime_genesis_ledger/.ocamlformat
  src/app/runtime_genesis_ledger/dune
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/runtime_config/runtime_config.ml
Labels: hard fork, MinaFoundation

#14868 Improve fork config generation develop
  src/app/ledger_export_bench/README.md
  src/app/ledger_export_bench/dune
  src/app/ledger_export_bench/ledger_export_benchmark.ml
  src/app/test_executive/hard_fork.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/mina_graphql/dune
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
Labels: P0, hard fork, MinaFoundation

#14266 Improve fork config generation
  src/app/ledger_export_bench/README.md
  src/app/ledger_export_bench/dune
  src/app/ledger_export_bench/ledger_export_benchmark.ml
  src/lib/mina_graphql/dune
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
Labels: P0, hard fork, MinaFoundation

#14793 [berkeley] Script to generate ledger tar from config with accounts
  scripts/generate_ledgers_tar_from_config.sh
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/runtime_genesis_ledger/.ocamlformat
  src/app/runtime_genesis_ledger/dune
  src/app/runtime_genesis_ledger/runtime_genesis_ledger.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/runtime_config/runtime_config.ml
Labels: P0, hard fork, MinaFoundation

#14888 Fix issues with the Rosetta API block queries
  nix/go.nix
  src/app/rosetta/lib/block.ml
Labels: bug, P0, rosetta, hard fork, MinaFoundation

#14917 Ledger export upgrades – into berkeley
  graphql_schema.json
  src/app/ledger_export_bench/ledger_export_benchmark.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
Labels: P0, hard fork, MinaFoundation

#14889 Ledger export upgrades
  graphql_schema.json
  src/app/ledger_export_bench/ledger_export_benchmark.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
Labels: P0, hard fork, MinaFoundation

#14907 more exhaustive timing tests
  src/app/test_executive/hard_fork.ml
Labels: P1

#14356 Batch to_verifiable ledger operations, and fix caching logic
  src/lib/mina_base/user_command.ml
  src/lib/mina_base/zkapp_command.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/snark_profiler_lib/snark_profiler_lib.ml
  src/lib/staged_ledger/dune
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark_intf.ml
Labels: P1

#8951 [RFC] Networking Refactor
  rfcs/0060-networking-refactor.md
Labels: ci-build-me

#9162 [RFC] Bitswap
  rfcs/0062-bitswap.md
Labels: ci-build-me

#14675 [RFC] Reducing daemon memory usage
  rfcs/0063-reducing-daemon-memory-usage.md
  src/app/disk_caching_stats/README.md
  src/app/disk_caching_stats/disk_caching_stats.ml
  src/app/disk_caching_stats/dune
  src/dune-project
Labels: P2

#14950 Merge back to develop
  buildkite/src/Jobs/Lint/Merge.dhall
  nix/go.nix
  src/app/rosetta/lib/block.ml
  src/app/test_executive/hard_fork.ml
  src/lib/mina_base/user_command.ml
  src/lib/mina_base/zkapp_command.ml
  src/lib/mina_generators/user_command_generators.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/o1trace/o1trace.ml
  src/lib/snark_profiler_lib/snark_profiler_lib.ml
  src/lib/staged_ledger/dune
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark_intf.ml
Labels: P0

#14953 Use first pass ledger for snarked ledger everywhere
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/ledger_proof/ledger_proof.ml
  src/lib/ledger_proof/ledger_proof_intf.ml
  src/lib/mina_block/validation.ml
  src/lib/mina_state/blockchain_state.ml
  src/lib/mina_state/protocol_state.ml
  src/lib/mina_state/protocol_state_intf.ml
  src/lib/mina_state/snarked_ledger_state.ml
  src/lib/mina_state/snarked_ledger_state_intf.ml
  src/lib/transition_frontier/frontier_base/breadcrumb.ml
Labels: P1

#14947 [rampup] Add 'merges cleanly to rampup' CI job
  buildkite/src/Jobs/Lint/Merge.dhall
Labels: P1

#14939 Docs readme typo fix
  docs/README.md
Labels: documentation

#10281 snapps test tool usage doc
  src/app/zkapp_test_transaction/README.md
  src/app/zkapp_test_transaction/res/account-after-deploy.png
  src/app/zkapp_test_transaction/res/account-after-setting-permissions.png
  src/app/zkapp_test_transaction/res/account-after-state-update.png
  src/app/zkapp_test_transaction/res/deploy-zkapp.png
Labels: ci-build-me

#14975 Add system / resource usage to status reports.
  src/lib/node_status_service/dune
  src/lib/node_status_service/node_status_service.ml
Labels: daemon, node status, MinaFoundation

#14938 ignore snarked ledger hash in `global_slot_hashes_tbl` in migration_mode
  src/app/replayer/replayer.ml
Labels: P0

#14977 ignore first-pass-ledger-hashes in migration-mode
  src/app/replayer/replayer.ml
Labels: P0

#14966 add config for mainnet version
  buildkite/src/Constants/Profiles.dhall
  src/app/archive/patch_migrated_db.sql
  src/app/replayer/replayer.ml
  src/config/berkeley_archive_migration.mlh
  src/config/protocol_version/version1.mlh
Labels: P0

#14946 update timing info
  buildkite/src/Constants/Profiles.dhall
  src/app/archive/create_schema.sql
  src/app/archive/lib/processor.ml
  src/app/archive/patch_migrated_db.sql
  src/app/replayer/replayer.ml
  src/app/rosetta/lib/account.ml
  src/config/berkeley_archive_migration.mlh
  src/config/protocol_version/version1.mlh
Labels: P0

#14991 Refactoring Merkle Mask
  src/lib/merkle_mask/base_merkle_tree_intf.mli
  src/lib/merkle_mask/dune
  src/lib/merkle_mask/inputs_intf.mli
  src/lib/merkle_mask/maskable_merkle_tree.ml
  src/lib/merkle_mask/maskable_merkle_tree.mli
  src/lib/merkle_mask/maskable_merkle_tree_intf.mli
  src/lib/merkle_mask/masking_merkle_tree.ml
  src/lib/merkle_mask/masking_merkle_tree.mli
  src/lib/merkle_mask/masking_merkle_tree_intf.mli
Labels: code quality

#14516 [compatible] Stop txn/network after slot feature
  src/app/test_executive/dune
  src/app/test_executive/slot_end_test.ml
  src/app/test_executive/slot_end_test.mli
  src/app/test_executive/test_executive.ml
  src/config/debug.mlh
  src/config/dev.mlh
  src/config/dev_medium_curves.mlh
  src/config/dev_snark.mlh
  src/config/devnet.mlh
  src/config/fake_hash.mlh
  src/config/fuzz_medium.mlh
  src/config/fuzz_small.mlh
  src/config/integration_tests.mlh
  src/config/mainnet.mlh
  src/config/nonconsensus_mainnet.mlh
  src/config/nonconsensus_medium_curves.mlh
  src/config/print_versioned_types.mlh
  src/config/test_archive_processor.mlh
  src/config/test_postake.mlh
  src/config/test_postake_catchup.mlh
  src/config/test_postake_five_even_txns.mlh
  src/config/test_postake_full_epoch.mlh
  src/config/test_postake_holy_grail.mlh
  src/config/test_postake_medium_curves.mlh
  src/config/test_postake_snarkless.mlh
  src/config/test_postake_snarkless_medium_curves.mlh
  src/config/test_postake_split.mlh
  src/config/test_postake_split_medium_curves.mlh
  src/config/test_postake_three_producers.mlh
  src/config/testnet_postake.mlh
  src/config/testnet_postake_many_producers.mlh
  src/config/testnet_postake_many_producers_medium_curves.mlh
  src/config/testnet_postake_medium_curves.mlh
  src/config/testnet_postake_snarkless.mlh
  src/config/testnet_postake_snarkless_fake_hash.mlh
  src/config/testnet_public.mlh
  src/lib/block_producer/block_producer.ml
  src/lib/block_producer/dune
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/integration_test_cloud_engine/mina_automation.ml
  src/lib/integration_test_lib/graphql_requests.ml
  src/lib/integration_test_lib/test_config.ml
  src/lib/ledger_catchup/dune
  src/lib/ledger_catchup/normal_catchup.ml
  src/lib/ledger_catchup/super_catchup.ml
  src/lib/mina_compile_config/dune
  src/lib/mina_compile_config/mina_compile_config.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/network_pool/indexed_pool.mli
  src/lib/network_pool/intf.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/runtime_config/dune
  src/lib/runtime_config/runtime_config.ml
  src/lib/transaction_inclusion_status/transaction_inclusion_status.ml
  src/lib/transition_frontier_controller/transition_frontier_controller.ml
  src/lib/transition_handler/dune
  src/lib/transition_handler/validator.ml
Labels: P0, hard fork, MinaFoundation
