Repository MinaProtocol/mina, pull requests merged in 2024-02, with the labels that each got.

#15008 Fix Rosetta SQL queries and improve Rosetta integration test reliance
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/rosetta-cli-config/config.json
Labels: rosetta, hard fork, MinaFoundation

#15021 [develop] Fix Rosetta SQL queries and improve Rosetta integration test reliance
  src/app/rosetta/lib/account.ml
  src/app/rosetta/lib/block.ml
  src/app/rosetta/rosetta-cli-config/config.json
Labels: rosetta, MinaFoundation

#14944 Fix/replayer use global slot from previous state
  scripts/monitor.sh
  src/app/archive/create_schema.sql
  src/app/archive/lib/processor.ml
  src/app/archive/patch_migrated_db.sql
  src/app/replayer/replayer.ml
  src/app/rosetta/lib/account.ml
  src/config/berkeley_archive_migration.mlh
  src/config/protocol_version/version1.mlh
  src/lib/transaction_logic/mina_transaction_logic.ml
Labels: P0

#15017 Test Rosetta with time-vesting accounts
  buildkite/scripts/rosetta-integration-tests.sh
  buildkite/src/Constants/DebianVersions.dhall
  src/app/rosetta/rosetta-cli-config/config.json
Labels: rosetta, MinaFoundation

#15077 Fork_config loses previous_ label
  src/config/fork.mlh
  src/config/fork_at_3757.mlh
  src/lib/blockchain_snark/blockchain_snark_state.ml
  src/lib/consensus/constants.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/genesis_constants/genesis_constants.ml
  src/lib/genesis_ledger_helper/lib/genesis_ledger_helper_lib.ml
  src/lib/mina_state/genesis_protocol_state.ml
  src/lib/network_pool/indexed_pool.ml
  src/lib/runtime_config/runtime_config.ml
  src/lib/snark_keys_header/snark_keys_header.ml
Labels: P0

#15081 Memoize Rosetta API GraphQL requests for genesis info
  src/app/rosetta/lib/block.ml
  src/app/rosetta/lib/network.ml
Labels: MinaFoundation

#14942 Hardfork data migration cron job
  helm/cron_jobs/berkeley-migration-complete-cronjob/.helmignore
  helm/cron_jobs/berkeley-migration-complete-cronjob/Chart.yaml
  helm/cron_jobs/berkeley-migration-complete-cronjob/README.md
  helm/cron_jobs/berkeley-migration-complete-cronjob/files/migration.sh
  helm/cron_jobs/berkeley-migration-complete-cronjob/files/test-run.sh
  helm/cron_jobs/berkeley-migration-complete-cronjob/templates/NOTES.txt
  helm/cron_jobs/berkeley-migration-complete-cronjob/templates/_helpers.tpl
  helm/cron_jobs/berkeley-migration-complete-cronjob/templates/cronjobs.yaml
  helm/cron_jobs/berkeley-migration-complete-cronjob/templates/gcloud-secret.yaml
  helm/cron_jobs/berkeley-migration-complete-cronjob/values.yaml
Labels: berkeley-rampup, berkeley-mainnet, Testworld-2-0-archive-node

#14593 The stateless verification tool
  dockerfiles/Dockerfile-delegation-stateless-verifier
  src/app/delegation_verify/README.md
  src/app/delegation_verify/cassandra.ml
  src/app/delegation_verify/cassandra.mli
  src/app/delegation_verify/delegation_verify.ml
  src/app/delegation_verify/delegation_verify.opam
  src/app/delegation_verify/dune
  src/app/delegation_verify/known_blocks.ml
  src/app/delegation_verify/output.ml
  src/app/delegation_verify/scripts/authenticate.sh
  src/app/delegation_verify/submission.ml
  src/app/delegation_verify/verifier.ml
Labels: MinaFoundation

#15140 Cli_lib: correctly mark alert as deprecated
  src/lib/cli_lib/commands.ml
Labels: code quality

#15141 Refactoring `Merkle_ledger`
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/any_ledger.mli
  src/lib/merkle_ledger/base_inputs_intf.ml
  src/lib/merkle_ledger/base_ledger_intf.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/database.mli
  src/lib/merkle_ledger/database_intf.ml
  src/lib/merkle_ledger/dune
  src/lib/merkle_ledger/graphviz.ml
  src/lib/merkle_ledger/graphviz.mli
  src/lib/merkle_ledger/intf.ml
  src/lib/merkle_ledger/ledger_extras_intf.ml
  src/lib/merkle_ledger/location.ml
  src/lib/merkle_ledger/location.mli
  src/lib/merkle_ledger/location_intf.mli
  src/lib/merkle_ledger/merkle_ledger_intf.ml
  src/lib/merkle_ledger/merkle_path.ml
  src/lib/merkle_ledger/merkle_path.mli
  src/lib/merkle_ledger/merkle_path_intf.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_ledger/null_ledger.mli
  src/lib/merkle_ledger/syncable_intf.ml
  src/lib/merkle_ledger/util.ml
  src/lib/merkle_ledger/util.mli
  src/lib/merkle_ledger_tests/test_database.ml
  src/lib/merkle_ledger_tests/test_mask.ml
  src/lib/merkle_ledger_tests/test_stubs.ml
  src/lib/merkle_mask/base_merkle_tree_intf.mli
  src/lib/mina_ledger/ledger.ml
  src/lib/mina_ledger/ledger.mli
  src/lib/mina_ledger/ledger_transfer.ml
  src/lib/syncable_ledger/syncable_ledger.ml
  src/lib/syncable_ledger/test.ml
Labels: code quality
