Repository MinaProtocol/mina, pull requests merged in 2025-07, with the labels that each got.

#17415 Exit_handlers: remove unused method
  src/lib/exit_handlers/exit_handlers.ml
Labels: enhancement

#17467 Add tests reproducing a deadlock related to lmdb observed in devnet
  src/lib/disk_cache/test/README.md
  src/lib/disk_cache/test/dune
  src/lib/disk_cache/test/test_cache_deadlock.ml
  src/lib/disk_cache/test/test_cache_deadlock.mli
  src/lib/disk_cache/test/test_filesystem_deadlock.ml
  src/lib/disk_cache/test/test_lmdb_deadlock.ml
Labels: lmdb-gc-interrupt-deadlock

#17490 fix dhall job names for legacy bookworm packages
  buildkite/src/Jobs/Release/MinaArtifactBookwormDevnetLegacyDevnet.dhall
  buildkite/src/Jobs/Release/MinaArtifactBookwormMainnetLegacyDevnet.dhall
Labels: bugfix

#17489 Snark Worker: fix incorrect CLI arg after hardfork localnet patch
  src/lib/snark_worker/entry.ml
Labels: bugfix

#17493 logger: migrate inline tests to Alcotest
  src/lib/logger/test/dune
  src/lib/logger/test/logger_test.ml
Labels: enhancement

#17496 Consensus_vrf/test: aesthetic changes
  src/lib/consensus/vrf/tests/test_consensus_vrf.ml
Labels: enhancement

#17503 LMDB Cache: set `get` log level to spam
  src/lib/disk_cache/lmdb/disk_cache.ml
Labels: enhancement, quality-of-life

#17504 LMDB Cache: remove all spam logs
  src/lib/disk_cache/lmdb/disk_cache.ml
Labels: enhancement

#17485 Remove hardcoded state size where previosly missed
  src/app/zkapps_examples/zkapps_examples.ml
  src/lib/mina_base/account_update.ml
  src/lib/mina_base/zkapp_precondition.ml
  src/lib/mina_generators/zkapp_command_generators.ml
  src/lib/transaction_logic/test/zkapp_logic.ml
Labels: enhancement, zkapp-state-size-32

#17167 Do not use pretty print for checkpoints as it might cause stack overflow
  changes/17167.md
  src/app/replayer/replayer.ml
Labels: bugfix

#17484 Improve zkapp transaction regeneration
  src/lib/transaction/transaction_hash.ml
Labels: enhancement

#17514 LMDB Cache: partially reuse GCed IDs so to save cycles on cleaning LMDB V2
  src/lib/disk_cache/lmdb/disk_cache.ml
Labels: enhancement, lmdb

#17523 Fix for publishing debian packages in nightly
  buildkite/scripts/release/manager.sh
  scripts/debian/builder-helpers.sh
  scripts/debian/reversion.sh
Labels: bugfix

#17487 Transaction Snark Test Util: use Testnet instead of t_DEPRECATED
  src/lib/transaction_snark/test/util.ml
Labels: signature-kind-runtime-configurable

#17428 Add converting ledger with test
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/dune
  src/lib/merkle_ledger/intf.ml
  src/lib/merkle_ledger/location.ml
  src/lib/merkle_ledger/merkle_path.ml
  src/lib/mina_base/account.ml
  src/lib/mina_ledger/dune
  src/lib/mina_ledger/ledger.ml
Labels: ledger-migration

#17542 Buildkite: grant Christian bypass changelog permission
  buildkite/scripts/changelog.sh
Labels: permissions

#17486 Restructure merkle ledger tests, updated
  src/dune-project
  src/lib/merkle_ledger/test/binary_tree.ml
  src/lib/merkle_ledger/test/dune
  src/lib/merkle_ledger/test/test.ml
  src/lib/merkle_ledger/test/test_converting.ml
  src/lib/merkle_ledger/test/test_database_in_mem.ml
  src/lib/merkle_ledger/test/test_database_integration.ml
  src/lib/merkle_ledger/test/test_mask.ml
  src/lib/merkle_ledger/test/test_stubs.ml
  src/lib/merkle_ledger_tests/test/dune
  src/lib/merkle_ledger_tests/test/main.ml
Labels: tests

#17430 Push sig kind out of Lib/Prover
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/test_genesis_creation.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/prover/intf.ml
  src/lib/prover/prover.ml
  src/lib/signature_kind/dune
  src/lib/signature_kind/mina_signature_kind.mli
  src/lib/signature_kind/type/dune
  src/lib/signature_kind/type/mina_signature_kind_type.ml
Labels: signature-kind-runtime-configurable

#17556 Add With_database functor to converting merkle tree
  src/lib/merkle_ledger/converting_merkle_tree.ml
  src/lib/merkle_ledger/converting_merkle_tree.mli
  src/lib/merkle_ledger/test/test_converting.ml
  src/lib/mina_ledger/ledger.ml
Labels: ledger-migration

#17566 Block Time: don't use eprintf, use logger instead
  src/lib/block_time/block_time.ml
Labels: enhancement

#17562 Abstract the snarked root ledger
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger/intf.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/genesis_proof/genesis_proof.ml
  src/lib/merkle_ledger/test/test_converting.ml
  src/lib/mina_ledger/ledger.ml
  src/lib/mina_ledger/ledger.mli
  src/lib/mina_ledger/root.ml
  src/lib/mina_ledger/root.mli
  src/lib/mina_lib/mina_lib.ml
  src/lib/sync_handler/sync_handler.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/full_frontier/full_frontier.mli
  src/lib/transition_frontier/persistent_frontier/persistent_frontier.ml
  src/lib/transition_frontier/persistent_root/persistent_root.ml
  src/lib/transition_frontier/transition_frontier.ml
  src/lib/transition_frontier/transition_frontier.mli
Labels: refactor, ledger-migration

#17549 remove genkey docker and debian
  buildkite/scripts/build-release.sh
  dockerfiles/Dockerfile-genkey
  scripts/debian/build.sh
  scripts/debian/builder-helpers.sh
Labels: cleanup, docker-image

#17585 Push sig kind out of test executive & network pool test
  src/app/test_executive/block_production_priority.ml
  src/app/test_executive/block_reward_test.ml
  src/app/test_executive/chain_reliability_test.ml
  src/app/test_executive/epoch_ledger.ml
  src/app/test_executive/gossip_consistency.ml
  src/app/test_executive/hard_fork.ml
  src/app/test_executive/medium_bootstrap.ml
  src/app/test_executive/payments_test.ml
  src/app/test_executive/peers_reliability_test.ml
  src/app/test_executive/slot_end_test.ml
  src/app/test_executive/test_executive.ml
  src/app/test_executive/verification_key_update.ml
  src/app/test_executive/zkapps.ml
  src/app/test_executive/zkapps_nonce_test.ml
  src/app/test_executive/zkapps_timing.ml
  src/lib/network_pool/test/indexed_pool_tests.ml
  src/lib/signature_kind/dune
  src/lib/signature_kind/mina_signature_kind.mli
  src/lib/signature_kind/type/dune
  src/lib/signature_kind/type/mina_signature_kind_type.ml
  src/lib/testing/integration_test_lib/intf.ml
  src/lib/testing/integration_test_lib/test_config.ml
Labels: signature-kind-runtime-configurable

#17574 Add neccessary debian package properties. To fix unknown suffix
  buildkite/scripts/release/manager.sh
  scripts/debian/builder-helpers.sh
Labels: packaging

#17553 [CI] support bookworm and noble in publishing
  buildkite/Makefile
  buildkite/scripts/release/manager.sh
  buildkite/src/Jobs/Promote/AutoPromoteNightly.dhall
  scripts/debian/verify.sh
Labels: packaging

#17576 Use Root ledger in epoch snapshots
  src/app/cli/src/init/mina_run.ml
  src/lib/bootstrap_controller/bootstrap_controller.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_graphql/types.ml
  src/lib/mina_ledger/root.ml
  src/lib/mina_ledger/root.mli
  src/lib/mina_ledger/sync_ledger.ml
  src/lib/mina_lib/tests/tests.ml
  src/lib/sync_handler/sync_handler.ml
Labels: ledger-migration
