Repository MinaProtocol/mina, pull requests merged in 2025-08, with the labels that each got.

#17594 Push sig kind out of work partitioner
  src/lib/transaction_snark/transaction_snark.ml
  src/lib/transaction_snark/transaction_snark_intf.ml
  src/lib/work_partitioner/snark_worker_shared.ml
  src/lib/work_partitioner/work_partitioner.ml
  src/lib/work_partitioner/work_partitioner.mli
Labels: signature-kind-runtime-configurable

#17583 Handle submission into work partitioner single pool correctly
  src/lib/work_partitioner/work_partitioner.ml
Labels: snark-worker-optim, bugfix

#17636 Fix merge of zkapp proof in work partitioner V3
  src/lib/mina_stdlib/nonempty_list.ml
  src/lib/mina_stdlib/nonempty_list.mli
  src/lib/snark_work_lib/id.ml
  src/lib/snark_work_lib/id.mli
  src/lib/work_partitioner/pending_zkapp_command.ml
  src/lib/work_partitioner/pending_zkapp_command.mli
  src/lib/work_partitioner/work_partitioner.ml
Labels: snark-worker-optim

#17641 Improve Genesis Ledger Creation
  src/app/cli/src/cli_entrypoint/mina_cli_entrypoint.ml
  src/app/cli/src/init/mina_run.ml
  src/app/cli/src/init/test_ledger_application.ml
  src/app/zkapp_test_transaction/lib/commands.ml
  src/lib/consensus/genesis_epoch_data.ml
  src/lib/consensus/intf.ml
  src/lib/consensus/proof_of_stake.ml
  src/lib/fake_network/fake_network.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_graphql/types.ml
  src/lib/mina_lib/tests/tests.ml
  src/lib/mina_state/genesis_protocol_state.ml
  src/lib/mina_state/genesis_protocol_state.mli
  src/lib/mina_state/protocol_state.ml
  src/lib/mina_state/protocol_state_intf.ml
  src/lib/network_pool/test/indexed_pool_tests.ml
  src/lib/network_pool/transaction_pool.ml
  src/lib/precomputed_values/precomputed_values.ml
  src/lib/prover/prover.ml
  src/lib/snark_profiler_lib/snark_profiler_lib.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/transaction_snark/test/transaction_union/transaction_union.ml
  src/lib/transaction_snark/test/util.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/transition_frontier.ml
Labels: ledger-migration

#17633 Define and use a Config.t type for Root ledgers
  src/lib/consensus/proof_of_stake.ml
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger_helper/genesis_ledger_helper.ml
  src/lib/mina_ledger/root.ml
  src/lib/mina_ledger/root.mli
  src/lib/mina_lib/tests/tests.ml
  src/lib/transition_frontier/full_frontier/full_frontier.ml
  src/lib/transition_frontier/persistent_root/persistent_root.ml
Labels: ledger-migration

#17649 Push sig kind out of user command input
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/user_command_input/user_command_input.ml
  src/lib/user_command_input/user_command_input.mli
Labels: signature-kind-runtime-configurable

#17650 Txn Snark: push sig kind out of txn validator
  src/lib/staged_ledger/pre_diff_info.ml
  src/lib/staged_ledger/staged_ledger.ml
  src/lib/staged_ledger/test/txn_application_test.ml
  src/lib/transaction_snark/transaction_validator.ml
  src/lib/transaction_snark/transaction_validator.mli
Labels: signature-kind-runtime-configurable

#17655 Prepare fork config inputs in mina_lib
  src/lib/mina_graphql/mina_graphql.ml
  src/lib/mina_lib/mina_lib.ml
  src/lib/mina_lib/mina_lib.mli
  src/lib/runtime_config/runtime_config.ml
  src/lib/testing/integration_test_local_engine/mina_docker.ml
Labels: hardfork-automation

#17668 Make Converting Ledgers & Unstable DB input to Root.Make
  src/lib/merkle_ledger/converting_merkle_tree.ml
  src/lib/merkle_ledger/converting_merkle_tree.mli
  src/lib/mina_ledger/ledger.ml
  src/lib/mina_ledger/ledger.mli
  src/lib/mina_ledger/root.ml
  src/lib/mina_ledger/root.mli
Labels: ledger-migration

#17653 Consider TMPDIR in computing s3_install_path
  src/lib/cache_dir/native/cache_dir.ml
Labels: enhancement

#17662 Move hashable big string to mina stdlib
  src/lib/merkle_ledger/location.ml
  src/lib/merkle_ledger/location.mli
  src/lib/merkle_ledger/test/test_database_in_mem.ml
  src/lib/merkle_ledger/test/test_database_integration.ml
  src/lib/merkle_ledger/test/test_mask.ml
  src/lib/mina_ledger/ledger.ml
  src/lib/mina_stdlib/bigstring.ml
  src/lib/mina_stdlib/bigstring.mli
  src/lib/syncable_ledger/test/test.ml
Labels: refactor

#17648 Various helper functions in Snark Work Lib
  src/lib/snark_work_lib/partitioned_result.ml
  src/lib/snark_work_lib/partitioned_result.mli
  src/lib/snark_work_lib/partitioned_spec.ml
  src/lib/snark_work_lib/partitioned_spec.mli
Labels: snark-worker-optim

#17672 Push sig kind out of Archive.Lib.Processor
  src/app/archive/cli/archive_cli.ml
  src/app/archive/lib/processor.ml
  src/app/archive_blocks/archive_blocks.ml
Labels: signature-kind-runtime-configurable

#17643 Pass back spec on successful result combination in partitioner
  src/lib/snark_work_lib/combined_result.mli
  src/lib/work_partitioner/combining_result.ml
Labels: snark-worker-optim

#17670 Remove Config.primary_directory in Root.Make(_).Config
  src/lib/consensus/proof_of_stake.ml
  src/lib/merkle_ledger/converting_merkle_tree.ml
  src/lib/merkle_ledger/intf.ml
  src/lib/mina_ledger/root.ml
  src/lib/mina_ledger/root.mli
  src/lib/transition_frontier/persistent_root/persistent_root.ml
Labels: enhancement

#17675 Folding accounts across all ledger masks
  src/lib/merkle_ledger/any_ledger.ml
  src/lib/merkle_ledger/converting_merkle_tree.ml
  src/lib/merkle_ledger/database.ml
  src/lib/merkle_ledger/intf.ml
  src/lib/merkle_ledger/null_ledger.ml
  src/lib/merkle_mask/masking_merkle_tree.ml
Labels: ledger-migration

#17687 Remove transfer_accounts_with from Root
  src/lib/genesis_ledger/genesis_ledger.ml
  src/lib/genesis_ledger/intf.ml
  src/lib/mina_ledger/root.ml
  src/lib/mina_ledger/root.mli
  src/lib/transition_frontier/persistent_root/persistent_root.ml
Labels: ledger-migration
